### ISSUE TITLE
0 Gas to claim

### ISSUE THREAD

**Issue by fransyozef** [CityOfZion/neon-wallet#100]
So I've haven't opened my NEON wallet for 2 days now (v0.0.3 on Mac). Now I just opened it and I noticed I have 0 Gas to claim. Normally I have some small ammount to claim. How is this possible?

**Comment by gpascualg** [comment]
Confirming this is happening to me too, seems to be a problem with the API?

**Comment by lawred2** [comment]
Same. Was working yesterday. Now saying 0 Gas.

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this.** As an aside, I've had to close about 5 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
