### ISSUE TITLE
Can't open wallet, endless loading screen

### ISSUE THREAD

**Issue by kimianiaga** [CityOfZion/neon-wallet#1000]
No one seems to be able to solve this problem !

**Comment by drptbl** [comment]
1. Which OS are you using?
2. Which wallet version are you trying to run?
3. Did it happen before or after update or there was no connection at all with updating the wallet (it was working fine and suddenly stopped to work)? If it broke after update, what version did you use before?
4. Do you remember if you did something specific before you closed wallet last time before it broke?
5. Are you sure that nothing is blocking your connection/wallet process from access to internet connection (firewall for example)?

**Comment by drptbl** [comment]
No response, closing.
