### ISSUE TITLE
Fail to load v 0.2.3

### ISSUE THREAD

**Issue by nikolaithomas** [CityOfZion/neon-wallet#1002]
I upgraded to 0.2.3 yesterday and I'm getting the "Failed to load." error message whenever I try to open the app. I can guarantee I do not have a network connectivity issue.
Environment: macOS Sierra 10.13.2

**Comment by drptbl** [comment]
1. Which OS are you using?
2. Which wallet version are you trying to run?
3. Did it happen before or after update or there was no connection at all with updating the wallet (it was working fine and suddenly stopped to work)? If it broke after update, what version did you use before?
4. Do you remember if you did something specific before you closed wallet last time before it broke?
5. Are you sure that nothing is blocking your connection/wallet process from access to internet connection (firewall for example)?
