### ISSUE TITLE
Neon 0.2.3 Showing no tokens

### ISSUE THREAD

**Issue by JamesLivo11** [CityOfZion/neon-wallet#1003]
Just downloaded the newest version of Neon wallet 0.2.3 and it doesn't show any tokens or balance. regardless if the amount of tokens is 0. On previous versions they show but not now, 

![capture](https://user-images.githubusercontent.com/38596182/39090053-3d2ce6d0-4613-11e8-87ec-9f25651c49eb.JPG)

## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by revan1013** [comment]
I have the exact same problem, same Ledger Nano with new firmware, and Win 10 OS. 

I tried installing old versions of NEON as well, and it didn't fix it. Left a message in the discord as well.

**Comment by Rehmah20** [comment]
I've got the same problem, check my Neon wallet and my Neo and Gas is showing as 0

**Comment by Rehmah20** [comment]
Not sure what or how to check further - I've looked on neotracker.io but it was still showing as 0
