### ISSUE TITLE
Ledger Nano S + NEON 0.2.3 Mac.dmg = Still can't send GAS after struggling for 4 months!

### ISSUE THREAD

**Issue by Frontiercoach** [CityOfZion/neon-wallet#1004]
I've been using Ledger Nano S with Neon Mac.dmg since Dec 2017.  I have not been able to send GAS right from the beginning despite having used all latest versions of  Ledger firmwares, NEO apps and NEON Wallets.  No problem sending NEO or claiming GAS, but just unable to send GAS.  It always responded with "Transaction failed!"
After installing the latest NEON 0.2.3, it now says "Transaction failed: Your transaction is too big for the ledger to sign!".  I tried sending various amounts with different number of decimal points.  I have only managed to send 0.001 GAS once, and cannot replicate it again. 
PLEASE HELP! I have been struggling with this problem for 4 months now to no avail!

**Comment by VinceDot** [comment]
Have you tried using 0.2.2 ?

**Comment by aestho** [comment]
I'm experiencing the same issue. I've tried everything at my disposal - restarting my computer, installing/re-installing NEON, testing various releases, unplugging/re-attaching ledger, uninstalling + reinstalling ledger NEO app, etc. All to no avail.

**Comment by snowypowers** [comment]
If you are receiving `Transaction failed: Your transaction is too big for the ledger to sign!`, just keep trying to send less GAS. Remember that GAS can go up to 8 decimals places so good luck.

FYI, ledger can sign about 20+ inputs so if you claim your GAS super regularly (each claim = 1 input), try sending about 20x the amount of GAS you claim usually. So if you claim 0.00000001 GAS everytime, you can only send out 0.0000002 GAS each time.

**Comment by WarrickBotha** [comment]
I have the identical problem. I have Neon Wallet 0.2.4 and a Ledger Nano S with the latest firmware. Claiming GAS is fine, but I cannot send GAS, no matter what amount of GAS I try to send, the wallet says that the Transaction Failed because the amount was too big for the Ledger to sign. 

Please help ?
