### ISSUE TITLE
Ensure that at least 4 letters of token symbol are shown in "Portfolio" section on wallet dashboard

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1005]
**Wallet version or commit SHA:**
71bee7e

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.371

**Prerequisites:**
At least one wallet imported to the app,
Balance of token which has at least 4 letters in token symbol

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button

Currently, if token symbol contains more than 3 letters, it's getting trimmed after second letter. Taking `THOR` token as an example, we're ending in `TH...` token in "Portfolio" section. This could cause issues in future in understanding current balances of wallet and confusion. Adding another token, for example `THEST`, user will see two tokens in "Portfolio" section named exactly the same - `TH...`. Because the most common cases for token symbols are 3 and 4 letters, we should ensure that at least 4 letters are shown. In addition to that, if token symbol is trimmed anyway (because it's longer than 4 letters), tooltip on mouse hover should be added showing full token symbol inside (it's not present currently).

**Screenshots/Video:**
![port2](https://user-images.githubusercontent.com/8177587/39121682-9ecd4594-46f2-11e8-92c0-f3ce9ceb4a46.png)

**Comment by Melicio** [comment]
Good morning @mhuggins , PeerAtlas.com will soon launch its project and ICO, and we prefer to call our token ATLAS. We are wondering if it is possible to make it 5 letters instead of 4, so we won't get trimmed at ATLA... As many of our community uses NEON Wallet that would presentation wise be great to see. Thanks in advance for your consideration!

**Comment by alexhulbert** [comment]
@drptbl I fixed this. It's currently pending QA.
@Melicio I checked the string "ATLAS" on the panel and it looks like you're all set! :+1: :shipit:

**Comment by Sqeeki55** [comment]
Thankyou so much for your help you two and I sure needed it 😚😚😚

**Comment by drptbl** [comment]
Tested, looks good.

**Comment by Sqeeki55** [comment]
Sounds like all of you are doing sooo much!It's great and this is squeezi55 . Had a failure of my tablet 20 days ago and on a new cell and I hoped I would find out about what was up at ZION and wow ATLAS congrats you really are geniuses and hope to check the sight soon and maybe still be apart 😂😊

**Comment by Sqeeki55** [comment]
This is Squeeki55 Please fix my errors while I'm waiting for new tablet if
you can. Thanks
