### ISSUE TITLE
Update fonts according to designs

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1007]
Fonts used in wallet app doesn't seem to be following fonts used in designs. There should be more details about fonts used in designs and then changes should be applied to the wallet app.

Check designs for reference.

**Comment by alexhulbert** [comment]
The font used in the designs is Gotham. However, it's not a free font. Does CoZ have the proper licensing to use it? If not, Google has its own open-source knockoff of Gotham called "Montserrat"

**Comment by comountainclimber** [comment]
@alexhulbert I found free downloads of gotham here => https://www.wfonts.com/font/gotham is this site in copy write violation or something?

**Comment by alexhulbert** [comment]
@comountainclimber Beats me. If you go to their website it says you have to purchase mobile software licenses in order to use their font in apps. I assume software is no different, but I'm no lawyer, so I might be wrong.

**Comment by drptbl** [comment]
Re-tested, found some issues related to new fonts, will create separate tickets for them.
