### ISSUE TITLE
More than 10 hours passed, I did not receive GAS

### ISSUE THREAD

**Issue by like3ds** [CityOfZion/neon-wallet#101]
More than 10 hours passed, I did not receive the GAS. The claime button shows zero all the time.

![default](https://user-images.githubusercontent.com/30974183/29248542-4d595766-8023-11e7-9bb7-deb5a4d65a18.PNG)

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the _sidebar of the subreddit_. **Please let everybody you know know this.**
