### ISSUE TITLE
White screen (Not Nvidia)

### ISSUE THREAD

**Issue by 4tune81** [CityOfZion/neon-wallet#1011]
I have firmware 1.4.1 running on my ledger with mcu 1.5 and Neonwallet 0.2.3 , when I open the wallet and try to log in with ledger a popup opens but remains completely white.
It is not a Nvidia problem . I updated my onboard intel graphicscard 4000 with the latest drivers.
I'm using a HP Elitebook 8570b with Windows 10 pro edition

**Comment by drptbl** [comment]
Please download latest version from:
https://github.com/CityOfZion/neon-wallet/releases/tag/0.2.6

And let us know if this issue has been fixed for you. Thanks!
