### ISSUE TITLE
Multiple addresses?

### ISSUE THREAD

**Issue by briannyeko** [CityOfZion/neon-wallet#1014]
When will you offer the ability to add multiple NEO Adresses?

**Comment by mhuggins** [comment]
The wallet already supports multiple addresses.  Simply sign out with one address and sign in with another.

**Comment by briannyeko** [comment]
even with signing in with a ledger nano S?

**Comment by mhuggins** [comment]
Yep, I switch between accounts and use Ledger on and off locally for development.  There's no issue with using more than one address.
