### ISSUE TITLE
Ledger Nano S not found by Neon

### ISSUE THREAD

**Issue by subzero788** [CityOfZion/neon-wallet#1015]
I used Neon extensively with my Ledger nano S from Sept till early Jan.

Recently updated the ledger to the current firmware (1.4.2) and Neon to version 0.2.3 but Neon does not detect the Nano at all (displays "USB Error: No device found")

I have tried:

1. Earlier versions of Neon that previously worked for me (eg 0.0.9)
2. Uninstalling and reinstalling both Neon and the Ledger Neo Ap

I have considered trying to downgrade the firmware on the nano but others have reported that the firmware is not an issue with Neon (see https://www.reddit.com/r/ledgerwallet/comments/8dmf4z/is_nano_s_with_firmware_142_working_with_neon/)

Can anyone offer any advice?

**Comment by stevesbrain** [comment]
Different USB cable? Different PC? :)

**Comment by subzero788** [comment]
Thanks for the tip stevesbrain. Worked on another computer; think it's something to do with my antivirus.

Cheers again!
