### ISSUE TITLE
Calculating claimable GAS failed

### ISSUE THREAD

**Issue by JayKan** [CityOfZion/neon-wallet#1019]
## PLEASE NOTE

Can't claim my GAS via current Neon Wallet, please see attached image for error:

<img width="472" alt="cannot_claim_gas" src="https://user-images.githubusercontent.com/1400300/39390509-4c9dc1f8-4a4a-11e8-95e6-90f4775db226.png">

Current neon wallet version: **0.2.2**

**Comment by subzero788** [comment]
I have the same issue with 0.2.3 and nano s

**Comment by oanhschenk** [comment]
I have same issue with 0.2.3 with the error message "Calculating claimable Gas failed". How to fix this problem? any idea?

**Comment by mhuggins** [comment]
Duplicate of #742.
