### ISSUE TITLE
Wallet value doesn't update + 0 GAS to be claimed....?

### ISSUE THREAD

**Issue by soyinka1994** [CityOfZion/neon-wallet#102]
Yesterday I had some gas that i could claim but I didn't. Today it says theres there is 0 GAS. What's up with that? + Its like the value of your wallet doesn't adjust anymore? Anyone experiencing the same issues?

**Comment by snowypowers** [comment]
see #99. Please close this issue.

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the _sidebar of the subreddit_. **Please let everybody you know know this.** This is the 7th issue with the exact same topic I've had to close. Please read previous issues before opening a new issue.
