### ISSUE TITLE
Disable ability to spam "Refresh" buttons on wallet dashboard

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1021]
**Wallet version or commit SHA:**
ef95d25

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.371

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Click on "Refresh" button several times in a row

Currently user is able to spam "Refresh" buttons causing requests to queue. "Refresh" buttons shouldn't be able to be clicked until requests have finished loading.

**Screenshots/Video:**
![ref_but_spam](https://user-images.githubusercontent.com/8177587/39396656-7395c3ac-4af2-11e8-82d1-7b2fad3fb6e7.gif)

**Comment by comountainclimber** [comment]
should be a trivial fix I can take care of it 👍

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/pull/1023

**Comment by mhuggins** [comment]
Code complete, just pending QA.

**Comment by drptbl** [comment]
After re-testing - this issue is still valid.

Changes from linked PR (#1023) applies only to `AssetBalancesPanel.jsx`, but `TokenBalancesPanel.jsx` has been forgotten. Because of that this issue is still valid for "Refresh" button in "Token Balances" section (it's spammable).

I wasn't able to test these changes on "Refresh" button in "Balances" section because it's broken currently (#1079). Will re-test later, after it's fixed.

**Comment by comountainclimber** [comment]
@drptbl good call... I can address all of the above

**Comment by mhuggins** [comment]
Fixed by #1159, pending QA.

**Comment by drptbl** [comment]
Looks good, thanks!
