### ISSUE TITLE
NEON wallet not syncing with blockchain

### ISSUE THREAD

**Issue by alexfree2323** [CityOfZion/neon-wallet#1028]
Hi,

I just downloaded the NEON wallet a few days ago. I sent 1 NEO to my wallet and everything was fine. I just sent 20 more and they are showing up on the blockchain but not on my NEON wallet app. Is there some fix for this?

I have the Mac Os Wallet and I use a ledger nano s to access

Thanks!

**Comment by mhuggins** [comment]
There have been some issues with the neoscan API and with some RPC endpoints over the past hours that are actively being worked on.  The workaround for now is to try logging back into the client or to try refetching balance.
