### ISSUE TITLE
Can not send NEO or claim GAS using Ledger Nano S & 0.2.3 

### ISSUE THREAD

**Issue by Cryptomanifest** [CityOfZion/neon-wallet#1031]
I Have not been able to send NEO from Neon Wallter using Ledger or claim GAS using Ledger Nano S
Updated everything on the ledger, apps, FW, etc.

Also updated everything to 0.2.3 for Neon Wallet

Help?

**Comment by comfyowl** [comment]
Same issue for me too.

**Comment by mhuggins** [comment]
Tracking this issue under #882.
