### ISSUE TITLE
My Neo Wallet 0.2.3 is not letting collect gas and is acting frozen for almost a day. Please help.Thankyou

### ISSUE THREAD

**Issue by Cowboyup77** [CityOfZion/neon-wallet#1032]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by mhuggins** [comment]
Duplicate of #1028.

**Comment by Olorunsola2** [comment]
Similar situation here. No solution? Plenty of GAS is owed to my account
