### ISSUE TITLE
Gas not accumulating in wallet.

### ISSUE THREAD

**Issue by gopherpig** [CityOfZion/neon-wallet#1036]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c
0.2.3
**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309
windows
**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.
havent collected gas in awhile. opened uo my wallet and gas shows 0 and claim button not lit up.
**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by mhuggins** [comment]
Not enough information.

**Comment by CozartLucas** [comment]
Having the same issues with my wallet.  Just updated to 2.3 from 2.2
