### ISSUE TITLE
2.3 wallet cannot claim gas

### ISSUE THREAD

**Issue by CozartLucas** [CityOfZion/neon-wallet#1037]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by CozartLucas** [comment]
Version 2.3
Win 10
Pre: Have tky tokens added to wallet
Reproduction:
1. start wallet 
2. all coins/tokens are showing
3. claim gas button is not highlighted and shows 0
4. will not accumulate gas

**Comment by CryptoKitty424** [comment]
Same issue here.  I took screenshots.  I can see the GAS available to claim on neotracker but NEON wallet shows 0.00. 

Version 2.3
Win 10
Pre: Have tky tokens added to wallet
Reproduction:

1 start wallet
2 all coins/tokens are showing
3 claim gas button is not highlighted and shows 0
4 will not accumulate gas
<img width="739" alt="neonwallet" src="https://user-images.githubusercontent.com/38844202/39411617-717fb34a-4bdb-11e8-8a78-cbac508da381.png">
<img width="867" alt="neonwallet2" src="https://user-images.githubusercontent.com/38844202/39411618-79abe566-4bdb-11e8-8fb2-8049f6f7e29a.png">

**Comment by CryptoCowboys** [comment]
Running into the same issue as well with NEON Wallet Version 2.3 on Mac OSX High Sierra version 10.13.4.

Not able to claim gas, gas amount accumulated on NEON wallet is a bit less than the amount of GAS accumulation showing on NeoTracker.io

Reproduction:

start wallet
all coins/tokens are showing
claim gas button shows .33492 GAS
press claim gas button. After a few minutes once blockchain updates the gas is still not claimed.

**Comment by mhuggins** [comment]
New release coming soon that should hopefully fix this.

**Comment by Cryptomanifest** [comment]
What about not being able to send NEO from Ledger Nano & Neon 0.2.3

Cant do that either. Just failed transaction results

**Comment by mhuggins** [comment]
@CryptoCowboys There's a separate issue that is tracking that, and a potential fix in the works.

**Comment by Cowboyup77** [comment]
Running into the same issue as well with NEON Wallet Version 2.3 on windows

Not able to claim gas, gas amount  is now not accumulated on  my NEON wallet  for a day now. NeoTracker.io

Reproduction:

start wallet
all coins/tokens are showing
press claim gas button. After a few minutes once blockchain updates the gas is still not claimed

**Comment by dgpgomes** [comment]
Same problem here.
Version 0.2.3 running in windows 10 64bits

Reproduction:
- start wallet
- all coins/tokens are showing

Claim button shows 0.000000

I noticed claiming through neonwallet actually makes the button on neon wallet available and clickable again but once I click on it and wallet updates with new balances, it gets stuck on 0.000000 again.

**Comment by pdufur23832** [comment]
Wallet version:  NEON wallet - v0.2.3
Environment:  macOS High Sierra - v10.13.4
  Prerequisites:  Holding NEO, GAS, RPX, and ONT  
Reproduction steps:  Have been claiming GAS for a few weeks successfully.  As of yesterday: 
1. Start wallet.
2. All coins/tokens are showing.
3. ‘Claim GAS’ button is grayed out and showing 0.0000000.
4. Not accumulating GAS.

**Comment by mhuggins** [comment]
Fixed by #1033.  Will be included in next release.
