### ISSUE TITLE
Unable to send TNC tokens from Neon wallet using a ledger

### ISSUE THREAD

**Issue by Himmy06** [CityOfZion/neon-wallet#1038]
I am able to see my TNC token count, but if I try to send them, they do not appear in the drop down menu as an option.  My other NEP 5 tokens such as RPX, ONT, DBC show up in the drop down menu.

Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by snowypowers** [comment]
Insufficient information.
