### ISSUE TITLE
Unclaimed GAS disappeared from Neon Wallet, and wont show any accruing GAS anymore

### ISSUE THREAD

**Issue by Vibehunter** [CityOfZion/neon-wallet#104]
Here is a screen capture:

![screen shot 2017-08-14 at 2 13 01 am](https://user-images.githubusercontent.com/30982141/29251325-2c3ae806-8096-11e7-8f88-9fb81d355a59.png)

I attempted to claim to see if i could redeem the gas still however, it appears the transaction has an error.

Have i lost my GAS?

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this.** As an aside, I've had to close about 5 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
