### ISSUE TITLE
can t claim gas on latest version 0.2.3, logging with ledger nano S latest firmware 1.4.2

### ISSUE THREAD

**Issue by floflofloflo** [CityOfZion/neon-wallet#1040]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
0.2.3
**Environment:**
e.g.: Win 10 Home (64 bit) 

**Prerequisites:**
working OK till previous version
login with ledger nano S firmware v1.4.2
using latest neon wallet 0.2.3

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Claim gas -> cannot 

some description (for ex. what happens after completing reproduction steps), e.g.:
 Claim gas -> cannot always says 0!!!!! (with of course some NEO on the wallet and without claiming for last 2 months, NEO tracker says I can claim xx GAS)

**Comment by drptbl** [comment]
Should be fixed with #1039 which is included with next release.
