### ISSUE TITLE
 GAS not accumulating and Claim button disabled

### ISSUE THREAD

**Issue by berkie77** [CityOfZion/neon-wallet#1043]
After sending my GAS to an external exchange, the GAS in my Neon Wallet is not accumulating and the Claim button is disabled. The amount of GAS that I can claim is set at 0.000000 and has not increased over time. Though, I do still have the same NEO balance in this wallet.

**Environment
MacOS Sierra v 10.12.6

**Wallet Version 
0.2.3

**Previous Steps.
1. 3 days ago, I sent my entire GAS balance to an online exchange. Success.
2. Today, my GAS Claim Button and its display counter has been at 0.00000000 and Disabled. The amount of claimable GAS does not increase over time. 
3. I installed the latest version of Neon Wallet from version 0.2.2 to 0.2.3 to see if an update would fix this. 
4. The problem remains still after the latest version

![screen shot 2018-04-30 at 5 14 42 pm](https://user-images.githubusercontent.com/38854588/39423028-38f51a50-4c9a-11e8-88e2-e9c26baaf249.png)

**Comment by drptbl** [comment]
Should be fixed with #1039 which is included with next release.
