### ISSUE TITLE
I cannot claim my GAS in my NEON Wallet, in version 0.2.3

### ISSUE THREAD

**Issue by wowology** [CityOfZion/neon-wallet#1046]
Hi,

I cannot claim my GAS in my NEON Wallet, in version 0.2.3.

Please advise.

**Comment by drptbl** [comment]
Should be fixed with #1039 which is included with next release.

**Comment by mhuggins** [comment]
This issue should be fixed in [version 0.2.4](https://github.com/CityOfZion/neon-wallet/releases/tag/0.2.4).
