### ISSUE TITLE
GAS disappeared.

### ISSUE THREAD

**Issue by Cryptology81** [CityOfZion/neon-wallet#105]
Hi, I haven't logged in to my Neon wallet for a few days, when I just did, all the accumulating GAS from the last week has been set to 0 and it's not accumulating any more.

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this.** As an aside, I've had to close about 10 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
