### ISSUE TITLE
Is there any way to verify that the token was successfully added?

### ISSUE THREAD

**Issue by OHHP** [CityOfZion/neon-wallet#1059]
I added a token, but the balance is zero.
Is there any way to verify that the token was successfully added?

**Wallet version or commit SHA:**
0.2.4

**Environment:**
Win 7 Home (64 bit)

**Comment by drptbl** [comment]
After starting the wallet, you can go to "Manage Neon settings" => "Manage tokens" and check if your script hash is properly added to the list of token script hashes.
