### ISSUE TITLE
Gas is gone?

### ISSUE THREAD

**Issue by bitsniper1** [CityOfZion/neon-wallet#106]
I have generated at 0.8 gas and when I finally decided to claim it I open up neon wallet and the gas is displayed as 0. was I hacked or is there a problem with the wallet? Also unable to generate new gas, has been display 0 the whole day already?

Thank YOu

**Comment by RealAtix** [comment]
Hey it's not gone, the gas part of the wallet is broken I guess.

You can see the claimed and unclaimed GAS by looking up your public address here https://neotracker.io/

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this.** As an aside, I've had to close about 10 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
