### ISSUE TITLE
Neon Wallet 0.2.4 - Paste function in the 'Login using a Private Key' field is not working. Cannot 'Paste' Private Key.

### ISSUE THREAD

**Issue by ThaSpil** [CityOfZion/neon-wallet#1060]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:** 
0.2.4

**Environment:**
Win 10 Pro (64 bit) Version 1709 Build 16299.371

**Prerequisites:**
Don't have any custom tokens added before running the wallet

**Reproduction steps:**
1. Install version 0.2.4.
2. Start Neon Wallet
3. Click on the ''Login using a Private Key''
4. Paste function does not work when trying to enter private key in the related field.

Copy/paste does not seem to work for the latest release of the neon wallet. Kindly advise

**Comment by drptbl** [comment]
Couldn't reproduce.

**Wallet version or commit SHA:**
0.2.4

**Environment:**
Win 10 Pro (64 bit) Version 1709 Build 16299.371

Same reproduction steps.
Tested copy outside of Neon wallet and paste in wallet - works.
Tested copy inside of Neon wallet and paste in wallet - works.

**Video:**
![neon_paste](https://user-images.githubusercontent.com/8177587/39630371-69501aa2-4faf-11e8-93f6-5f30926e85a1.gif)

**Comment by ThaSpil** [comment]
Re-installed and it now works.
Closing issue.
Thanks
