### ISSUE TITLE
Neon 0.2.4 dmg, new wallet will not load, gas stuck at zero

### ISSUE THREAD

**Issue by DEANOBO** [CityOfZion/neon-wallet#1061]
Please com
<img width="360" alt="screen shot 2018-05-03 at 10 21 10 am" src="https://user-images.githubusercontent.com/36774056/39592516-d5aec8e6-4ebb-11e8-9878-fd4f87eb6a12.png">
plete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by gitinthetrunk** [comment]
My gas is listed in the claim button as if I want to claim gas. There is .0001 gas listed next to my Neo count. I do not want to claim gas at this time

**Comment by gitinthetrunk** [comment]
I am on Mac and that is using the 0.2.4 update
