### ISSUE TITLE
Wallet will not update on Mac 10.12.6... Steal receiving no GAS credit.

### ISSUE THREAD

**Issue by onemoby** [CityOfZion/neon-wallet#1064]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.4 dmg

**Environment:**
e.g.: Mac 10.12.6

**Prerequisites:**
e.g.: Only have NEO in wallet...

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description: Have had Neo for 2 days now and have not received any GAS..
When opining wallet, window informs  me "my wallet needs to update" 
Update does not work. Will not download..

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by mhuggins** [comment]
Not enough information.

**Comment by mhuggins** [comment]
Everything requested in the form.

**Comment by onemoby** [comment]
I have filled out the form with everything applicable to my best knowledge
and ability.

The update that became available 4 days ago for the Mac does not work..

I am still not receiving GAS.  And also having a hard time opening my Leder
Namo S.

**Comment by onemoby** [comment]
Pertaining to this problem.

1: Unplug Ledger.

2: Delete current wallet.

3. Download updated wallet.

4. Wake up Neo in Ledger.

Worked perfectly.


There is still a problem with "claim GAS"  in the 2.4. dmg update. But at
least now I can see GAS accruing,,, just cant claim it.
