### ISSUE TITLE
unable to send TNC tokens from NEON wallet

### ISSUE THREAD

**Issue by Himmy06** [CityOfZion/neon-wallet#1065]
I am able to see my TNC token count, but if I try to send them, they do not appear in the drop down menu as an option. My other NEP 5 tokens such as RPX, ONT, DBC show up in the drop down menu.

**Wallet version or commit SHA:**
Neon 0.2.4

**Environment:**
MaC OS

**Prerequisites:**
Unable to send trinity token form Neon Wallet.

**Reproduction steps:**
1. Start Neon Wallet
2. view TNC Balance
3. TNC token does not appear on drop down menu under send

After viewing TNC balance, TNC token doesn't appear as an option on drop down menu. Other tokens such as NEO, ONT, RPX, DBC appear in the drop down menu

**Screenshots/Video:**
not avail

**Comment by drptbl** [comment]
This issue shouldn't happen anymore. If yes, please re-open this issue. Thanks.

**Comment by Himmy06** [comment]
The issue is not resolved . I tried using the newest wallet. No luck .
