### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by nate555** [CityOfZion/neon-wallet#1067]
I created a NEON wallet and only made one outgoing transaction. I do not see the transaction nor the hash In the transaction history. How can I locate this transaction?

**Comment by buddhaman8** [comment]
Still having problems on (0.2.4) wallet with GAS claims - when they do go through, there's no transaction history showing on list!
Also some tokens/balances keep disappearing or don't even show up on my dashboard

**Comment by mhuggins** [comment]
Not enough information.  Please complete the issue form when submitting an issue.
