### ISSUE TITLE
 Issue with viewing Switcheo (SWH) balance on MAC Neon wallet

### ISSUE THREAD

**Issue by yonisdior** [CityOfZion/neon-wallet#1068]
When I open the Neon wallet, it doesn't show my Switcheo balances. But, when I search for my public address on NeoScan and Neo Tracker, they both show the balance of my wallet. This just started happening after I updated the Neon wallet to 0.2.4. This is on MacOS sierra 10.12.1. 

Images:

<img width="531" alt="screen shot 2018-05-06 at 2 18 03 am" src="https://user-images.githubusercontent.com/39020445/39670463-c747531c-50d3-11e8-8995-5feaf9ed7d3c.png">
![img_3283](https://user-images.githubusercontent.com/39020445/39670468-ccd5c3ea-50d3-11e8-936f-c5da2771e3bf.jpeg)
![camphoto_1254324197](https://user-images.githubusercontent.com/39020445/39670469-cee37cb8-50d3-11e8-92b1-e4406b9e2886.JPG)
![img_3284](https://user-images.githubusercontent.com/39020445/39670472-d2a91006-50d3-11e8-95a9-d4ba7ce63cc1.jpeg)

Someone please fix this. Thanks

**Wallet version or commit SHA:**
0.2.4

**Environment:**
macOS Sierra 10.12.1 

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet: I do not. Only Switcheo.

**Comment by austinhinderer** [comment]
Have you actually added the custom token hash to your Neon wallet?

[132947096727c84c7f9e076c90f08fec3bc17f18](https://neotracker.io/asset/132947096727c84c7f9e076c90f08fec3bc17f18)

**Comment by snowypowers** [comment]
No response, closing.
