### ISSUE TITLE
GAS Claim Failed then GONE

### ISSUE THREAD

**Issue by Cubbies905** [CityOfZion/neon-wallet#107]
I had 58.1 GAS I was trying to claim yesterday after downloading NEON wallet.  I had build it up by storing in web wallet while I waited for a Mac client where I could claim the gas.  Yesterday I tried to claim the 58.1 which were showing up to claim, and it was giving me a claim failed message.  This morning I just opened up the wallet and there is no 0 gas showing in my account and 0 available to claim.  WTF?

**Comment by Cubbies905** [comment]
my public Key is Aeo8VCKRFBhEoT2tw1Qsd8Jh2jjKVoVLpY 

Please help!

**Comment by RealAtix** [comment]
https://neotracker.io/address/Aeo8VCKRFBhEoT2tw1Qsd8Jh2jjKVoVLpY
As you can see your unclaimed gas is still here.

The wallet is currently having an issue with displaying GAS.

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this.** As an aside, I've had to close about 10 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
