### ISSUE TITLE
Going to "Login using a Ledger" page after Ledger is auto-locked makes wallet unresponsible

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1078]
**Wallet version or commit SHA:**
0.2.4

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.431

**Prerequisites:**
Ledger wallet

**Reproduction steps:**
1. Connect Ledger wallet with USB port
2. Enter your PIN
3. Wait until Ledger auto-locks because of inactivity
4. Start Neon Wallet
5. Click on "Login using a Ledger" button

That's a corner case. Wallet is unresponsible after going to "Login using a Ledger" page if Ledger was locked using auto-lock feature. 

After starting the wallet with Ledger connected but not unlocked, wallet works fine and states "USB Error: No device found.". In case described above, wallet says "Looking for USB Devices." and makes wallet unresponsible.

**Screenshots/Video:**
![ledger issue](https://user-images.githubusercontent.com/8177587/39822866-fe4b3e7a-53ab-11e8-902e-6f9a8260ed0d.gif)

**Comment by comountainclimber** [comment]
No longer an issue in v2.0.0
