### ISSUE TITLE
"Refresh" button in "Balances" section calls wrong paths (localhost instead API host) (together with "Retry?" buttons)

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1079]
**Wallet version or commit SHA:**
0f2951a

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.431

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Select any saved wallet
3. Enter your passphrase
4. Click on "Login" button
5. Click on "Refresh" button in "Balances" section

"Refresh" button in "Balances" section calls wrong paths (localhost instead API host):
`file:///C:/Users/biuro/source/repos/neon-wallet/app/dist/undefined/v1/get_all_nodes`
Example from production release build:
`https://api.neoscan.io/api/main_net/v1/get_all_nodes`

This issue also applies to all "Retry?" buttons while there're connection issues in the wallet.

This issue is related to this PR: #1009. After checking it out and clicking on "Refresh" - same issue happens. It calls localhost.

**Screenshots/Video:**
- "Refresh" issue in "Balances" section
![refreshissue](https://user-images.githubusercontent.com/8177587/39826737-ed909a30-53b5-11e8-9459-6a53d7a58bf2.gif)
- "Retry?" issue while wallet has connection issues:
![retryissue](https://user-images.githubusercontent.com/8177587/39826738-edacf874-53b5-11e8-8f01-7cab1190f411.gif)

**Comment by alexhulbert** [comment]
@drptbl This issue has been fixed by PR #1177. Currently pending QA :ok_hand:

**Comment by drptbl** [comment]
@alexhulbert Tested, looks good. Thank you.
