### ISSUE TITLE
Neo coin (NOT GAS) balance in Neon wallet is not updating for days

### ISSUE THREAD

**Issue by photojacketman** [CityOfZion/neon-wallet#108]
Neo coin (NOT GAS) balance in my windows (10) Neon wallet is not updating in correlation with the current price. i.e. my balance has been stuck at $600 for the past several days.

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. You should also make sure to update to the latest version 0.0.3c, found on the sidebar of the subreddit or neo.org. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this**. As an aside, I've had to close about 10 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
