### ISSUE TITLE
Going to "Send" section too fast (or in offline mode) causes wallet to end in blank page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1081]
**Wallet version or commit SHA:**
0f2951a

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.431

**Prerequisites:**
At least one wallet imported to the app
Disconnect internet connection

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Click on "Send" section in sidebar navigation

If reproduction steps are done in offline mode, this issue always occur.
You can also reproduce this issue in online mode, if you go to "Send" section too fast (right after logging in to the wallet).

**Screenshots/Video:**

- Offline mode:
![send_offline_blank](https://user-images.githubusercontent.com/8177587/39829550-238c790c-53bf-11e8-97f2-f8ee7a1d0040.gif)

- Online mode:
![send_too_fast](https://user-images.githubusercontent.com/8177587/39829555-284e452e-53bf-11e8-80c2-041e68db4be2.gif)

**Comment by mhuggins** [comment]
Thanks for reporting.  I'm currently working on the v2 designs for the send screen, so this will go away with part of that.

**Comment by comountainclimber** [comment]
@alexhulbert is this still something you plan to work on?

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/pull/1297

**Comment by comountainclimber** [comment]
Fixed in design-v2 branch
