### ISSUE TITLE
Token Issues

### ISSUE THREAD

**Issue by Llc00lh** [CityOfZion/neon-wallet#1083]
**Wallet version or commit SHA:**
0.2.4

**Environment:**
Win 10 Home (64 bit) 

**Prerequisites:**
Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), 
after adding the token hash and saving, nothing seems to appear on the screen below the claim gas tab

**Screenshots/Video:**
![image3](https://user-images.githubusercontent.com/39170963/39891362-4042faa4-5495-11e8-83f0-910a6ef22ec2.jpeg)
![image1](https://user-images.githubusercontent.com/39170963/39891363-405e8116-5495-11e8-9656-2d8e150a82d4.jpeg)

**Comment by mhuggins** [comment]
@Llc00lh Does the address you're checking have a balance > 0 for those tokens?  What if you restart the app?

**Comment by Llc00lh** [comment]
I’ve not got any of the tokens that I am trying to add I don’t think, but even then the names should appear in the box. Yes I’ve restarted the and Reid talked it etc..

**Comment by mhuggins** [comment]
We intentionally filter out tokens that have a 0-balance.  This section becomes overwhelming otherwise.

**Comment by Llc00lh** [comment]
So if I am expecting an airdrop as have added the token hash, would this balance then appear on the screen when I receive the token?

**Comment by mhuggins** [comment]
That's right!

**Comment by Llc00lh** [comment]
great, thank you. can you then help me add the coins which i was due to get aridrops off, eg mct and ncc, they are the ones i know off.. ont i claimed through binance
