### ISSUE TITLE
Add 'import a wallet' feature like on Aphelion wallet

### ISSUE THREAD

**Issue by instamouse** [CityOfZion/neon-wallet#1086]
I want to be able to add a previously encrypted address as a saved wallet (without having to decrypt and re-encrypt)

**Comment by comountainclimber** [comment]
this is coming very soon @instamouse and the work is already completed 👍 https://github.com/CityOfZion/neon-wallet/pull/1070

**Comment by instamouse** [comment]
well done, keep up the good work!
