### ISSUE TITLE
TOKENS NOT SAVING AFTER LOADING HASH - APPEAR ON EXPLORER BUT CAN'T SEE IN WALLET

### ISSUE THREAD

**Issue by yokomson** [CityOfZion/neon-wallet#1089]
**Wallet version or commit SHA:**
Wallet 0.2.4

**Environment:**
Win 10 Home (64 bit) Version 

**Prerequisites:**
N/A

**Reproduction steps:**

1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button
5. Add TKY Script Hash: 132947096727c84c7f9e076c90f08fec3bc17f18
6. Click Save
7. Exit and enter wallet 

After clicking back into the wallet, the TKY token does not appear under "Token" where ONT is. Also, it doesn't appear it is being saved as if you go back under "Manage Tokens" it is no longer a saved script hash. However, under the explorer, the TKY token does appear under the address with which it was sent. 

**Screenshots/Video:**
N/A

**Comment by kimianiaga** [comment]
My Wallet Address in Explorer showed my ONT token value at 80.52423.  However, my Ledger S Wallet shows only 7.0000 tokens.  How can I get the remaining 73.52423 tokens into my Ledger Wallet Address.  I'm using Neon Wallet to access my Ledger S.

**Comment by drptbl** [comment]
This was probably caused because API your wallet was using were blocks behind. Please re-open if it's still an issue.
