### ISSUE TITLE
Neo GAS Balance No Longer Increasing and Zero

### ISSUE THREAD

**Issue by photojacketman** [CityOfZion/neon-wallet#109]
My Windows (10) wallet GAS balance is now zero and no longer accumulating GAS. Balance is zero and not increasing. I have 18 Neo in my wallet.

![image](https://user-images.githubusercontent.com/30982282/29251680-8206fbf4-8059-11e7-9b5e-6b0a1310f977.png)

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this**. As an aside, I've had to close about 10 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
