### ISSUE TITLE
Neon Wallet & Ledger Nano S: Transaction Failed - Too Big For Ledger To Sign

### ISSUE THREAD

**Issue by WarrickBotha** [CityOfZion/neon-wallet#1093]
I have Neon Wallet 0.2.4 and a Ledger Nano S with the latest firmware. Claiming GAS is fine, but I cannot send GAS from the wallet, no matter what amount of GAS I try to send, the wallet says that the Transaction Failed because the amount was too big for the Ledger to sign. 

Please help ?

![failed transaction](https://user-images.githubusercontent.com/39237707/39967165-fd9a7154-56b6-11e8-8da2-9d4fb39f5e0a.jpg)

**Comment by snowypowers** [comment]
The ledger can only take up to a certain number of inputs due to limited RAM, its about 25 inputs. So you will have to calculate how much GAS can you send in one shot.

You can find out your gas inputs by going to `https://neoscan.io/api/main_net/v1/get_balance/{address}` and checking out the `unspent` list for GAS.

**Comment by WarrickBotha** [comment]
Thanks for this suggestion. I have no technical computer knowledge. I did as you said AND there is a long list of about 31 transactions. What do I do with this info ? How do I set my Legder to send more transactions ? How do other people send more than a few NEO or GAS if this happens ?

**Comment by mhuggins** [comment]
Try adding up the sum of NEO from a handful of those transactions.  For example, if you have 5 transactions into your address for a total of 10.548 NEO, try sending exactly that amount to start.  The number of transactions you sum up should be no more than 25.

**Comment by WarrickBotha** [comment]
I appreciate the help guys, but I'm looking to fix this problem. Adding up prior transactions and then only being able to send that exact amount cannot be the solution here. Every time I send NEO/GAS from my NEON wallet, I want to send the exact amount that I want, not the sum total of all my prior transactions

**Comment by mhuggins** [comment]
Have you tried doing it? You'll find that it solves the problem.

**Comment by WarrickBotha** [comment]
If that could correct the problem from that point onward, then i will definitely try it tonight. Thank you all for the help, guys I will revert back tomorrow with a successful or failed attempt.

**Comment by mhuggins** [comment]
Yes, the source of the issue is that there are too many prior inbound transactions used to compose the next outbound transaction, then it won't fit on ledger memory.  By making a smaller outbound transaction that is comprised of < 25 inbound transactions, then it should fit in ledger memory.

**Comment by WarrickBotha** [comment]
Thank you so much guys, I starting sending 0,00000001 GAS and slowly sent more and more with each transaction and now it seems I can send any amount I want. I am completely blown away by the CoZ/NEO community and everyone's willingness to help. Thanks again.

**Comment by mhuggins** [comment]
Glad it's solved!
