### ISSUE TITLE
"Settings" position is missing from sidebar navigation

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1099]
**Wallet version or commit SHA:**
5d010f1

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button

"Settings" position is missing from sidebar navigation.

For reference check `2.0-Home-Light` designs.

**Screenshots/Video:**
![current](https://user-images.githubusercontent.com/8177587/40010856-4f19c56c-57a6-11e8-8e5b-b32badf12f2e.PNG)

**Comment by mhuggins** [comment]
Closing this since it's merged into `design-v2`.

**Comment by drptbl** [comment]
Re-tested, fixed.
