### ISSUE TITLE
update ANS and ANC references

### ISSUE THREAD

**Issue by canesin** [CityOfZion/neon-wallet#11]
Example:
https://github.com/CityOfZion/neon-wallet/blob/master/app/actions/index.js#L26

I see this in many places on the API for sending transactions itself, does this need the RCP nodes to adopt 2.0 before ? Low priority on this, as user facing can just show whatever you want.

**Comment by Ejhfast** [comment]
yes, this is important to iron out. we are already showing Neo and Gas on the frontend, but making sure underlying API remains compatible is critical. most of the important bits are encapsulated in JS SDK component

**Comment by Ejhfast** [comment]
Fixed in https://github.com/CityOfZion/neon-wallet/commit/60e1a415dc2aba7bb69d872a5d9c329c059c935a
