### ISSUE TITLE
Gas Value in my wallet still reading zero after 2 days

### ISSUE THREAD

**Issue by mycryptoinvestment** [CityOfZion/neon-wallet#110]
I observed that my Gas value is not being updated and reading zero since I started staking my neo coins in the neo wallet.
Please help me rectify this.

**Comment by mocmocamoc** [comment]
I'm also seeing zero gas available to be claimed at the moment, although I have successfully claimed some over the past week.

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this**. As an aside, I've had to close about 10 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
