### ISSUE TITLE
Graph doesn't update after changing time range on wallet dashboard

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1100]
**Wallet version or commit SHA:**
5d010f1

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Click on "1 Day" on top of graph to trigger change of graph time range

After going to wallet dashboard and trying to change time range of graph, there're errors thrown in console and graph is not getting updated. It worked before.

**Screenshots/Video:**
![brokengraph](https://user-images.githubusercontent.com/8177587/40011306-b1f77016-57a7-11e8-879b-5bb3d5d43118.gif)
![jserror](https://user-images.githubusercontent.com/8177587/40011310-b35fbea4-57a7-11e8-9bc8-99a094d267bb.PNG)

**Comment by alexhulbert** [comment]
@drptbl This has been fixed by PR #1176 to the best of my knowledge. Currently Pending QA :+1:

**Comment by drptbl** [comment]
@alexhulbert Looks good, thanks.
