### ISSUE TITLE
NEON Wallet not syncing with block explorers

### ISSUE THREAD

**Issue by Ronin4nana** [CityOfZion/neon-wallet#1102]
**Wallet version or commit SHA:**
0.2.4

**Environment:**
macOS High Sierra Version 10.13.4

**Prerequisites:**
Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Claim Gas
3. Sign Ledger twice
4. Check NEOScan and NEOTracker (Balances reflect GAS claim, but NEON doesn't adjust the GAS balance)
5. Continues to receive "Failed to obtain blockchain info"
6. Tried installing all NEON versions down to 0.1.4 and switching betweem Neontracker, NEOScan and Antchain. 
7. The block that displays on NEON is newer than the block that appears on each block explorer. The last transaction history reflects May 2, 2018, but nothing since even though there's been 2 invocations (May 10/11) and 2 GAS claims (Both today) since then.

**Comment by Ronin4nana** [comment]
Is the reason... because the wallet is not synced? http://monitor.cityofzion.io/ 
#2,263,673  (-5,041)

**Comment by ciconsulting** [comment]
Probably related. When I open my wallet (v0.2.4, macOS) it displays a block number that is about 10-20 blocks behind the [CoZ monitor](http://monitor.cityofzion.io/). This number never advances no matter how long I leave the wallet open, although the popup that says "Success. Received latest blockchain information." does appear from time to time.

**Comment by Ronin4nana** [comment]
https://www.reddit.com/r/NEO/comments/8jlkmg/neon_lag_there_is_currently_a_ongoing_ddos_attack/?st=jh7tfgtr&sh=b81ed190

**Comment by Ronin4nana** [comment]
Temporary work around, use the Aphelion wallet. https://aphelion.org/#wallet NEON sync is currently -10k blocks

**Comment by drptbl** [comment]
This is caused because of current on-going issues with neon-wallet API (`api.neonwallet.com/v2/`) and neoscan API (`api.neoscan.io`) are under DDoS attack.

More details here:
https://www.reddit.com/r/NEO/comments/8jlkmg/neon_lag_there_is_currently_a_ongoing_ddos_attack/

You can check that currently neon-wallet API is ~12500 blocks behind (http://monitor.cityofzion.io/).
After it's fixed, everything will be back to normal.
