### ISSUE TITLE
"Calculating claimable GAS failed" error message

### ISSUE THREAD

**Issue by PiiggyBank** [CityOfZion/neon-wallet#1103]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
Version0.2.4

**Environment:**
MacOS High Sierra
Version 10.13.4

**Prerequisites:**
have claimable GAS

**Reproduction steps:**

1. Start Neon Wallet
2. Click on Login" via ledger
3. "Click" claim GAS
4. Sign first transaction 
5. 1-2 minutes elapse 
6. GAS balance toggles from .044 to .031
7. Balance toggle between first scene amount and slightly smaller amount
8. Error received: "Calculating claimable GAS failed."

![screen shot 2018-05-14 at 3 06 16 pm](https://user-images.githubusercontent.com/39282430/40026628-e9ac2960-578a-11e8-9cfb-20f1f9e56208.png)

**Comment by andersonaguiar** [comment]
Same here

**Comment by vergotle** [comment]
Same for me.

**Comment by gwoody83** [comment]
Same here but log in thru saved wallet.

**Comment by ncsolar** [comment]
Same issue for me

**Comment by buddhaman8** [comment]
Same here, 3 days on off on off...!  0.2.4 on MAC os

**Comment by PiiggyBank** [comment]
Update: Finally able to claim GAS but it does not show in the transaction history..?

**Comment by Bazooka2304** [comment]
Same here

**Comment by drptbl** [comment]
This is mostly caused because of current on-going issues with neon-wallet API (`api.neonwallet.com/v2/`) and neoscan API (`api.neoscan.io`) are under DDoS attack.

More details here:
https://www.reddit.com/r/NEO/comments/8jlkmg/neon_lag_there_is_currently_a_ongoing_ddos_attack/

You can check that currently neon-wallet API is ~12500 blocks behind (http://monitor.cityofzion.io/).
After it's fixed, everything will be back to normal.

**Comment by iody** [comment]
im still not able to claim gas same issue?

**Comment by joe1234555** [comment]
This is happening again?

**Comment by NicksDee** [comment]
same problem with me. Using Ledger Nano S and Neon Wallet on Macbook. I even can't receive NEO's I transferred from Binance to my Ledger Address. Binance Tx still showing Processing for last few hours. I already tried uninstalling and re-installing the NEO from Ledger. Also, I reinstalled NEON Wallet on my MacBook. Same error. i can't even withdraw NEOs from my wallet anymore. any help?

**Comment by sfaisal-modus** [comment]
+ 1

**Comment by AtHeartEngineer** [comment]
Also having this issue, mac 10.14,  latest neon wallet, can't claim any gas.
