### ISSUE TITLE
After installing Neon Wallet and trying to login using Ledger Nano S I get Access is Denied

### ISSUE THREAD

**Issue by xxMAGICxx** [CityOfZion/neon-wallet#1109]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
0.2.4

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.431

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**

After installing the new Neon wallet and trying to login using my ledger it says Access is denied and gives me the location of a tmp.node file in my hard drive

**Comment by canesin** [comment]
Is your Ledger update to firmware 1.4.2 ?
