### ISSUE TITLE
US and GAS not updating

### ISSUE THREAD

**Issue by bouncyenemy** [CityOfZion/neon-wallet#111]
The US price and GAS button have not updated for about 15 hours. Is this a self-correcting issue or is there some action I can take to resolve it? Thanks!

**Comment by tradersu** [comment]
Think this is a widely reported problem on reddit, I'm having the same issue, frustrating.

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this**. As an aside, I've had to close about 10 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
