### ISSUE TITLE
Security for NEON Wallet

### ISSUE THREAD

**Issue by ethbeta** [CityOfZion/neon-wallet#1114]
I hope the team developed the City of Zion will complement more functional 2FA security through Google Authenticator or mail account owners, it is necessary, I am very worried when using for on my computer It can be hack private key at any time if my computer being monitored by hacker, so I would need a second layer of security can help more secure when used. Thanks!

**Comment by benohanlon** [comment]
Buy a Nano S Ledger and use that with the wallet.

**Comment by canesin** [comment]
2FA is a centralized solution not applicable.
