### ISSUE TITLE
Gas showing 0

### ISSUE THREAD

**Issue by martythekid** [CityOfZion/neon-wallet#112]
I've been holding Neo in the Neon wallet since last week. On Friday, my Gas was accumulating. Today when I checked the wallet the gas was back to 0 but I have not claimed any. Is there a fix for this? Thanks!

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this**. As an aside, I've had to close about 10 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
