### ISSUE TITLE
"Block" value doesn't update in the wallet (it's only set once when wallet is started)

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1131]
**Wallet version:**
0.2.5

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
- At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Look at "Blocks" value in the wallet header
5. Wait some time, let's say 15 minutes

After waiting you can notice that value of "Blocks" didn't change. It's fetched once while wallet is started and is never updated again.

**Screenshots/Video:**
![blocks](https://user-images.githubusercontent.com/8177587/40248847-7fb9ca90-5ad1-11e8-8ac7-9f4f68d0e185.PNG)

**Comment by ilconduttore** [comment]
same here

**Comment by drptbl** [comment]
This is fixed in #1264. Thanks.
