### ISSUE TITLE
My NEO balance is showing "0" after I deposited NEO yesterday successfully

### ISSUE THREAD

**Issue by 7jai** [CityOfZion/neon-wallet#114]
Hi there,

Yesterday I successfully deposited NEO into my NEON wallet, and saw transaction history listed.   This morning when I login, it showed me a "0" balance and also has no transaction history.

I am currently using the latest 0.0.3 version as well for windows.

Could you please advise?

Thank you in advance for your help.

**Comment by raj-indulkar** [comment]
Neon wallet does not recognize fractional values. For example if you send 1.9 Neo to the wallet, you will only get credited with 1 NEO and you will lose the fractional value of .9, even though you paid for it.

Also .1 to .2 neo approx, is the transfer fee (charged by most exchanges, like bittrex), so when you are transferring amount to the wallet, send say 2.2 neo, so you get credited with 2 neo. If you send 2 neo, only 1.9 will be sent after the fee is deducted, and the neon wallet ignore the decimal balace of 0.9 and your wallet will only be credited with 1 neo.

**Comment by cdncoin1962** [comment]
I've found out where my coins are going and I'm not happy at all. Whoever is at address 
AR4QmqYENiZAD6oXe7ftm6eDcwtHk7rVTT has my missing coins and I want them back.

The exchange isn't the problem, and NEON is NOT just ignoring the fraction. The owner of that address is rounding down and stealing the remainder.

<img width="919" alt="screen shot 2017-08-14 at 10 47 54 am" src="https://user-images.githubusercontent.com/31006174/29274961-ef09a946-80df-11e7-80d0-144557265fa2.png">

--

**Comment by cdncoin1962** [comment]
Also....when I try to scan that address, I get a "timed out" message. Every time!

**Comment by cdncoin1962** [comment]
Whoever is address   AR4QmqYENiZAD6oXe7ftm6eDcwtHk7rVTT   they've collected a lot of NEO by taking peoples coin fractions.
<img width="577" alt="screen shot 2017-08-14 at 11 08 33 am" src="https://user-images.githubusercontent.com/31006174/29275353-39e6cec0-80e1-11e7-81af-31aa4464c63d.png">

**Comment by canesin** [comment]
Does your installer has the official hashes ?
Hashes

Mac: 75e28561366fce63338d930f83ad6bb88cbff7bd17820fb860e48f7e882d8f42
openssl sha -sha256 Neon-0.0.3.dmg

Windows: c5efab9ebde83c598b98d959fbfec061285489f8a6ebf270600d1ec3abb9e293
certUtil -hashfile "Neon Setup 0.0.3.exe" SHA256

Linux (appimage): 73a7c29453dc0b3324eec1d18a6183f30d46c6da4b1f5be9a32eed1d48df9d77
sha256sum Linux.Neon-0.0.3-x86_64.AppImage.tar.gz

Linux (debian): c52c2bc775b5f7ff1ab9514c3ca3918044b134ba99d10ea08036356b75ba5594
sha256sum Linux.Neon_0.0.3_amd64.deb.tar.gz

**Comment by anfn101** [comment]
"Whoever is at address
AR4QmqYENiZAD6oXe7ftm6eDcwtHk7rVTT has my missing coins and I want them back."

For Neo, Neon is unable to even accept fractions. When sending to any address, not just one created in Neon, that is the case. Neon has nothing to do with that. That is Bittrex's wallet address... nobody but an exchange could have that amount. This is related to the Bittrex fraction issue. This is not anything new.

**Comment by cdncoin1962** [comment]
Interesting....I sent Bittrex that address, & told them I want my coins
back and very soon after, the entire exchange is shut down for "database
maintenance". Hopefully this issue is one of their "database maintenance"
issues being resolved. It makes me sick to see people being ripped off by
anyone.

**Comment by cdncoin1962** [comment]
Looks like they are back up and running. Only thing I see new is this....
