### ISSUE TITLE
"Edit" and "Delete Contact" buttons should be wider on "Contacts" page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1141]
**Wallet version or commit SHA:**
ed179d5

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Click on "Contacts" section in sidebar navigation

Compare "Edit" and "Delete Contact" buttons width with these on designs. Currently they're a lot shorter. Also the spacing between icons and labels should be fixed after that.

**Expected design:**
- `6.0-Contacts-Light`

**Screenshots/Video:**
![buttons](https://user-images.githubusercontent.com/8177587/40589975-45a59a46-61f7-11e8-99f0-a249942a683a.PNG)

**Comment by mhuggins** [comment]
Marking as closed, ready for QA on `design-v2` branch.
