### ISSUE TITLE
"Pencil" icon is broken inside "Edit" button on "Contacts" page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1142]
**Wallet version or commit SHA:**
ed179d5

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Click on "Contacts" section in sidebar navigation

As shown on screenshot, pencil icon is broken.

**Expected design:**
- `6.0-Contacts-Light`

**Screenshots/Video:**
![edit](https://user-images.githubusercontent.com/8177587/40589983-7c4c7d9e-61f7-11e8-9e38-dbe585b4662d.PNG)

**Comment by mhuggins** [comment]
Marking as closed, ready for QA on `design-v2` branch.
