### ISSUE TITLE
"New contact" button icon differs from designs on "Contacts" page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1143]
**Wallet version or commit SHA:**
ed179d5

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Click on "Contacts" section in sidebar navigation

"New contact" button icon should be different. The one currently used should be used only on "New contact" page, but not on "Contacts".

**Expected design:**
- `6.0-Contacts-Light`

**Screenshots/Video:**
![newcontact](https://user-images.githubusercontent.com/8177587/40590000-ec835a2e-61f7-11e8-8f11-d016cd0ec0ba.PNG)

**Comment by mhuggins** [comment]
We don't have that icon in SVG format, I'll have to see if @asalib is able to extract it and send it over.  This is what is looks like according to the Invision designs:

<img width="162" alt="screen shot 2018-05-28 at 3 17 02 pm" src="https://user-images.githubusercontent.com/169093/40628368-3a33ee2c-628a-11e8-8d8b-fdce652f3613.png">

**Comment by asalib** [comment]
That's actually a mistake on my part. Original icon is correct. SVG attached.

Sorry github doesn't support svg uploads, had to zip it.
[Contact-Add.svg.zip](https://github.com/CityOfZion/neon-wallet/files/2046328/Contact-Add.svg.zip)

**Comment by drptbl** [comment]
Tested, looks good. Thanks.
