### ISSUE TITLE
Label on "Add Contact" page should be changed to "New Contact"

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1144]
**Wallet version or commit SHA:**
ed179d5

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Click on "Contacts" section in sidebar navigation
5. Click on "New Contact" button

Currently the title of the page is "Add Contact". It should be changed to "New Contact" according to designs.

**Expected design:**
- `6.1-AddEditContact-Light`

**Screenshots/Video:**
![addcontact](https://user-images.githubusercontent.com/8177587/40590038-87a83524-61f8-11e8-812b-d692088cdadc.PNG)

**Comment by mhuggins** [comment]
Marking as closed, ready for QA on `design-v2` branch.
