### ISSUE TITLE
Label inside "Save Contact" button should be changed to "Add to Contacts"

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1145]
**Wallet version or commit SHA:**
ed179d5

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Click on "Contacts" section in sidebar navigation
5. Click on "New Contact" button

Currently label states "Save Contact". It should be changed to "Add to Contacts" according to designs.

**Expected design:**
- `6.1-AddEditContact-Light`

**Screenshots/Video:**
![savetocontact](https://user-images.githubusercontent.com/8177587/40590079-171a4c10-61f9-11e8-80e6-67d00c025907.PNG)

**Comment by mhuggins** [comment]
Marking as closed, ready for QA on `design-v2` branch.
