### ISSUE TITLE
Labels, fields and icons should be centered horizontally on "Create Wallet" page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1146]
**Wallet version or commit SHA:**
ed179d5

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "New Wallet" button
3. Fill "Wallet Name" input field together with passphrases
4. Click on "Create Wallet" button

It doesn't look good currently. Labels, fields and icons should be centered horizontally. Also there should be more spacing between labels and fields (look at "Public Address" label).

**Screenshots/Video:**
![createnewwallet](https://user-images.githubusercontent.com/8177587/40590286-a792cb70-61fc-11e8-9e84-d6b00450a72c.PNG)

**Comment by mhuggins** [comment]
Fixed by #1155, pending QA.

**Comment by drptbl** [comment]
Can we also add more spacing between labels and fields?

![retest](https://user-images.githubusercontent.com/8177587/41008723-d010a6b2-692c-11e8-86ca-6c74bbd2071a.PNG)

**Comment by drptbl** [comment]
Re-tested, there are more improvements to be done on this screen but I will create separate tickets for them. Thanks.
