### ISSUE TITLE
No Side Effect model?

### ISSUE THREAD

**Issue by ryanbas21** [CityOfZion/neon-wallet#115]
I noticed reading through the source that there doesn't seem to be a side effect model at play.

There are asynchronous requests occurring like `setTimeout` that are not being handled. This becomes an issue in functional programming especially in Redux because it depends on the idea of deterministic state rendering and not handling side effects can break that.

Has this been discussed or thought about?

I personally like redux-saga, however im not sure if streams may be more appropriate for this type of an application, in which case maybe `redux-observable`?

Also perhaps for a seperate issue, it may be worth implementing prettier and an eslint file that you guys like so that OSS contributions can keep that styling.

**Comment by canesin** [comment]
@ryanbas21 just a product of the speed things are going.. if you want to PR an MVP for your idea that would be great (just don`t loose to much time as this can go to trash, just to put discussion on more concrete basis).

**Comment by shawnmclean** [comment]
This falls under #216 now.
