### ISSUE TITLE
USD Value not updating?

### ISSUE THREAD

**Issue by J0rdi3** [CityOfZion/neon-wallet#116]
Hey guys,

Is anyone else having an issue with the USD value of your NEO not updating?

I have 40 NEO, and it is saying it is only $1364.58 (it has been stuck on this for a few days)...it should be much higher.

Any ideas?

<img width="461" alt="screen shot 2017-08-14 at 12 39 09 pm" src="https://user-images.githubusercontent.com/30992987/29256431-aa9011ca-80ed-11e7-9c12-9321d619698b.png">

**Comment by Shaunt90** [comment]
Having the same issue. Look forward to hearing a suggestion, also looking forward to seeing the balance go up!

**Comment by anfn101** [comment]
You should all update to the latest wallet version - go to neo.org to find the link.
