### ISSUE TITLE
USD Value Not Updating

### ISSUE THREAD

**Issue by J0rdi3** [CityOfZion/neon-wallet#117]
Please review this post as this issue hasn't been resolved in the update 8-9 days ago.

Using the latest 0.0.3c update directly from neo.org for MAC.

The USD value is not updating in accordance to coinmarketspot/bittrex. Clearly API isn't working.

Tried re-install, still not working....

This value should represent $2000 +
<img width="461" alt="screen shot 2017-08-14 at 12 39 09 pm" src="https://user-images.githubusercontent.com/30992987/29256840-aa1abef4-80f0-11e7-86ec-28720bd5e680.png">

**Comment by J0rdi3** [comment]
@anfn101 - please review this, rather than closing it.

**Comment by anfn101** [comment]
This is not the proper channel for support. **Github is for code and developer discussion.** Please either find help on our subreddit or our support Slack, a link for which can be found on the sidebar of the subreddit. Thanks.
