### ISSUE TITLE
Phantasma Protocol can not be added to the wallet 

### ISSUE THREAD

**Issue by sha7171** [CityOfZion/neon-wallet#1170]
I am having problem adding the Phantasma Protocol token to my neon wallet 

**Wallet version or commit SHA:**       0.2.5
**Environment:** Win 7 Enterprise  (64 bit) 
**Prerequisites:**
 I have added "Phantasma Protocol custom token (SOUL) " but it does not appear in the wallet dashboard  

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "+ Add a new token to purchase" button
3. Enter the scrip hash of the token  and then click “save”. 
     Hash: 4b4f63919b9ecfd2483f0c72ff46ed31b5bbb7a4
4. Press the refresh button and the token should appear

I did the above steps but  the token did not appear in the dashboard

The attached files:
1. Screen shot of my wallet scan from "neoscan.io" shows the token in my wallet .
2. Screen shot of of the Neon wallet shows the Hash I have added and the tokens in the dashboard
3. Phantasma Protocol Contract
![token hash confirmation](https://user-images.githubusercontent.com/39863051/40879867-5a8b5b06-66b8-11e8-8573-addb617cc2c5.jpg)
![wallet screen shot](https://user-images.githubusercontent.com/39863051/40879941-717006cc-66b9-11e8-8e96-d84f9886a157.jpg)
![neoscan screen capture](https://user-images.githubusercontent.com/39863051/40879942-7cc4e678-66b9-11e8-8650-f5392d788b4d.jpg)

**Comment by Relfos** [comment]
The correct scripthash for Phantasma Protocol is:
ed07cffad18f1308db51920d99a2af60ac66a7b3

**Comment by sha7171** [comment]
Thanks Relfos :+1: 
There are two Hash addresses for Phantasma Protocol in Neo Tracker website

Use the one given by Relfos : ed07cffad18f1308db51920d99a2af60ac66a7b3
