### ISSUE TITLE
0.2.5 Not showing TNC Tokens

### ISSUE THREAD

**Issue by Couch77** [CityOfZion/neon-wallet#1172]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by Couch77** [comment]
I have just downloaded neon wallet 0.2.5 and my TNC token balance is not showing. It was showing in the previous version of the wallet. The only tokens I can see are NEO, GAS, ONT and MCT, but not TNC.

**Comment by austinhinderer** [comment]
[You need to add the custom token hash in Neon wallet.](https://www.reddit.com/r/TrinityTNC/comments/7we3v8/trinity_neon_wallet_step_by_step_guide_how_to_add/)

> Click Manage Neon Settings > Manage Tokens > Add New Token > Paste
> 08e8c4400f1af2c20c28e0018f29535eb85d15b6

**Comment by Couch77** [comment]
Hi Austin,

 

Thank you for your reply. That fixed the problem and I am most grateful to you.

 

Thank you so much, and have a great day.

 

Kind Regards

 

Angelo.
