### ISSUE TITLE
Show "GAS Claim unavailable" instead of "Claim 0.00000000 GAS" if get_unclaimed request failed

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1178]
**Wallet version or commit SHA:**
 `fix-connectivity-issues` branch (a134a66)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
- Any app for intercepting of HTTP requests
- At least one wallet imported to the app

**Requested url:**
`api.neoscan.io/api/main_net/v1/get_unclaimed/{wallet_addr}`

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Start intercepting
5. Click on "Refresh account balance" button
6. After url mentioned above is intercepted, drop it (or change response to `{}` or `[]`)

If `get_unclaimed` is dropped it shows "Claim 0.00000000 GAS". It should show "GAS Claim unavailable" label instead. It works on `null` but doesn't work for other cases.

**Screenshots/Video:**
![claim_0](https://user-images.githubusercontent.com/8177587/40949476-87ed05f6-686e-11e8-83a5-66776523f949.PNG)

**Comment by evgenyboxer** [comment]
@drptbl Fixed on branch

**Comment by drptbl** [comment]
Works good now on first wallet login, but on manual/automatic refresh it still has some issues.

**Comment by comountainclimber** [comment]
No longer an issue in v2.0.0
<img width="462" alt="screen shot 2018-11-26 at 9 54 01 pm" src="https://user-images.githubusercontent.com/13072035/49059377-d50c3b00-f1c5-11e8-9307-cb8e8950a654.png">

**Comment by drptbl** [comment]
Re-tested, doesn't happen anymore.
