### ISSUE TITLE
Typo inside "GAS Claim unavailable" tip

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1179]
There's a "Claimng GAS" text inside the tip instead of "GAS Claiming".

**Screenshots/Video:**
![typo](https://user-images.githubusercontent.com/8177587/40949576-f47210c2-686e-11e8-9387-9aa823d5af95.png)

**Comment by evgenyboxer** [comment]
@drptbl fixed on branch

**Comment by drptbl** [comment]
Tested, works good. Thanks.
