### ISSUE TITLE
Don't show USD values if prices from coinmarketcap couldn't be fetched

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1180]
**Wallet version or commit SHA:**
 `fix-connectivity-issues` branch (a134a66)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
- Any app for intercepting of HTTP requests
- At least one wallet imported to the app
- Any balance on the wallet with USD value

**Requested url:**
`api.coinmarketcap.com/v1/ticker/?limit=0&convert=USD`

**Reproduction steps:**
1. Start intercepting
2. Start Neon Wallet
3. After url mentioned above is intercepted, drop it (or change response to `null`)
4. Click on "Login using a saved wallet" button
5. Select your wallet, enter your passphrase and click on "Login" button

If price from coinmarketcap couldn't be fetched, we shouldn't show USD values for NEO, GAS and Total.

**Screenshots/Video:**
![cccap](https://user-images.githubusercontent.com/8177587/40949684-7dccb5ac-686f-11e8-9c58-58050c12873a.PNG)

**Comment by evgenyboxer** [comment]
@drptbl fixed on branch

**Comment by drptbl** [comment]
Tested, works good. Thanks.
