### ISSUE TITLE
Unnecessary blank page with loader on wallet refresh if request has failed on first login to the wallet

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1181]
**Wallet version or commit SHA:**
 `fix-connectivity-issues` branch (a134a66)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
- Any app for intercepting of HTTP requests
- At least one wallet imported to the app

**Requested url:**
`api.neoscan.io/api/main_net/v1/get_transaction_history/{wallet_addr}`
or
`api.neoscan.io/api/main_net/v1/get_all_nodes`

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Start intercepting
4. Select your wallet, enter your passphrase and click on "Login" button
5. After url mentioned above is intercepted, drop it (or change response to `null`)
6. Click on "Refresh account balance" button or wait for automatic refresh of the wallet

If you login to the wallet for first time and drop any of these requests - `get_transaction_history` or `get_all_nodes` - and then click on "Refresh account balance" (or wait for automatic refresh), wallet changes to a blank page with loader for a while. If next try is success, it won't appear again (the blank page with loader). But if any of these request fail constantly, blank page with loader will appears every time.

**Screenshots/Video:**
![blankpage](https://user-images.githubusercontent.com/8177587/40949812-1c124ede-6870-11e8-9fbf-1ce36fbed273.gif)

**Comment by comountainclimber** [comment]
Fixed https://github.com/CityOfZion/neon-wallet/releases/tag/2.0.0 🎉
