### ISSUE TITLE
"Failed to retrieve blockchain information." error show up if any of the requests has failed on wallet refresh

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1182]
**Wallet version or commit SHA:**
 `fix-connectivity-issues` branch (a134a66)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
- Any app for intercepting of HTTP requests
- At least one wallet imported to the app

**Requested url:**
- any url called on wallet refresh (`get_transaction_history` for example)

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Start intercepting
5. Click on "Refresh account balance" button
6. After url mentioned above is intercepted, drop it (or change response to `null`)

If any request which is called on wallet refresh has failed, "Failed to retrieve blockchain information" error shows up. Shouldn't it show up only if some specific requests failed and not on all of them?

**Screenshots/Video:**
![failed_](https://user-images.githubusercontent.com/8177587/40949978-f11106d4-6870-11e8-9935-e9cb3b2363ad.PNG)

**Comment by clieo** [comment]
I received "failed to retrieve blockchain information" when I put my neo wallet on "running on Mainnet". When I put the wallet on "Testnet" or "Coz Testnet", it shows "received latest blochchain information". My neo balance is showing "0" although I have neo in the wallet. How do I fix this?

**Comment by nealmcfarlane** [comment]
I have the same issue, Version 0.2.6

**Comment by iosazee** [comment]
I have the exact same issue. #COZ, what can we do to resolve this?

**Comment by clieo** [comment]
I found a way and here it is: after opening the wallet, go to "manage neo settings" and choose "neoscan" under "block explorer". You will see your wallet and also be able to send and receive.

**Comment by clieo** [comment]
See my post on github.

**Comment by comountainclimber** [comment]
Fixed in v2.0.0

**Comment by drptbl** [comment]
Re-tested, fixed in v2.
