### ISSUE TITLE
Transaction history from before error shouldn't show up until get_transaction_history request has finished

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1183]
**Wallet version or commit SHA:**
 `fix-connectivity-issues` branch (a134a66)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
- Any app for intercepting of HTTP requests
- At least one wallet imported to the app

**Requested url:**
- `api.neoscan.io/api/main_net/v1/get_transaction_history/{wallet_addr}`

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Start intercepting
5. Click on "Refresh account balance" button
6. After url mentioned above is intercepted, drop it (or change response to `null`)

If there was an issue with `get_transaction_history` and "Failed to load transactions" message show up, then after you click on "Refresh account balance" button, you can see that old transaction history shows up again (the disabled one) until `get_transaction_history` request is processed again. This could cause flickering of transaction history if request is going to fail constantly.

**Screenshots/Video:**
![trans_fail](https://user-images.githubusercontent.com/8177587/40950120-a80552f0-6871-11e8-8bfa-76ab9a1160c9.gif)

**Comment by evgenyboxer** [comment]
@mhuggins is it possible to reset an action when getting an error?

**Comment by comountainclimber** [comment]
No longer an issue in v2.0.0

**Comment by drptbl** [comment]
Tested, doesn't happen in v2 anymore.
