### ISSUE TITLE
Enviroment , how to win10 home? Squeeki55

### ISSUE THREAD

**Issue by Sqeeki55** [CityOfZion/neon-wallet#1188]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by Sqeeki55** [comment]
How do I start Neon wallet, I believe that I have in the beginning and a key with 2 barriers so it cant be hacked nextmanagneon settings button? Next click  on manage tokens-- no idea lastly it saysclick add a new token button  confusedSqueeki55

**Comment by Sqeeki55** [comment]
I` ll take any help high light ateas I need to click ?????? Thanks

**Comment by drptbl** [comment]
I'm sorry but I'm not sure if I understand.

**Comment by Sqeeki55** [comment]
Sorry dont need anything now
