### ISSUE TITLE
can not copy/paste into NEON wallet for mac...

### ISSUE THREAD

**Issue by halfwayline15** [CityOfZion/neon-wallet#119]
tried to copy and paste the private key in to the login but no joy. Surely we re not expected to type it in manually?

**Comment by aars** [comment]
Works fine here. (10.12.6)

**Comment by halfwayline15** [comment]
could be that I'm still using Yosemite?

**Comment by johnwillc** [comment]
same problem here no copy and paste windows 10.

**Comment by halfwayline15** [comment]
oh ok...and thats on Windows too then! 
I've quite a few NEO so don't want them on an unreliable wallet?

**Comment by canesin** [comment]
Use ctrl+v to paste the key on windows, or command+v on mac.
