### ISSUE TITLE
Handle a case when get_claimable request failed after clicking on "Claim X GAS" button

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1192]
**Wallet version or commit SHA:**
0.2.5

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
- Any app for intercepting of HTTP requests
- At least one wallet imported to the app
- Any amount of GAS to claim

**Requested url:**
`api.neoscan.io/api/main_net/v1/get_claimable/{wallet_addr}`

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Start intercepting
5. Click on "Claim X GAS" button
6. After url mentioned above is intercepted, drop it (or change response to `null`)

If `get_claimable` is dropped it shows part of JavaScript error in the notification currently.

**Screenshots/Video:**
![gas_failed](https://user-images.githubusercontent.com/8177587/41007603-e20379f4-6926-11e8-8f6c-6d99edf56507.PNG)

**Comment by comountainclimber** [comment]
Closing this in favor of consolidating here #1674
