### ISSUE TITLE
Neo and Gas Balance showing 0 in Ledger Nano S,Please HELP!!!

### ISSUE THREAD

**Issue by grishatataru** [CityOfZion/neon-wallet#1193]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: Latest One

**Environment:**
e.g.: Mac OS 10.13.15

**Prerequisites:**
e.g.: Neo and Gas Balance Showing 0

**Reproduction steps:**
e.g.:
1. Uninstalled NEON WALLET
2. Installed the latest Update
3. Turn ledger Nano on and off few times
4. Refreshed many times

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by snowypowers** [comment]
closing due to insufficient information
