### ISSUE TITLE
Neon Wallet Windows 10 - Cant log into new wallet

### ISSUE THREAD

**Issue by Nixeus42** [CityOfZion/neon-wallet#120]
Good day

Cant log into new NEON wallet on PC. Cant copy and paste private key and try typing it as well. Nothing happens when you click the login button.

Regards

**Comment by totalvm** [comment]
Are you sure the private key is okay?
Also did you create the wallet with the Neon Wallet itself?

**Comment by Nixeus42** [comment]
Yes I copied the key from the wallet created. It does not allow me to paste
and when I manually type it I cant click login. Nothing happens.

Using Windows 10. Please assist. I created another new wallet. Same issue.

Regards

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by canesin** [comment]
Can't reproduce, must be a local issue.

![image](https://user-images.githubusercontent.com/353648/29280029-b431ea06-80e7-11e7-8c91-ba8597ce426b.png)

![image](https://user-images.githubusercontent.com/353648/29280050-c8d79820-80e7-11e7-9074-71fd3c2d2fa0.png)

![image](https://user-images.githubusercontent.com/353648/29280056-cdc42f38-80e7-11e7-8045-4dcb2d2a05a5.png)

**Comment by canesin** [comment]
**Use Ctrl+V to paste the key**:
![image](https://user-images.githubusercontent.com/353648/29280094-e8dddfe4-80e7-11e7-8349-70db63b16dc8.png)
![image](https://user-images.githubusercontent.com/353648/29280123-03484c8e-80e8-11e7-9351-bf1ec2d70354.png)
![image](https://user-images.githubusercontent.com/353648/29280129-06d5a554-80e8-11e7-911d-fc5176715f6c.png)

**Comment by Nixeus42** [comment]
You are the man. Thanks a million

**Comment by anfn101** [comment]
Remember- **Github is not a support desk and should NEVER be used as such**... Issues like this can be reported on Reddit or in our support Slack (link found on the sidebar of the subreddit). Thanks.
