### ISSUE TITLE
Some values become incorrect when clicking the date dropdown on the historic prices graph

### ISSUE THREAD

**Issue by alexhulbert** [CityOfZion/neon-wallet#1204]
This issue was originally discovered by @drptbl
-------------------------------------------------------------

**Wallet version or commit SHA:**
a91d1ae

**Environment:**
OS: Ubuntu 16.10
Arch: x86_64
Kernal Version: 4.11.2-041102-generic
(This also happens on Win 10 Home (64 bit) Version 1803 Build 17134.48, as reported by @drptbl )

**Prerequisites:**
- Active network connection

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Log into a saved wallet
3. Click the "1 month"/"1 day"/"1 week" button in the top right corner

some description (for ex. what happens after completing reproduction steps), e.g.:
- The current neo/gas value on the top center of historic price graph sometimes goes up or down by a cent
- The percentages in the "balances" section change to not reflect a single day of changes. The time span they represent decreases to an hour.

**Screenshots/Video:**
![graph_issues](https://user-images.githubusercontent.com/2229212/41124990-8f3607d6-6a71-11e8-97cb-1996c66b54e2.gif)

**Comment by drptbl** [comment]
Re-tested, looks good.
