### ISSUE TITLE
Cant open the wallet 

### ISSUE THREAD

**Issue by Lassithedog** [CityOfZion/neon-wallet#1207]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**  Neon wallet 0.2.5
**Environment:**
e.g.: Win 10 Home (64 bit) Version 1804 Build 17134.81

**Prerequisites:**
The moment when issue started i only had NEO in the wallet. the issue started immediately. i was in my wallet and first time using it when the wallet stalled and my computer crashed. upon restart i got a missing dll. error.  ERROR IN C:\\WINDOWS\SYSTEM32\NVSPCAP64.DLL MISSING ENTRY: SHADOWPLAYONSYSTEMSTART

**Reproduction steps:**
e.g.:
1. Start Neon Wallet, get a javascript error and unable to start it. I also cant uninstall it. i get an error that uninstallation location does not exist. if reinstall neonwallet i can use it. 

some description (for ex. what happens after completing reproduction steps), e.g.:
If i restart the computer then i get the automatic error message on my screen. If i try to open neonwallet i get the javascript error. if i reinstall neonwallet it works. but once i restart the computer the same issue comes back immediately. 

**Screenshots/Video:**
below the screenshot of the javascript error when i try to open the wallet. 

![image](https://user-images.githubusercontent.com/40056643/41148089-c5cb717e-6b10-11e8-9791-6b2f62446371.png)

**Comment by totalvm** [comment]
This may sound weird, but can you update your Graphic Card drivers?
The error you are getting is from nvidia shadowplay, so it might have something to do with it

**Comment by Lassithedog** [comment]
hi, thanks. i did that. and the error on shadowplay disappeared. but the javascript error stays. so i am unable to open the neon wallet

**Comment by totalvm** [comment]
could you try installing the app as an admin and see if that works?

**Comment by Lassithedog** [comment]
hi, mm. maybe im stupid but what do you mean by installing as an admin? As I of course have Admin rights when running the install on my PC. :)

**Comment by totalvm** [comment]
right click on the installer file and do "execute as admin", normally this shouldn't matter though.

**Comment by Lassithedog** [comment]
Hi, i did as you suggested but the problem remains. It seems that MCafee AV finds the installer as a thread and places it in quarantine. MAybe this has something to do with it as well. long story short with my current set up i am unable to use the neonwallet.

**Comment by drptbl** [comment]
@Lassithedog If MCAfee AV places some of the files from Neon Wallet in quarantine, there's nothing weird that wallet doesn't work properly for you. Please try again with latest version and if this doesn't help - the only way to fix this is to add Neon Wallet to AV exclusions. After doing this, install it again and it should work perfectly. Let us know if this issue has been resolved for you, thanks!
