### ISSUE TITLE
Hash check on windows is not matching.

### ISSUE THREAD

**Issue by PBScott** [CityOfZion/neon-wallet#1208]
My hash check is not matching the hash of the newest release for windows. Please check the file.
Neon-0.2.5.Windows.exe

On the download page it has this hash:
db4772f27c70d2f23f40826167ea0dfa3c23bf3d0fbcf08c60b3dc5d0e5a1ab6

I am getting this hash 
10EB3AA29EB7B3B877DA7FD3C23D842E1291086CD5E2B18A73027D603A0E6EFD

**Comment by snowypowers** [comment]
The hash is correct. Your download might be corrupted or downloaded from a bad link. Please delete and try to download it again.
