### ISSUE TITLE
Funds not sending, not in wallet

### ISSUE THREAD

**Issue by Saultron** [CityOfZion/neon-wallet#121]
Hello!

I sent my funds to my bittrex wallet but it doesnt show pending. It has been over 10 hours already. When I try to resend the funds from NEON wallet it says "You do not have enough NEO to send". I check the block chain explorer and it says my funds are still in my wallet. My GAS bar also has GAS accumulated. I think my funds are in limbo. Can anyone help me out?

**Comment by cdncoin1962** [comment]
I've had funds go missing. I sent four coins from Bittrex and only 3 showed up in the wallet. This has happened a few times. Someone is either scamming my coins/bits of coins, or something is seriously wrong with this wallet.

Either way....I'll be finding a new wallet as soon as one is available. I'm losing to much money at $50US a coin.

**Comment by cdncoin1962** [comment]
I found out where my coins are going. Address: AR4QmqYENiZAD6oXe7ftm6eDcwtHk7rVTT
See attached. I want them back!

<img width="919" alt="screen shot 2017-08-14 at 10 47 54 am" src="https://user-images.githubusercontent.com/31006174/29274700-0f4ebddc-80df-11e7-9854-f7db1d5b5dd4.png">

**Comment by totalvm** [comment]
@Saultron what are you wallet addresses and did you get a txid?

@cdncoin1962 
You can't have half coins and any coins sent that are not a whole number are lost in the void.
So only send exact numbers (integers).

NEO is not divisible.
If you send exactly 4 coins from Bittrex, they deduct 0.1 ans sending 3.9, which means 0.9 is lost during transaction

**Comment by CRYPTORICH** [comment]
Hey cdncoin1962, 
Did you happen to read all of the prompts before sending your coins to this wallet? 

![neo](https://user-images.githubusercontent.com/31010569/29277971-6156eb70-80e1-11e7-9741-cbd7b8506120.PNG)

**Comment by canesin** [comment]
@Saultron this is Bittrex account receiving it.
**NEO is indivisible**

![image](https://user-images.githubusercontent.com/353648/29278577-30bebb80-80e3-11e7-9a17-b58ea3560a03.png)

**Comment by Saultron** [comment]
@canesin I'm not having a problem with the indivisibility. I'm aware of this policy. This was another user that commented on ticket. I am having issued with the FUNDS not showing in my accounts. The blockchain explorer says my funds are in my account but NEON wallet doesnt load them nor after sending funds to Bittrex does it give me a pending deposit. My funds are in the blockchain but i am not able to access them. NEON wallet only says 1 transaction; which is the deposit. It doesn't reflect the withdrawal.

**Comment by canesin** [comment]
Sorry for this @Saultron , some users thing spamming is the solution and I ended up closing it. So you can see them on the explorer but they do not show on the wallet, a wallet is just a window in the blockchain, this must mean you have some connectivity problem. Have you verified that ?

**Comment by Saultron** [comment]
@canesin Hey man no worries. I figured. Yes, i have reset all my connections but nothing yet. I also went through REDDIT to look at the other wallets that are on the side bar. I used my private key and the FUNDS appeared on the new wallet; but the same issue occurred. I tried to send them to my Bittrex account and it basically timed out? I would click "confirm" and the funds would still just show on the wallets end. I have verified the Bittrex address; its the same one I'm applying when asked to what address to withdraw to. Thoughts? Like i said, I see my funds on the block chain and its associated with my public address.

**Comment by canesin** [comment]
@Saultron this looks to be related to some nodes timing out, we will span some extra servers (monitor.cityofzion.io), comeback in one day.

**Comment by Saultron** [comment]
@canesin Much appreciated brother! Will do!

**Comment by totalvm** [comment]
@Saultron glad you could solve it on your own.
Sorry for any inconvenience.
