### ISSUE TITLE
Show a warning when high amount of GAS fee is set

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1227]
**Wallet version or commit SHA:**
 `feature/prioritize-transactions` branch (027541c)

Currently we're not protecting users from mistakes/typos in amount of GAS fee in any way. I think that it would be nice to set some sort of a warning (?) when high amount of GAS is set as a fee. We should define appropriate threshold for this. There should also be a limit which defines max amount of GAS as a fee.

**Comment by comountainclimber** [comment]
Because the new mocks indicate a hardcoded priority fee value im closing this issue please see the design assets below https://github.com/CityOfZion/neon-wallet/blob/design-v2/design/_Dark/4.0-Send-Dark%20-%20A.jpg
