### ISSUE TITLE
RPC requests are getting cancelled

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1228]
**Wallet version or commit SHA:**
 `dev` branch (c8585ba)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.112

**Prerequisites:**
- At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Wait for some time having your wallet running in the background

I've observed that sometimes RPC requests are cancelled by Neon Wallet. This is going to cause issues with missing balances for specific assets. For example - 10 requests are triggered to fetch balances for 10 assets, 2 of them are cancelled - user is going to miss balances for 2 assets.

I'm guessing that this is probably caused because of longer response times from RPC nodes. I know that there is `5000ms` timeout defined while sending a transaction. Does it also apply to requests for fetching blocks and balances of assets from RPC nodes? If yes then maybe we should increase that timeout (`neo.org` nodes are quite slow while it comes to response times and they time out very often) and in addition to that retry cancelled requests for getting block height and fetching balances?

**Screenshots/Video:**
![xhr_cancel](https://user-images.githubusercontent.com/8177587/41507317-bd7e9a9c-7230-11e8-9cbe-c1099051ca61.gif)

**Comment by zsiglin** [comment]
@drptbl I was only able to reproduce something similar by throttling my connection way down with a custom profile. (5kb/s max download). The 5000ms timeout does apply to fetching blocks and balances as defined in the `neon-js` client.

https://github.com/CityOfZion/neon-js/blob/7aab57de5fe88f134dc6020e5d12f26aa46e21b4/src/rpc/query.js#L322

What would the expected behavior be? Retry `n` times and display a failure message after that?

**Comment by drptbl** [comment]
@zsiglin I was able to reproduce this easily while connected to `neo.org` node (without throttling), however using throttling should simulate similar case.

Are you sure that timeout doesn't apply for these? What causes this requests to be cancelled then (if not this)? I can see that all requests are cancelled after 5secs, so it seems that what you've linked above is actually applied to these requests.

I think that solution of retrying the request for `n` times is good, however my another idea is that if retry failed `n` times, we could try to pick 2nd best RPC node and then try with it. Finally if second node would fail, we could throw an error.

@comountainclimber @evgenyboxer 
Do you have any insights about solution for this issue?

**Comment by DalderupMaurice** [comment]
This timeout was increased to `30000` in version `3.10.0`. Worth giving it another shot? (after upgrading neon-js) @drptbl

**Comment by drptbl** [comment]
@DalderupMaurice @comountainclimber We're calling one request for each NEP-5 token balance. If we're having much tokens, there're much requests. What if one of the requests fail to respond (1 out of 10 for example) in 30 secs? In this case user is not going to see his balance *only* for this specific token for which request has failed.

**Comment by comountainclimber** [comment]
@drptbl no we arent... there have been several changes over the past few weeks and making one call is now one of them leveraging neo-js `api.nep5.getTokenBalances`
