### ISSUE TITLE
Can't Claim GAS

### ISSUE THREAD

**Issue by CryptoAJ** [CityOfZion/neon-wallet#1231]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
0.2.5

**Environment:**
Win 10 Home (64 bit) Version 1803 (OS Build 17134.112)

**Prerequisites:**
Don't know what this means.

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Claim XXXX GAS" button
3. Get error message "Error calculating claimable GAS: Transaction failed!"

I updated to 0.2.5 June 15 at 8:14 PM.  Since then I have not been able to claim GAS, I get an error message as described above.

**Screenshots/Video:**
![neon](https://user-images.githubusercontent.com/40344124/41512574-54f66e08-7250-11e8-90b0-ce8a466bca94.PNG)

**Comment by SteveNebulous** [comment]
having the same issue

**Comment by Katsura99** [comment]
I have the same issue.

**Comment by RazielR** [comment]
Could someone already solve the problem?

**Comment by rvdlaar** [comment]
Same issue!

**Comment by CryptoAJ** [comment]
It seems to be working now. I've been able to claim twice in the last 24 hours.

**Comment by chrisjoanne** [comment]
Monday 27th August - got the same problem.

**Comment by okohub** [comment]
Still having this issue.

**Comment by mskiraz** [comment]
Same problem here with the latest version :(

**Comment by mskiraz** [comment]
Same problem here with the latest version :(
