### ISSUE TITLE
"Retry" button in "Token Balances" section calls wrong paths (localhost instead API host)

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1232]
**Wallet version or commit SHA:**
`design-v2` branch (26820ed)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.112

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Disconnect from internet connection
2. Start Neon Wallet
3. Select any saved wallet
4. Enter your passphrase
5. Click on "Login" button
6. Click on "Retry" button in "Token Balances" section

"Retry" button in "Token Balances" section calls wrong paths (localhost instead API host).

**Screenshots/Video:**
![retry_broken](https://user-images.githubusercontent.com/8177587/41512994-c0449880-7294-11e8-8a3c-7f225cc0d854.PNG)

**Comment by comountainclimber** [comment]
Issue fixed in design-v2
