### ISSUE TITLE
Scroll bar on wallet manager page shouldn't be shown if it's not needed

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1236]
**Wallet version or commit SHA:**
`design-v2` branch (26820ed)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.112

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Wallet Manager" button

Unnecessary scroll bar is visible on wallet manager page. We shouldn't show it when it's not needed.

**Screenshots/Video:**
![scrollbar4](https://user-images.githubusercontent.com/8177587/41568516-4f81965c-7366-11e8-95c3-fda74eb0f809.gif)

**Comment by drptbl** [comment]
Re-tested, this is still an issue:
![scrollbarz](https://user-images.githubusercontent.com/8177587/43746424-7e554790-99e4-11e8-90ab-6170ed196025.PNG)

**Comment by comountainclimber** [comment]
Fixed in design-v2 branch
