### ISSUE TITLE
[v2.5] Import Wallet

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1237]
Placeholder for import wallet UI. Reference mockups here: https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by comountainclimber** [comment]
The latest assets can be found here https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by drptbl** [comment]
Tested, issues found:
#1275, #1276, #1277, #1278
