### ISSUE TITLE
[v2.5] Implementing themed color palette

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1239]
Placeholder for implementation of the themed color palettes (light and dark). Reference mockups here: https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by comountainclimber** [comment]
The latest assets can be found here https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by comountainclimber** [comment]
Unless otherwise noted we will no longer be initially releasing with two themes... This will be one of the biggest features in our first update

**Comment by drptbl** [comment]
Implemented.
