### ISSUE TITLE
[v2.5] Transaction History

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1240]
Placeholder for transaction history UI. Reference mockups here: https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by comountainclimber** [comment]
The latest assets can be found here https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by comountainclimber** [comment]
@krsjoseph absolutely open to anyone as long as not marked as in progress 👍on the project board found here => https://github.com/CityOfZion/neon-wallet/projects/3

Start by forking neon-wallet and creating a feature branch. Please submit a WIP PR before getting too far along just so that other contributors as well as myself can comment and give feedback as you work.

If you have not already please join discord channel too!

**Comment by comountainclimber** [comment]
@krsjoseph I forgot to mention please branch off of `design-v2`

**Comment by comountainclimber** [comment]
@krsjoseph Are you still interested in working on this? If not I plan to get started in the next day or so

**Comment by drptbl** [comment]
Some polishing has to be done, but functionality is ready in overall.
