### ISSUE TITLE
[v2.5] Receive

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1242]
Placeholder for receive UI. Reference mockups here: https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by comountainclimber** [comment]
The latest assets can be found here https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by Albeos90** [comment]
In the new wallet design you should add the NEO logo for NEO and The logo for all other tokens too. Instead of only writing names.

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/pull/1186

**Comment by drptbl** [comment]
Looks fine. Tested.
