### ISSUE TITLE
[v2.5] Settings

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1244]
Placeholder for settings UI. Reference mockups here: https://github.com/CityOfZion/neon-wallet/tree/design-v2/designf

**Comment by comountainclimber** [comment]
The latest assets can be found here https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by drptbl** [comment]
https://github.com/CityOfZion/neon-wallet/issues/1242#issuecomment-433226796
