### ISSUE TITLE
[v2.5] Authentication

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1245]
Placeholder for auth UI. Reference mockups here: https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by comountainclimber** [comment]
The latest assets can be found here https://github.com/CityOfZion/neon-wallet/tree/design-v2/design

**Comment by drptbl** [comment]
Finished testing this part, added all not fixed issues on GitHub.
