### ISSUE TITLE
Login Button malfunction

### ISSUE THREAD

**Issue by matwxx** [CityOfZion/neon-wallet#125]
Today I could still login by typing private key and press the login button. Now its not working. I click the login button, nothing open up.

**Comment by totalvm** [comment]
Which version are you using?

**Comment by mmartain** [comment]
Same here. Version 0.0.4. Nothing happens

**Comment by Ejhfast** [comment]
In every reported case of this so far, the user was not typing in their private key correctly. We will provide more proactive feedback in the future
