### ISSUE TITLE
NEO PUBLIC ADDRESS HAS CHANGED

### ISSUE THREAD

**Issue by grishatataru** [CityOfZion/neon-wallet#1253]
Its my 2nd time writing about this issue,all of a sudden i got a new public address.
It was created at the same time when my funds were trasfered.

When i open my ledger i see only this address: AVjDZ7VVz7foeqFmdW2R5okbjr1pTEmEBs

When i go to neo tracker all my funds have moved to new address:

AVjDZ7VVz7foeqFmdW2R5okbjr1pTEmEBs
419 NEO

Sent to

AcWyPgfSVovTnE5rG6w3KNMCcoipjuDBxP
419 NEO

How can i get them back to my old address?(current one on ledger )

Im using mac os and 0.2.5 neon wallet

I tried to erase my ledger and restore using 24 keys/seeds but same thing

Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by drptbl** [comment]
You can't get back your funds after they were sent to other address which you don't have access to. This also doesn't sound like wallet-related issue.
