### ISSUE TITLE
Ledger S wont sign Tx

### ISSUE THREAD

**Issue by dougy82** [CityOfZion/neon-wallet#1255]
**Wallet version or commit SHA:**
0.2.5

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
Tx problem on ledger S

**Reproduction steps:**
Open wallet using ledger nano
Attempt any sized SEND
Tx appears on device but cannot SIGN or DENY

Have attempted on two machines / ledger is upto date. reinstalled wallet.

Any help/support appreciated.

Thanks

**Comment by cobraxp** [comment]
Same issues on 3 computer with up to date ledger. wallet 2.5. Been trying to move ONT for a week now.

**Comment by Cryptojo** [comment]
I also have the same issue on 2 computers. I can deposit into wallet but I can not withdraw anything. gives me error unknown (0x6d07) What the heck wrong with this application.

**Comment by drptbl** [comment]
Please upgrade your Ledger firmware to the latest version and try again. Let us know if that didn't help.
