### ISSUE TITLE
Can't send ONT tokens to Binance with Ledger Nano S: Transaction failed: Ledger device: UNKNOWN_ERROR (0x6d07)

### ISSUE THREAD

**Issue by lin-lu** [CityOfZion/neon-wallet#1259]
I could not send ONT tokens to my Binance account, I got an error message:
Transaction failed: Ledger device: UNKNOWN_ERROR (0x6d07)

Neon Wallet Version 0.2.5
OS: Windows 10

**Comment by imolev** [comment]
I have the same issue while sending GAS but the error is 0x6d08

**Comment by storerjeremy** [comment]
I am also experiencing the same issue.

Neon Wallet Version 0.2.5
Mac

**Comment by lin-lu** [comment]
Fixed, thanks!

**Comment by rohittattu** [comment]
For updating Firmware, is it safe to proceed with your tokens still on the ledger? Any tips? Thanks.
