### ISSUE TITLE
Cmd+C copy functionality not working

### ISSUE THREAD

**Issue by kamenjan** [CityOfZion/neon-wallet#126]
I am having hard time copying generated keys when I try to create new wallet. It doesn't matter if I use Cmd+C or Copy function from Edit menu it just does not copy highlighted text to clipboard. While clicking inside the application window I get the following error in the console:

`2017-08-15 17:39:00.419 Electron Helper[42599:1056342] Couldn't set selectedTextBackgroundColor from default ()`

Not sure, but it seems it might be connected to the copy text bug.

**Comment by Ejhfast** [comment]
Please try the latest release, 0.0.4

**Comment by kamenjan** [comment]
Thank you, works like a charm :)
