### ISSUE TITLE
(V2.5)Tnc not showing in wallet(it had existing Tnc in there) but showing as successful on Neoscan?

### ISSUE THREAD

**Issue by TncFiend** [CityOfZion/neon-wallet#1263]
Neon Wallet 0.2.5

Windows 10 home(64bit)

I sent Tnc to a friend, Both Neo-Scan and Neo-explorer are saying the transaction is complete, but they are not showing in her wallet?

She had existing Tnc in that wallet, so it's not a script hash issue?

She has opened and closed her wallet multiple times over the last 3 days, but still they are not showing 
I have even seen her wallet and it is not showing, but showing on Neo-scan and Neo-Explorer? Help?

**Comment by drptbl** [comment]
Please verify that you've added proper script hash to "Manage Tokens" section in "Settings".
