### ISSUE TITLE
My Unclaimed GAS all disappear and gone!!!!!

### ISSUE THREAD

**Issue by raintears** [CityOfZion/neon-wallet#1270]
Please return me all my GAS. Just look at my wallet, how can there be no GAS at all no transactions no claimed records and all gone? I deposited NEO inside and no GAS? There used to be until recently all gone.

**Comment by comountainclimber** [comment]
Not enough information.

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io
