### ISSUE TITLE
Wrong icon of "show password" feature on password input fields

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1273]
**Wallet version or commit SHA:**
`design-v2` branch (a73c5b1)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.112

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Create Wallet" button

Icon of "show password" feature on password input fields doesn't match designs.

**Expected:**
![exp](https://user-images.githubusercontent.com/8177587/42141014-379dff4a-7da6-11e8-8d39-cdc2f64d496b.PNG)

**Current:**
![cur](https://user-images.githubusercontent.com/8177587/42141002-23032a06-7da6-11e8-8a20-1d7609981565.PNG)

**Comment by comountainclimber** [comment]
Waiting for feedback from design on this issue

**Comment by comountainclimber** [comment]
Confirmed with design that the current implementation is 👌
