### ISSUE TITLE
Neon Wallet - Balance shows '0' ! Can someone help?

### ISSUE THREAD

**Issue by MilotM** [CityOfZion/neon-wallet#128]
Hi guys, i installed Neon wallet yesterday and everything was ok the whole time...(made deposit, earned gas etc..)
Today when i opened it showed 0 balance... i tried all the steps shown on other posts like (reinstalling, trying testnet-mainnet, checking firewall...)
In chain explorer it shows that i have 24 neon the exact amount i should have, but it just doesn't show on neon wallet...

my pubadd: AZLeQjmUjpaoYC9KR4T1QN5cEWfPG2mB26

**Comment by MilotM** [comment]
my public address: AZLeQjmUjpaoYC9KR4T1QN5cEWfPG2mB26

**Comment by Ejhfast** [comment]
From my vantage, Neon thinks you have 24: http://api.neonwallet.com/v1/address/balance/AZLeQjmUjpaoYC9KR4T1QN5cEWfPG2mB26

You must have some connectivity issue?

**Comment by MilotM** [comment]
Well i am connecting very good because when i press refresh it receives the latest blockchain information!!!
No connectivity issue here, but maybe a bug!

**Comment by MilotM** [comment]
And why the f*** do you close the issue when it is not solved?

**Comment by AshRolls** [comment]
Github is not a support channel, it is for the reporting code related issues.
