### ISSUE TITLE
Saying invalid private key

### ISSUE THREAD

**Issue by vflixormix** [CityOfZion/neon-wallet#1282]
Can someone please help. i havent used my neon wallet for a while and when i tried to login using my private key it keeps saying 'invalid private key' im not sure what to do.
im using window 10,  64 bit

im not sure what wallet version it is

im clicking on
login using a private key
i copy and paste my key and then it gives me the error message

**Comment by comountainclimber** [comment]
For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io
