### ISSUE TITLE
"getblockcount" is invoked twice on wallet refresh (manual and automatic)

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1283]
**Wallet version or commit SHA:**
 `dev` branch (e109f2d)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.112

**Prerequisites:**
- At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Open Chrome developer tools and switch to "Network" tab
4. Select your wallet, enter your passphrase and click on "Login" button

After logging in for the first time in the wallet you can see that `getblockcount` is invoked twice in a row (this is also caused on manual and automatic refresh of the wallet).

This is caused because of this part of code:
https://github.com/CityOfZion/neon-wallet/blob/dev/app/actions/balancesActions.js#L19-L22

`getRPCEndpointFrom` invokes a first call to `getblockcount` (with `ping` function) and then `client.getBlockCount()` is calling it for the second time. We should find a way to improve this.

**Screenshots/Video:**
![weirdo](https://user-images.githubusercontent.com/8177587/41507489-7abf5d74-7233-11e8-957f-f0460e9b5723.gif)

**Comment by zsiglin** [comment]
@drptbl I'm unable to reproduce this on both the `dev` and `design-v2` branches. Can you confirm?

This commit may have addressed it https://github.com/CityOfZion/neon-wallet/commit/0866f71112250eb99744c34718a0e2d87f422753

**Comment by drptbl** [comment]
@zsiglin You're completely right, this issue doesn't exist anymore and was probably addressed in 0866f71. I wasn't aware as it's not mentioned in the PR. Thanks a lot for looking in to it 👍.
