### ISSUE TITLE
Hook up getvalidators call to populate the candidate keys

### ISSUE THREAD

**Issue by evgenyboxer** [CityOfZion/neon-wallet#1287]

**Comment by evgenyboxer** [comment]
Waiting on https://github.com/CityOfZion/neon-js/pull/276

**Comment by comountainclimber** [comment]
Seeing as priorities have shifted and consensus node voting is not yet a stable feature on the network I am closing all issues related to voting for now however have labeled them for future reference in case we want to reopen.
