### ISSUE TITLE
Can i get ONT second round airdrop in neon walled 0.2.5?

### ISSUE THREAD

**Issue by lijiaoshou** [CityOfZion/neon-wallet#1289]
I hold NEO,and I get the first round ONT airdrop on March 1st, 2018.As We konwn,ONT MainNet has Online.Can I get the half airdrop in NEON Wallet 0.2.5?And do I need to change ONT token in NEON
to the real ONT on ONT's MainNet?

**Comment by jonatanblockchain** [comment]
https://medium.com/ontologynetwork/mainnet-ont-token-swap-notice-%E5%85%B3%E4%BA%8Eont%E4%B8%BB%E7%BD%91%E5%88%87%E6%8D%A2%E7%9A%84%E8%AF%B4%E6%98%8E-4cd38c2fc55b

**Comment by comountainclimber** [comment]
For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io
