### ISSUE TITLE
armv71 Support

### ISSUE THREAD

**Issue by GoldenOrangeX** [CityOfZion/neon-wallet#129]
Hi,
I'm looking to store my NEO using my Raspberry Pi 3 with Ubuntu-Mate installed, however I noticed there's no supported versions for the systems architecture. Is there a workaround to this, or is armv71 already supported and I'm just missing a step.

My apologies if this is a simple fix/dumb question, I'm new to all this.
Thank you,
Golden.

**Comment by canesin** [comment]
Did you tried to build in raspberry ?
install nodejs and download the repository:
first: sudo npm install -g webpack
inside the folder:
npm install
webpack
npm start

if that works.. you can generate your own installer:
npm run dist

good luck..

**Comment by GoldenOrangeX** [comment]
Hi, my apologies for the delayed response. All commands leading up to 'webpack' work fine. Upon executing webpack the following errors are displayed: https://pastebin.com/x281PaT7

I'm running Node v8.4.0 and npm v5.3.0.

**Comment by damonp** [comment]
Tested both latest git and 0.0.4 zip.  Same error near the end of the `npm install`.  Looks like electron doesn't like arm?

```
> Neon@0.0.4 postinstall /home/pi/Projects/neon-wallet-0.0.4
> install-app-deps

⚠️  Please use as subcommand: electron-builder install-app-deps
Options:
  --platform  The target platform
                        [choices: "linux", "darwin", "win32"] [default: "linux"]
  --arch      The target arch   [choices: "ia32", "x64", "all"] [default: "arm"]

Invalid values:
  Argument: arch, Given: "arm", Choices: "ia32", "x64", "all"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Neon@0.0.4 postinstall: `install-app-deps`
npm ERR! Exit status 1
```

```
raspi:/home/pi# npm -v
5.3.0
raspi:/home/pi# node -v
v8.4.0
```

**Comment by Satoshinaire** [comment]
Seems from a bit of digging that while Electron is supported on Raspberry Pi, electron-builder isn't. So you'd need to do a number of those build and packaging steps manually.

**Comment by Satoshinaire** [comment]
Some potentially useful info here: https://github.com/chentsulin/electron-react-boilerplate/issues/896

**Comment by Kris191** [comment]
Did this every get action-ed? i would be keen to use the wallet on my raspberry Pi with ledger support

**Comment by canesin** [comment]
@Kris191 it is open source, could you try to build it for the Pi ? Unfortunately we have no testing env or demand to maintain Pi builds.
