### ISSUE TITLE
Windows SmartScreen prompt when installing 0.0.4

### ISSUE THREAD

**Issue by markved** [CityOfZion/neon-wallet#130]
When trying to run .exe on Windows (in my case Windows 10), it throws SmartScreen prompt with the unknown publisher.
![coz_neon_wallet_windowswarning](https://user-images.githubusercontent.com/11667494/29426086-81b8ff24-8353-11e7-9300-e7db1c0c5dc6.png)

This isn't the case with 0.0.3 as it installs without any SmartScreen prompt and also shows the valid publisher.
![neon_publisher](https://user-images.githubusercontent.com/11667494/29426157-ba2c991a-8353-11e7-8323-aa440aa63381.png)

Although users can verify by double-checking download source URL, I think it would be more authentic to set a valid publisher.

**Comment by Ejhfast** [comment]
thanks for the heads up, I didn't get that warning with 0.0.4 in testing

**Comment by markved** [comment]
No problem. It looks like app is signed properly as I can see publisher name under installed program.
![neon_installed_validpublisher](https://user-images.githubusercontent.com/11667494/29430370-22569bae-8362-11e7-9a41-1150de4ed556.png)
I guess MS SmartScreen is displaying that warning based on reputation of the certificate. So as more valid installs occur, it will go away and not display to users. Let's see if others report it or if it goes away after several users installing this version.

**Comment by fernanda1979** [comment]
I cant open the wallet in windows 10. does not show any error, just doesn't open.

**Comment by AZBrad** [comment]
I'm getting same smart screen error when trying to install 0.0.5 ... also not allowing me to fully uninstall previous versions without "permission" ..  what is the best current error free ver of Neon wallet?

**Comment by Satoshinaire** [comment]
You can work around this if you're confident you got the wallet from the right place.

When Neon 0.0.5 is prevented from launching by Windows Defender SmartScreen due to "Unknown Publisher", you can right+click, then click Properties, and then click Unblock. Then restart Neon.

Best of luck!
