### ISSUE TITLE
error checking wallet version........

### ISSUE THREAD

**Issue by Easymoney456** [CityOfZion/neon-wallet#1305]
version 0.2.4 and then tried version 0.2.5

mac operating system

says "error checking wallet, then when i connect and click the ledger button it just goes all white"

i have been using the wallet for months without a problem

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/pull/1299 release  (scheduled for next 24 hours) will fix this issue @Easymoney456 @pdx99
