### ISSUE TITLE
My Neon 2.4 wallet is blank when I log in.  When I tried to load windows version 2.5 error messages keeps popping up.  how can I fix this?

### ISSUE THREAD

**Issue by sgc1987** [CityOfZion/neon-wallet#1306]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by MadBasque** [comment]
Same problem.  Used Neon wallet yesterday to claim GAS and no problem.  Tried today to open it to deposit newly purchased NEO and I get the green wavy signal and then all white, with a note at the bottom about not being right version.  I went to Github and downloaded City of Zion's latest release (which is the one I already had from May 14th) and still same problem.

**Comment by drptbl** [comment]
@sgc1987 @MadBasque 
Latest version of the wallet resolve your issues:
https://github.com/CityOfZion/neon-wallet/releases/tag/0.2.6
