### ISSUE TITLE
NEP-5 token balances are being hidden if neoscan `get_balance` request fails

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1313]
**Wallet version or commit SHA:**
`dev` branch (ae58feb)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.112

**Reproduction steps:**
Drop `get_balance` request response.

Console error is thrown and NEP-5 token balances are being hidden if neoscan `get_balance` request fails.

**Screenshot/Video:**
![drop_getbalance](https://user-images.githubusercontent.com/8177587/42468744-0a2f28fc-83b6-11e8-90a1-b50acd95a895.PNG)

**Comment by comountainclimber** [comment]
fixed in https://github.com/CityOfZion/neon-wallet/releases/tag/2.0.0
