### ISSUE TITLE
cant access my wallet using my ledger nano. 

### ISSUE THREAD

**Issue by juergenbraatz** [CityOfZion/neon-wallet#1316]
I cant access my wallet using my ledger nano. I've changed nothing and it worked great until i tried to use it an hour ago. Only a blank page end at startup a message error checking wallet version.

**Comment by scottyk49** [comment]
same here

**Comment by NoTechSkill** [comment]
Me too. I tried to download version 2.0.6 & now it's just a blank screen. Trying to log in using my Ledger Nano S. Please help! Thanks. B

**Comment by ktbrady** [comment]
I am getting an error message and unable to retrieve my balance -- what is going on???

**Comment by ktbrady** [comment]
My Wallet shows a balance of 0

**Comment by ktbrady** [comment]
Neo tracker shows correct balance and same address as wallet -- but wallet show zero balance????

**Comment by juergenbraatz** [comment]
Is anybody trying to solve that problem????????

**Comment by juergenbraatz** [comment]
I have my ledger now for 2 weeks and i thought this is a save solution. What a mistake.

**Comment by comountainclimber** [comment]
Please download the new version neonwallet.com the problem should be resolved

**Comment by scottyk49** [comment]
Yep latest version 0.2.6 fixed my "Blank Screen" and "Error checking wallet version" pop up.
Thanks.
