### ISSUE TITLE
Blank screen while creating new wallet when cache is not present on the disk

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1317]
**Wallet version or commit SHA:**
`dev` branch (ae58feb)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.112

**Pre-requisites:**
Clear your wallet cache from the disk

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Create new wallet" button
3. Type your passphrase twice
4. Click on "Generate keys" button

If disk cache is not present and wallet is run, while trying to create a new wallet - wallet ends in blank screen with console error thrown.

**Screenshot/Video:**
![blankstuff](https://user-images.githubusercontent.com/8177587/42522290-04dfc716-846b-11e8-97fd-46a7a1703909.PNG)

**Comment by comountainclimber** [comment]
Fixed in release 0.2.6 🎉
