### ISSUE TITLE
Disable "Scan QR Code" button if camera is not available while logging in with private key

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1318]
**Wallet version or commit SHA:**
`dev` branch (ae58feb)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.112

**Pre-requisites:**
No camera available (VM for example)

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login with private key" button

If there is no camera available when going to "Login with private key" page, "Scan QR Code" button should be disabled. Currently if button is clicked, there's an error thrown in console however it's not visible in the wallet UI, so users are not informed about this. Also button changes to "Cancel" - it shouldn't happen in case of error.

If it's not possible to check camera and disable this button, we should at least show the error after clicking on it.

**Screenshot/Video:**
![show_error](https://user-images.githubusercontent.com/8177587/42522837-6cd495c6-846c-11e8-870c-e2ad1e8d1fef.PNG)

**Comment by ranbena** [comment]
I'll take this

**Comment by tbeck860** [comment]
Fix tested successfully on Windows 10 Pro v1803 Build 17134.523
![1-15-2019 5-18-13 pm](https://user-images.githubusercontent.com/31013176/51218525-15e12000-18ea-11e9-9771-156edeada781.png)

**Comment by comountainclimber** [comment]
Please award @tbeck860 100 🚀

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/220a87f0e9cedf43f05278182794d9c5f49ad6f144e9ebc7fb7aa4b5994c68d8
