### ISSUE TITLE
0.2.6 update DMG disk issue.

### ISSUE THREAD

**Issue by ArranR23** [CityOfZion/neon-wallet#1322]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
0.2.5

**Environment:**
Macbook Pro OS X El Capitan

**Prerequisites:**
ONT, MCT & HPT holding in wallet

**Reproduction steps:**
0.2.6 update DMG file coming up as not Reconised 

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by drptbl** [comment]
@ArranR23 It looks like your downloaded dmg file has been corrupted. Can you re-download and try again? Thanks.

**Comment by ArranR23** [comment]
I’ve tried to Redownload about 6 times. Still no luck.

**Comment by drptbl** [comment]
It looks like this is an issue with old macOS version itself. After some digging, I've found possible solutions for you:

> I had the same problem, and managed to open .dmg files by going into Disk Utility>File>Open Disk Image. Once opened in Disk Utility, Double Click (Right Click) the icon and click show in Finder. Then I could install what I wanted! Hop it works for you!

> Hold down the Control key when you click on the .dmg then select Open from the context menu.  This should give you a window to "allow anyway".

Please let me know if that resolved your issue. If not, can you post a screenshot of the error that you see, please? Thanks.

**Comment by drptbl** [comment]
I'm closing this because it's not related to wallet itself.

**Comment by ArranR23** [comment]
Here’s a screen shot. Still not working
