### ISSUE TITLE
Unable to send TNC and MCT tokens from Neon Wallet

### ISSUE THREAD

**Issue by Himmy06** [CityOfZion/neon-wallet#1323]
I am able to see my TNC and MCT token counts, but if I try to send them, they do not appear in the drop down menu as an option. My other NEP 5 tokens such as RPX, ONT, DBC show up in the drop down menu.

Wallet version or commit SHA:
Neon 0.2.6

Environment:
MaC OS

Prerequisites:
Unable to send trinity token form Neon Wallet.

Reproduction steps:

Start Neon Wallet
view TNC Balance
TNC token does not appear on drop down menu under send
After viewing TNC balance, TNC token doesn't appear as an option on drop down menu. Other tokens such as NEO, ONT, RPX, DBC appear in the drop down menu

Screenshots/Video:
not avail

**Comment by drptbl** [comment]
I've tested your issue several times on Windows and macOS (now and before) and I can't reproduce this in any way.

Windows:
![tnc_windows](https://user-images.githubusercontent.com/8177587/42643868-78c50278-85fa-11e8-860a-22c904dfec97.PNG)

macOS:


Transaction:
https://neoscan.io/transaction/91e57a6d2ecc8c4d53614eac5c7ecc84437cb354808fc27d544f1bb7803eec53

**Comment by drptbl** [comment]
@Himmy06 I'm colosing this because there are no further details about the issue. Please let us know if this occurs for you again (and answer a question from above, please). I've couldn't reproduce this and there are no more reports for this error from other people.

**Comment by Himmy06** [comment]
The other issue I have that may be part of this problem is adding and subtracting tokens. When I try to remove a token, it won’t allow me to, in addition, I’m unable to add any new tokens. I tried to add the Hash for TNC again but was unsuccessful.

**Comment by drptbl** [comment]
@Himmy06 Can you post some screenshots with your NEP-5 tokens visible in the wallet (you can hide balances) and another one with this drop-down opened? Thanks.
