### ISSUE TITLE
Neon 2.6 - Infected File

### ISSUE THREAD

**Issue by texdevo** [CityOfZion/neon-wallet#1324]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
2.6

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
Real Protect-EC!767E2B62237A (McAfee states is infected file found in .exe download and deletes NEON WAllet

**Reproduction steps:**
downloaded and installed 4 times. 

some description (for ex. what happens after completing reproduction steps), e.g.:
McAfee virus scan states file is infected and quarentines making download error.

**Screenshots/Video:**

![image](https://user-images.githubusercontent.com/31101888/42652604-88ae38ac-85d8-11e8-84ee-02663e710614.png)

![image](https://user-images.githubusercontent.com/31101888/42653007-b76eb60c-85d9-11e8-984a-947337072a39.png)

**Comment by drptbl** [comment]
This is known and it's false-positive (you can avoid this with adding neon to exclusions in your AV):
#577, #920, #1207
