### ISSUE TITLE
Neon Wallet Issue

### ISSUE THREAD

**Issue by Nate5858** [CityOfZion/neon-wallet#1327]
My neon wallet doesn't display any transactions and it also says that there's a problem with the blockchain. I've tried un installing and re installing and that doesn't work. I'm also updated to the latest version on Windows 10

**Comment by comountainclimber** [comment]
You made two issues with the same info and closed the first one... are you still having a problem?

**Comment by Nate5858** [comment]
Yeah I’m still having that problem. I don’t know why I closed the first one lol

**Comment by drptbl** [comment]
This happens basically when you're having issues while connection to neoscan (timed out requests, requests failed, etc). This is not a bug in the wallet - that's how it handles backend errors.
