### ISSUE TITLE
Fund Missing

### ISSUE THREAD

**Issue by EvilRebel** [CityOfZion/neon-wallet#133]
Yesterday i had transferred 1.1 neo from my bittrex wallet to my neo wallet address APzLLRwFDHaXz2prxoQioZZXY2C9wHRLhg.The transaction id was 0158b84618ba035e1fcda16a1dbb777449c631fd1750175af59d327ec82f3a4e.But today when i opened the neo wallet balance is shown as zero.Can someone help me figure out y this is happening?

**Comment by totalvm** [comment]
download the latest version (0.0.4) your funds are on on that address so no worries
