### ISSUE TITLE
Lost my Neo coins on the NEON wallet!!!!

### ISSUE THREAD

**Issue by SinclairCrypto** [CityOfZion/neon-wallet#134]
Hi,

I have a terrible experiences with the NEON wallet by City of Zion. First of all it is impossible to find a costumer support, that is why I am writing here, second I lost my coins. I have sent them and they even showed up on the wallet, but they are gone today.
Thanks God I only sent 3 of them. Anyone know how I can get in contact with the people from City Of Zion?

**Comment by AshRolls** [comment]
Please try in the #support channel of slack (links are in the sidebar at reddit). Github is for the reporting of code related issues, not technical support so I'm closing this.
