### ISSUE TITLE
How do I recover my private key for Neon wallet?

### ISSUE THREAD

**Issue by Otticus** [CityOfZion/neon-wallet#1342]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
2.6

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.165

**Prerequisites:**
I lost the paper print out when I created the wallet that showed the two scan codes with the Encrypted key and private key printed on it. I want to find my private key so I can enter it into the Ontology Mainnet to claim 2nd half of airdrop (yes I know I'm slow) and swap tokens. 

**Reproduction steps:**

Can anyone tell me how I would recover my private key?
**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by drptbl** [comment]
@Otticus if you still have your wallet added to the list of "Saved Wallet", you can do this in the "Manage Neon Settings" screen. Click on "Lock" icon and type your password.
