### ISSUE TITLE
Graph is not properly aligned in the "Market Data" window on the dashboard page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1343]
**Wallet version or commit SHA:**
`design-v2` branch (5a523f5)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.112

**Reproduction steps:**
1. Start Neon Wallet
2. Login to any wallet

As seen on attached screenshots - graph is not properly aligned in the "Market Data" window on the dashboard page.

**Screenshot/Video:**
![broken_graph](https://user-images.githubusercontent.com/8177587/43171249-7cbf6afe-8fa9-11e8-85b8-3116ddacc9f7.PNG)

**Comment by comountainclimber** [comment]
Would you be able to tell me what resolution the app is in this state?

**Comment by drptbl** [comment]
@comountainclimber 
Inner window resolution is: 1264x811 (default, no resize).
My desktop resolution is: 1920x1080.

**Comment by drptbl** [comment]
Tested, fixed 👍 .
