### ISSUE TITLE
Unnecessary scroll bar visible on wallet main page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1344]
**Wallet version or commit SHA:**
`design-v2` branch (5a523f5)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.112

**Reproduction steps:**
1. Start Neon Wallet

Unnecessary scroll bar is visible on wallet main page. This is regression (it was fixed before).

**Screenshot/Video:**
![scroll_bar_issue](https://user-images.githubusercontent.com/8177587/43171284-a1a25d90-8fa9-11e8-93d5-e7a2aed3bf9b.PNG)

**Comment by comountainclimber** [comment]
Fixed in design-v2 branch
