### ISSUE TITLE
Cannot open my Neon wallet on my windows desktop

### ISSUE THREAD

**Issue by bethscapade** [CityOfZion/neon-wallet#1346]
**Wallet version or commit SHA:**
Neon .0.2.2 windows exe

**Environment:**
Win 10 Home (64 bit) Version laptop desktop

**Prerequisites:**
I have custom tokens added before running the wallet

**Reproduction steps:**
1. Start Neon Wallet   NEON wallet will not start or open

I have not opened my wallet in a few weeks and when I click the icon on my desk top nothing happens. 
I am afraid to uninstall and reinstall it for fear of losing my tokens What do I do?

**Comment by comountainclimber** [comment]
Please download the newest version 0.2.6 thanks
