### ISSUE TITLE
Can't withdrawal NEO - somebody please help 

### ISSUE THREAD

**Issue by jlh1121** [CityOfZion/neon-wallet#135]
Are you the wallet accessible at NEO.org? (
Are you guys located at 

Are you guys located at neowallet.cn? Is the wallet website link at neo.org... How do I withdraw from the Neo wallet? 

1.  I started at "home", then under "transfer"
2.  Select "Neo"
3.  Under "receiver", I provide my Neo Bittrex account address (to deposit to)
4.  Enter the "value" which is 101 Neo

What am I missing? Nothing happens...

Thanks,

Jeremy

**Comment by totalvm** [comment]
No that's someone else, not managed by CoZ.
You can move your private key over to any other wallet and try to use that instead.
