### ISSUE TITLE
NNC and other NEP-5 tokens not showing in NEON Wallet 0.2.6

### ISSUE THREAD

**Issue by wy555** [CityOfZion/neon-wallet#1350]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
0.2.6

**Environment:**
MacOS 10.13.3, Macbook Pro 2018 model.

**Prerequisites:**
Added the custom token for NNC.

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, 
No problem in adding new token, but the my token NNC is not showing.   On other platform is showing.

It only showed once on NEON Wallet 0.2.6 but before and after that, the tokens were empty and not shown on NEON wallet.

**Comment by wy555** [comment]
I was told that the issue is not related to the NEON wallet but that the NEO block-chain mining nodes need to have the software updated.  But it has been so long.  When is the timeline to resolve this issue?

**Comment by drptbl** [comment]
@wy555 You're right - this is not an issue related to the wallet. I don't know what the ETA is, sadly.
