### ISSUE TITLE
Neon-wallet not able to add new NEP-5 token

### ISSUE THREAD

**Issue by junlocker** [CityOfZion/neon-wallet#1353]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
version 0.2.6

**Environment:**
MacOs sierra Version 10.12.6

**Prerequisites:**
NA

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button
5.  Click on "save" button

My neon wallet not working new added token on my wallet. I have added the ONT and COUP Hash, but they aren't showing on my neon wallet.

<img width="1008" alt="screen shot 2018-08-05 at 11 17 20 pm" src="https://user-images.githubusercontent.com/42132319/43700142-673499fa-9906-11e8-8e38-833c0a295c97.png">

<img width="679" alt="screen shot 2018-08-05 at 11 17 44 pm" src="https://user-images.githubusercontent.com/42132319/43700150-6da3bc58-9906-11e8-9e3b-f9ae9c915c12.png">

**Comment by nickptty** [comment]
got same problem

**Comment by comountainclimber** [comment]
All token hashes should be pulling dynamically from https://github.com/CityOfZion/neo-tokens

This issue should no longer be a problem in 0.2.7
