### ISSUE TITLE
Wallet ends in blank page randomly on dashboard after login

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1354]
**Wallet version or commit SHA:**
`design-v2` branch (5a523f5)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.112

**Reproduction steps:**
1. Start Neon Wallet
2. Login to any wallet
3. It should be blank page, if not, then logout and login again until this happens

This is quite hard to reproduce, but it happens from time to time after logging to the wallet. It's probably related to fetching or presenting of NEP-5 assets, so you have to add some asset to your wallet before and input it's script hash to make it visible. Looks like wallet turns blank screen after login and throws an error in console.

**Screenshot/Video:**
![rpxofnull](https://user-images.githubusercontent.com/8177587/43790252-5771c1ce-9a72-11e8-81cf-77f2fe67a187.PNG)

**Comment by comountainclimber** [comment]
Fixed in design-v2 branch
