### ISSUE TITLE
Add ability to switch to TestNet on settings page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1355]
Currently there is no way to switch networks. We could add a drop-down for this on settings page, after user is logged in.

**Comment by 0ben0** [comment]
@drptbl - Jakub have you seen this mock-up?

![image](https://user-images.githubusercontent.com/35338801/43880503-9ad66e68-9ba0-11e8-8f6b-d9ffa75da563.png)

👍
