### ISSUE TITLE
NEO/Gas toggle

### ISSUE THREAD

**Issue by ksteigerwald** [CityOfZion/neon-wallet#137]
What would happen if a user tried to send Neo, but hit the Gas toggle? I am not certain yet so I ask... My guess is you would loose the coin. If this is the case, please consider updating the UI as it is very unclear which state you are in. I am out 121 Neo, and I can only assume this might had been the issue. 

Having a boolean toggle with no color contrast is just an accident waiting to happen(ed).

**Comment by anfn101** [comment]
I have just tested this a minute ago. There is no issue with doing so.
