### ISSUE TITLE
i didnt get deposit

### ISSUE THREAD

**Issue by pecmeister** [CityOfZion/neon-wallet#1375]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by pecmeister** [comment]
i send 100 ont from your wallet neo and they are not visible in transaction history and i ddint get it to exchange : https://neoscan.io/transaction/c8e2f1d713730952829ed5c4b62c29dab1e11b782af3737831c54f4956a8a1e0

![screenshot_2](https://user-images.githubusercontent.com/42461657/44251298-259fef80-a1f8-11e8-9e9a-ba7532484ca2.png)

**Comment by pecmeister** [comment]
also it is 2nd day i see it is under maintainance

![screenshot_3](https://user-images.githubusercontent.com/42461657/44251405-86c7c300-a1f8-11e8-9bd3-beeec78fd0b3.png)

**Comment by comountainclimber** [comment]
Looks totally fine to me https://neoscan.io/address/ANRKKMQaH7123sHvJ2a7tNVj8UkAFAKT4o please remember you can always switch block chain explorers in settings
