### ISSUE TITLE
Sent Neo to ONT wallet

### ISSUE THREAD

**Issue by bolle307** [CityOfZion/neon-wallet#1377]
I accidently sent Neo to Ont desktop wallet.
It is still on Neo blockchain , can i retrieve them back into my Neon wallet ???
Neo tracker hash: 994c20b17c556e45ad8c6f29e9d5e42b5e39332dc8944f83ff4b2b1adfb1be10
Ont hash: ASjVfsfWB8SEskMCY8G6KfhMMHF9w4aKaC
Sorry if this is not the right place to post.

 Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.26

**Environment:**
e.g.: Win 7 Proffesionel (64 bit) 

**Prerequisites:**
e.g.: have ont, dbc, qlc, xqta, mct in wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by comountainclimber** [comment]
Please ask for help on the NEO discord as this is not an issue with our wallet https://discord.cityofzion.io
