### ISSUE TITLE
0.2.7 NO ONT

### ISSUE THREAD

**Issue by bristolbear** [CityOfZion/neon-wallet#1378]
Hi. after installing new update I can no longer see or send my ONT ? am I doing something wrong ?
I am using nano s and installed not app from ledger live .

can anyone help !

**Comment by Denodeno** [comment]
Same here

**Comment by comountainclimber** [comment]
I have been actively investigating this issue sorry for the inconvenience... 

Rest assured your funds are totally safe and secure. Closing the application and reauthenticating should resolve the issue. Let me know if the problem persists after trying those steps @Denodeno and @bristolbear

**Comment by comountainclimber** [comment]
This issue should be fully resolved closing for now

**Comment by jpflug64** [comment]
> I have been actively investigating this issue sorry for the inconvenience...
> 
> Rest assured your funds are totally safe and secure. Closing the application and reauthenticating should resolve the issue. Let me know if the problem persists after trying those steps @Denodeno and @bristolbear

I just updated to 0.2.8 and all my ONT and MCT are gone.  I have closed and reauthenticated.  Using Ledger Nano S.  I looked last night before updating  and ONT and MCT were definitely there
