### ISSUE TITLE
how to import ONT wallet to NEON wallet using keystore  ?

### ISSUE THREAD

**Issue by bolle307** [CityOfZion/neon-wallet#1381]
Hello , does someone know how to import ONT wallet to NEON wallet using keystore  ??? thank you in advance.

Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.7

**Environment:**
e.g.: Win 7

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by Denodeno** [comment]
I tried the same but still cant see ONT on my Wallet

**Comment by comountainclimber** [comment]
For help using the wallet please ask for help in #support on the NEO discord https://discord.cityofzion.io. Closing this issue for now
