### ISSUE TITLE
Version number - where is it shown in the running program?

### ISSUE THREAD

**Issue by tester2011** [CityOfZion/neon-wallet#1389]
Simple one:

Where is the version number shown in the program window?

Perhaps it's my eyesight, or perhaps it's just not there?

Mike.

**Comment by comountainclimber** [comment]
You can see the version by selecting neon => about in the top bar
<img width="389" alt="screen shot 2018-08-20 at 11 10 42 am" src="https://user-images.githubusercontent.com/13072035/44355456-e678d500-a469-11e8-8b36-1b8885befe8c.png">

**Comment by tester2011** [comment]
I'm using the Linux version and can't see the option to do that.

Mike.
