### ISSUE TITLE
Implement new notifications design

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1394]
See mocks... Also note that Error notifications should not autodismiss as this is bad UX

**Comment by drptbl** [comment]
Tested, everything looks fine except one thing - error notifications are still dismissed automatically:
![notif](https://user-images.githubusercontent.com/8177587/46740792-ed6ed780-cca3-11e8-8b7c-d01c57aa2b19.gif)

**Comment by comountainclimber** [comment]
As per discussion with product the error messages will self dismiss **but** with an increased timeout compared to v1... I will go ahead and add border radius to the notifications though good find!

**Comment by drptbl** [comment]
Finished.
