### ISSUE TITLE
unable to claim GAS, and unable to send out my NEO too

### ISSUE THREAD

**Issue by jinike** [CityOfZion/neon-wallet#1396]
Hi ! I have a problem.... tried many times...after a few hours still the same problem.
Error calculating claimable GAS: timeout of 5000ms exceeded
my is 0.2.7 version...even I log out and login back..same problem.
any solution ?
and , now I trying to send out my NEO also failed, and unable to send out.....

**Comment by JDMJDMJDM** [comment]
I have the same issue

**Comment by Bajszi** [comment]
I have the same issue:
Just installed the newest NEON software and using it with Ledger on an iMac running High Sierra. After claiming my GAS, I sign the first tx then about 5 sec later I got the same message: "Error calculating claimable GAS: timeout of 5000ms exceeded".

**Comment by jinike** [comment]
Problem still unsolved... Error claim gas, and unable to send out Neo.

**Comment by chrisjoanne** [comment]
Monday 27th August - I have the same problem.

**Comment by parousia17** [comment]
Monday 8/27/18 - Same problem. If anyone comes up with a solution please let me know.

**Comment by doubleredrolex** [comment]
Aug 27, 2018
Same problem for me. Can’t claim gas. Getting the same error as everyone else. 
Error timeout 5000ms 
Mac OS Sierra 10.12.6
Neon 0.2.7
Most of the time when I log in, it doesn’t show my ONT or NNT tokens. Sometimes it does though. 

I am able to send NEO to my wallet but cannot claim gas. It doesn’t look like my amount of claimable gas is changing either. It’s been showing 2.64889099 for days.

**Comment by chrisjoanne** [comment]
Just an update from yesterday. I must have pressed "claim gas" over 60 or 70 times and eventually it's worked. After reading it worked for some people I just had a my Neon wallet open on another screen and kept hitting "Claim gas" for around an hour or so while catching up on emails.

**Comment by doubleredrolex** [comment]
I’ve been trying that for a while but I’ll keep doing it. I even reinstalled the wallet and still no difference. I’ll double check my firewall settings. 

**Email sent from my iPhone

**Comment by comountainclimber** [comment]
First off I want to thank you all for reporting the issue here on github... As of 8/28 this issue should be resolved in 0.2.7. Please note this has absolutely nothing to do with neon-wallet but rather issues related to extremely high levels of transactions on the NEO network. All GAS claims and transactions should be working as expected at this point
