### ISSUE TITLE
I am not able to open new wallet on my MAC 

### ISSUE THREAD

**Issue by fartnipplegiblets** [CityOfZion/neon-wallet#1401]
Hello. I am not able to open new wallet on my MAC. I'm feeling nervous as I tried to open my NEON wallet after many months and it was opening with errors and no NEO. I'm hoping this is beacuase I was opening an old version of the wallet, but when I installed the new version it wouldn't open at all. I got the following error: "Neon" can't be opened because it is from an unidentified developer" I remember this same thing happened many months ago and someone on GitHub gave me a link to download a copy from their server. Any help would be greatly appreciated. Thanks!

Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by comountainclimber** [comment]
You just have to right click and then choose open... this is the same for any application without an Apple distribution license (tons and tons of popular OSX apps)

https://support.apple.com/kb/ph25088?locale=en_US
