### ISSUE TITLE
Error calculating claimable GAS: Transaction failed!

### ISSUE THREAD

**Issue by jewseppi** [CityOfZion/neon-wallet#1406]
**Wallet version or commit SHA:**
Neon-0.2.7.Mac.dmg

**Environment:**
macOS High Sierra 10.13.6

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Claim GAS"
3. Sign 1 of 2 transaction on Ledger
4. Transaction fails and returns error

**Screenshots/Video:**
![clip](https://user-images.githubusercontent.com/6901751/44891867-a73f5500-acaf-11e8-9308-11e4bb7f6a97.png)

**Comment by anomogh** [comment]
I can confirm that the same error happens on Windows.

**Wallet version or commit SHA:**
Neon-0.2.8.Windows.exe

**Environment:**
Windows 10

Reproduction steps are the same.

**Comment by comountainclimber** [comment]
Closing this issue for now as GAS claims are currently being processed successfully
