### ISSUE TITLE
[feature request] Payment link from a web page opens the wallet

### ISSUE THREAD

**Issue by ByteFan** [CityOfZion/neon-wallet#1410]
As said above. Very much suitable for any merchant.

The wallet would automatically open on end user desktop computer and handle inputs (address, asset, amount) from a payment link (or QR code when mobile wallet) in a merchant web page.

All inputs would be pre-filled in the wallet GUI, the customer would only be required to validate the payment.

**Comment by comountainclimber** [comment]
Closing in favor of consolidating here => https://github.com/CityOfZion/neon-wallet/issues/1829
