### ISSUE TITLE
Please help. Downloaded Neon Wallet 0.2.8 as prompted onto my desktop pc windows, once downloaded Neon Wallet Balances are all Zero inside the Neon Wallet on my Desktop PC.   When checked on Neoscan I can see all of my tokens with accurate balances.  Is this just me or this a Neon Glitch.  Not sure, any help would be so appreciated.  I don't know what to do to fix this issue.  Where are all my Tokens?  I see them on Neoscan in my wallet, but they are not inside the wallet on my computer.  ?  I am lost, should of not tried to upgrade wallet.  

### ISSUE THREAD

**Issue by graysononassis** [CityOfZion/neon-wallet#1411]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by comountainclimber** [comment]
Please remove the invalid token hash you added via “manage tokens”

**Comment by graysononassis** [comment]
What?  I'm sorry, I don't understand.?

**Comment by comountainclimber** [comment]
Go to settings and then manage tokens next delete the invalid token hash you added.

**Comment by graysononassis** [comment]
OK, I understand, how will I know which one is invalid?  I own about 15 nep5 tokens?  I did not change anything in my wallet recently.

**Comment by graysononassis** [comment]
Let me do the above steps and see what I can figure out.  I apologize for the confusion.

**Comment by comountainclimber** [comment]
Because we now reference the full list of all nep5 tokens for users by default, you should be able to remove every hash you added via manage tokens

**Comment by comountainclimber** [comment]
Sorry for the inconvenience we will be fixing this very soon so even if users add invalid hashes the token balances will still render

**Comment by graysononassis** [comment]
OK, I understand now,  I did have an issue with SDT or SDS and both balances showing up recently.  Possibly that was the issue, let me see what I can figure out, Thank You very much.  Let me see if I can fix this myself.

**Comment by graysononassis** [comment]
Hello again,  OK There are 3 hash which have a delete button next to them.  They are the ones at the bottom the last 3, the rest of the hash above them just have the lock symbol.  I can go ahead and delete the 3 which have the Delete Icon Next to them?   I must have opened up the old version because I am now getting the message and prompt to update and download the new wallet again.  Don't know why, I've done this already.

**Comment by comountainclimber** [comment]
1.) download the most recent version here https://neonwallet.com
2.) delete every token hash you added via manage tokens in settings (one or more of them are invalid)

If you need additional help please ask in the #support channel of the NEO discord 👍

**Comment by graysononassis** [comment]
Thank You Very Much!!!   I am up and running again thanks to your help.  I deleted the 3 Hash which had the delete Icons next to them, then downloaded 0.2.8 again for windows and all of my balances are there.  Thank You very much for your time and help.
