### ISSUE TITLE
Manage Tokens Discrepancies

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neon-wallet#1414]
**Wallet version or commit SHA:**
0.2.8

**Environment:**
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134

**Prerequisites:**
None

**Reproduction steps:**
1. Start Neon Wallet
2. Open a wallet with NKN in it
3. No balance shown for NKN
4. Logout
5. Go to Manage Tokens and add a token
6. Add NKN hash again and save (now exists in list twice)
7. Login to wallet again
8. Balance for NKN is now displayed (odd because NKN hash is now on the token list twice)
9. Close Neon Wallet
10. Reopen and open wallet with NKN inside
11. Again, no balance displayed for NKN
12. Logout and go back to managed tokens
13. The previously added hash has been deleted. Only locked hashes remain.

**Screenshots/Video:**
Unnecessary. Please let me know if you need more info.

**Comment by jseagrave21** [comment]
@comountainclimber Yes, I just tested it again. That is the hash I enter to be able to see the tokens but it already appears on the list, so I don't understand why adding it a second time works.

**Comment by drptbl** [comment]
@jseagrave21 Thanks for reporting, going to investigate this further this weekend.
