### ISSUE TITLE
Coins missing in Ledger Nano S Wallet

### ISSUE THREAD

**Issue by dchan24crypto** [CityOfZion/neon-wallet#1422]
**Wallet version or commit SHA:**
 0.2.8

**Environment:**
 macOS High Sierra Version 10.13.6 

**Prerequisites:**
 GAS coins missing/unable to access coins when NEO block explorer confirmed transection with correct public address.

**Reproduction steps:**

1. Start Neon Wallet
2. logged into Neon Wallet via Ledger Nano S
3. No GAS amount available
4. Transection History on the right confirmed coins existed before
5. NEON Wallet is up-to-date
6. Latest Ledger Live software installed

Hi, I have a Ledger Nano S device which I have transferred 267.04181799 GAS to last month. I have updated my NEON wallet to latest version (2.0.8 ) and installed Ledger Live. After signing into my NEON wallet via Ledger wallet today as usual, all the GAS are missing despite the transection was traceable. Are you able to help please?

**Screenshots/Video:**
![41955033_504903300026235_6690500127276138496_n](https://user-images.githubusercontent.com/42303658/45731220-570b3280-bb8b-11e8-9e83-c5bd9507839c.png)
![screenshot 2018-09-18 21 39 19](https://user-images.githubusercontent.com/42303658/45731233-6b4f2f80-bb8b-11e8-9e44-3bf17cae2cf1.png)
![screenshot 2018-09-18 21 40 57](https://user-images.githubusercontent.com/42303658/45731269-92a5fc80-bb8b-11e8-89ff-2ea6f18b9ab8.png)

**Comment by comountainclimber** [comment]
@dchan24crypto this is a known bug but thank you for reporting. Please delete all script hashes that you have added manually to the app in settings => manage tokens. One or more of them are invalid. This will fix the issue 👍

**Comment by cgme0698** [comment]
Frustrated.  Now I have version 2.0.0 of NEON Wallet, and settings no longer has a manage tokens feature, so I can't figure out how to delete script hashes.  Same problem as above.  

"Error calculating claimable GAS: Block or transaction already exists and cannot be sent repeatedly"
Public address:  ATwiXn6j2GTzofympoj1z54Y2BaEkETkK4
