### ISSUE TITLE
no tokens after update to 2.8

### ISSUE THREAD

**Issue by simon84lau** [CityOfZion/neon-wallet#1449]
**Wallet version **
e.g.: 0.2.8

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
No tokens show in my wallet after upgrading to the latest version

**Reproduction steps:**

1. Start Neon Wallet
2. Login via private key

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/issues/1444
