### ISSUE TITLE
Red Pulse Support

### ISSUE THREAD

**Issue by Trickatreat** [CityOfZion/neon-wallet#145]
Red Pulse ICO is coming up on September 10th. Neon wallet has been recommended to send NEO to purchase them, but they haven't said anything about where the XRP is going to be stored. Has there been any thought as to supporting XRP in NEON?

**Comment by canesin** [comment]
@Trickatreat Neon is going to support native assets and NEP5 tokens in the near future. I believe (please consult XRP to be sure) that XRP will be a NEP5 token. So it is in the roadmap, to facilitate this - I will close this issue and refetor to it in a new one asking for NEP5 support.

That should clarify things for non-technical investors.
