### ISSUE TITLE
Hide password and private key by default on final screen of wallet creation

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1453]
**Wallet version or commit SHA:**
`design-v2` branch (8a1a780)

Wallet password and private key should be hidden by default on final screen of wallet creation (because it's hidden by default on previous screen while typing the password).

**Screenshot/Video:**
![create_wallet](https://user-images.githubusercontent.com/8177587/46165653-7a239980-c291-11e8-9635-29a45fbdce68.gif)

**Comment by comountainclimber** [comment]
Thanks for reporting this after careful consideration lets just stick with hiding the password for now in this view adding to the v2 board now...

**Comment by drptbl** [comment]
Not ready for QA yet.

**Comment by drptbl** [comment]
Fixed.
