### ISSUE TITLE
No token balances showing in wallet after setting up O Wallet 

### ISSUE THREAD

**Issue by Gurustu** [CityOfZion/neon-wallet#1455]
I cannot see my tokens in my neon wallet.  This issue seems to have happened about the same time as I transferred my ONT tokens to a new O wallet.  I have tried reloading the latest 2.8 update and logging in with saved wallet, encrypted key and private key but it still shows zero balances.  I can view all my balances on Neoscan.  Any suggestions would be gratefully received. Thanks.

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/issues/1444
