### ISSUE TITLE
Support NEP5 and native assets

### ISSUE THREAD

**Issue by canesin** [CityOfZion/neon-wallet#146]
With upcoming ICOs the wallet needs support for other assets and tokens besides the system ones.
Users are already expecting this feature as of #145.

**Comment by olivier-w** [comment]
Red Pulse just sent an email saying that Neon will not be supported in the upcoming ICO. Are there plans to have NEP5 support by October 8th?

<img width="645" alt="screen shot 2017-09-26 at 12 17 25 am" src="https://user-images.githubusercontent.com/465250/30842418-3ed2dbf0-a250-11e7-9e74-b4ab5b6974ed.png">

**Comment by txcx** [comment]
Would be cool to have that before ICO :) Thank you.

**Comment by iqoptioncoin** [comment]
Please don't leave the NEON update for MAC to just minutes before the Red-Pulse ICO. Please release it by the 5 Oct 2017, as MAC users cannot use the NEO GUI.

**Comment by dkliman** [comment]
So when will I be able to add any token I want to my NEO wallet, and be able to send and receive that?

**Comment by NewWorldBC** [comment]
Yes this is what i also would like to know, I've put RPX in my ledger but after that I founded out that I can't move them out of there so now I can't reach my funds, even with neotracker.io i can't open the wallet ... please help .. Thanks alot

**Comment by drreen** [comment]
Looking forward to this one...sent my RPX to the Ledger as well... *facepalm*

**Comment by BluBoy** [comment]
Is it possible to get an update on this? (has it made it into v0.8.0 and is there an estimated release date for that version?)

Issue has been open for 3 or 4 months. NEP-5 ICOs are starting to launch now.
Some ICOs (Deepbrain) are recommending people downgrade to v0.6.0 in order to participate, despite you removing the functionality in v0.7.0 because it didn't work as expected.

Concerned that a messy ICO may tarnish the NEO platform

**Comment by canesin** [comment]
@BluBoy relax, the release will happen way before Christmas.

**Comment by n-marek** [comment]
I ma glad I am not the only one who sent their RPX to Ledger 😆 
The ultimate HODL 💰

**Comment by drreen** [comment]
Looking forward to the update!

**Comment by Xcoder89** [comment]
Somewhat a noob question: Can addresses generated using wallet version 0.0.7 receive & hold NEP5 tokens? Ability to hold tokens should be version agnostic, right?

**Comment by BluBoy** [comment]
@Xcoder89 correct. The wallet ID itself will hold NEP-5 tokens just fine.
Currently the NEON Wallet interface to that wallet IF just doesn't display them.

@canesin Sorry to push, but any updates with this? There are a number of ICOs about to hit the final stages and we need to be able to tell investors if NEON supports NEP-5 or not. This is close to 4 months old now and will be cutting it close. I note that it is also one of the last tickets holding up v0.0.8. Are there issues implementing this?

**Comment by Melicio** [comment]
@canesin U mentioned that the release will be "way before Christmas" but i think it isn't happening as Christmas is tomorrow? I really like to store my NEP5 tokens on Ledger. via NEON wallet.

**Comment by omelnyk** [comment]
Did you guys consider reaching out to the past and upcoming NEO-based ICOs for financing the implementation of this task?

**Comment by ministoat** [comment]
The dev version shows dbc tokens on Nano Ledger but they aren't transferable- is this due to neon or the ledger app?

**Comment by blokewhistler** [comment]
any update on when this will be released we are told to relax but accurate information would be nice please

**Comment by anfn101** [comment]
NEP-5 support is in.
