### ISSUE TITLE
Ability to scan QR and autofill send details (nep9)

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1460]

**Comment by drptbl** [comment]
Works only for NEO and GAS currently, throws error and infinite loader in any other asset:
<img width="1194" alt="screenshot 2018-10-26 at 20 50 45" src="https://user-images.githubusercontent.com/8177587/47586587-f4167380-d960-11e8-8a44-e3fcda010953.png">
<img width="1198" alt="screenshot 2018-10-26 at 20 51 04" src="https://user-images.githubusercontent.com/8177587/47586588-f4167380-d960-11e8-9fba-b8a6d39475b3.png">

**Comment by comountainclimber** [comment]
Fixed
