### ISSUE TITLE
Missing ONT in NEON wallet

### ISSUE THREAD

**Issue by dchan24crypto** [CityOfZion/neon-wallet#1471]
**Wallet version or commit SHA:**
0.2.8

**Environment:**
MacOS High Sierra Version 10.13.6

**Prerequisites:**
e.g.: Missing ONT - transferred from Binance since April 2018

**Reproduction steps:**

1. Start Neon Wallet
2. Logged in as usual
3. ONT coins used to be there but is now gone

some description (for ex. what happens after completing reproduction steps), 
Checked on neoscan and the coins are still there
![screenshot 2018-09-28 19 25 40](https://user-images.githubusercontent.com/42303658/46239985-84a76700-c355-11e8-858c-1b545a7cc5a3.png)
![screenshot 2018-09-28 19 25 40](https://user-images.githubusercontent.com/42303658/46239987-8b35de80-c355-11e8-8cd9-e25baac50110.png)

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by dchan24crypto** [comment]
![42803127_10155423007512142_3142347955227328512_n](https://user-images.githubusercontent.com/42303658/46239996-bfa99a80-c355-11e8-88ac-aa5de239ddd9.jpg)

**Comment by camberos** [comment]
Any update on this issue? having the same thing

**Comment by dchan24crypto** [comment]
Managed to get ONT back but there was another coin that was given via free
airdrop which was unrecoverable

**Comment by comountainclimber** [comment]
Resolved in v2.0.0

**Comment by opensourcenewbie** [comment]
I have a similar issue to @roryjob .  Fortunately I only sent 1 ONT as a test, but it's not showing up in Neon (2.0.0)

Any suggestions, please?

**Comment by fabwa** [comment]
Neon does not support ONT. Please use a compatible wallet.

**Comment by opensourcenewbie** [comment]
@fabwa   Thanks for your reply, and confirming that **the information on CoinCentral is incorrect / out of date**

"You can also receive ONT by holding NEO in any non-exchange wallet. Some of these wallets may not display ONT after the drop, but you “will nevertheless be able to retrieve ONT in a wallet that does not display ONT from a wallet which does display ONT”, for example, the Neon Wallet."

https://coincentral.com/neo-will-drop-ont-to-the-community-tomorrow-heres-how-to-get-some/
