### ISSUE TITLE
Neon Wallet Private Key (WIF) missing

### ISSUE THREAD

**Issue by justinbritz** [CityOfZion/neon-wallet#148]
Hi Guys, i downloaded the Neon Wallet off of the Neo website and installed it onto my PC.
I was given a private key (WIF) and entered it my pc and didnt think to save the key like a tjop!
Can anyone give me an idea where i can get my Neon Wallet Key from (WIF)

**Comment by willisplummer** [comment]
@justinbritz if you haven't transferred any funds into your wallet yet, you should just create a new private key and be sure to store it securely

**Comment by justinbritz** [comment]
There are quite alot of Neo's in there already :-(

**Comment by totalvm** [comment]
Sorry, if you lost/didn't save your private key there is nothing we can do

**Comment by justinbritz** [comment]
How do i restore my wallet from a back up file?
Where is the backup file default saved to on PC?

**Comment by totalvm** [comment]
did you save a backup file?

**Comment by justinbritz** [comment]
i dont recall, i might have?
Its worth checking!
is there a default location where file would save to on PC?

**Comment by totalvm** [comment]
If you created the address with the Neon wallet, it doesn't save any file.
If you used the Neo-gui then you should have a .db3 file
If you used an online one you should have a .json file

If you have none of the above, I'm afraid there is nothing you can do to access your wallet

**Comment by justinbritz** [comment]
I used neon wallet :-(
Thanks

Ps is there maybe any chance in the future that perhaps after more
development that i might be able to retrieve sometime?

**Comment by totalvm** [comment]
No, your private key is the only thing that can access your funds.
That's also why there is a warning to save it before continuing.

**Comment by justinbritz** [comment]
ok
Thanks
