### ISSUE TITLE
Present Address instead of ScriptHashes on transfer history

### ISSUE THREAD

**Issue by igormcoelho** [CityOfZion/neon-wallet#1480]
On Transaction History, transfers are displayed as scripthash, but should be presented as base-58 Address. It's safer and makes more sense for users.

![image](https://user-images.githubusercontent.com/290989/46433269-cd309d00-c726-11e8-84ae-ea7fa7ad9cac.png)

**Wallet version or commit SHA:**
0.2.7

**Environment:**
Linux

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
1. Start Neon Wallet
2. Login and look to the right

**Comment by igormcoelho** [comment]
This is a follow-up from discussions at: https://github.com/neo-project/neo-vm/issues/17

**Comment by comountainclimber** [comment]
Fixed in v2.0.0

**Comment by igormcoelho** [comment]
Congratulation, NW 2.0 is amazing
