### ISSUE TITLE
Claiming ONT tokens from Neo

### ISSUE THREAD

**Issue by Woodguy265** [CityOfZion/neon-wallet#1486]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by Woodguy265** [comment]
I received ONT tokens because I owned Neo. I was able to transfer my ONT from Neo into my O wallet and I was able to swap them into the O wallet. Once this was done my 2nd half of ONT tokens was supposed to show up in my wallet. They have not shown up. Its been 5 days. Did I miss something? Thanks.

**Comment by comountainclimber** [comment]
Please reach out to support on the official NEO discord if this is still an issue.
