### ISSUE TITLE
My neo is gone

### ISSUE THREAD

**Issue by zachwelten** [CityOfZion/neon-wallet#149]
hey so i restarted my computer yesterday and my neo and gas were gon off of the neon wallet for pc desktop. i checked my WIF on neo tracker and nothing. so i tried my pubkic address off of bittrex that i used for my latest transfer and it said i had all my neo and gas there any help you can give me

**Comment by AshRolls** [comment]
Hello @zachwelten . Github is for the reporting of code issues only. Please join #support channel in slack and ask for assistance there.
