### ISSUE TITLE
Virus in version: Windows.Neon.Setup.0.0.4.exe

### ISSUE THREAD

**Issue by ZetaOS** [CityOfZion/neon-wallet#150]
Hey guys!

My virus scanner detected a virus in download: Windows.Neon.Setup.0.0.4.exe also windows it self prevented me to install.
A online sceck whit Virus total swows only one virus, so it can be a fake detection. Better safe than sorry,
Can the Devopers take a look at this and give me (us) a feedback if or when it`s safe to use?

Thanks!
Vic Green

**Comment by Ejhfast** [comment]
can you post the screenshot? if you downloaded from the github release page there is no virus in the software, the scanner is triggering a false positive

**Comment by totalvm** [comment]
This is because the exe file is not signed by a trusted source.
