### ISSUE TITLE
Release of snap/flatpak for linux 

### ISSUE THREAD

**Issue by hyviquel** [CityOfZion/neon-wallet#1509]
Building snap and/or flatpak packages would enable automatic update of neon on Linux which is very practical. Indeed, linux users need to download and manually install the appimage after each update and because of scam sites, updating the software manually is a major security flaw.

**Comment by comountainclimber** [comment]
We will definitely look into this thank you very much for the suggestion @hyviquel

**Comment by comountainclimber** [comment]
I am closing this issue for now as we will be unable to support automatic updates on all platforms in the near future
