### ISSUE TITLE
Empty position in assets drop-down inside "Request assets" tab on "Receive" page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1527]
**Wallet version or commit SHA:**
`design-v2` branch (a64a531)

**Environment:**
MacBook Pro (13-inch, 2017), macOS Mojave 10.14

**Reproduction steps:**
1. Login to your wallet
2. Click on "Receive" button on the left menu
3. Click on "Request Assets" tab
4. Click on "Assets" drop-down => third position is empty

**Description:**
Empty position in assets drop-down inside "Request assets" tab on "Receive" page.

**Screenshots/Video:**
<img width="568" alt="screenshot 2018-10-16 at 22 42 54" src="https://user-images.githubusercontent.com/8177587/47046457-68992780-d195-11e8-97c4-e3debabc2f18.png">

**Comment by comountainclimber** [comment]
Super weird but directly related to https://github.com/CityOfZion/neo-tokens/blob/a9a9b59ff834d91c94472bafa4e34b32ccce48d8/tokenList.json#L2

🙁

**Comment by drptbl** [comment]
Fixed.
