### ISSUE TITLE
Defect: add contact window padding is 0

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#1537]
**Wallet version or commit SHA:**
0.0.7

**Environment:**
win 10

**Prerequisites:**

**Reproduction steps:**
e.g.:
Activity view => add contact button

padding is 0 for the add contact view

**Screenshots/Video:**
![capture](https://user-images.githubusercontent.com/29798928/47101642-dc6c1c00-d1f7-11e8-84e1-c5dfdeb5193e.PNG)

**Comment by drptbl** [comment]
Fixed.
