### ISSUE TITLE
Defect: Token Balances "Nothing to See Here" not vertically centered

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#1539]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
0.0.7

**Environment:**
Win 10

**Prerequisites:**
Dont have any tokens in the wallet

**Reproduction steps:**

In the smallest window size, the 'Nothing to see here' text in the Token Balances card is not verticalled centered.

**Screenshots/Video:**
![capture](https://user-images.githubusercontent.com/29798928/47101930-a24f4a00-d1f8-11e8-89cb-709d4fe97980.PNG)

**Comment by drptbl** [comment]
Fixed.
