### ISSUE TITLE
Defect: Toast notification copy not vertically centered

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#1540]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
0.0.7

**Environment:**
win 10

**Prerequisites:**

**Reproduction steps:**
Hit refresh button on wallet view

The copy in the toast notification is not aligned with the 'checkmark' graphic

**Screenshots/Video:**
![capture](https://user-images.githubusercontent.com/29798928/47102079-ff4b0000-d1f8-11e8-9c3c-000c0dc3d769.PNG)

**Comment by drptbl** [comment]
Fixed.
