### ISSUE TITLE
Defect: Formatting of token balances

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#1544]
**Wallet version or commit SHA:**
0.0.7

**Environment:**
win 10

**Prerequisites:**
wallet open with neo and gas (or other nep5 with balances)

**Reproduction steps:**

1. "Holdings" formatting overflows  for large volumes in `Token Balances` card.
2. NEO/GAS values run together in `Holdings` Card

**Screenshots/Video:**
Sent via DM to @comountainclimber

**Comment by drptbl** [comment]
Partially fixed (issues while having huge $ balance are still expected).

<img width="449" alt="screenshot 2018-10-26 at 20 18 11" src="https://user-images.githubusercontent.com/8177587/47584937-47d28e00-d95c-11e8-86cf-97e87bf8fd18.png">
