### ISSUE TITLE
Design Proposal: Change `Holdings` label to avoid value conflicts with `Total Portfolio Value`

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#1545]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
0.0.7

**Environment:**
Win 10

**Prerequisites:**
Holding of system assets (NEO/GAS) and NEP5 with a registered price on CMC

When holding NEP5 tokens with a registered price on coinmarketcap alongside NEO/GAS, a fiat value is displayed in both the `Holdings` and `Total Portfolio Value` cards that will differ.  Proposal is to change the label for the `Holdings` card to something like `System Assets` for clarity.  Additionally, changing `Total Portfolio Value` to `Total Wallet Value` aligns the terminology with the rest of the application (Manage Wallets etc...)

**Comment by drptbl** [comment]
Fixed.
