### ISSUE TITLE
How to update.

### ISSUE THREAD

**Issue by gb1995** [CityOfZion/neon-wallet#156]
Hello,

Can i safely update my Neonwallet from 0.0.3 to 0.0.4 by "reinstalling" the dmg?

**Comment by aars** [comment]
I had no issues doing just that. But it would be good to know that this is supported, and perhaps where Neon stores it's data (`~/Library/Application Support/Neon` on Mac).

**Comment by Ejhfast** [comment]
Yes, but please post such questions in slack #support channel or on reddit
