### ISSUE TITLE
NEX-04-006 Wallet: Outdated Electron Version is being used (Info)

### ISSUE THREAD

**Issue by cure53** [CityOfZion/neon-wallet#1565]
The Neon Wallet desktop application currently relies on Electron 2.0.7, which is an outdated version. In the following it is shown that the _navigator.userAgent_ property indeed returns Electron 2.0.7.

**Value of _navigator.userAgent_:**
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Neon/0.2.8 Chrome/61.0.3163.100 Electron/2.0.7 Safari/537.36`

As described in the Electron's release notes, a security vulnerability is fixed in 2.0.12. The latter is the latest release of 2.x version. In order to protect users from the platform's vulnerabilities, it is recommended to always use the latest version of Electron.

**Comment by comountainclimber** [comment]
Fixed in https://github.com/CityOfZion/neon-wallet/releases/tag/2.0.0
