### ISSUE TITLE
Private KeyGen for NEON wallet different to address

### ISSUE THREAD

**Issue by nathanleonard3** [CityOfZion/neon-wallet#157]
Hi mate, 

I am having some issues with the NEON wallet that are doing my head in. 
The scenario is this: I download the NEON wallet and install no problem and then set up a new wallet. It generates a private key for me which I saved in screenshot format and emailed to myself and backed up to a second location immediately (see screenshot attached). And I don't care about posting this private key because there is nothing in there!
![neon capture](https://user-images.githubusercontent.com/31647554/30051609-07937c3e-9266-11e7-8ebf-93495814dadb.PNG)

I then logout of the program and when I log back in I have zero balance! After a couple of hours scrolling through the forums, I find that plenty of other people have had the same issue! What seems to be unique about my case is that I have been issued with a private key for a wallet that had a different address to the one I sent it to. As in I set up a wallet with the following address: 

AHWM7FdKekCDdV2oCdD4rqxxwEe7PpEsQS

But was issued with a private key for a different address! That being: 

AGJYkwRw9HS7adEkbzqM72HT7fcXggUkdp

So now on neotracker.io I can see the balance of my NEO coins but they're
in a wallet that I have no private ID for because the ID that was generated
before I sent them through was for a different wallet. As in the wallet on the 
start-up screen and the address of the one when I was in the program (the one
I actually used thinking that was my actual address) are different! The public address on the neon interface when I first opened the program was different. I was issued with a private key for an address that was different from the one that I first logged into. Huh?

How on earth do I rectify that? Why would that be the case in the first place?

And where do I go from here? 

Please help, this is sooooooooo annoying. 

Cheers, 

Nathan

**Comment by nathanleonard3** [comment]
PS I did not make a new wallet in doing this. I only pressed on the LOGIN button and entered my private key

**Comment by djsox13** [comment]
I have exactly the same problem - surely someone can help us

**Comment by AshRolls** [comment]
Hi @nathanleonard3 . The private key in the screenshot matches the public address in the screenshot ( AGJYkwRw9HS7adEkbzqM72HT7fcXggUkdp ). 

Why would you send NEO to a different address ( AHWM7FdKekCDdV2oCdD4rqxxwEe7PpEsQS ) ? That address would have a different private key to the one that you saved in the screenshot.

I think there may be a misunderstanding here with how public / private keys work here. Please join #support in the NEO slack and we can assist you further, as GitHub is intended for code issues, thank you.
