### ISSUE TITLE
User is redirected to neoscan home page instead of expected neoscan page in some cases

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1574]
**Wallet version or commit SHA:**
`design-v2` branch (9e2d017)

**Environment:**
MacBook Pro (13-inch, 2017), macOS Mojave 10.14

**Reproduction steps for "My Public Address" case:**
1. Create new wallet
2. Login to your wallet
3. Click on "My Public Address" address in top left on dashboard
4. You're redirected to neoscan address page but because this is new wallet, you're redirected back to homepage instead

**Reproduction steps for "Deposit into this wallet" case:**
1. Create new wallet
2. Login to your wallet
3. Click on "Receive" in left menu
4. Click on "Request Assets" tab
5. Click on "Deposit into this wallet" address
6. You're redirected to neoscan address page but because this is new wallet, you're redirected back to home page instead

**Reproduction steps for "View Activity" case:**
1. Login to wallet or create new wallet
2. Click on "Contacts" in left menu
3. Add new contact which has no history (new address)
4. Click on "View Activity" button
5. You're redirected to neoscan address page but because this address has no history (new address), you're redirected back to home page instead

**Description:**
In all cases described above, user is redirected to neoscan home page instead of presenting proper information/error for user. We should find a proper solution to handle this cases.

**Comment by comountainclimber** [comment]
Closing this in favor of tracking here https://github.com/CityOfZion/neo-scan/issues/366
