### ISSUE TITLE
Token values are filled incorrectly if asset balance is less than 0.00000100 (if input value was higher than current balance or user used "MAX" button)

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1577]
**Wallet version or commit SHA:**
`design-v2` branch (9e2d017)

**Environment:**
MacBook Pro (13-inch, 2017), macOS Mojave 10.14

**Pre-requirements:**
Less than 0.00000100 balance of any asset on the wallet (for example: 0.00000099 GAS or 0.00000009 GAS)

**Reproduction steps:**
1. Login to your wallet
2. Click on "Send" button in the left menu
3. Choose your desired token in "Asset" field (for ex. "GAS")
4. Type "1" in "Amount" field or click on "MAX" button (same behaviour)

**Description:**
After last reproduction step you can see "88" being typed instead of desired/max available value (in case while having 0.00000008 GAS on the wallet).

**Screenshots/Video:**
https://i.imgur.com/gFGZqTb.gifv

**Comment by drptbl** [comment]
Not fixed:
https://i.imgur.com/jZwA805.gifv

**Comment by comountainclimber** [comment]
fixed in https://github.com/CityOfZion/neon-wallet/releases/tag/2.0.0
