### ISSUE TITLE
Handle a case when user denied system permissions for camera

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1582]
**Wallet version or commit SHA:**
`design-v2` branch (9e2d017)

**Environment:**
MacBook Pro (13-inch, 2017), macOS Mojave 10.14

**Description:**
After trying to use camera for something for the first time, you have to allow Neon to use your camera (system permissions). If you deny them (purposely or not), all you can see is gray space instead of camera preview. We could detect if user denied permissions and show proper message or tutorial on how to fix this.

**Screenshots/Video:**
https://i.imgur.com/jURrGJd.gifv

**Comment by ranbena** [comment]
Can put an indication no prob. I'll conjure up some design perhaps.

BUT regarding leading the user to change the permission - n browsers there are a couple of ways to do that but I think they're irrelevant to Electron..

Any suggestions on how to reprompt or allow the user to change permission choice in Neon?

**Comment by ranbena** [comment]
I'm on this

**Comment by drptbl** [comment]
@ranbena Tested, everything works fine. The only thing is that when it fails on Linux, you're always linked to Ubuntu distro help page (even if you're on Debian for example). Still better than nothing 👍. Great job.
