### ISSUE TITLE
Disable ability to input divided amount of NEO while contributing in token sale

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1584]
**Wallet version or commit SHA:**
`design-v2` branch (9e2d017)

**Environment:**
MacBook Pro (13-inch, 2017), macOS Mojave 10.14

**Reproduction steps:**
1. Login to wallet
2. Click on "Token Sale" button in left menu
3. Input 0.01 NEO in "Amount" field
4. Try to contribute

**Description:**
User shouldn't be able to input divided amount of NEO while contributing in token sale.

**Screenshots/Video:**
<img width="711" alt="screenshot 2018-10-23 at 18 56 39" src="https://user-images.githubusercontent.com/8177587/47377380-66831b80-d6f5-11e8-908b-35e0ce3f126f.png">

**Comment by comountainclimber** [comment]
Because we still validate this amount I am tabling this and labeling is as "nice to have"
