### ISSUE TITLE
Very minor issue/error

### ISSUE THREAD

**Issue by anastrophe** [CityOfZion/neon-wallet#159]
I am on V 0.0.4. Got a red banner just now, and it advises that Neon wallet is out of date, and to please download...........v 0.0.4.

Obviously, it's v 0.0.5 that is the next version. Not a big deal really - it was obviously clear there's an update, which is great. Just super-tiny confusing to be told to upgrade to the same version. :)

**Comment by Ejhfast** [comment]
Thanks, this has been fixed in 0.0.5!
