### ISSUE TITLE
Windows.Neon.Setup.0.0.5.exe - virus?

### ISSUE THREAD

**Issue by remm12** [CityOfZion/neon-wallet#160]
<img src='https://i.imgur.com/nhP7fPR.png' />``

**Comment by AshRolls** [comment]
This is not a virus, don't worry. The executable isn't signed against a public authority, which is why Windows is trying to protect you with this dialog, if you go to 'More info' you will be able to continue installation.

**Comment by remm12** [comment]
Thanks for fast answer. Issue is fixed.
