### ISSUE TITLE
0.2.8 Not showing DBC Tokens

### ISSUE THREAD

**Issue by Mirasif** [CityOfZion/neon-wallet#1605]
Hello, I updated my neon wallet few weeks ago, it was working perfectly until today. 

i logged in on it today it was working fine at first, i could see my DBC tokens in it, so i try to send some DBC tokens from it to Kucoin exchange, it give red "transaction failed" error that's why i closed the app and re-opened it, so that i can try again....  now i can't see any of my tokens on it anymore but i can see them in "neotracker" that they are in my account... 

but Neon wallet is no-longer showing them, plz help 

thanks

**Comment by ArtemBernatskyy** [comment]
Try to reinstall neon.app, this solution has worked for me.
But also remove ALL configuration files !

**Comment by gbswanson** [comment]
I can't see any tokens.  I just tried reinstalling neon and made sure it was a clean uninstall, but to no avail.

**Comment by ArtemBernatskyy** [comment]
Ensure that you can see tokens in https://neoscan.io.

If YES then make a CLEAN reinstall (for Mac OS use freemacsoft.net/appcleaner) so you need to be sure that you've deleted ALL config files

If NO then you don't have tokens .

**Comment by squido75** [comment]
Did a clean install of the neon.app, and tokens are still not showing. (After clean install, I can claim GAS.)

I do have tokens, and they are listed in https://neoscan.io.

Neon.app Version : 0.2.8
OS: MacOS 10.13.3

**Comment by instafan** [comment]
> Did a clean install of the neon.app, and tokens are still not showing. (After clean install, I can claim GAS.)
> 
> I do have tokens, and they are listed in https://neoscan.io.
> 
> Neon.app Version : 0.2.8
> OS: MacOS 10.13.3

Hey @squido75 how's everything from your end? Can you see your tokens now?

**Comment by comountainclimber** [comment]
fixed in https://github.com/CityOfZion/neon-wallet/releases/tag/2.0.0
