### ISSUE TITLE
gas claim failed with 0.0.5

### ISSUE THREAD

**Issue by Cerv4ntez** [CityOfZion/neon-wallet#161]
Hi, 

with 0.0.5 i can no longer claim gas. when trying to my neo is sent to myself (as i can check in the blockchain) but a message in red saying gas claim failed appears, no matter how often i try.
heres a transaction that failedÖ
https://neotracker.io/tx/d340c8db1fc5c8ab2b8aa2d690cc0854a2218a0c4985325424500a712c48be22

![image](https://user-images.githubusercontent.com/18594385/30173347-9916f8f6-93f7-11e7-8bb1-125be64b20bb.png)

**Comment by jamesfredericks** [comment]
I get the same exact error

**Comment by cryptheist** [comment]
same exact issue for me.

**Comment by kranes** [comment]
I have same issue. When i click "claim GAS" , it will hang to "Sending Neo to Yourself". Tried to Logout and LogIn, same issue encountered... Anyone from Neo Support please assist us? Many thanks

**Comment by egret85** [comment]
I have this issue as well. For me everything shows correct on neotracker.io.  The NEON wallet however doesn't look like it is updating correctly. Tran history is missing transactions and the GAS has stopped increasing.  I also check using the api (http://api.neonwallet.com/v2/address/balance/{PUBLIC_ADDRESS}) and the return is also incorrect.  The API does match what the wallet shows, but does not match neotracker.io.

**Comment by Satoshinaire** [comment]
Neon's server needed a rebuild due to some behind-the-scenes API changes. This is in progress now, so everything should be working again shortly.

**Comment by cryptomitchman** [comment]
I am having the exact same issue with wallet 0.0.6 . Can you rebuild neons server again? Ii can't claim my gass. I get the same red message. I tried sending neo to myself and t didnt work.

**Comment by stevesbrain** [comment]
@cryptomitchman I don't think this is the same issue. I can claim without issue on 0.0.6.
