### ISSUE TITLE
design-v2(UX): [Enhance] Create Wallet: No status message or user message feedback for passwords that do not match 

### ISSUE THREAD

**Issue by phetter** [CityOfZion/neon-wallet#1619]
**Wallet version or commit SHA:**
2.0.0

**Environment:**
Ubuntu Linux 16.04

**Prerequisites:**
None

**Reproduction steps:**
1. Click "Manage Wallets"
2. Click "Create"
3. Fill out information
4. Enter passwords that do not match

When passwords do not match there is no status message. One has to click both eyes to understand why the create wallet button is grey.

**Comment by jseagrave21** [comment]
I'm not sure if this is a difference between Windows and linux, but I do receive a message when passwords don't match.

![image](https://user-images.githubusercontent.com/40873301/47872415-c5b6ef00-ddcb-11e8-9523-0393dc997105.png)

**Comment by jseagrave21** [comment]
[deleted my last comment. I realized this issue is for creating a wallet, not logging into an existing wallet]
