### ISSUE TITLE
2.0.0 Unable to enter amount to send, defaulting to maximum available

### ISSUE THREAD

**Issue by ThomasLobker** [CityOfZion/neon-wallet#1620]
**Wallet version or commit SHA:**
2.0.0 (50dd6cc)

**Environment:**
Linux Ubuntu 16.04 (amd64) using Neon-2.0.0-x86_64.AppImage

**Prerequisites:**
Installed the AppImage, opened the existing wallet from disk from NEON 0.2.8.

**Reproduction steps:**
1. Start Neon Wallet, login to an existing wallet with assets, wait for everything to be loaded
2. Click on "Send" button
3. Select asset and recipient address from the address book
4. Click in the amount box, select the existing 0 and try to make it 5

Expected to happen:
- 5 NEO ready to send

What happens now:
- The total available amount of NEO is filled in. I'm unable to change this to the desired amount of 5 NEO. Backspace and delete are not working, pasting an amount is not working.

**Screenshots/Video:**
On request via Slack

**Comment by comountainclimber** [comment]
Fixed 👍
