### ISSUE TITLE
"Import" functionality is missing on wallet start page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1621]
Currently you're able to export your wallet details, but to import them you have to create a dummy wallet, login to it, then go to "Settings" to see import functionality. It should be accessible from start page of the wallet without requirement to login.

**Comment by phetter** [comment]
I have a cople of things that have come up regarding this as I was looking at working on it:

1. If you go into settings and recover wallets (via NEP-6 file) it will pull a list of wallets that you can see under Manage Wallets, but you can't switch between them from there. I'd like to add a feature to the Manage Wallets page to switch to another wallet in the list. I propose we add an item to the drill down, and perhaps to the list view of wallets, that lets you switch to that wallet. "Set Active", "Use this wallet", or similar. This button, imo, would just log you out and redirect you to the login with that wallet pre-filled in the login section or popup a login pane. I'm leaning toward the login pane popup.

2. I want to add a button on the main screen that says "import recovery file", or whatever language you think is best, that will let you do so without having to first login. The import would perform the import then redirect you back to the login screen with the dropdown populated with the list of wallets for you to select to login. We would keep the import wallet button as is.

**Comment by dauTT** [comment]
@comountainclimber ,

Do you simple want to add a new tab, `Recover Wallet` on the `import wallet` page? The functionality  of `Recover Wallet` is the same as the one that we have in the `Settings` ?

![image](https://user-images.githubusercontent.com/30392990/60055821-2a1e1a00-96df-11e9-9c01-252ce582a37e.png)

![image](https://user-images.githubusercontent.com/30392990/60055961-9b5dcd00-96df-11e9-81ea-7197883820df.png)

**Comment by comountainclimber** [comment]
<img width="1222" alt="Screen Shot 2019-06-24 at 7 21 00 PM" src="https://user-images.githubusercontent.com/13072035/60058147-4311d580-96b5-11e9-8dd9-029ceace393b.png">

**Comment by comountainclimber** [comment]
@dauTT I was thinking something like this let me know what you think

**Comment by uvmetal** [comment]
I kind of like this, but I still feel like recover and import are confusing. It seems it may be the use of the term "wallet". Importing a NEP6 versus importing a private key, etc, is where it gets ambiguous, imho.

**Comment by uvmetal** [comment]
Maybe some clarification along the lines of import wallet by file versus by key?

**Comment by dauTT** [comment]
This feature is implemented. It depends on PR #1879. For simplicity, to avoid to resolve complex merge conflicts, we will submit a PR after PR #1879 is merged.

**Comment by dauTT** [comment]
@comountainclimber , we should probably close this issue. :+1:
