### ISSUE TITLE
design-v2(UX): [Enhance] No network indicator when on MainNet, only on TestNet

### ISSUE THREAD

**Issue by phetter** [CityOfZion/neon-wallet#1623]
**Wallet version or commit SHA:**
2.0.0

**Environment:**
Ubuntu Linux 16.04

**Prerequisites:**
None

**Reproduction steps:**
1. Login to a wallet

Network indicator only appears for TestNet, but none is shown when on MainNet

**Comment by comountainclimber** [comment]
Thank you @phetter but this is actually by design... We want the "default" net to be main and any others labeled closing this one for now
