### ISSUE TITLE
Ledger login button gets disabled while NEO app is open

### ISSUE THREAD

**Issue by DalderupMaurice** [CityOfZion/neon-wallet#1624]
**Wallet version or commit SHA:**
2.0.0 

**Environment:**
Windows 10 Home 64 bits

**Prerequisites:**
Own a Nano Ledger S

**Reproduction steps:**
1. Start Neon Wallet
2. Navigate to login using a Ledger 
3. Insert Ledger & unlock with pincode 
4. Open NEO app
5. DO NOT CLICK LOGIN --> WAIT couple seconds (note that at this point, the mouse pointer turns into a normal pointer)
6. You now see that the login button becomes disabled and you see a spinner next to "Connect and unlock your ledger device"
7. After a couple moments (approx 10sec) the login button is enabled again (note that any button or such still doesn't have the mouse pointer, but the default pointer) 

**Screenshots/Video:**
During this GIF I kept the NEO app open at all times! (The button remains disabled for a 10 seconds, but the GIF duration is too short to capture this)
![](https://gyazo.com/62ef3b481ce34cef4edcbc9d9acef674.gif)

**Comment by comountainclimber** [comment]
fixed 🎉

**Comment by nspt09** [comment]
I recently downloaded the newest version of the Neon Wallet (2.0.0, Neon.AppImage). I am having the same problem as @DalderupMaurice. I am using Ubuntu 18.10.
