### ISSUE TITLE
design-v2(UX): [Enhance] Manage Contacts: Delete from list view

### ISSUE THREAD

**Issue by phetter** [CityOfZion/neon-wallet#1625]
**Wallet version or commit SHA:**
2.0.0

**Environment:**
Ubuntu Linux 16.04

**Prerequisites:**
None

**Reproduction steps:**
1. Login to a wallet

It would be nice to be able to delete contacts from the list view (no need to press edit) or with a group select.

**Comment by comountainclimber** [comment]
please award @phetter 200 👍

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/4d9444405b926866f2001468a0d1f4766c1d61da91fb7a46e9d1c917f65ec938
