### ISSUE TITLE
design-v2(UX): [Enhance] Chart scale dropdown menu

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neon-wallet#1626]
**Wallet version or commit SHA:**
2.0.0

**Environment:**
Win 10 Pro

**Prerequisites:**
None

**Reproduction steps:**
1. Login to a wallet

- On the home screen it looks like the scale for the chart is a dropdown menu but when I click on it, it cycles through (no dropdown menu). The icon should actually yield a dropdown menu.
- Also the best fidelity I get is 1 Day. We should be able to get better resolution. (1 hour, 4 hour)
- Finally, the default timeframe is 1 month. I think this scale is much too large for the average user. Perhaps 1 Day would be a better default timeframe.

**Screenshots/Video:**
![dropdown](https://user-images.githubusercontent.com/40873301/47866631-8f25a800-ddbc-11e8-8baa-dad2897d48ec.png)

**Comment by ranbena** [comment]
Heyo, I'm working on this and will soon have a PR.
Plz assign me or mark In Progress (I lack the permissions).

**Comment by comountainclimber** [comment]
Fixed 🎉
