### ISSUE TITLE
design-v2 [bug]: Chart display is frequently in error

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neon-wallet#1628]
**Wallet version or commit SHA:**
2.0.0

**Environment:**
Win 10 Pro

**Prerequisites:**
None

**Reproduction steps:**
1. Start Neon Wallet

The chart display is often incorrect and does not correct with refresh.

**Screenshots/Video:**
![2ndmonth scale](https://user-images.githubusercontent.com/40873301/47870361-9c479480-ddc6-11e8-914d-c0d1dc7b6eb6.png)

vs.

![month scale](https://user-images.githubusercontent.com/40873301/47870378-a23d7580-ddc6-11e8-9a96-d3fcf300511a.png)

**Comment by ranbena** [comment]
@jseagrave21 Some changes were made to chart duration lately. Plz retest and see if bug persists.

**Comment by jseagrave21** [comment]
This specific bug does not seem to be recurring. I will close and reopen if it appears again.
