### ISSUE TITLE
cannot reinstall neon wallet 

### ISSUE THREAD

**Issue by mrtwistednutz** [CityOfZion/neon-wallet#163]
Hi,
I recently read a message in my neon wallet telling me to update version 0.04 as my current version was  out of date.

After update, wallet would not open.

I  tried uninstalling to reinstall and open, but now wallet will not install due to insufficient permissions.

error opening file for writing:

C:\Users\David\AppData\Local\Programs\Neon\Uninstall Neon.exe

I am admin on this PC and should have access to all files, however I cannot alter or delete this file

please advise

**Comment by stevesbrain** [comment]
Visit Slack for support with the use of the software, but, I'd be checking if you've got permissions to the parent folder, if the file is locked or in use, etc.

**Comment by viperroos** [comment]
How do I get into the slack group? All invitation links expired.

**Comment by Satoshinaire** [comment]
@viperroos See the Slack link in the sidebar here: https://www.reddit.com/r/NEO/

**Comment by ServantOfNone** [comment]
@mrtwistednutz I found a solution on this page (solution 2) that worked for me. 
1. Right click the neon.exe file
2. Properties
3. Click Compatibility Tab
4. Run Compatibility Trouble Shooter
5. Use Recommended Settings
