### ISSUE TITLE
design-v2 UX [bug]: Charts are inconsistent

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neon-wallet#1631]
**Wallet version or commit SHA:**
2.0.0.21

**Environment:**
Win 10 Pro

**Prerequisites:**
None

**Reproduction steps:**
1. Start Neon Wallet
2. Toggle through charts

Related to https://github.com/CityOfZion/neon-wallet/issues/1628
The Chart display is inconsistent.

The Charts should either display using 1 month/week/day increments or cover one period

**Screenshots/Video:**
![month](https://user-images.githubusercontent.com/40873301/47885315-a9c64400-ddf1-11e8-89a2-17528892eff9.png)

vs.

![week](https://user-images.githubusercontent.com/40873301/47885321-afbc2500-ddf1-11e8-9deb-72f7b289660a.png)

vs.

![day](https://user-images.githubusercontent.com/40873301/47885325-b5196f80-ddf1-11e8-9a43-69b64ed6644f.png)

**Comment by ranbena** [comment]
I fail to understand what the bug is from the issue description. Plz elaborate or point to the problem.

**Comment by jseagrave21** [comment]
@ranbena Okay, the chart timeframes not consistent. For the day and month timeframe, the chart displays a single day/month period. However, the week timeframe displays a graph were each point on the graph represents a week.

The charts should be consistent. So, if one period is supposed to be shown then the weekly chart should only show one week's worth of data.
