### ISSUE TITLE
design-v2 UX [enhancement]: All tokens not visible when sending/receiving

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neon-wallet#1633]
**Wallet version or commit SHA:**
2.0.0.21

**Environment:**
Win 10 Pro

**Prerequisites:**
None

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Send" or "Receive"

**What is happening:**
Not all tokens are listed.

**What should be happening**
All tokens should be visible (e.g. add the ability to scroll through assets so window size can remain fixed)

**Screenshots/Video:**
![total](https://user-images.githubusercontent.com/40873301/47886318-8baf1280-ddf6-11e8-94e4-1ad8f7e93012.png)

vs.

![list](https://user-images.githubusercontent.com/40873301/47886321-91a4f380-ddf6-11e8-89b2-5d201513007c.png)

**Comment by comountainclimber** [comment]
After a long deliberation with our designer we decided that what we have now is superior to offering scrolling in the "amounts panel" closing this issue for now

**Comment by jseagrave21** [comment]
Okay sounds good. Thank you for the feedback!
