### ISSUE TITLE
Font inconsistency for currency symbol

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neon-wallet#1639]
**Wallet version or commit SHA:**
2.0.0.dev (b2519eff)

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 10.0.17134 Build 17134

**Prerequisites:**
N/A

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Log in
3. Change currency to RUB (Russian Ruble)
4. Go back to wallet page

For "System Assets" and "Market Data" currency font is inconsistent with the default font and falling back to the system one.

**Bad:** font-family: Gotham-Medium;
**Good:** font-family: 'Gotham', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif 

_I'd suggest not to define font manually but to use global var to share same values everywhere._ 

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/454196/47968465-64e01e80-e038-11e8-9e18-025d60cc74e5.png)

**Comment by ranbena** [comment]
@osmirnov suggests applying font fallbacks which is doable indeed but I'd rather understand the problem first.
Anyone have an idea why the fonts aren't showing up? Network hiccup? Browser / Electron / Implementation bug?

**Comment by ranbena** [comment]
Ohh ok. On it 👍

**Comment by drptbl** [comment]
Re-tested, looks good.
