### ISSUE TITLE
There is no validation on wallet name while importing new wallets from *.json file

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1640]
**Wallet version or commit SHA:**
`design-v2` branch (b2519ef)

**Environment:**
MacBook Pro (13-inch, 2017), macOS Mojave 10.14

**Reproduction steps:**
1. Create a new wallet named "test"
2. Login to newly created wallet
3. Click on "Settings" button in the left menu
4. Click on "Export" button and save *.json file anywhere
5. Close your Neon wallet and clear it's app data (fresh Neon wallet installation)
6. Start Neon wallet
7. Create a new wallet named "test"
8. Login to newly created wallet
9. Click on "Settings" button in the left menu
10. Click on "Import" button and choose previously saved *.json file
11. Logout from current wallet
12. Click on drop-down with saved wallet => you can see 2x "test", both of them will login you to the wallet which was created as 1st

**Description:**
If you have a saved wallet named "test" and then you import a *.json file with another wallet which has exactly the same name ("test") - you will end up having 2x "test" wallet in the app. You're able to login only to first wallet created (saved wallet in this case), doesn't matter which "test" wallet you're going to choose from drop-down list (1st "test" or 2nd "test") - it will always log you in to the 1st one.

**Screenshots/Video:**
Video is taken from 6th reproduction step (after saving *.json file with a wallet named "test"):
https://i.imgur.com/h3LEgkq.gifv

**Comment by ranbena** [comment]
Easiest fix imo is an automatic suffix to wallet name upon conflict.
The import would succeed and wallet renamed to "test-1" or perhaps "test-${timestamp}".
Wdyt?

**Comment by drptbl** [comment]
@ranbena This seems to be partially solved. Currently (after recent changes), if you try to import a *.json file which contains a wallet with the same name as one of the saved wallets, you will get following error:
![wallet-exist](https://user-images.githubusercontent.com/8177587/48803394-160dd680-ed12-11e8-8d20-955258c5cae4.PNG)

I think that it's quite unclear in situation if you're trying to import a file with more than 1 wallet (for example 5 wallets in *.json file). You will end up having no idea which wallet blocks the import. It would be good to show names of the wallets that are blocking the import, so user is aware which wallet names to change. What do you think?

**Comment by drptbl** [comment]
@evgenyboxer @ranbena It seems that recent changes has introduced a regression which causes that wallets are still imported (even while error show up). I think that this has been introduced with #1716, I didn't see them on #1697 before. Please let me know if you want a new issue for this. I've decided to leave it here because it's a regression from work on this issue.

<img width="683" alt="screenshot 2018-11-26 at 15 55 07" src="https://user-images.githubusercontent.com/8177587/49022003-24d20e80-f194-11e8-96a4-bdf13b9eabe4.png">
<img width="655" alt="screenshot 2018-11-26 at 15 54 53" src="https://user-images.githubusercontent.com/8177587/49022005-24d20e80-f194-11e8-8fc4-27539a526bb7.png">

**Comment by ranbena** [comment]
10x @drptbl. Looking into it now.

**Comment by ranbena** [comment]
THE SHAME!
@drptbl 10x for noticing this. @evgenyboxer PR is out https://github.com/CityOfZion/neon-wallet/pull/1726.

**Comment by drptbl** [comment]
Looks good now, thanks 👍.
