### ISSUE TITLE
My Neon 0.0.5 doesn't show all my crypto

### ISSUE THREAD

**Issue by Reznor1023** [CityOfZion/neon-wallet#165]
Hi ,
I downloaded the Neon 0.0.5 for Mac. Worked like a charm. Had 111 units showing. Sent another 9. the Neo tracker says I have 120, but my wallet only shows 111. 
I ve tried clearing caches, rebooting, refreshing, all the such, and no luck. 
Can anyone help?

Thanks!

**Comment by Satoshinaire** [comment]
Neon's server needed a rebuild due to some behind-the-scenes API changes. This is in progress now, so everything should be working again shortly.

Visit and read the #support channel on Slack for updates.
