### ISSUE TITLE
CAN SOMEONE FIX THE NEON WALLET -- 

### ISSUE THREAD

**Issue by iknowmorenow** [CityOfZion/neon-wallet#1660]
**ISSUE:** 
1st. I have the current NEON Wallet version. 
2nd. I have to keep updating and Adding my nep 5 token. Just hopefully see the tokens. 
Sometimes the token shows up, however for a few short minutes then it disappears again. Keeping me from sending my tokens. TO BE HONEST this should be a PRIORITY TO FIX..

**Comment by dennish007** [comment]
yes same here. lately sending NEP5 is unusable. have to switch to neotracker.io for sending NEP5.

**Comment by Anukshuk** [comment]
Same here. I am totally fed up working on neon wallet. The item shows up and then disappears before I send TKY to the exchange? Very frustrating to say the least

**Comment by dennish007** [comment]
> Same here. I am totally fed up working on neon wallet. The item shows up and then disappears before I send TKY to the exchange? Very frustrating to say the least

I worked on version 0.2.6 and everything worked fine. NEON 0.2.8 moved to other API providers and probably are not working on legacy systems.

**Comment by instafan** [comment]
> > Same here. I am totally fed up working on neon wallet. The item shows up and then disappears before I send TKY to the exchange? Very frustrating to say the least
> 
> I worked on version 0.2.6 and everything worked fine. NEON 0.2.8 moved to other API providers and probably are not working on legacy systems.

Hey there - how did it work from your end? did you downgrade from 0.2.8 to 0.2.6? Can you please provide more details? Thanks.

**Comment by dennish007** [comment]
> > > Same here. I am totally fed up working on neon wallet. The item shows up and then disappears before I send TKY to the exchange? Very frustrating to say the least
> > 
> > 
> > I worked on version 0.2.6 and everything worked fine. NEON 0.2.8 moved to other API providers and probably are not working on legacy systems.
> 
> Hey there - how did it work from your end? did you downgrade from 0.2.8 to 0.2.6? Can you please provide more details? Thanks.

I did not downgrade. used a different mac with 0.2.6 on it.

**Comment by Anukshuk** [comment]
Same problem with both versions

**Comment by dennish007** [comment]
> Same problem with both versions

Did not test is yet, but version 2.0 seems to solve this problem of 'tokens appearing and disappearing'

**Comment by comountainclimber** [comment]
Please download 2.0.0 https://neonwallet.com
