### ISSUE TITLE
Wrong password message possible typo

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neon-wallet#1661]
**Wallet version or commit SHA:**
2.0.0.dev (be831ac7)

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 10.0.17134 Build 17134

**Prerequisites:**
N/A

**Reproduction steps:**
1. Start Neon Wallet
2. Try to login with the wrong password
3. You will see "Wrong Password or scrypt parameters!"

Is it a typo in "scr**y**pt"? Why is "Password" with a capital letter?

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/454196/48304013-64d09a80-e4e0-11e8-8274-9ee608766592.png)

**Comment by comountainclimber** [comment]
This should be an issue opened in neon-js not neon-wallet. I have little control over the error messages that bubble up from that dependency but I suppose we can leave this issue open

**Comment by comountainclimber** [comment]
Closing this one for now as the fix has been merged to neon-js
