### ISSUE TITLE
Add Contact hidden validation

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neon-wallet#1662]
**Wallet version or commit SHA:**
2.0.0.dev (be831ac7)

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 10.0.17134 Build 17134

**Prerequisites:**
N/A

**Reproduction steps:**
1. Start Neon Wallet
2. Login
3. Try to add a contract with invalid data -> "Add to Contacts" button is inactive

The app behaves correct but there are no validation messages for a user to fix issues.

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/454196/48304124-16240000-e4e2-11e8-94cc-6d71b994c646.png)

**Comment by tbeck860** [comment]
Tested successfully on 2.1.0.dev Windows 10 Pro build 17134.648 v1803 
Invalid address error handling displayed  

![3-30-2019 7-15-59 PM](https://user-images.githubusercontent.com/31013176/55283448-bf985080-5320-11e9-8072-87506c7d466a.png)

**Comment by comountainclimber** [comment]
Thanks for verifying @tbeck860 !

**Comment by comountainclimber** [comment]
This feature is in the 2.2.0 release candidate. Closing for now 🎉
