### ISSUE TITLE
Hard code in Sent transaction component

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neon-wallet#1668]
**Wallet version or commit SHA:**
2.0.0.dev (be831ac7)

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 10.0.17134 Build 17134

**Prerequisites:**
N/A

**Reproduction steps:**
1. Start Neon Wallet
2. Login
3. Send min GAS -> transaction should be completed

Expectation: It should display real asset instead of hard code.

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/454196/48306457-066ae280-e507-11e8-8747-6a4af432dde1.png)

**Comment by comountainclimber** [comment]
Not sure how your suggestion would work if a user for instance sent 25 different tokens for instance

**Comment by osmirnov** [comment]
Fair enough, maybe "25 assets were sent to 10 recipients"?

**Comment by comountainclimber** [comment]
Closing this for now as the current functionality is to list the number of assets and number of recipients like you had suggested in your last comment. Feel free to comment if you think there are still enhancements to be made
