### ISSUE TITLE
wallet not showing ballance and not allowing gas update

### ISSUE THREAD

**Issue by pookiecheese** [CityOfZion/neon-wallet#167]
i initially downloaded neon from neon.com then deleted it without using it. i then downloaded v.5 from github and ran that. i can get in/out ok. sent 1 neo test and worked ok
40e7e43895b7870de73bc27e47222ccf16b1909b7757ed78b6b836befd782294
was showing unspent but now showing spent over an hour later but shows as 1 neo in account
i then sent 70 neo
650d813a625c9e383c5d16cc1025d5222b84c31250d7f9c935b655db99862e3e
it never showed up and i cant update gas. it shows that it came and is unspent but 5 are spent and somewhere else . where are the tokens?

**Comment by pookiecheese** [comment]
I opened a neo tracker wallet and tried to send hidden tokens but it says that i don't have enough tokens even when i try to send 60

**Comment by pookiecheese** [comment]
is Bitrex the link is there some missing identifyer or protocol?

**Comment by pookiecheese** [comment]
sorry closed in error

**Comment by Satoshinaire** [comment]
@pookiecheese It should be closed and you should seek support in the appropriate Slack channel. This GitHub is for tracking development tasks.
