### ISSUE TITLE
Transferred 24 Neo from Bittrex, not showing up in wallet?

### ISSUE THREAD

**Issue by LucianoCrypto** [CityOfZion/neon-wallet#168]
Just about an hour ago I transferred 24 Neo from Bittrex to my public Neo address. Neotracker.io shows my transaction when I look up my Txid and shows the balance properly unspent. But on Neon wallet 0.0.5 it isn't showing up no matter how many times I reload the app.

Is there any fix coming for this in the near future? Have I lost access to my coins for now? I'm sorry to be frantic, I'm just new to this.

**Comment by needaname4now** [comment]
Same Issue! And when I look up the transaction it says it cost me 2 Neo!!!

Scaring the shit outa me with the lack of responses.

**Comment by stevesbrain** [comment]
@LucianoCrypto If you have your private key, and neo tracker shows the balance correctly, you have definitely not lost your funds!

**Comment by Satoshinaire** [comment]
Neon's server needed a rebuild due to some behind-the-scenes API changes. This is in progress now, so everything should be working again shortly.

Visit and read the #support channel on Slack for updates.
