### ISSUE TITLE
Unable to send "RPX" token because it's still present on hardcoded list of testnet tokens

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1684]
![issuee](https://user-images.githubusercontent.com/8177587/48369890-0eb64f80-e6b8-11e8-9662-61ef116efa32.gif)

**Comment by comountainclimber** [comment]
This is no longer an issue as of 2.3.0:
1.) Add script hash for RPX `0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9`
2.) Attempt Send
