### ISSUE TITLE
Don't show "Wallet Imported" page if wallet couldn't be successfully imported

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1688]
If wallet couldn't be successfully imported (because it was already imported for example), we're still showing "Wallet Imported" page together with an error that it couldn't be imported. We shouldn't show "Wallet Imported" page in this case, only error.

![wall](https://user-images.githubusercontent.com/8177587/48379013-03bce880-e6d3-11e8-8996-b8b4f1d70d41.PNG)

**Comment by ranbena** [comment]
@drptbl Can you provide an STR?

**Comment by comountainclimber** [comment]
Fixed in 2.1.0
