### ISSUE TITLE
all my neo are gone

### ISSUE THREAD

**Issue by minimoi1234** [CityOfZion/neon-wallet#169]
Hi I made a neo withdraw from bittrex to my neon wallet and the neo were not there.
10 minutes later the rest of my wallet was gone too.
What can I do?

**Comment by stevesbrain** [comment]
@minimoi1234 Check your address in neotracker - are the funds still there? Project owners will also direct you over to the Neo Slack channel for support, rather than GitHub btw, which is for code issues specifically.

**Comment by Satoshinaire** [comment]
Neon's server needed a rebuild due to some behind-the-scenes API changes. This is in progress now, so everything should be working again shortly.

Visit and read the #support channel on Slack for updates.

**Comment by minimoi1234** [comment]
Thanks got everything back this morning.
