### ISSUE TITLE
[Feature Request] Automaticly grey-out/disable 'dead' tokens

### ISSUE THREAD

**Issue by the-ult** [CityOfZion/neon-wallet#1693]
**Wallet version or commit SHA:**
2.0

**Environment:**
e.g.: Win 10 (64 bit) Version 1803

### Request

There are tokens, which are rebranded e.g.
- CGE -> AVA
- IAM -> TOLL
or moved to their own chain
- ZPT

It would be nice if these tokens would be automatically 'grey-outed' or something else (filter, default not visible, etc).
That would cleanup the wallet a lot :-)

And it would be easier to see which tokens you could sent to the 'VOID' :-)

Don't know if there is an 'easy' way to check this? But it would be really nice.

(BTW.. awesome job on the new wallet! )

**Comment by comountainclimber** [comment]
This issue has been sitting in the backlog for sometime... Going to close it for now and will revisit this if there is more interest. Thanks for the suggestion @the-ult 

For now the list of active tokens is maintained in the neo-tokens repo which seems like it has been working well for the community thus far
