### ISSUE TITLE
FAILED Downloaded after new browser. re:Canesin

### ISSUE THREAD

**Issue by jalkjuyt** [CityOfZion/neon-wallet#1694]
_Originally posted by @canesin in https://github.com/CityOfZion/neon-wallet/issues/1691#issuecomment-438202815_

I tried a different browser and of course downloaded from the Git hub link provided.

The issue persists. FAILED Download unfortunately.

Any suggestions?

Wallet is Neon 2.0.0

Environment: Mac 10.13.3 high sierra Mac book pro 2010

**Comment by comountainclimber** [comment]
Cannot repro on macOS 10.12.6 closing this for now...
