### ISSUE TITLE
Unable to send RHT tokens

### ISSUE THREAD

**Issue by dondaniel83** [CityOfZion/neon-wallet#1700]
**Wallet version or commit SHA:**
Neon Wallet 2.0.0

**Environment:**
Win 7 Ultimate

**Prerequisites:**
Using ledger for sending 1 RHT token to another wallet

**Reproduction steps:**

1. Start Neon Wallet 2.0.0 with ledger
2. Click on Send buttom
3. Select RHT Asset
4. Add ammount: 1
5. Add recipient adress: private wallet

In summary:
I'm not able to send the token RHT to another wallet, I got this error:

"You can only send RHT up to 0 decimals". 
The ammount used is 1 with no decimals.

Screenshots:

![rht_error](https://user-images.githubusercontent.com/43292863/48624415-9fd54100-e9ac-11e8-9c87-104d550726c7.jpg)

**Comment by drptbl** [comment]
Re-tested, looks good now.

**Comment by Aesedai** [comment]
Where can we get the updated exe for this? I'm still getting this error.

**Comment by drptbl** [comment]
@Aesedai it was not released yet.
