### ISSUE TITLE
Activity page wrong amount for self-send transaction

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neon-wallet#1701]
**Wallet version or commit SHA:**
2.0.0 (800d415)

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 10.0.17134 Build 17134

**Prerequisites:**
N/A

**Reproduction steps:**
1. Start Neon Wallet
2. Login
3. Send 0.00000001 GAS to yourself (the sender and the receiver address is the same)
4. After the transaction execution go to "Activity" page -> 0 instead of 0.00000001

Expectation: It should display 0.00000001 GAS.

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/454196/48663049-81c51a80-ea58-11e8-9162-0a3fd73e71e8.png)

**Comment by ranbena** [comment]
This seems like a NeoScan bug as the API request itself returns `"amount":"0"` value.

Request:
https://neoscan.io/api/main_net/v1/get_address_abstracts/AaSvMiKMQqkev2VctudCNVu3t8Tjd1xKpG/1

Result:
```json
{
  "entries": [{
    "txid":"6b45d56eb5013c922154ac11958cfe7de89d275c67b3ab692f5ad3909c3bbdec",
    "time":1541888575,
    "block_height":2947374,
    "asset":"602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
    "amount":"0",
    "address_to":"AaSvMiKMQqkev2VctudCNVu3t8Tjd1xKpG",
    "address_from":"AaSvMiKMQqkev2VctudCNVu3t8Tjd1xKpG"},
]
```

**Comment by ranbena** [comment]
I looked a bit more into it and apparently this consistently occurs for self-send txs, regardless of the amount.
For instance, [this transaction](https://neoscan.io/transaction/67bd2f5beebbcbe24029ba4082392c1c53095931e438a1b017c333a84d9c5a9a) for 766 NEO results in `amount: "0"` as well, when observing it in [the API call](https://neoscan.io/api/main_net/v1/get_address_abstracts/ALHxkfrT78M4nV9b7dCUVfN9mpnT5SrEPk/2).

@osmirnov lmk if you want to file the issue yourself or else I'd do it 👍🏻

**Comment by osmirnov** [comment]
[NeoScan Issue #380](https://github.com/CityOfZion/neo-scan/issues/380) were opened. I've piggybacked your research @ranbena. Thank you for investigating this.
