### ISSUE TITLE
Replace Confirmation dialogue with React popup for Contact removal

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neon-wallet#1702]
**Wallet version or commit SHA:**
2.0.0 (800d415)

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 10.0.17134 Build 17134

**Prerequisites:**
N/A

**Reproduction steps:**
1. Start Neon Wallet
2. Login
3. Go edit contact
4. Click "Remove Contact"  -> JS confirmation dialogue will be displayed

Expectation: Some UI aligned with Wallet styles.

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/454196/48663136-8dfda780-ea59-11e8-9efb-69c1089046b1.png)

**Comment by drptbl** [comment]
Tested, looks good.
