### ISSUE TITLE
Cannot add contact for my wallet address on Activity page

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neon-wallet#1703]
**Wallet version or commit SHA:**
2.0.0 (800d415)

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 10.0.17134 Build 17134

**Prerequisites:**
N/A

**Reproduction steps:**
1. Start Neon Wallet
2. Login
3. Make transaction on your own wallet address
4. Go on Activity page  -> "Add Contact" button is unavailable

Expectation: "Add Contact" should be available because on "Contact" page we can create a contact for our wallet address.

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/454196/48663902-c5258600-ea64-11e8-9b55-9d6c48661979.png)

**Comment by comountainclimber** [comment]
Please award @phetter 100 🚀

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/6b84fb0383d72a0c6d71766c96ecf8591fa7f7a24914f0df6b86f473d2db8d3b
