### ISSUE TITLE
rustylogic is stable down and causes issues with the wallet

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neon-wallet#1707]
**Wallet version or commit SHA:**
2.0.0 (800d415)

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 10.0.17134 Build 17134

**Prerequisites:**
N/A

**Reproduction steps:**
rustylogic.ddns.net is stable lagging. If the wallet uses that node it is lagging as well. I've tried to switch to a different node but after 5 minutes the wallet switches back to rustylogic.ddns.net

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/454196/48666998-7266c100-ea9a-11e8-8cf4-b6de608aa486.png)

**Comment by comountainclimber** [comment]
Fixed with https://github.com/CityOfZion/neon-wallet/pull/1740 will be available in next release
