### ISSUE TITLE
I updated my wallet and all my Neo was taken out.

### ISSUE THREAD

**Issue by JGTX** [CityOfZion/neon-wallet#171]
I updated my wallet and all my Neo was taken out.

**Comment by dannycryptos** [comment]
I'm having the same issue; however, before transferring any Neo from Bittrex, I updated to the newest version. It showed up within minutes in the Neon Wallet. After I closed the program and reopened it, it shows a 0 balance. When I check neotogas, it shows I do have a balance still on the website but I'm really not liking that it isnt showing up in the actual wallet. 

I know the transaction was recorded on the blockchain, but this makes me regret moving my Neo from the exchange. I've uninstalled and reinstalled the wallet with no prevail.

Any help would be great!

**Comment by Satoshinaire** [comment]
Neon's server needed a rebuild due to some behind-the-scenes API changes. This is in progress now, so everything should be working again shortly.

Visit and read the #support channel on Slack for updates.

**Comment by tivalensol** [comment]
How do we get access to the slack page? We don;t have an 'invite'!

**Comment by Satoshinaire** [comment]
@tivalensol Check for the Slack invite link in the sidebar on the [NEO Subreddit](https://www.reddit.com/r/NEO/)

**Comment by tivalensol** [comment]
can you help with my other post?

**Comment by totalvm** [comment]
This is not for support issues
