### ISSUE TITLE
neon wallet 2.0.0 not showing balances with ledger nano s

### ISSUE THREAD

**Issue by asohbat** [CityOfZion/neon-wallet#1710]
hello guys . somebody simply closed a recent discussion about this new neonwallet still not showing balances and im not able to send them out of this awful wallet . 

all the issues with ledger nano s is still in the same place and graphical user interface is the worst and too polluted with unnecessary info and loads of buttons for no good .( the necessary ones are the balance and send/receive functions which are a joke for now ) .

downgrade your whole team and project to whatever it was working properly a year ago

**Comment by asohbat** [comment]
why dont you guys remove your old releases when you block connecting them and ask users to download the latest version ! ? 

cant even try other versions to see if i can send my balance out of this thing !

**Comment by asohbat** [comment]
ISSUE IS STILL THERE BUT I MANAGED TO FIX IT IF IT HELPS ANYBODY : 


just managed to extract my private key from ledger since my address HOLDS THE EXACT AMOUNT IN THE BLOCK EXPLORERS .
then manually put it into neotracker.io and TADA ! withdrew all of it in a bling of an eye to my binance . WILL NEVER EVER USE NEONWALLET ANYMORE

**Comment by comountainclimber** [comment]
"why dont you guys remove your old releases when you block connecting them and ask users to download the latest version ! ?

cant even try other versions to see if i can send my balance out of this thing !" 

What are you talking about?

**Comment by asohbat** [comment]
Neonwallet version 2.0.0 wont show ledger nano s balances

**Comment by asohbat** [comment]
> > why dont you guys remove your old releases when you block connecting them and ask users to download the latest version ! ?
> > cant even try other versions to see if i can send my balance out of this thing !
> 
> What are you talking about?

when neon wallet 2.0.0 was not showing my balances i tried 0.2.0 0.2.4 0.2.8 all of them didnt work and forced me to download the latest version to work properly

**Comment by comountainclimber** [comment]
We do not force users to upgrade not sure what makes you think that... Users can run whatever version they want

**Comment by asohbat** [comment]
Your whatever versions wont comply with your rules. Its done already me and
neo project took part an hr ago
