### ISSUE TITLE
Neon 2.0/Ledger Nano S wont balance won't sync

### ISSUE THREAD

**Issue by bballjbv1** [CityOfZion/neon-wallet#1713]
I transferred Neo to my Neon V2 wallet (latest) via a Ledger Nano S integration and Neotracker.io was able to verify and confirm that the Neo transferred. However, my ledger Nano S Neon address is not showing the updated balance. Neoscan does not show it either. All the other block explorers are showing it except Neoscan and my Neon Wallet? Any clue if this is just a old block that is out of sync on the mainnet and will be fixed later?

**Comment by comountainclimber** [comment]
Should be fixed now 👍 sorry for any inconvenience
