### ISSUE TITLE
Error: Block or transaction validation failed.

### ISSUE THREAD

**Issue by blockdotzero** [CityOfZion/neon-wallet#1714]
Hi

I currently cannot send any GAS as I am getting the following error from the Neon Wallet (using my Ledger Nano S):
"Error: Block or transaction validation failed."

Have tried different combinations/ options (no fees, Fast, Fastest, Faster, smaller amounts of Gas (from MAX GAS amount down to 0.000001 GAS, etc ). I consistently get such error.

I could however send ONT tokens fine (I do not have NEO tokens on the wallet).

Also I am using latest version of NEON, and have reinstalled NEO on my Ledger

**Wallet version or commit SHA:**
2.0.0

**Environment:**
Macos 10.13.6

**Prerequisites:**
dont have NEO tokens loaded on the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet using Ledger Nano S
2. Click on "Send" button
3. Select GAS, Fill recipient address, amount
4. Click on "Send"(with or without fees)
5. Confirm & Sign with the LEgder Nano S

**Comment by kenwebster64** [comment]
Same issues today. Won't claim GAS. Won't permit withdrawal of NEO. 2 different computers, different connections, different Neon wallets.

**Comment by comountainclimber** [comment]
Should be fixed now 👍 sorry for any inconvenience

**Comment by kenwebster64** [comment]
Fixed! Thanks. 

Best regards,

Ken
925-212-4229

**Comment by rafaboni** [comment]
I have the same issue can someone help me to fix it?
 I'm using my ledger nano s!

**Comment by Markus811013** [comment]
Hey there @comountainclimber this chat is quite old, but I have the same issue now.

I currently cannot send any GAS as I am getting the following error from the Neon Wallet (using my Ledger Nano S):
"Error: Block or transaction validation failed."

Thanks for help.
