### ISSUE TITLE
LX token is displayed multiple times

### ISSUE THREAD

**Issue by DalderupMaurice** [CityOfZion/neon-wallet#1719]
While looking at the wallet, the LX token is displayed twice

**Wallet version or commit SHA:**
2.0.0

**Environment:**
macOS Mojave 10.14.1 (18B75)

**Prerequisites:**
Own LX

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Observe `Token Balances` section on the "homepage" and see LX listed twice

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/10922045/48906583-34381b80-ee65-11e8-8d00-ed79543266f9.png)

**Comment by comountainclimber** [comment]
Purchased LX on Switcheo and have been trying to repro this issue but not having any luck... Also audited the balance flow to make sure no duplicate requests are being made for balance info 😕 

@DalderupMaurice is there any additional info you can supply?

<img width="467" alt="screen shot 2018-12-02 at 9 19 51 pm" src="https://user-images.githubusercontent.com/13072035/49352930-17c38c80-f678-11e8-86f8-1f9c4b0d7374.png">

**Comment by comountainclimber** [comment]
Closing this issue as I have not been able to replicate or seen this occur...
