### ISSUE TITLE
Infinite loader on MainNet node selection page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1729]
**Wallet version or commit SHA:**
`dev` branch (c92b866)

**Environment:**
MacBook Pro (13-inch, 2017), macOS Mojave 10.14.1

**Reproduction steps:**
1. Start Neon Wallet
2. Login to any wallet
3. Click on "Settings" button in the left menu
4. Click on "Node selection" position in settings

**Screenshot/Video:**
https://i.imgur.com/ZD6corV.gifv

**Comment by comountainclimber** [comment]
Please award: 
@ranbena 200 points
@dvd-schwrtz 100 points
@evgenyboxer 100 points

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/52a8ff627aa7c29e0b398f7e3026818a9e23b9adc1fcf6e2398da5ac029ee0e0
