### ISSUE TITLE
Neo have been transferred out this morning unknown address!

### ISSUE THREAD

**Issue by tivalensol** [CityOfZion/neon-wallet#173]
Good morning,

This is the first time I have written here and would really appreciate any of your advice. I have had all my neo in a neon wallet for a month (38 Neo). Last night I bought some more on Bittrex with no issue and transferred across to my neon wallet with no issue. (I have a screenshot I can post if anyone replies). The Neo appeared in my wallet. This morning I noticed all my Neo have been transferred out of my wallet to an unknown address that I cannot identify and it certainly wasn;t me. I was asleep and the wallet was closed. My private key is on my desktop secure and not online anywhere. Is this a wallet bug? is this a wallet update that is simply storing my neo elsewhere whilst it updates?

Please help as it appears I have lost all neo and I don;t have a point of contact and there may be a major breach in the Neon wallet.

Please help, anyone!!

**Comment by Satoshinaire** [comment]
I'm sorry to hear this, sounds scary. First, I'd recommend you double-check your public address with a blockchain explorer like [neotracker.io](https://neotracker.io) to see if they're safe.

Then, as this isn't a development task but rather a software support issue, join the [Slack team](https://neo-slack-invite.herokuapp.com/) and ask for help in the #support channel.

Closing this issue would also be appreciated.
