### ISSUE TITLE
Make the key entering bar a tad more wide

### ISSUE THREAD

**Issue by Nikolaj-K** [CityOfZion/neon-wallet#1737]
Version 2, 
Windows 10,
Open private key entering method tab.
The private key mask bar is set to be a bit too short, so that it just does not show you the full private key when you enter them. As soon as you enter the last digits, the string displayed will shift so that you can't read the whole entered key at once. 

This might somehow be system related, but minor improvement proposal: I'd suggest to make this 2cm more broad.

**Comment by comountainclimber** [comment]
Will take a look thanks for the suggestion @Nikolaj-K
