### ISSUE TITLE
Can't Send GAS

### ISSUE THREAD

**Issue by Stingo390** [CityOfZion/neon-wallet#174]
I can't send GAS to Binance. I have checked the address and that I am trying to send GAS and not NEO. 
![image](https://user-images.githubusercontent.com/31773682/30220219-84230e52-94b6-11e7-8c89-9401b3b157ec.png)

**Comment by Stingo390** [comment]
If I go to https://neotracker.io/ and put my public address in, the GAS tally does not match the GAS that my NEON wallet says I have.

**Comment by Satoshinaire** [comment]
Please seek support in the #support channel of the NEO Slack. This GitHub repo is for tracking development tasks.
