### ISSUE TITLE
NEON should broadcast transactions to multiple nodes

### ISSUE THREAD

**Issue by ThomasLobker** [CityOfZion/neon-wallet#1741]
When you transfer NEP-5 tokens, NEON will create a transaction and broadcast it to an RPC node. The node should add the transaction to the mempool and broadcast it to the rest of the network so it can eventually be added to the chain. When this is done, you will get the transaction hash from NEON and you have to assume that the RPC node is actually broadcasting the transaction throughout the NEO network.

The problem is, you cannot trust the RPC nodes to do this. So there is a chance that you will send a transaction that will never be committed, or even worse, that the transaction will be committed much later than anticipated. If this is the case, then the user might have tried to sent the tokens in a new transaction already causing a double-spend scenario.

I would like to propose a couple of improvements to help in these situations.

1. Broadcast the transactions to multiple nodes at once. This should not cause any harm, because transactions can be committed only once to the chain anyway. But the risk that transactions will get lost will be lowered significantly.
2. Keep sent transactions in an internal transaction log and keep trying to broadcast them until they are confirmed, if new blocks keep coming in but the transaction is not getting confirmed.
3. When creating a new transaction, display the hash before broadcasting. This should help the user to see that he is creating a new transaction, and not retrying the same old transaction. Maybe we should even let the user choose the randomness that is added to each transaction.

This applies on NEP-5 transfers only since they are not UTXO based.

**Comment by comountainclimber** [comment]
Please award @ranbena 100 and @evgenyboxer 100 for the code review here https://github.com/CityOfZion/neon-wallet/pull/1781 and here https://github.com/CityOfZion/neon-wallet/pull/1766

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/d24882f33f56a405c55ec93ea0306423ab06385e3d4937b735c06ea984d67b39
