### ISSUE TITLE
Neon Send Bug Version2.0.0

### ISSUE THREAD

**Issue by Nimroht** [CityOfZion/neon-wallet#1742]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
Neon-2.0.0.Windows

**Environment:**
Win 10 Pro (64 bit) 

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet.

**Reproduction steps:**
I have try sending 3 Neo to an other Walllet.
1. Going Send
2. set amount of 3 neo
3. Wallet address: see Attachment
4. Send without Fees
5. Accept Risk
6. Sending
At my first try, i get an Request Timeout Error. At my second try, i get an RCP or RPC Server error.
After i relog in my Neon-2.0.0 Wallet, 3 Pieces of my Neo´s are gone. In the History is the sending listet. The Wallet Address is correct. But the 3 Neo are not reaching my Wallet. Can you Help? I had sending 1 Neo as Test to my Wallet and it worked well. I attach two jpg. My Test Status and my history sending.

**Screenshots/Video:**
![1neo worked](https://user-images.githubusercontent.com/33104145/49471330-e4663680-f80c-11e8-8b65-3c0372f45acc.JPG)
![send historyt](https://user-images.githubusercontent.com/33104145/49471331-e4663680-f80c-11e8-9042-f38f5c505fc2.JPG)

**Comment by comountainclimber** [comment]
Closing this for now please reach out on NEO discord for additional support @Nimroht
