### ISSUE TITLE
Fiat value for SOUL is not returning the correct amount

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1747]
Because there are multiple tokens with the ticker SOUL an * must be added to the symbol name in the request to crypto compare in order to return the correct value for the nep5 token coded in neon-wallet

**Comment by comountainclimber** [comment]
fixed with https://github.com/CityOfZion/neon-wallet/pull/1751

**Comment by drptbl** [comment]
Looks good. Fixed.
