### ISSUE TITLE
Where does NEON saves the wallet on linux?

### ISSUE THREAD

**Issue by chenmin1107** [CityOfZion/neon-wallet#175]
I want to know where NEON saves its wallet info on linux. Thanks a lot!

**Comment by MediaServe** [comment]
Encrypted wallets are saved in `~/.config/Neon/storage/` according to `strace`

**Comment by chenmin1107** [comment]
Got it, thanks a lot!

**Comment by fonziemedia** [comment]
Hi,

Do you know where this is on mac?

Cheers
