### ISSUE TITLE
Transaction time Neo to exchange

### ISSUE THREAD

**Issue by CryptoSpartacus9** [CityOfZion/neon-wallet#1753]
Hello,

Yesterday I've send some NEO and GAS from my Neon wallet to an exchange. Unfortunatly I haven't received my fundings yet...Does somebody know the average transaction time for sending Tokens to an exchange?

I did this once before, and at that time it only took 3 minutes. Is there some kind of maintenance going on or am I missing something? 

The transactions are shown on my Neon activity list and I checked the walletadres of the exchange several times. On my exchange their is no update and I haven't got a deposit notification.

When I click on view in the Neon wallet I'm redirected to a the Neoscan but I have a hard time figuring out,  how I can see if the transaction is complete. 

Can somebody out there help me please?

Your sincerly,

Terrence

**Comment by comountainclimber** [comment]
Closing this for now... Please visit NEO discord for additional support @CryptoSpartacus9
