### ISSUE TITLE
failed to load version 2.2

### ISSUE THREAD

**Issue by jd1mande** [CityOfZion/neon-wallet#1767]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by jd1mande** [comment]
failed to load version 2.2 on windows 7 this used to work and gas tokens were moved here.
will I be able to upload and install version or should I even try?

**Comment by comountainclimber** [comment]
There is no 2.2 so not sure what you are referring to... closing this for now

**Comment by jd1mande** [comment]
Maxwell:

I am reaching out for some help to get the neon wallet functioning. What I can see is that the neon set up file shows
0.2.2.  windows, it was installed on Sept. 12, 2017. When I open the neon wallet I get the Failed to load in the upper left corner
of the neon screen. have the Public address, the Encrypted address and the private key.

Can you provide some direction on how to address and correct the issue?

Thank You,

John Mandeville
________________________________

**Comment by comountainclimber** [comment]
Still not sure what you are referring to... Like I mentioned previously the most recent release is 2.0.0 not 0.2.2 please download the latest release

**Comment by jd1mande** [comment]
Maxwell:

I have downloaded and installed 2.0 as suggested but now I cannot get my gas into the wallet.
The gas is sitting on my system  C: drive but I am lost now,
Any suggestion or directions on what to do now would be greatly appreciated.

Thank You,

John

________________________________

**Comment by comountainclimber** [comment]
"The gas is sitting on my system C: drive" what does that even mean?

**Comment by glschar** [comment]
I have version 2.0.0 of the wallet. After I enter my password, the wallet screen starts to load and then goes blank. It worked fine the last time I used it 10 days ago. Any ideas on what I can try?
