### ISSUE TITLE
Neon Wallet 2.0.0 blank sceeen after login

### ISSUE THREAD

**Issue by klik6** [CityOfZion/neon-wallet#1778]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: screen blank after login

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on “private key”
3. Wait for login

some description (for ex. what happens after completing reproduction steps), goes through its login procedure then flashes the home page for second (but only sometimes) before going blank

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by Dan196** [comment]
Same for me.

**Comment by Jesusmvp** [comment]
Same me 4th...

**Comment by tjosm** [comment]
I'm having the same issue. Here's what Developer Tools show,
https://gyazo.com/0217d5e5c201bf460f325ab6e74910aa

**Comment by tjosm** [comment]
> same here this neon wallet is bs fucken scam, soon as i can access my neo im putting it right back in binance. does anyone know how i can access my neo?? please help

You're a stupid cunt.

**Comment by MikeV19** [comment]
same.  log in then white screen with Neon in the left corner. What is the fix???

**Comment by pnwwolf** [comment]
> > same here this neon wallet is bs fucken scam, soon as i can access my neo im putting it right back in binance. does anyone know how i can access my neo?? please help
> 
> You're a stupid cunt.

fuck you faggot go choke on a dick hope you loose your neo stupid cunt

**Comment by LONEBROHAN** [comment]
Same here, and it was working fine earlier today, I can run 0.2.8 and see my funds but 2.0 goes blank,  tried it on my laptop too and same problem. I access with the ledger nano and v2.0 can not open

**Comment by pnwwolf** [comment]
update, still having problem but was able to send my neo to different address by clicking "activity" right after loging in and waiting for blockchain to update and then going to "send" however after clicking "wallet" it goes blank again.

**Comment by comountainclimber** [comment]
while I am still holding off until tomorrow morning to publish an official release feel free to download the binaries linked in the draft here https://github.com/CityOfZion/neon-wallet/releases/tag/untagged-52f55ace29c87a691ff1 which resolves the issue 👍

**Comment by dezcool** [comment]
> while I am still holding off until tomorrow morning to publish an official release feel free to download the binaries linked in the draft here https://github.com/CityOfZion/neon-wallet/releases/tag/untagged-52f55ace29c87a691ff1 which resolves the issue 👍

404

**Comment by comountainclimber** [comment]
Ahh so sorry draft releases are not public - my apologies. Will publish this shortly sorry about that

**Comment by dezcool** [comment]
> Ahh so sorry draft releases are not public which I did not realize - my apologies. Will publish this shortly sorry about that

All right. Cheers!

**Comment by LONEBROHAN** [comment]
NEON is currently not working due to issue with crypto compare API. You can either wait for a fix to be released, or use the O3 wallet http://o3.network/

**Comment by Jesusmvp** [comment]
I’m just gonna give it some time to resolve it self, I’ll be checking tomorrow in YouTube if anyone will talk about it, or just wait for the next latest Neon wallet release, we will see, anyone that figure this out first, please share thanks

**Comment by tjosm** [comment]
It's working now.

**Comment by Dan196** [comment]
Mine is fixed. Thank you.

**Comment by klik6** [comment]
Working for me too, thanks
