### ISSUE TITLE
Ledger issue: blank screen after pushing LOGIN

### ISSUE THREAD

**Issue by sleepndevelop** [CityOfZion/neon-wallet#1779]
**Wallet version or commit SHA:**
2.0.0

**Environment:**
Win 10 Home (64 bit) 

**Prerequisites:**
- Have a Ledger
- Don't have any custom tokens added before running the wallet

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Ledger" button
3. Click on "Login" button

Then the wallet shows a white screen, while the Ledger thumb drive shows a ***very*** long key (is that my NEO public key? Seems too long though)

**Comment by dezcool** [comment]
Same.

**Comment by comountainclimber** [comment]
while I am still holding off until tomorrow morning to publish an official release feel free to download the binaries linked in the draft here https://github.com/CityOfZion/neon-wallet/releases/tag/untagged-52f55ace29c87a691ff1 which resolves the issue 👍

**Comment by steveclifton** [comment]
Same here

**Comment by jbdn16** [comment]
Same here, what is the solution? we must wait for a new wallet update for check our money?

**Comment by sleepndevelop** [comment]
I think tomorrow they will release a new binary that will fix that. I've received an email from them.
Let's wait
