### ISSUE TITLE
Transaction Failed on version 0.0.4 - Cant send NEO out from NEON Wallet

### ISSUE THREAD

**Issue by Kakole** [CityOfZion/neon-wallet#178]
I've been trying to move my NEO to different wallet before updating to the new Windows version in-case something goes wrong after installation. It doesn't allow me to move my NEO. 
Has anyone figured a way around this?

**Comment by Gustianto** [comment]
same here.. it said "sending failed and need me to upgrade to version 0.0.4, but i already at version 0.04.. want to uninstall but scared something bad happened..

**Comment by Gustianto** [comment]
just found a solution here.. use neotracker.io and log using your private key.. you can access your coin there.. and send to another wallet if you want ..

**Comment by Satoshinaire** [comment]
This is deliberate, version 0.0.4 had to be effectively disabled, you need to upgrade to version 0.0.5 for this to go away.

**Comment by Satoshinaire** [comment]
Also, significant to mention, your NEO are not stored _in_ your wallet. NEO are stored on the blockchain, and you simply access them through wallet software. So upgrading the software will have no impact on your NEO directly. There is no need to move them during an upgrade, they were never on your computer to begin with.
