### ISSUE TITLE
Bug: Fix Broken Layout in Receive (dev)

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1788]
At some point the layout in the receive tab broke not sure how or when this popped up but it needs to be addressed before 2.1.0 can go out!

(currently on `dev`  branch)
<img width="1102" alt="screen shot 2019-01-10 at 9 05 58 pm" src="https://user-images.githubusercontent.com/13072035/51012698-b961b780-151b-11e9-9a26-dbf7800343b0.png">

**Comment by comountainclimber** [comment]
please award @phetter 100

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/fe4c1ab1b0bfacf82ac686e065e5fdef376bbf77bea6c560c4715c8be4ce9ad5
