### ISSUE TITLE
neon wallet constantly telling me to upgrade to version 0.0.4 - it already is [SOLVED]

### ISSUE THREAD

**Issue by terrybiggs** [CityOfZion/neon-wallet#179]
As per title... have closed and opened/signed in again, and the issue continues. Was fine up until about a week ago. Also cannot send myself gas, the 'error' warning kicks in every 7 or 8 seconds. Again, claiming GAS was fine up until around a week ago. 

Current block is displayed as 1353731 (not sure where I can find if it's synced, the NEO website gives a figure of about 1140000 or so, much lower than what my neon wallet says is the latest block).

Thanks :-)

**Comment by terrybiggs** [comment]
now block in neon wallet says 1353739, so it's counting rather than frozen, but stumped as to why I'm having this issue. found a post on reddit saying it needs to catch up syncying, but as I say, it's been a week and still getting the 'warning' to upgrade to the version I already have.

**Comment by Gustianto** [comment]
same here... stuck cant take my NEO coin out from the wallet..

**Comment by Gustianto** [comment]
you can access your coin from neotracker.io using your private key..

**Comment by Satoshinaire** [comment]
@terrybiggs This is an error in version 0.0.4, it should say to upgrade to version 0.0.5 which is now available. This error is also fixed in version 0.0.5 (it will say the correct update when the time comes).

**Comment by terrybiggs** [comment]
ty Satoshinaire, solved :-)
