### ISSUE TITLE
wallet neon i cant not open

### ISSUE THREAD

**Issue by alexmelro** [CityOfZion/neon-wallet#1790]
good night, I have the neon wallet the last version, with some coins, and 2 days ago the wallet was with the image all white, after that, I could not enter the wallet because I just put my password, username, no let me put it, say no options, I happened to see and lost my private key to enter, what I do now, I hope you can help me ??
thanks and regards.
Antonio Oliveira

**Comment by comountainclimber** [comment]
@alexmelro Please visit the official NEO discord for support
