### ISSUE TITLE
Cannot send NKN after updating to latest release (with a workaround)

### ISSUE THREAD

**Issue by 98farhan94** [CityOfZion/neon-wallet#1792]
**Wallet version or commit SHA:**
v2.0 latest release

**Environment:**
macOS High Sierra

**Prerequisites:**
Update from old Neon wallet release (0.2.8) to new one. Use Ledger Nano S.

**Reproduction steps:**
1. Have old version of Neon wallet, add NKN token contract address.
2. Update to latest release.
3. Transactions will fail with insufficient balance warning even when there is balance.
4. Go to Token Sale -> Add Token, remove the NKN contract address.
5. Then the transfer works fine.

Not sure what would cause this weird issue.

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/issues/1414
