### ISSUE TITLE
chore: remove unnecessary brackets

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1796]
JSX brackets were unnecessary committed to dev causing a defect in the UI

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/pull/1776

**Comment by comountainclimber** [comment]
Please award @DalderupMaurice 100 points 👍

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/84e2516a7057a0ba76af64627668a6059fc9bf4160812afa47ede8c2f9deb62c
