### ISSUE TITLE
Ledger login button gets disabled while NEO app is open on Ledger Nano S

### ISSUE THREAD

**Issue by nspt09** [CityOfZion/neon-wallet#1797]
**Wallet version or commit SHA:**
Neon-2.0.0.Linux.AppImage

**Environment:**
Ubuntu 18.04.1 LTS

**Prerequisites:**
Own a Nano Ledger S

**Reproduction steps:**

1. Start Neon Wallet
2. Navigate to login using a Ledger
3. Insert Ledger & unlock with pincode
4. Open NEO app
5. DO NOT CLICK LOGIN --> WAIT approx. 2 seconds
6. Now you can see that the login button becomes disabled and you see a spinner next to "Connect and unlock your ledger device"
7. After approx. 2 seconds  the login button is enabled again
8. After that it repeats the points 5-7

**Screenshots/Video:**
During this GIF I kept the NEO app on my Ledger Nano S device open at all times!

![neon](https://user-images.githubusercontent.com/47364188/52297217-84ad1880-2980-11e9-9dd6-6123d86983f5.gif)

**Comment by lllwvlvwlll** [comment]
@eliastan
