### ISSUE TITLE
NEO Coin missing

### ISSUE THREAD

**Issue by avenuein** [CityOfZion/neon-wallet#1798]
I sent  Neo Coin from client NEON wallet to exchange (bibox Neo wallet) . But not received Neo Coin from 2 days.. and exchange (bibox) customer support says  "your recharge is invalid after verification. Please check with the customer service of the sending platform"

NEO Transaction Hash :: 
a2aa90c45fb0a46508fbc2d5d9651275a0ee3080211bce09ade19eb21933785d

**Comment by comountainclimber** [comment]
This is not the appropriate place to ask for basic support please visit the official NEO discord for help
