### ISSUE TITLE
USD price in wallet does not appropriately reflect actual market value of NEO

### ISSUE THREAD

**Issue by colinclosser** [CityOfZion/neon-wallet#1799]
Hi CoZ. This has been an issue for a couple of months now. Great work on 2.0.0 by the way. Colin 

**Wallet version or commit SHA:**
2.0.0

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 1809 Build 17763.292

**Prerequisites:**
none

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Observe listed price of NEO in USD
3. Make markets twice, selling NEO for BTC or other blue-chip crypto in a high-volume market such as Binance, and then exchange blue-chip crypto to actual USD fiat in a high-volume market such as Coinbase. Or just do the calculations yourself without selling anything
4. Observe the 1-4% difference between the actual USD value of NEO and listed NEON Wallet price of NEO in USD

some description (for ex. what happens after completing reproduction steps), e.g.:
Okay let's use an example of *right now*

NEON Wallet Price: NEO $7.48 USD

Binance NEO/BTC: 0.002105 BTC
Coinbase BTC/USD: $3444.17

$3444.17 * 0.002105 BTC = $7.249

error calculation:
7.48/7.249= 1.031 - the ticker is over 3 percent high!

**Screenshots/Video:**
![pricedifference](https://user-images.githubusercontent.com/30250826/52490410-ada4f780-2b92-11e9-8336-3c2584a98c9b.png)

**Comment by comountainclimber** [comment]
We use cryptocompare for global average prices the check the API and you will see we are referencing the correct data

**Comment by comountainclimber** [comment]
https://min-api.cryptocompare.com/

**Comment by colinclosser** [comment]
Yes, it's a tough issue. I'm aware that NEO has not had high volume fiat markets since the China ban. Hopefully the NEO ecosystem can get here in 5 years. I think the solution offered by this Bitcoin wallet is the gold standard.

Thank you for your time and consideration.


![bitcoin](https://user-images.githubusercontent.com/30250826/52493991-d03b0e80-2b9a-11e9-960d-8242280f56c5.png)
