### ISSUE TITLE
Neon Wallet 2.0.0 Goes Blank After Login on MacOs

### ISSUE THREAD

**Issue by doczee** [CityOfZion/neon-wallet#1800]
Wallet goes blank after login, MacOS Mojave 10.14.3 on MacBook Retina mid 2014

**Wallet version or commit SHA:**
Version 2.0.0

**Environment:**
MacOS Mojave 10.14.3

**Reproduction steps:**
1. Start Neon Wallet
2. Sign in Walled
3. Wallet goes blank

<img width="1094" alt="screen shot 2019-02-10 at 9 31 34 pm" src="https://user-images.githubusercontent.com/38846608/52545211-5ca42780-2d7b-11e9-9afb-3319a99675e5.png">

**Comment by apply75** [comment]
also happening on my wallet with my hp laptop ..
.running windows 7
 64 bit version...intel i7

**Comment by steveslatky** [comment]
Had it happen on linux mint as well. So it is not an OS issue. It seemed to only start happening, sometime in the past 2 days. Since that was the last time I open Neon.

**Comment by bryanlabchuk** [comment]
windows 10 64 bit, same issue. login succeeds, app goes blank after loading wallet.

**Comment by blockbasher** [comment]
Same here on windows 10 64 bit.   Was working fine roughly 2-3 hours ago.  white screen after successful login

**Comment by machr** [comment]
Same issue after login with Ledger Nano. Downloaded and replaced an outdated version of Neon in /Applications/ from Github.

**Comment by comountainclimber** [comment]
This was due to an issue related to the API we rely on for pricing data has been fixed in 2.1.0 which is going though its final rounds of QA. Sorry for the inconvenience this may have caused!
