### ISSUE TITLE
Unable to claim GAS with Neon 2.0

### ISSUE THREAD

**Issue by dennish007** [CityOfZion/neon-wallet#1802]
**Wallet version or commit SHA:**
2.0.0

**Environment:**
Mac OSX 10.12.6

**Reproduction steps:**
1. Start Neon Wallet
2. Login
3. Claim GAS

System reaction:
Neon is claiming by spending all NEO (visible in transaction overview)
After that nothing happens, no GAS transfer
Claiming using neotracker.io works. 

Might be address specific, so email me for the address if needed.

**Comment by comountainclimber** [comment]
We are working on improving the GAS claim user experience - occasionally during times of network instability claims can fail

**Comment by dennish007** [comment]
installed 2.1.0 and claim was now succesfull. 

so consider this issue as ’solved indirectly’.

thanks.
