### ISSUE TITLE
Neon wallet not showing transfer 

### ISSUE THREAD

**Issue by nicholaspryan** [CityOfZion/neon-wallet#1806]
Neon V2.0.0
IOS  10.11.6

I created a wallet and sent 1 NEO from Binance to test it and it worked fine. 

I then sent another 40ish coins after copying and pasting an address from Neon. 

When I have come back to neon awhile later there is no additional coins in the wallet. 

I checked the activity and there is the other address in the activity log. 

![screen shot 2019-02-25 at 16 14 41](https://user-images.githubusercontent.com/47108567/53361022-fe587680-392e-11e9-973f-5f4682dbbb38.png)

AV*****wz is my public address. and i dont know where the other AJ****kjk came from. 

Since I opened this wallet have only ever sent coins to it and have not sent any out. How do I see where this payment went. or how did the AJ****kjk make its way into my wallet

**Comment by fabwa** [comment]
AJ****kjk is likely the binance wallet (1 NEO incoming) AV*****wz is there twice for a GAS claim (0 NEO tx and incoming GAS) - your 40NEO tx simply did not make it (yet). Check binance for a tx id.

**Comment by nicholaspryan** [comment]
there is a TXid

**Comment by nicholaspryan** [comment]
its a good few hours ago

**Comment by fabwa** [comment]
did you check neoscan?

**Comment by nicholaspryan** [comment]
I just did but i don't know what i am looking at tbh. Im pretty fresh to this

**Comment by nicholaspryan** [comment]
surely. it should have come through now its been over 8 hours. I know there is a wait but i thought more like 1/2 hrs max
