### ISSUE TITLE
Neo wallet not showing transfer

### ISSUE THREAD

**Issue by nicholaspryan** [CityOfZion/neon-wallet#1807]
https://github.com/CityOfZion/neon-wallet/issues/1806

issue closed but not resolved yet Neo wallet not showing transfer after 24hrs

Neon V2.0.0
IOS 10.11.6

I created a wallet and sent 1 NEO from Binance to test it and it worked fine.

I then sent another 40ish coins after copying and pasting an address from Neon.

When I have come back to neon awhile later there is no additional coins in the wallet.

I checked the activity and there is the other address in the activity log.

![screen shot 2019-02-25 at 16 14 41](https://user-images.githubusercontent.com/47108567/53361022-fe587680-392e-11e9-973f-5f4682dbbb38.png)

AV*****wz is my public address. and i dont know where the other AJ****kjk came from.

Since I opened this wallet have only ever sent coins to it and have not sent any out. How do I see where this payment went. or how did the AJ****kjk make its way into my wallet

Reply 

AJ****kjk is likely the binance wallet (1 NEO incoming) AV*****wz is there twice for a GAS claim (0 NEO tx and incoming GAS) - your 40NEO tx simply did not make it (yet). Check binance for a tx id.

**Comment by fabwa** [comment]
Please share your public key or the tx id (which would reveal your public key as well). There is nothing wrong with the activity log you showed. As said before, you received 1 NEO from kjk (probably binance). The other 2 entries are from a GAS claim you made. There is no other incoming tx thus far. This seems not to be a Neon wallet issue..

**Comment by nicholaspryan** [comment]
fe644931d61e0c9b816074668d8a92636720091525881e6db67dddf6ed303ad3

**Comment by nicholaspryan** [comment]
Thank you

**Comment by fabwa** [comment]
This tx shows that 1 NEO was sent to AWVv4sscYYSNpzpnBuFpxBkQc1nwSsPsj9 and 10 NEO to AXqNoebjUK9uLzbeUBQGF48hKN5CJbGMWb. (https://neoscan.io/transaction/FE644931D61E0C9B816074668D8A92636720091525881E6DB67DDDF6ED303AD3).
It does not show the public address that is associated with your account from your screenshot. I am afraid we cannot help you here. Please contact binance support
