### ISSUE TITLE
Your transaction is too big for the Ledger to sign

### ISSUE THREAD

**Issue by boxofscraps** [CityOfZion/neon-wallet#1813]
Completely cannot send any GAS out of ledger wallet.  NEO and other assets were able to be transferred without any issues. 

**Ledger Firmware version:**
1.4.2

**Wallet version or commit SHA:**
2.1.0

**Environment:**
Win 10 Education (64 bit) Version 1809 Build 17763.316

**Prerequisites:**
Don't have any custom tokens added before running the wallet

**Reproduction steps:**
1. Start Neon Wallet
2. Login using Ledger device 
3. Send Asset "GAS"
4. Amount can be maximum or any integer
5. Before signing with Ledger, there is an error "Your transaction is too big for the Ledger to sign"

**Comment by saltyskip** [comment]
https://utxo-manager.o3.app/

You can solve it with O3 using this app
