### ISSUE TITLE
RCPT token / Perhaps minted tokens, not showing up.

### ISSUE THREAD

**Issue by SyndicateCrypto** [CityOfZion/neon-wallet#1814]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
2.1.0

**Environment:**
e.g.: Win 10 Home (64 bit) Version	10.0.17134 Build 17134

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click Activity to see tokens received but not showing up

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.
RCPT token, perhaps due to them being minted, do not show up in this latest release. They showed up in the 2.0.0 release.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by comountainclimber** [comment]
Closing this issue for lack of details and activity
