### ISSUE TITLE
Not an issue, but a big thumbs-up!

### ISSUE THREAD

**Issue by tester2011** [CityOfZion/neon-wallet#1817]
I couldn't see any way to contact the author directly, so I thought I'd post here - obviously , please feel free to delete...

I have to say that Neon-wallet is how a crypto wallet should be done. I've used many over the years and many of them all force you to jump through hoops to get the simplest of things done.

So many other projects should take a long, hard look at this one and realise this is the standard they should be aiming for.

Thanks again for making my NEO-based life, so, so much simpler!

Cheers,

Mike.

**Comment by comountainclimber** [comment]
Thanks so much for the support and positive feedback @tester2011 ! If you have any feature suggestions or additional feedback be sure to let us know 😄
