### ISSUE TITLE
NEO Wallet upgraded to 2.1.0.Windows but Total Wallet Value is set to Zero

### ISSUE THREAD

**Issue by billycyn** [CityOfZion/neon-wallet#1822]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: Ledger Nano S - Firmware version 1.5.5

**Environment:**
e.g.: Win 8 Home (64 bit)

Prequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
[Neno Wallet Upgraded.docx](https://github.com/CityOfZion/neon-wallet/files/3007232/Neno.Wallet.Upgraded.docx)

**Comment by comountainclimber** [comment]
not enough information...
