### ISSUE TITLE
feature suggestion: Ability to hide pricing data

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1824]
A user should have the ability to hide fiat price values entirely from the application if they desire. This feature would add a new value under settings which would allow users to hide all fiat pricing data.

**Comment by dauTT** [comment]
@comountainclimber,
why do we want to implement this feature? What is the motivation behind it?

**Comment by comountainclimber** [comment]
It is a feature request that has come up in the past... The motivation is that some users want to be able to access neon without thinking about fiat values still not sure what the exact UX/UI would look like on the dashboard in this case
