### ISSUE TITLE
feature suggestion: ability to submit a feature request / issue report from Neon

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1825]
There should be some way for users to submit bug reports or suggest features from within neon. It could be as simple as adding in a link to the GH issue creation page in settings....

**Comment by dauTT** [comment]
@comountainclimber, FYI I am working on this issue.

**Comment by dauTT** [comment]
@comountainclimber ,

Something like this, is fine?

![Screencast-from-04 07 2019-23_58_32](https://user-images.githubusercontent.com/30392990/60689220-3cf0d580-9ebb-11e9-86b7-426cfd722d64.gif)

**Comment by comountainclimber** [comment]
I like what you have done here @dauTT perhaps instead of adding an additional "link" to the settings page we can update the panel header from Community Support => Need Help? which will then render the page you set up. I also think that this page would look better using our modal component rather than having it be its own route

**Comment by dauTT** [comment]
I got the first part:

> perhaps instead of adding an additional "link" to the settings page we can update the panel header from Community Support => Need Help? which will then render the page you set up

In regards to the second part:

>  I also think that this page would look better using our modal component rather than having it be its own route

,  we should render this new github issue page in a similar fashion as we do when we press the `Add Token` button. Is my understanding correct?

```JavaScript
renderHeaderBarRightContent = () => (
    <div
      onClick={() => this.openTokenModal()}
      className={styles.headerButtonContainer}
    >
      <AddIcon className={styles.add} />
      <span>Add Token</span>
    </div>
  )
```
![image](https://user-images.githubusercontent.com/30392990/60842692-fc53cd80-a1d4-11e9-8baa-1fb2ce863b8f.png)

**Comment by comountainclimber** [comment]
Sorry I should have been more clear I meant here: 
![Screen Shot 2019-07-08 at 4 09 04 PM](https://user-images.githubusercontent.com/13072035/60845836-be39b800-a19a-11e9-92eb-221d855855f5.png)

**Comment by dauTT** [comment]
Ok. What about this?

![Screencast-from-09 07 2019-01_13_24](https://user-images.githubusercontent.com/30392990/60848660-d126a980-a1e7-11e9-8bbc-263d9f92a1f8.gif)

**Comment by comountainclimber** [comment]
@dauTT that looks great! I think we can drop the "Community support =>" part but other than that looks good

**Comment by comountainclimber** [comment]
Closing this out due to inactivity and to focus on unrelated issues/feature work
