### ISSUE TITLE
feature suggestion: API for dApp developers to interface with

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1829]
Placeholder issue for a discussion and updates regarding API development

**Comment by raisezhang** [comment]
Is there any progress on this?  Similar to scatter client.

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/issues/1410

**Comment by comountainclimber** [comment]
@raisezhang there has been a little work done so far... is this something you are interested in working on?

**Comment by raisezhang** [comment]
@comountainclimber    

I can spend some time on weekends.    can I refer to scatter client for implementation?

**Comment by comountainclimber** [comment]
Sounds great! We should be referring to the (accepted) draft NEP standard for implementation details https://github.com/neo-project/proposals/pull/69
