### ISSUE TITLE
2 missing ONT tokens in NEO wallet

### ISSUE THREAD

**Issue by wowology** [CityOfZion/neon-wallet#1830]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
v2.1.0

**Environment:**
Mac OS Mojave version 10.14.2

**Prerequisites:**
Don't have any custom tokens added before running the wallet

**Reproduction steps:**

In my NEON wallet I have 48 ONT tokens.  Yesterday I transferred 2 ONT tokens to my NEON wallet from Binance.

In Binance the transaction shows completed, but in my wallet no extra ONT tokens show.  On the explorer.ont.io the transaction shows an a total on my address of 50, however in my NEO wallet it only shows 48.

Please advise what to do.

Thanks.
 
**Screenshots/Video:**
<img width="956" alt="Screenshot 2019-04-03 at 18 35 32" src="https://user-images.githubusercontent.com/33553639/55497485-bc170900-5641-11e9-80ba-a734acf56a5e.png">
<img width="177" alt="Screenshot 2019-04-03 at 18 35 42" src="https://user-images.githubusercontent.com/33553639/55497497-c0432680-5641-11e9-8bce-b7b6cfce65c0.png">

**Comment by comountainclimber** [comment]
NEON supports NEO, GAS and nep5 tokens but does not support Ontology.
