### ISSUE TITLE
feature suggestion: show block height in UI

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1833]
There should be some indicator of the current block height in the UI. (The code to wire this up has mostly already all been written and can be found in `blockHeightActions.js`)

One idea is to have this piece located above the Logout button however open to suggestions from the community.

**Comment by jsquardo** [comment]
I would love to tackle this issue if you want me to?! @comountainclimber

**Comment by comountainclimber** [comment]
That would be awesome @jsquardo ! I think the original idea was to have it somewhere in the SideBar component please let me know if you have any questions and I can help with anything and everything that pops up!

**Comment by jsquardo** [comment]
Ok awesome! Thank you so much.

**Comment by comountainclimber** [comment]
@jsquardo 

Something like this will get you the blockheight of the current node just so you know:

```
    import { getNode, getRPCEndpoint } from '../../../actions/nodeStorageActions'

    let url = await getNode(net)
    if (isEmpty(url)) {
      url = await getRPCEndpoint(net)
    }
    const RPC = new rpc.RPCClient(url)
```

**Comment by jsquardo** [comment]
@comountainclimber 

Ok thank you! I will get to work on it tonight for sure.

**Comment by comountainclimber** [comment]
@jsquardo any update as to your progress on this feature?
