### ISSUE TITLE
feature suggestion: Claim button after success should update immediately

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1835]
Claim button after success notification should update as well immediately (stays grayed out with old gas amount)

**Comment by dauTT** [comment]
@comountainclimber,
Is this not a feature?

It stays like this for 5 minutes
![image](https://user-images.githubusercontent.com/30392990/61999157-982d7680-b0bb-11e9-8457-b31092a7eecd.png)

but afterwards the claim button changes to cyan color again:

![image](https://user-images.githubusercontent.com/30392990/61999177-d6c33100-b0bb-11e9-8fa9-02dbd482a245.png)

**Do you want the claim button to switch color from gray to cyan, immediately after success notification, even though we can claim gas only after 5 minutes?**
