### ISSUE TITLE
Neon Wallet No Displaying any NEO

### ISSUE THREAD

**Issue by vlar** [CityOfZion/neon-wallet#184]
Hey, 

I'm using the version 0,0,5 and I'm login using a private key. 
Yet, when i'm logging in my wallet shows 0 GAS 0 NEON while i had some in it. 

When I check my public Key online it sees the transactions and the amount I used to have. 

Could you let me know how to proceed ? 

This is kind of worrying a bit. 

Cheers

**Comment by Satoshinaire** [comment]
@vlar Jump over into the #support channel of the [Slack](http://neosmarteconomy.herokuapp.com/) for assistance. Issues on this GitHub repo are for development tasks.
