### ISSUE TITLE
Binance confirmed my tranfet to my wallet of ONT. It never showed up in my wallet. It has been over two weeks?

### ISSUE THREAD

**Issue by 777poe** [CityOfZion/neon-wallet#1840]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by comountainclimber** [comment]
Neon wallet does not support the ontology blockchain... Please us a wallet that does to access your tokens https://medium.com/ontologynetwork/ontology-ont-and-ontology-gas-ong-wallet-and-exchange-information-f030409132e4

**Comment by 777poe** [comment]
I sent my ONT from Binance to my Neon Wallet. Is it lost or can I reclaim it? I have proof that I sent it but never received it. How can I retrieve it?

**Comment by comountainclimber** [comment]
Please read the comment above...

**Comment by 777poe** [comment]
> Please see the comment above...

I understand but did I lose it all? Why does the wallet not specifically have what can be transferred and what cannot be transferred.  The message reads; "Only send assets that are compatible with NEO blockchain. (NEO, Gas, etc...) What is the etc...? It never states to NOT send ONT. Did i lose it all?

**Comment by comountainclimber** [comment]
Please see #support in the official NEO discord for additional assistance...

> Why does the wallet not specifically have what can be transferred and what cannot be transferred.

it does that exactly in the quote you you pasted - the etc would be any smart contracts deployed on the NEO blockchain
