### ISSUE TITLE
Send Transfer - SDUSD don't appear on exchange after sending ! founds lost

### ISSUE THREAD

**Issue by BrunoAB1** [CityOfZion/neon-wallet#1841]
I send 2 transfers, SDUSD from neon wallet to an exchange and both transactions didn't appear on exchange !! 
I contacted exchange, they didn't see the transfers...
i had SDUSD on neon wallet, i used  script hash 7146278a76c33fc6bb870fcaa428e3cdb16809ac to add token.

Can someone help me pls ?

**Comment by BrunoAB1** [comment]
HELP ! 
CAN SOME ONE HELP ME PLS ! NEON LOST ALL MY SDUSD !!!!

**Comment by BrunoAB1** [comment]
I CAN'T FIND MY NEO BALANCE NOWHERE ! There is no transfer on history.
Same on swhitcheo i don't find my balance of neo and sdusd

**Comment by BrunoAB1** [comment]
the sdusd i recieved from Switcheo appear on Neon but when i transfer some sdusd to another adress they desappear

they never appear on my reception adress and my balance ususd tokens on neon decrease !!!!

What's happening ??

**Comment by comountainclimber** [comment]
I reccomend reaching out to support in the official NEO discord as this does not seem to be an issue with neon itself. I will reopen this issue if this is not the case!
