### ISSUE TITLE
Ontology not showing us

### ISSUE THREAD

**Issue by aufache** [CityOfZion/neon-wallet#1851]
Ive been depositing my ont to my neon wallet since august and have not seen it update. The address is correct. The ont explorer shows its in there. The neo explorers do not.

How can i move the invisible ONT to a different wallet??? Or at least make my funds visible.
Is my ontology gone?

I'm using my ledger with the neon wallet.

**Comment by comountainclimber** [comment]
This may be confusing but ONT is not a token on the NEO network please access your address on an ONT supporting wallet (like https://github.com/ontio/OWallet/releases or https://o3.network/)
