### ISSUE TITLE
Error: Block or transaction validation failed and failed gas claim

### ISSUE THREAD

**Issue by rafaboni** [CityOfZion/neon-wallet#1852]
**Wallet version or commit SHA:**
neon Version 2.2.1

**Environment:**
osx 10.13.6 

no ccustom tockens

**Reproduction steps:**

1. Start Neon Wallet
2. Click on "claim" button
3. sign the transaction with my ledger nano s
4. error block or transaction already exist and cannot be sent repeatedly

i have been trying to claim gas but it just make sign 1 time when usually is twice and I tried again so i Get this error block or transaction already exist and cannot be sent repeatedly.
then I tried to send my coins to other wallet to sent it back to check if I can resolve it but when I tried to do it the wallet said Error: Block or transaction validation failed

![IMG_0783](https://user-images.githubusercontent.com/32377694/58050904-a3de4900-7b1e-11e9-8ec3-2e16c76b2fd4.JPG)

![IMG_0784](https://user-images.githubusercontent.com/32377694/58050905-a3de4900-7b1e-11e9-9069-656993b4490c.JPG)

**Comment by crk84** [comment]
I have the exact same problem with Neon wallet: 1) Unable to send Neo. 2) Unable to claim Gas. 
For sending Neo I have tried all the fee options from no fee to high fee.  It doesnt work.

**Comment by comountainclimber** [comment]
There might have been some slight network instabilities causing this issue also attempting to broadcast the same transaction repeatedly can cause this problem. As of this morning all NEO sends and GAS claims are functioning exactly as expected so closing this on for now

**Comment by StM47333333** [comment]
I have the exact same problem with Neon wallet: 1) Unable to send Neo. 2) Unable to claim Gas.
For sending Neo I have tried all the fee options from no fee to high fee. It doesnt work.
