### ISSUE TITLE
show gas display different results

### ISSUE THREAD

**Issue by bopetfdl** [CityOfZion/neon-wallet#1853]
**Environment:**
Server A: Ubuntu 18.10 (64 bit) neo 2.9.4
Server B: Ubuntu 18.10 (64 bit) neo 2.9.4

**Reproduction steps:**
1. Stop neo on Server A
2. Copy wallet.db3 file from A to B
3. Start A & B
4. Install plugins, download chain.zcc.zip and place the neo-cli root directory, restart B
5. After the synchronization is complete, and index completed(Server B)
6. execute "show gas" on A & B, but the "available gas" different

some description:
I can confirm that the height is the same and both are synchronized to the latest block.

**Comment by comountainclimber** [comment]
@bopetfdl perhaps you opened this issue in the wrong repo?
