### ISSUE TITLE
Zero Balance

### ISSUE THREAD

**Issue by jujujujuju45** [CityOfZion/neon-wallet#186]
Is anyone else having a zero balance issue with NEON 0.0.5? Transaction history is also blank. Everything was fine yesterday....

**Comment by noob1313** [comment]
I am having the same issue. Block chain explorer shows my balance but NEON wallet 0.0.5 shows nothing.

**Comment by Kgood47** [comment]
I am having the same issue with my NEON wallet as well.  Last night it showed my balance and now shows nothing.

**Comment by Meistermichel** [comment]
Experiencing the same issue.

**Comment by rridder** [comment]
Yes have the same issue.

**Comment by AshRolls** [comment]
NEON wallet API is currently down. We are currently investigating the reason. Please join #support in slack rather than GitHub, which is intended for code issues.
