### ISSUE TITLE
feature suggestion: We should render a QR for encrypted keys (without passwords)

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1862]
For consistency we should offer the ability for users to save a copy of a QR of their encrypted key (exactly how we provide address/private key) this will allow users to take advantage of the work completed here: https://github.com/CityOfZion/neon-wallet/pull/1855

**Comment by dauTT** [comment]
@comountainclimber,
the option to generate the QR (address/private key) is only possible after the **creation** or the **import** of a **wallet**. Where exactly do you want to add the option to generate the QR of encrypted key?

I believe we should add this option after :
1) `creation wallet`
2) `import wallet` (option encrypted key: #1863)
3) `Encrypt a key` (This option is available in the **setting** section)

**Comment by comountainclimber** [comment]
@dauTT that is exactly correct... Those would be the three places. Please note the work to scan the QR has already been completed here: https://github.com/CityOfZion/neon-wallet/pull/1855

**Comment by dauTT** [comment]
I would like to check the code changes that I have made on the `test` net.

How do you usually create a new wallet on the `test` net? When I run 

`yarn dev >/dev/null`

neon wallet is connecting to the `main` net by default and the home page does not have any option to switch between `test` and `main`.

**Comment by comountainclimber** [comment]
@dauTT A wallet address will "work" on both networks if created using neon

**Comment by comountainclimber** [comment]
For development purposes I recommend always using the command `yarn dev`

**Comment by comountainclimber** [comment]
Taken care of in https://github.com/CityOfZion/neon-wallet/pull/1873
