### ISSUE TITLE
Ability to import account using encrypted key

### ISSUE THREAD

**Issue by canesin** [CityOfZion/neon-wallet#1863]
Currently it is only possible to import a account using a WIF, that in itself presents a security risk as you have to copy the key or type the key in full. While not a strong protection copying the encrypted key is safer.

This feature is a regression as in NEON prior to v2 was possible to import a encrypted key account.

**Comment by comountainclimber** [comment]
Thanks for the feedback and opening this issue @canesin I will make sure it gets prioritized/fixed

**Comment by dauTT** [comment]
Hi @canesin,
you are referring to this import? You would like to add an option to import encrypted key?

![image](https://user-images.githubusercontent.com/30392990/59152043-2df24100-8a3d-11e9-801a-8fce079373ca.png)

**Comment by canesin** [comment]
That is correct @dauTT !

**Comment by dauTT** [comment]
@comountainclimber , 

FYI, I am working on this issue.

**Comment by dauTT** [comment]
@comountainclimber , we should probably close this issue. :+1:
