### ISSUE TITLE
Missing NEO and GAS

### ISSUE THREAD

**Issue by xdays764** [CityOfZion/neon-wallet#1870]
I signed into my NEON account today and was met with blank pages. No NEO, GAS, or activity was present.
<img width="1100" alt="Screen Shot 2019-06-07 at 9 25 01 PM" src="https://user-images.githubusercontent.com/51498806/59140422-edc28e00-896a-11e9-818c-8babf1d0dcc3.png">

**Comment by dbglassman** [comment]
[neo snap shot 6-8-19.docx](https://github.com/CityOfZion/neon-wallet/files/3269119/neo.snap.shot.6-8-19.docx)

having same problem all my neo and gas has vanished.  have had this problem before and then after a new update the problem resolves.  Or after rebooting computer.  Thus far I have not seen my assets in quite a while.  Concerned.  Anyone have a solution.

**Comment by JiraiyaTheSage** [comment]
1. Check your address on the explorer and you'll see all assets are still in the wallet.

2. Select a different NODE and Neon will show the balance.

> I signed into my NEON account today and was met with blank pages. No NEO, GAS, or activity was present.
> <img alt="Screen Shot 2019-06-07 at 9 25 01 PM" width="1100" src="https://user-images.githubusercontent.com/51498806/59140422-edc28e00-896a-11e9-818c-8babf1d0dcc3.png">

**Comment by xdays764** [comment]
How do I select a different NODE?

**Comment by JiraiyaTheSage** [comment]
> How do I select a different NODE?

Log into your wallet, go to Settings then Node Selection. Select any from the top ones.

**Comment by xdays764** [comment]
I changed the Node and still have nothing in my wallet.

**Comment by comountainclimber** [comment]
@xdays764 have you confirmed using a block explorer that that address actually has NEO?

**Comment by xdays764** [comment]
I’m sorry, but I’m not sure how to go about doing this. Can you guide me?

**Comment by xdays764** [comment]
I went to block explorer in settings and it was set to NEOSCAN

**Comment by comountainclimber** [comment]
Paste your public address here https://neoscan.io/ 😄

**Comment by xdays764** [comment]
I did that and it does not bring up my account. I’m getting concerned that my account has somehow been drained.

**Comment by dbglassman** [comment]
I’m having the same problem. Tried putting my address in and nothing
happened.  Not sure 🤔 if using the explorer site correctly

**Comment by xdays764** [comment]
Am I to assume from you closing the thread that I have no hope of recovering my account? Surely, there must be some way of tracking the activity on my account.

**Comment by comountainclimber** [comment]
As the issue template says:

```For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io``` this is not a software issue with Neon... NEO is a public blockchain it is extremely easy to see any and all activity associated with **any** wallet

**Comment by xdays764** [comment]
Ok, thank you.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Maxwell Lasky <notifications@github.com> Date: 6/11/19  5:59 PM  (GMT-05:00) To: CityOfZion/neon-wallet <neon-wallet@noreply.github.com> Cc: xdays764 <pholahan1@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [CityOfZion/neon-wallet] Missing NEO and GAS (#1870) As the issue template says:
For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io this is not a software issue with Neon... NEO is a public blockchain it is extremely easy to see any and all activity associated with any wallet

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CityOfZion/neon-wallet/issues/1870?email_source=notifications\u0026email_token=AMI46NQTOD4ZOF3PQGH5FPLP2AN5XA5CNFSM4HWASVMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXOUBZQ#issuecomment-501039334",
"url": "https://github.com/CityOfZion/neon-wallet/issues/1870?email_source=notifications\u0026email_token=AMI46NQTOD4ZOF3PQGH5FPLP2AN5XA5CNFSM4HWASVMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXOUBZQ#issuecomment-501039334",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
