### ISSUE TITLE
Can't Claim GAS any more

### ISSUE THREAD

**Issue by josephj11** [CityOfZion/neon-wallet#1871]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
2.2.1 
**Environment:**
kubuntu 18.04
**Prerequisites:**
Used wallet successfully for days - including claiming GAS
**Reproduction steps:**

1. Start Neon Wallet
2. Click on "Claim GAS" button

Get:
   Error calculating Claimable Gas Polling reached ...
  (Went away before I could read rest of it)
    Then, clicking again I get:
    Block or transaction already exists and
    can not be repeatedly sent

After that times out, I go back to the first message when I try it again
GAS keeps accumulating, but I can't claim it

**Comment by Johan89798** [comment]
I have exactly the same problem, tried to claim GAS after update of wallet to latest version, Same two error messages.

**Comment by josephj11** [comment]
It recovered itself after a few hours, but it was disconcerting.

**Comment by comountainclimber** [comment]
Closing this in favor of consolidating here https://github.com/CityOfZion/neon-wallet/issues/1674
