### ISSUE TITLE
Ledger Interaction

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neon-wallet#1874]
I believe that there is a minor thing to be done regarding Ledger interaction.
The BIP's that specify deterministic wallet generation recommends that we should have one account and then keep generating addresses.

I mean:
Someone creates an account:
* A1: Temporary
* A2: Savings
* A3: My Pizza Company

Each time you receive any funds in any of these accounts, NEON wallet should give another address of each specific account to receive the next funds.
In this sense, the procedure is to check balance until you find an address of that account that has not yet received funds.

**Comment by comountainclimber** [comment]
I am not sure about this... the more I think about the more I worry that bringing such a drastic change to the ledger UX in neon would really confuse our users

**Comment by vncoelho** [comment]
That is true, my friend.
MEW in Live Mode is similar to the current implementation of Neon Wallet.
Lets just keep the idea in mind and see the future.
