### ISSUE TITLE
Can't send GAS from wallet

### ISSUE THREAD

**Issue by CORPARU** [CityOfZion/neon-wallet#1881]
When sending a message is displayed:
OOPS! SOMETHING WENT WRONG.
Error: One of the Policy filters failed.

OS: Debian 9 (4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux)

**Screenshot:**
[Screen](https://drive.google.com/open?id=1kGAh_2SGJmTTsOz9E8sbgZyiO3dEhtbX)

Everything else goes fine!

**Comment by comountainclimber** [comment]
We are looking into this thank you for reporting. For now you can attach a fee to the transaction you are attempting to make to get around this issue

**Comment by Cruiser107** [comment]
Hello,
i have the same problem.

OS: Win7 x64

Please fix :)

**Comment by Celia200** [comment]
I have the same issue even trying to attach a fee it will not send. please fix!!!

**Comment by carldex** [comment]
Same issue here

I made several NEO / GAS / TOKENS transfers from the same address (paper Wallet) to the same one other address (Ledger Nano S).
But I do not know why, in the last attempt to transfer my last GAS  it does not transfer in any way ... it always gives error ... ("Error: One of the policy filter failed)

- First I tried to transfer the entire balance, including decimals, NOT SUBMITTED
- Then I tried without decimals, trying to send only integer, NOT SUBMITTED
- I tried to transfer a small part (only 1 GAS) also do NOT SUBMITTED

I tried in all with no fees and with fees (subtracting from the balance, obviously) and nothing

(At Ledger shows correct balance of those who successfully completed)

What is the problem with these latest attempts at GAS transfers?

Win10 x 64
Neon-2.2.1.Windows
![20190711_104456(vmmsi-cr)](https://user-images.githubusercontent.com/52790805/61060845-93857480-a3d1-11e9-8a63-18af2bed3c2c.png)

**Comment by matthieuvandiepen** [comment]
Still an issue with sending GAS from wallets? I tried 4 different wallets, no luck to send GAS. Sending NEO works OK.

Sending NEO GAS is not posted on the blockchain. Same problem with every wallet I tried, so this seems to be problem on the NEO infrastructure

**Comment by TechMagy** [comment]
Quick question.... How can this be closed if the issue has not been resolved? I've been trying to find out what the deal is with this for a while now

**Comment by matthieuvandiepen** [comment]
Hello, later on I was able to send the Gas anyway, so the problem seems to be solved, thanks

**Comment by TechMagy** [comment]
@matthieuvandiepen How did you do that? What steps did you take? What version of Neon are you running. In another thread I've been told to try sending GAS to myself first to see if that unlocks the issue. Will report back in on how that goes later today. 

See https://github.com/CityOfZion/neon-wallet/issues/1937

**Comment by CORPARU** [comment]
OOPS! SOMETHING WENT WRONG...
Error: Based on the size of this transaction a fee of at least 0.05 GAS is required.
----------------------------------

The error began to repeat again! 

I tried to reduce the amount of gas so that it was enough for sending, but it does not help.

**Comment by CORPARU** [comment]
I figured it out, it turns out the commission for sending gas has increased

**Comment by klesun** [comment]
Few of our dapp users reported that this "one of the policy filters failed" error started happening since yesterday for any non-zero cost Smart Contract transaction they make via https://mainnet1.neo2.coz.io/

Though for some users the issue does not seem to happen, possibly it's specific to particular countries

Dunno if coz.io is anyhow affiliated with neon-wallet, but hope this piece of info will happen to be useful for other people googling the error...
