### ISSUE TITLE
Neon - Saved Wallet Location 

### ISSUE THREAD

**Issue by Lemoine05** [CityOfZion/neon-wallet#1883]
Good morning,

I have recently migrated all files from from one computer to another (windows) including the Neon wallet. 

I understand that the “saved” wallet is localised but that the “saved” wallet would also migrate over which is not the case. 

I would like to understand if the saved wallet has migrated over but is hidden or still on the original computer. 

Is there a way to locate the saved wallet file once created? 

Would really appreciate any advice.

**Comment by comountainclimber** [comment]
@Lemoine05 on windows it should be located at `C:\Users\your_username\AppData\Roaming\Neon\storage\`
