### ISSUE TITLE
Feature Suggestion: MainNet | TestNet Selection on Login Screen

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neon-wallet#1884]
BLUF: I think you should be able to select mainnet or testnet from the login screen.

Background: While reviewing https://github.com/CityOfZion/neon-wallet/pull/1882, I wanted to enter a testnet address to login as watch only. I could not find a way to select mainnet or testnet from the home page. So, I entered a testnet wallet address to "WATCH" and initially thought something had gone wrong when my address couldn't be found. I had to switch to testnet via settings after I logged in, in order to view my address.

**Wallet version or commit SHA:**
2.2.1

**Environment:**
Win 10

**Prerequisites:**
N/A

**Reproduction steps:**
N/A

**Screenshots/Video:**
N/A

**Comment by comountainclimber** [comment]
At this time I am not 100% sure I want to add any more changes to the "home" screen as there are advantages to keeping things simple but this or something like it is definitely worth considering

**Comment by comountainclimber** [comment]
Going to close this one for now will reopen/revisit if there is interest in the future
