### ISSUE TITLE
Can't see my coins in Neon wallet. Neotracke.io shows them though. Please help

### ISSUE THREAD

**Issue by sidauz** [CityOfZion/neon-wallet#190]

**Comment by AshRolls** [comment]
PLEASE NOTE

For support using the software or concerns about the status of your funds, please go to the #support channel in the Neo Smart Economy Slack.

GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by sidauz** [comment]
Neo Smart Economy Slack is not working for me. I am getting an application when trying to go to support slack

**Comment by sidauz** [comment]
Got it sorted. Thanks
