### ISSUE TITLE
feature suggestion: Do we really need the 'Watch" login?

### ISSUE THREAD

**Issue by tester2011** [CityOfZion/neon-wallet#1900]
Hi Guys,

Just exploring the latest version of Neon wallet.

Intrigued by the "Watch" login option, so I tried 'Watching' the Neon/COZ donation address...

Far too much access to the account - I can even create send transactions, unsigned obviously, but this seems to be asking for trouble. How hard would it be for a hacker to forge transaction signing - probably not that easy.

Still, I think it's an option that isn't needed. There's more than enough info available for any of the blockchain explorers.

Too creepy...

Mike.

**Comment by comountainclimber** [comment]
> How hard would it be for a hacker to forge transaction signing

If this was possible the entire blockchain would be compromised... I do not really understand what the issue you are trying to point out here is

> Far too much access to the account 

This is all public information already...
