### ISSUE TITLE
Unhandled error when wallet NEP5 balance has > 15 significant digits

### ISSUE THREAD

**Issue by gubanotorious** [CityOfZion/neon-wallet#1905]
**Wallet version**
2.3.0

**Environment:**
Any (Win 10 Pro for screenshot)

**Prerequisites:**
Large NEP5 Token Balance - ie: 184089261.22210488

**Reproduction steps:**
1. Start Neon Wallet
2. Open Wallet with NEP5 with balance > 15 significant digits
2. Click on "Send" button
3. Select NEP5 to send, amount, address, with or without fee.
4. Click on "Send" and confirm / send

**UI Result**
Buttons disabled, no status response (error or success)

**Underlying Error**
bundle.js:26 Uncaught (in promise) Error: gt() number type has more than 15 significant digits: 184089261.22210488

**Screenshots/Video:**
https://drive.google.com/file/d/1hfn12jSl7vi0h2IxjEeH4rHG8a6NJFJC

**Comment by comountainclimber** [comment]
This was actually resolved with this PR => https://github.com/CityOfZion/neon-wallet/pull/1901 will be out in the next release
