### ISSUE TITLE
Upgrade neon-js to latest version (v4.7.0?)

### ISSUE THREAD

**Issue by dauTT** [CityOfZion/neon-wallet#1906]
Currently, neon-wallet is using [neon-js v3.11.9](https://github.com/CityOfZion/neon-wallet/blob/2.3.0/package.json#L72) has a dependency. I believe this version of neon-js is outdated and therefore it will beneficial to upgrade it to a new version v4.x.x. (As a side note, this upgrade is necessary, if we want to tackle issue [871](https://github.com/CityOfZion/neon-wallet/issues/871))

At this point, I am not sure whether we shall upgrade neon-js to `v4.7.0` or wait for the next version which will include support for NEO3 (https://github.com/CityOfZion/neon-js/issues/441). @comountainclimber  what is your opinion on this?
 

**Wallet version or commit SHA:**
2.3.0

**Environment:**
Ubuntu 18.x

**Prerequisites:**
NA

**Reproduction steps:**
NA

**Screenshots/Video:**
NA

**Comment by comountainclimber** [comment]
While I think this is worth while I don't see why it is necessary in order to support private net development but maybe I am missing something... Couldn't we simply include a text input on the node selection page or something similar?

**Comment by dauTT** [comment]
It is not that simple. Here is the documentation on how to interact with a privnet:
http://cityofzion.io/neon-js/docs/en/guides/basic/privnet.html
and more discussion on this matter is here: 
https://github.com/CityOfZion/neon-js/issues/455

**Comment by comountainclimber** [comment]
I see... Adding input for a custom node here would only work if that RPC node was connected to mainnet which would not accomplish what we are looking for.

I definitely support upgrading neon-js in neon if you are willing to pursue this work and can also help out with any blockers. Thanks @dauTT

**Comment by dauTT** [comment]
I am happy to work on this but in a few weeks from now, once we have the next release of neon-js with support for NEO3.

**Comment by MorganDream** [comment]
@dauTT The release of NEO3 and neon-js for NEO3 is not decided yet. And don't worry, neon-js will have both NEO2 and NEO3 versions when release NEO3.

**Comment by dauTT** [comment]
Thanks, @MorganDream for the update. Right now, we are not in a hurry to upgrade neon-js as everything is working fine. So we don't mind to wait until we get a release of neon-js with support for NEO3. :smile:

**Comment by comountainclimber** [comment]
> And don't worry, neon-js will have both NEO2 and NEO3 versions when release NEO3.

Is this still the plan for now? Also do you know the status of what still needs to be done in `v5.0.0-next.2` to make it feature complete with NEO3?

**Comment by lllwvlvwlll** [comment]
closing, no longer relevant.
