### ISSUE TITLE
ONT transferred from Binance is not reflecting in my NEON wallet

### ISSUE THREAD

**Issue by g4usat** [CityOfZion/neon-wallet#1910]
Hi, I've transferred ONT tokens from Binance to my Neon Wallet v 2.2.1 today. But, the wallet is not showing my transferred ONT. I had couple of ONT tokens earlier in the Neon wallet from a long time back as part of some airdrop and it's just showing only that. However, when I checked at ONT tracker https://explorer.ont.io/address/AYfsBpdRNW1WCUYjtoD1e2685E1FjDW4Cb/ALL/20/1 it's showing the old 2 tokens and the newly transferred tokens.

I'm unable to understand as why the newly transferred ONT tokens are not showing up. Can you please help me fix this? I'm really worried as what's going on with my wallet. Appreciate if anyone can help me fix this ASAP. Thanks a lot

**Comment by dauTT** [comment]
Hi g4usat,

Fortunately NEO and ONT are using the same mechanism to generate public and private key. So, No worry, you didn't lose your tokens. You can access them via 

1) O3 wallet, https://o3.network/
2) Native Ont wallet, https://github.com/ontio/owallet

**Currently neon-wallet is not supporting native ONT token**. The ONT tokens that are currently showing on your neon wallet are NEP5 tokens. You should probably swap them with the corresponding native ONT. (Ask the ontology community for this)

**Comment by g4usat** [comment]
Hi dauTT,
Great..Thanks for your information. I'll try the O3 wallet.
