### ISSUE TITLE
Sent ONT without GAS (hey, its an option!)

### ISSUE THREAD

**Issue by glitchyGhost** [CityOfZion/neon-wallet#1918]
**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c
2.3.0
**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309
mac OSX Mojave
**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet
None
**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "send"
3. Click on 'Send with zero fees"
4. Click send
5. 9 hours later, still no payment?

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.
I can see the transaction on NeoScan (and the wallet says holds balance) but when I go to wallet, it's empty.  The ONT blockchain scanner says 0 balance in said wallet too.

ID: 5b98922c8c3b031b6c5c251f0eb84ba93359f41f6d69c0e4f5eca18cf243f9ca

Lesson learned; just why even allow sending that slow?  I will always pay the GAS in future.

So how long will it take? will it even make it? Can I somehow reverse or cancel stuck send?

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by glitchyGhost** [comment]
I've been informed its the old ONT, not Mainnet ONT.  Why doesn't Neon support the mainnet upgrades?  How on earth to I get the coins back, when they've been sent to a non-mainnet compatible wallet?  Thanks

**Comment by comountainclimber** [comment]
Neon only supports the NEO blockchain... If you are still need help please reach out in the official NEO discord for support

**Comment by glitchyGhost** [comment]
If so, then how/why was I able to send other coins there?  I have several
others, including NEO?

Excuse my ignorance.
