### ISSUE TITLE
Neon 3.0 - Cross chain support (Neo 2x and 3x in same app version)

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1936]
Creating this issue to open the discussion up to the community around whether or not it makes sense for Neon to support both networks from the same version.

From an engineering perspective and UX perspective it is a very challenging task to support both blockchains. The current proposal is to have Neon 3.0 have full support for the Neo3 ecosystem (with Neon 2.x still running on Neo 2.x chain).

**Comment by lllwvlvwlll** [comment]
@comountainclimber can we close this out?
