### ISSUE TITLE
Pre Release 2.5.0 Portuguese translation review

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neon-wallet#1963]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c
Pre Release 2.5.0

**Environment:**
Win 10 Pro

**Prerequisites:**
Portuguese language

![image](https://user-images.githubusercontent.com/38396062/78921059-b8933a80-7a6a-11ea-86f2-b7afffd116e7.png)
Looks like a report button, or support, I don't know. Can we use country flags?
![image](https://user-images.githubusercontent.com/38396062/78921156-e1b3cb00-7a6a-11ea-968d-03cb90b2fdde.png)
"Abrir" 

![image](https://user-images.githubusercontent.com/38396062/78921220-f6905e80-7a6a-11ea-9c60-394efa26919b.png)
"Chave (WIF)"

![image](https://user-images.githubusercontent.com/38396062/78921357-29d2ed80-7a6b-11ea-822e-f1e8238dca0e.png)
"Chave (NEP-2)" 

![image](https://user-images.githubusercontent.com/38396062/78921547-71f21000-7a6b-11ea-87c5-f08f32cfa284.png)
"Endereço NEO"

![image](https://user-images.githubusercontent.com/38396062/78922287-a61a0080-7a6c-11ea-94fa-4d84f56ef421.png)
"Hardware"

![image](https://user-images.githubusercontent.com/38396062/78922581-29d3ed00-7a6d-11ea-81e1-01ef04697505.png)
"Carregando..."

![image](https://user-images.githubusercontent.com/38396062/78922721-67387a80-7a6d-11ea-9bac-dc38f77c938f.png)
Not translated.

![image](https://user-images.githubusercontent.com/38396062/78922791-86cfa300-7a6d-11ea-8950-8b263d6430da.png)
"Saldo de Moedas"

![image](https://user-images.githubusercontent.com/38396062/78922843-a36bdb00-7a6d-11ea-8a64-e2baac0089a0.png)
"Valor da Wallet"

![image](https://user-images.githubusercontent.com/38396062/78922912-bd0d2280-7a6d-11ea-9c62-66d408388822.png)
Too much text. We should reduce this text by 50 to 75%. I'm pretty sure nobody is reading this.

![image](https://user-images.githubusercontent.com/38396062/78923198-36a51080-7a6e-11ea-8b6f-274a58901b3f.png)
"Solicitar pagamento"

![image](https://user-images.githubusercontent.com/38396062/78923267-4d4b6780-7a6e-11ea-8180-661813e9cd15.png)
"Endereço para depósito"

![image](https://user-images.githubusercontent.com/38396062/78923289-589e9300-7a6e-11ea-86ce-7f57d21b1e3d.png)
"Adicionar nota..."

![image](https://user-images.githubusercontent.com/38396062/78923476-a2877900-7a6e-11ea-9dba-2d2313ba14e9.png)

![image](https://user-images.githubusercontent.com/38396062/78923572-d1055400-7a6e-11ea-882d-c85dee401bfa.png)
"da"

![image](https://user-images.githubusercontent.com/38396062/78923697-0316b600-7a6f-11ea-9ccf-db2adab8fd3e.png)

![image](https://user-images.githubusercontent.com/38396062/78923741-145fc280-7a6f-11ea-8649-344566cc7ec5.png)
Not translated.

**Comment by comountainclimber** [comment]
Thanks @lock9 all of these except the last issue should be resolved feel free to reopen if you feel like this is critical
