### ISSUE TITLE
neon-wallet 2.5.0 Chinese translation error

### ISSUE THREAD

**Issue by steven1227** [CityOfZion/neon-wallet#1966]
The exchange activities tab displays some Korean text, not Chinese 

**Wallet version or commit SHA:**
2.5.0

**Screenshots/Video:**
<img width="1168" alt="Screenshot 2020-04-13 at 5 21 08 PM" src="https://user-images.githubusercontent.com/9437492/79109786-9cb1d080-7dab-11ea-9f4f-f1b77b843b44.png">

**Comment by comountainclimber** [comment]
Thanks @steven1227 should be resolved in the new release
