### ISSUE TITLE
Still showing zero balance even after downloaded the most recent .03 version

### ISSUE THREAD

**Issue by MetaCorrells** [CityOfZion/neon-wallet#197]
Hello - thanks for releasing the 0.03 version for Mac. I've downloaded this version however i'm still showing a Zero balance. As expected i'm able to find my assets on the blockchain. 

Any idea what I might be doing wrong with the install or is there another release that could possibly help?

**Comment by Satoshinaire** [comment]
@MetaCorrells The current version is 0.0.5, you might want to check you downloaded the correct update?

Also, as mentioned in the template for this issue, you should see #support in Slack for general assistance.
