### ISSUE TITLE
Error calculating claimable GAS: undefined

### ISSUE THREAD

**Issue by wouterds** [CityOfZion/neon-wallet#1973]
Can't claim GAS using the latest version of the wallet. I'm connecting using a Ledger Nano S on macOS, there's 2 GAS to claim but I can't, it keeps failing.

**Wallet version or commit SHA:**
2.5.0

**Environment:**
macOS Catalina 10.15.5

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Claim GAS" button

**Screenshots/Video:**
![Screenshot 2020-06-15 at 09 46 58](https://user-images.githubusercontent.com/1210628/84631281-67317c80-aeed-11ea-8c38-9c2659d98e65.jpg)

**Comment by hydex86** [comment]
+1, same issue with same configuration.

**Comment by CapitanRedBeard** [comment]
Also getting this

**Comment by nicscal** [comment]
Same issue with the same config

**Comment by mhui** [comment]
I tried it later and it worked. Might need to close ledger live too

**Comment by jgonfer** [comment]
I also had the same issue, but tried what @mhui suggested and worked fine! 👍

Just closed `Ledger Live` and `NEON`, and then opened `NEON` again and tried to claim. All good now!
