### ISSUE TITLE
Status of neo scan api hosted on neonwallet.com

### ISSUE THREAD

**Issue by corollari** [CityOfZion/neon-wallet#1974]
Hi, I'm cleaning up monitor.cityofzion.io and found that there's some references to a neo scan api instance on http://testnet-api.neonwallet.com/v2/ which has been inactive for some time now. Are there any future plans for this service or can it be removed from the list of monitored servers?

**Comment by comountainclimber** [comment]
Sorry for the delay in responding to this issue... It can be removed from the list of monitored servers 👍 thanks for asking

**Comment by corollari** [comment]
Thanks
