### ISSUE TITLE
Failed to send funds using Ledger Nano S

### ISSUE THREAD

**Issue by yhamry** [CityOfZion/neon-wallet#1976]
**Wallet version:**
v2.5.0

**Environment:**
MacOS Mojave (10.14.6)

**Reproduction steps:**
1. Start Neon Wallet
2. Log in using Ledger Wallet
3. Try to send assets on the Send tab.
4. Click on "Send assets without fee"
5. Click on Confirm & Send
6. Transaction fails - A Toast "Transaction Failed: undefined" is shown.

**Screenshots:**
![image](https://user-images.githubusercontent.com/22011158/88634426-08038200-d0bf-11ea-8366-7bbdc3b2af82.png)

**Comment by mhui** [comment]
I tried it later and it worked. Might need to close ledger live too
