### ISSUE TITLE
Cannot claim gas, 

### ISSUE THREAD

**Issue by Txzus** [CityOfZion/neon-wallet#1979]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
v2.5.0

**Environment:**
Win 10 Pro(64 bit) Version 1903 Build 18362.959

**Prerequisites:**
Updated to v2.5.0 last night and tried to claim gas after not logging in for over a month.

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Wallet" button
3. Click on "Claim GAS"
4. Receive error message.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png
![image](https://user-images.githubusercontent.com/69122538/89131184-e0565480-d4d8-11ea-93f7-46e2403e3529.png)

**Comment by josephj11** [comment]
This is almost identical to #1977 .

**Comment by Txzus** [comment]
The day after I was able to successfully claim GAS (did not do anything), only clicked Claim GAS and it worked.

**Comment by cedracine** [comment]
v2.6.2 windows nano X fw & app up to date, same problem for last 2 days, tried to set few different nodes manually, no success.
![neo gas](https://user-images.githubusercontent.com/53321805/125175433-4756b000-e1f6-11eb-8bbe-c1214793393f.JPG)
