### ISSUE TITLE
LOST ALL MY NEO IN NEON WALLET

### ISSUE THREAD

**Issue by samson467** [CityOfZion/neon-wallet#1988]
Hello

Today I logged in on my NEON wallet after 5 months break. I updated it . I noticed that all of my neo dissapeared. In the activity section there is a transaction of 25 neo sent to the other adress. I am sure that I didn`t make such transaction. I have never shared my private key or any data with anyone.

Does it mean that I my neo have been stolen ?

How was it possible?

Is there antything I can do to recover them?

**Comment by MasterIDI** [comment]
Hello
