### ISSUE TITLE
Issues with connection "Failed to load. Retry or select a different node."

### ISSUE THREAD

**Issue by AlekseiSmirnov** [CityOfZion/neon-wallet#1989]
**Wallet version or commit SHA:**
2.5.0

**Environment:**
macOsCatalina 10.15.6

**Prerequisites:**
Problems with connection "Failed to load. Retry or select a different node."

**Reproduction steps:**
1. Start Neon Wallet
2. Log in to your wallet

I'm trying to transfer NEO from my wallet, but can't perform the transaction as there are some problems with connectivity. As I see from Discord, this problem is very common. I tried to switch between different nodes, but it doesn't help. Tried at different laptops, all same

**Screenshots/Video:**
<img width="1098" alt="Screen Shot 2020-09-30 at 10 45 08 PM" src="https://user-images.githubusercontent.com/10200871/94737720-9ec61680-036e-11eb-8ad6-84a4510da672.png">

**Comment by chephren** [comment]
I have exactly the same issue. please resolve  this problem quickly or anyone with a solution to this, please share. Thanks.

**Comment by comountainclimber** [comment]
This should be resolved as of this morning sorry for the issues @chephren and @AlekseiSmirnov !
