### ISSUE TITLE
Missing Code Signature

### ISSUE THREAD

**Issue by atagliata** [CityOfZion/neon-wallet#1990]
Neon just prompted me to download an update. I downloaded, installed, and relaunched the program. I immediately got a warning from Little Snitch (an app that monitors connections to my compouter) that says the "program has no code signature". I have enver seen this warning before, and am somewhat alarmed by it.

I don't if this is a problem unique to me, or if it affects everyone. At any rate, it seemed risky to allow connections, so I denied all connections. That is obviously a problem going forward, as I can no longer connect my wallet : (

If there is anyone with insight into why I got this message, please advise me on how to proceed. 
I am not a developer or coder, so please respond in laymens terms, if that's possible.

Thanks, Rob

**Wallet version or commit SHA:**
Neon 2.5.0

**Environment:**
iMac Retina 5K 2017 Mac OSX Mojave 10.14.6

**Prerequisites:**
If by 'tokens' you mean NEO, yes, I have tokens in the wallet.

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
...and I immediately get a warning from Little Snitch (app that polices connections) that says the "program has no code signature"

I deny all connections and quit program.

**Screenshots/Video:**
<img width="785" alt="Screen Shot 2020-10-03 at 2 45 28 PM" src="https://user-images.githubusercontent.com/72317679/94999597-5eda7b80-0588-11eb-9bb1-c1c603896420.png">

**Comment by comountainclimber** [comment]
Will be resolved in release 2.6.0
