### ISSUE TITLE
Release announcement for v2.6.0

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#1991]
This issue will create a marketing release banner for neon v2.6.0.

**Comment by J-G-W** [comment]
This is the place holder, we will want to update the main screen with relevant data (correct tokens, etc.) and description if someone can advise.

![image](https://user-images.githubusercontent.com/36457062/97996449-af3f3600-1ddf-11eb-9654-e5a99899e9e7.png)

**Comment by lllwvlvwlll** [comment]
For Copy:

* Over-The-Air feature updates
* Integrations with Neon Mobile
* Improved notification system
* Design enhancements

Can we also get a small version number on there?  Maybe a water mark in the bottom left?  `v2.6`
