### ISSUE TITLE
Hi all. I sent 93 ONT from Exodus to my Neon wallet a few months ago, the transaction is showing in the blockchain as completed but it is not showing in my Neon wallet. Any ideas? Transaction hash: 21320c5d3df0b0712f1ed5f6357d079307ad8acbdd137e3a2e0c6126fa433902 Using Catalina OS 

### ISSUE THREAD

**Issue by cosmic-springs** [CityOfZion/neon-wallet#1997]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by wick55** [comment]
I have the same problem.. Confirmed on the blockchain, balance hasn't changed in the NEON wallet.
