### ISSUE TITLE
New rebranded MacOS install scren

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#1999]
On MacOS we need mocks for the rebranded installer window see screen shot below

<img width="589" alt="Screen Shot 2020-10-17 at 10 09 47 PM" src="https://user-images.githubusercontent.com/13072035/96358562-c5ea4b00-10c5-11eb-80a0-a9c5dd58ad77.png">

**Comment by J-G-W** [comment]
Hey Max, this is what I'm thinking. I haven't used the actual wallet icon as I like the look of the isometric icon, both are synonymous with the brand but might be worth asking the team later. I've also gone for a dark background, let me know if this is a problem. I'm sending the sketch file to you now. 
![image](https://user-images.githubusercontent.com/36457062/96582264-edfac980-12d2-11eb-8c06-96e90d790a0b.png)
