### ISSUE TITLE
test cases for primary functionality

### ISSUE THREAD

**Issue by j4zz** [CityOfZion/neon-wallet#20]
Is there a reason there are no test cases for this project yet? Especially since this project is a wallet, I would have expected to find some test cases to ensure its correct functionality, at least for `/wallet/index.js`. Not wanting to sound indignant, just asking for reasons.

**Comment by canesin** [comment]
@j4zz you are right and wrong, all your comments would be right if the file was not pulled from: https://github.com/CityOfZion/neon-js .. that has the testing in place ;)

**Comment by j4zz** [comment]
In that case, shouldn’t `neon-js` be packaged up and used here, instead of copying files? Sorry if I’m being obnoxious, just being inquisitive to understand the project’s choices.

**Comment by canesin** [comment]
Now you can open another issue: It should, is just that things are moving really fast and development was done in one place and moved to other.. if you want to PR I`m sure Ethan is ok with receiving your help.
