### ISSUE TITLE
Impossible to send FLM

### ISSUE THREAD

**Issue by h1tco1n** [CityOfZion/neon-wallet#2030]
Hi,
I can not send FLM :
"Oops! Something went wrong. Error : a network error has occurred. You don't have enough FLM. 

it happens even before the confirmation on Ledger.
I can receive FLM. I can send Neo and Gas.

Thankx

**Wallet version or commit SHA:**
2.6.0

**Environment:**
Win 10 Home (64 bit)

**Comment by comountainclimber** [comment]
Thanks for opening this @h1tco1n we are taking a look 👀

**Comment by h1tco1n** [comment]
@comountainclimber thank you. 
I just downloaded the update 2.6.1 but the problem remains the same.

**Comment by Hamedpkh** [comment]
I am having exactly similar problem. Any solutions?

Thanks

**Comment by h1tco1n** [comment]
> I am having exactly similar problem. Any solutions?
> 
> Thanks

I ended up extracting the private key from my Ledger wallet and imported it into Neoline.

**Comment by Hamedpkh** [comment]
> > I am having exactly similar problem. Any solutions?
> > Thanks
> 
> I ended up extracting the private key from my Ledger wallet and importing it into Neoline.

Thank you. I'll try it out!

**Comment by Hamedpkh** [comment]
> > I am having exactly similar problem. Any solutions?
> > Thanks
> 
> I ended up extracting the private key from my Ledger wallet and importing it into Neoline.

Thank you. It worked!

**Comment by andrewmcnaughton** [comment]
Is there a way to do this without extracting the private key from my Ledger? I want to avoid that at all costs.
