### ISSUE TITLE
NEON Wallet not working with the new SWTH on your wallet address

### ISSUE THREAD

**Issue by tt1970** [CityOfZion/neon-wallet#2033]
NEON Wallet not working with the new SWTH on your wallet address
SWTH Contract: 3e09e602eeeb401a2fec8e8ea137d59aae54a139

**Wallet version or commit SHA:**
Version 2.6.1

**Environment:**
Windows 10 Pro for Workstations 2004 build 19041.630

**Prerequisites:**
Have some converted SWTH on Switcheo balance, none in wallet and connect your wallet to switcheo.exchange

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click Refresh  -> everything OK
3. Withdraw new SWTH to wallet from Switcheo
4. Click resfresh in NEON Wallet -> NEON Wallet fails to retrieve wallet data
5. Deposit the withdrawn SWTH back to Switcheo balance
6. Click refresh- -> Everything fine again

**Screenshots/Video:**
None

**Comment by lllwvlvwlll** [comment]
This is caused by a non-standard response time (int) from the token contract.  Resolution in Neon wallet will occur after support for NEP5 integer response types are are added to neon.js.
Blocked by https://github.com/CityOfZion/neon-js/issues/641
