### ISSUE TITLE
Failed to retrieve blockchain information - Ledger wallet

### ISSUE THREAD

**Issue by KZFlyer** [CityOfZion/neon-wallet#2034]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
neon wallet - v2.6.1

**Environment:**
Win 10 Pro version 10.0.19041 Build 19041

**Prerequisites:**
No longer loads blockchain info when loading Ledger wallet. Stopped working after this transaction https://neoscan.io/transaction/563b1cf2e2607564df260c683d72f2c175c3915257352aa8ddb112dc24afc34d

**Reproduction steps:**
1. Start Neon Wallet
2. does not load blockchain information
3. Click on refresh
4. does not load blockchain information
5. change block explorer
6. return to wallet and click on refresh
7. does not load blockchain information
8. change node
9. return to wallet and click on refresh
10. does not load blockchain information

**Screenshots/Video:**

![image](https://user-images.githubusercontent.com/39107717/100884768-e0169780-347f-11eb-8a56-d92d6aa5cb95.png)
![image](https://user-images.githubusercontent.com/39107717/100885163-5915ef00-3480-11eb-8be9-bfba865d8515.png)

**Comment by comountainclimber** [comment]
Thanks for opening this issue we are actively working on resolving this

**Comment by comountainclimber** [comment]
@KZFlyer you should be able to access your balance info...

We will be releasing another patch shortly to handle edge cases breaking balance logic for the SWTH contract sorry for the inconvenience
