### ISSUE TITLE
EFX Token price displayed  in Neon Wallet does not match with market price

### ISSUE THREAD

**Issue by Coolsmith1980** [CityOfZion/neon-wallet#2042]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
Neon Wallet v2.6.1

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**EFX Token price displayed  in Neon Wallet does not match with market price

**Reproduction steps:**

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/76633394/103160848-a3934d00-482d-11eb-9217-3952116f8e97.png)

**Comment by Maet57** [comment]
I have the same issue. As of today EFX is $0.028 on the exchanges (2.8cents). But is $0.13 in the NEON wallet (13 cents).
There has to be a glitch somewhere but how do we bring this to the attention of the NEON people?
![EFX Price](https://user-images.githubusercontent.com/78460289/106695057-ea931000-662d-11eb-92d9-591bcec888ae.JPG)

**Comment by Maet57** [comment]
I also have the latest Windows version of NEON Wallet
