### ISSUE TITLE
Wallet hacked. Neo transferred out

### ISSUE THREAD

**Issue by dtteo** [CityOfZion/neon-wallet#2044]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
2.6.1

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
I had Neo, GAS and TKY added. All were transferred out

**Reproduction steps:**
1) i logged into my wallet today, first time in a month. I saw my balance was 0. I looked in activity and on 6/12/20, someone transferred out all my NEO, GAS and TKY. It was sent to ALSFL6gChZecNn7D5Ts1cxGU4PvxZgNHwA

**Comment by trackmaxi** [comment]
Hi, did you get anywhere with this? I had my NEON wallet hacked last year and lost 500 NEO and some other tokens that were in there, and I'd like to see how to follow up getting them back!

Thanks.....
