### ISSUE TITLE
Neon wallet login to ledger - problems

### ISSUE THREAD

**Issue by GHutch51** [CityOfZion/neon-wallet#2047]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
Neon Wallet 2.6.1

**Environment:**
Windows 10

**Prerequisites:**
None

**Reproduction steps:**
1) start Neon wallet
2) goto login via ledger
3) unlock ledger
4) Neon wallet stalls at waiting for unlock ledger

Tried different sequences of opening  ledger and neon wallet, but not sucessfull, sticks at this point and cant login to wallet.

Not a new wallet, been using for 2 years sucessfully with Neon and ledger.

Ledger is Nano X  - NEO app is  version 1.3.5.

Appreciate help to sort this.

**Comment by DeToxer** [comment]
I have the same problem. The Neon wallet worked fine the last time i logged in (few months ago). Downloaded v2.6.1 and i am stuck in this blank page indefinitely. Neo team, please address this

**Comment by GHutch51** [comment]
Thanks,

For me the problem also started with the download of the new version 2.6.1.

Good to see others have this issue.

**Comment by DeToxer** [comment]
From their support channel in discord they wrote this: 
"Try opening your developer tools console in Neon (View->Toggle Developer Tools or Ctrl-Shift-i) and see if there is some error message in the console that might explain why it's not loading the view."

**Comment by DeToxer** [comment]
I finally managed to log in.

1. Try to login as you would normally with your ledger. 
2. When the Neon Wallet goes blank, close the Neon Wallet and open it again (dont disconnect the ledger)
3. Open Neon Wallet again and navigate to the ledger login option. It will now say that you should navigate to Neo on your ledger and select it. Do that. The Neon Wallet will go blank again. Close Neon wallet and open it again (dont disconnect the ledger).
4. Open the Neon Wallet again and navigate to the ledger login option. You can now finally login

**Comment by GHutch51** [comment]
Hi,

Thanks for the advice - glad you got in.

I tried it, but am still stuck at the  'connect and unlock ledger device'
stage with the 2 spinning arrows.  The Neon wallet does not go blank as you
describe, but just sits with spinning arrows for long time ?

I'll try again tomorrow with all the sequences again.

Not very confidence boosting in the Neon wallet at the moment.

**Comment by DeToxer** [comment]
So when you type in your PIN in the ledger, the Neon Wallet doesn't go blank?

**Comment by GHutch51** [comment]
Good news solved it just now...

I connected the ledger direct into laptop USB port rather than through an
extension with several different ports on it. They are all Dell devices,
but only works if connecting direct into the lap top and not via extension.

Lesson learnt - confidence in Neon wallet restored.

Thanks for your help with this, much appreciated.

**Comment by DeToxer** [comment]
It might be some security feature perhaps?
Anways, glad you got in!
