### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Woodehh** [CityOfZion/neon-wallet#2050]
**Wallet version or commit SHA:**
2.6.1

**Environment:**
MacOS

**Prerequisites:**
None

**Reproduction steps:**
1. Start Neon Wallet
2. Try to unlock an wallet with the wrong password
3. When not set to English it will show the English description for: `Wrong Password or scrypt parameters!`

**Screenshots/Video:**
<img width="1312" alt="Schermafbeelding 2021-01-15 om 14 13 01" src="https://user-images.githubusercontent.com/6039482/104731376-e31dcc80-573b-11eb-86c1-9783c6b8739a.png">

**Comment by comountainclimber** [comment]
Thanks for opening! This error actually comes from within `neon-js` which currently does not support internationalization....
