### ISSUE TITLE
No option on send for NEON wallet

### ISSUE THREAD

**Issue by beny912** [CityOfZion/neon-wallet#2092]
NEON wallet version 2.6.2
WIN 10 64 bit
I have GAS tokens

I click select gas
enter amount
enter recipient
hit enter
message says verify correct address
Nothing happens no option to continue

![neon](https://user-images.githubusercontent.com/79664149/109364159-cbb22300-7853-11eb-8ba7-d865f3179033.png)

**Comment by comountainclimber** [comment]
The button to continue is right below the  dialogue and cut off from the screen shot @beny912 

<img width="993" alt="Screen Shot 2021-03-08 at 7 25 15 AM" src="https://user-images.githubusercontent.com/13072035/110333945-727a8a00-7fdf-11eb-90b6-c63f310acb18.png">
