### ISSUE TITLE
Broken links from activity page to dora

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#2109]
Version: v2.6.2 Windows

On the activity page, slicking `View` on a transaction navigates out of app to:
 `https://dora.coz.io/transaction/{{txid}}`

We have changed the pathing and it should now be:
`https://dora.coz.io/transaction/neo2/mainnet/{{txid}}`

**Comment by comountainclimber** [comment]
This one has been resolved for some time
