### ISSUE TITLE
NEO and GAS tokens disappeared after updating the wallet to its latest version

### ISSUE THREAD

**Issue by lpaparelli** [CityOfZion/neon-wallet#2112]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by licjai** [comment]
me encentro en un problema no se como resolver los dondos de la cuenta fueron retirados el dia 16 de marzo del presente año, con una extraña red de secuencia en retiros, para poder recuperarlos???

**Comment by licjai** [comment]
> Por fa
vor complete el siguiente formulario. Cualquier problema agregado que no incluya estos detalles se cerrará como "información insuficiente".
> 
> Para obtener asistencia sobre el uso del software o inquietudes sobre el estado de sus fondos, vaya al canal #support en el servidor NEO Smart Economy Discord: https://discord.cityofzion.io
> 
> **Versión de billetera o confirmar SHA:**
> por ejemplo: 0.2.3 o [dcae88c](https://github.com/CityOfZion/neon-wallet/commit/dcae88cc9fdb6d56be457d10884a0ddeac482e0c)
> 
> **Entorno:**
> por ejemplo: Win 10 Home (64 bits) Versión 1709 Compilación 16299.309
> 
> **Requisitos previos:**
> p **.** Ej., No tener tokens personalizados agregados antes de ejecutar la billetera
> 
> **Pasos de reproducción:**
> por ejemplo:
> 
> 1. Iniciar Neon Wallet
> 2. Haga clic en el botón "Administrar configuración de Neon"
> 3. Haga clic en el botón "Administrar tokens"
> 4. Haga clic en el botón "Agregar un token nuevo".
> 
> alguna descripción (por ejemplo, qué sucede después de completar los pasos de reproducción), por ejemplo:
> Después de hacer clic en el botón "Agregar un nuevo token", la billetera "se cuelga" durante 2 segundos.
> 
> **Capturas de pantalla / video:**
> por ejemplo: https://example.com/screenshot.png

**Comment by licjai** [comment]
https://discord.cityofzion.io no me da acceso
