### ISSUE TITLE
Coins are not visible in the wallet with Ladger Nano X

### ISSUE THREAD

**Issue by azmigtele** [CityOfZion/neon-wallet#2113]
Good afternoon. Coins are no longer displayed in the wallet, your link does not work - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.:  v2.6.2

**Environment:**
e.g.: Win 7 64, service pack 1

Playback steps: 

I go to my personal account in the software. There are no tokens. On the site, they are displayed that they are in the wallet.

See examples, screenshots
https://neotracker.io/address/AcWSxy1KFYtET5bkY4Vasar3nPZaXqkzQh
![11](https://user-images.githubusercontent.com/81925171/114591100-33042500-9c92-11eb-8d09-416a50d878e8.PNG)
![2](https://user-images.githubusercontent.com/81925171/114591103-34355200-9c92-11eb-843c-4a97e114d0ee.PNG)
![3](https://user-images.githubusercontent.com/81925171/114591105-34355200-9c92-11eb-9c07-83ffaa6e6592.PNG)
![4](https://user-images.githubusercontent.com/81925171/114591109-34cde880-9c92-11eb-901d-0cb13724731f.PNG)

Please help me solve the issue here or answer the email az@migtelele.ru

**Comment by Rumblefish727** [comment]
I am having the exact same issue.

**Comment by azmigtele** [comment]
> I am having the exact same issue.

Error on the system side, please urgently fix the program or allow you to withdraw coins

**Comment by comountainclimber** [comment]
👋 we are actively working on this issue right now thank you for reporting

**Comment by azmigtele** [comment]
>  we are actively working on this issue right now thank you for reporting

Super, thank you, we are waiting

**Comment by comountainclimber** [comment]
Should be totally resolved as of yesterday
