### ISSUE TITLE
System Assets - Failed to load

### ISSUE THREAD

**Issue by pim059** [CityOfZion/neon-wallet#2114]
**Wallet version or commit SHA:**
v2.6.2

**Environment:**
Windows 10 Home (64 bit) Version 20H2 Build 19042.867

**Prerequisites:**
Can't access wallet funds, getting the message under system assets "Failed to load. Retry or select a different node." 

**Reproduction steps:**
1. Start Neon Wallet (via Ledger)
2. Login to wallet

I'm trying to access my wallet to check my funds, but it seems to be having connection problems. It shows the error under system assets "Failed to load. Retry or select a different node." And it doesn't show my NEO and GAS tokens under token balances

I tried to switch between different nodes, but it doesn't help

**Screenshots/Video:**
![neon-wallet-github](https://user-images.githubusercontent.com/82471274/114606587-bd9d5200-9c9b-11eb-8e6c-20e43fb26e06.jpg)

**Comment by ARA1969** [comment]
Also having similar issues, logging in using password. NEO and GAS not showing, all other tokens present.

**Comment by Joy-ks** [comment]
Hello, same issues for me. NEO ans GAS not showing and also get this message: "Failed to load. Retry or select a different node."
When i try with the web wallet (https://neotracker.io/wallet) funds are there but it is impossible to claim GAS.

**Comment by comountainclimber** [comment]
Should be resolved as of yesterday...
