### ISSUE TITLE
Can't send GAS from NEON wallet 2.6.2

### ISSUE THREAD

**Issue by phantasticalesh** [CityOfZion/neon-wallet#2115]
Hi

is there still a problem with sending GAS from NEON wallet 2.6.2 to Binance? None of the options work. Whichever FEE option I choose I get this error:

Error: Based on the size of this transaction a fee of at least 0.33546000000000004 GAS is required.

I want to transfer 12 GAS and have 13.5

I don't get it

**Comment by EdgeDLT** [comment]
@phantasticalesh You probably have a lot of GAS UTXOs which are making the transaction size very big, thus needing a high fee. You can use a wallet that allows you to set the higher fee, or build a custom transaction that you sign and send from Neon. 

If neither of those options sound appealing, you can also try send yourself a very small amount of GAS. Maybe 0.001 or even less to start. If it goes through, try again with 1 GAS. Doing this will batch up your UTXOs. After that you can probably send the whole amount to Binance again.

**Comment by phantasticalesh** [comment]
> @phantasticalesh You probably have a lot of GAS UTXOs which are making the transaction size very big, thus needing a high fee. You can use a wallet that allows you to set the higher fee, or build a custom transaction that you sign and send from Neon.
> 
> If neither of those options sound appealing, you can also try send yourself a very small amount of GAS. Maybe 0.001 or even less to start. If it goes through, try again with 1 GAS. Doing this will batch up your UTXOs. After that you can probably send the whole amount to Binance again.

What exactly is GAS UTXO?

**Comment by phantasticalesh** [comment]
I'm testing the strategy of sending 0.01 but that's it. It's the only amount I can send...did it 10 times already. no other amount goes through

**Comment by EdgeDLT** [comment]
A [UTXO](https://www.investopedia.com/terms/u/utxo.asp) is an unspent output. You don't really have a single GAS balance, but a number of unspent GAS outputs that combine to equal your total balance. If you have too many, the transaction built using them all will be too big and therefore have a big fee.

If you don't want to pay the fee, sending small transactions until you have consolidated all your unspents is required. If 0.01 works, try 0.1, then 1. If you can send 1, the rest shouldn't be a problem.

**Comment by phantasticalesh** [comment]
Well, after testing 20 times the only amount I can send is 0.001

**Comment by phantasticalesh** [comment]
finally, after god knows how many transactions it went through
