### ISSUE TITLE
[wallet connect] - ability to open and sign transactions in neon

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-wallet#2136]
**Summary** 
As a dapp user I want to be able to click a button that opens neon with a transaction ready for me to sign and relay back to the dapp

**Designs:**
1. https://tools.avocode.com/comment/groups/f4aeb93f05d34ff79bcd8c094e302b2c?artboardOriginalId=69AC3925-1026-45C2-91B5-90C4431CFA7D&theme=light

2. https://tools.avocode.com/comment/groups/f4aeb93f05d34ff79bcd8c094e302b2c?artboardOriginalId=6847B4A0-47D9-47E2-856E-46E571A4D15F&theme=light

**Acceptance Criteria:** 
With the dApp already connected to the wallet, when users perform an action that demands a transaction to be validated in the wallet, we should:
- Open/maximize the neon wallet, in the [Wallet Connect page ](https://tools.avocode.com/comment/groups/f4aeb93f05d34ff79bcd8c094e302b2c?artboardOriginalId=6847B4A0-47D9-47E2-856E-46E571A4D15F&theme=light), showing a new notification with a description of the action related in the transaction and also a list of the methods being invoked in the Request Details section
- The user is required to either accept or reject the request.
- Approving the transaction broadcasts the signed transaction back to the dApp

**Comment by gil** [comment]
I believe you tagged the wrong person :)
