### ISSUE TITLE
NW - Implement N3 migration support

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#2148]
This feature implements N3 migration support for both keys stored in the wallet and ledger devices. Implementation can be done in parallel to #2147 , but completion is blocked until N3 ledger integration is complete.  The current proposal is to build out native support in Neon Wallet Desktop (as opposed to using WalletConnect or dAPI).

Workflow Link: https://lucid.app/lucidchart/invitations/accept/inv_6e40cb91-ece0-403c-bbcd-c60565a97de2

**Comment by rssavietto** [comment]
@picarodias Hi Fred, for now I'm turning this into an Epic as this may include multiple different issues under it. Please coordinate with Tyler if that's how it should be handled or not.

**Comment by lllwvlvwlll** [comment]
Superceded by #2198
