### ISSUE TITLE
How to delete saved wallet

### ISSUE THREAD

**Issue by ioannistsil** [CityOfZion/neon-wallet#2179]
I found there is no delete wallet option in NEON wallet i made a test wallet and i would like to delete it

**Comment by lllwvlvwlll** [comment]
To delete an account, log into a different account, then navigate to `Manage Wallets` in the upper right corner.  You will have the ability to delete a wallet there. 
![image](https://user-images.githubusercontent.com/29798928/131741705-b5c969d4-999a-4235-b163-085bcfd0db23.png)
