### ISSUE TITLE
Migration GAS Fee not working

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/neon-wallet#2182]
**Wallet version or commit SHA:**
2.7.5

**Environment:**
Win 10

**Prerequisites:**
- An account with enough GAS to cover Migration Fee.
- Some tokens to migrate.

**Reproduction steps:**
- Start Migration
- Try to Migrate less than 10 NEO or less than 20 GAS.
- Migration will not complete and error will show: "Not enough GAS to pay the transaction"

**Screenshots/Video:**

- Error when attempting migration:
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/9342d157-13de-416d-853f-3166d2c9f87e)

- More than 100 GAS in the account:
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/6c65fc24-15bc-4343-a7ca-c55999b99d81)

**Comment by lllwvlvwlll** [comment]
resolved in v2.8.0
