### ISSUE TITLE
Migration History not Showing GAS Migration

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/neon-wallet#2183]
**Wallet version or commit SHA:**
2.7.5

**Environment:**
Win 10

**Prerequisites:**
- An account with GAS to migrate.

**Reproduction steps:**
1. Start Neon Wallet
2. Complete migration of GAS Tokens
3. Transactions won't show on Migration History List

**Screenshot:**
- Only NEO migration transactions show up in the history:
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/ec710d26-cb7a-4bcd-a2ac-cefc875a5f91)

**Comment by lllwvlvwlll** [comment]
Resolved in v2.8.0
