### ISSUE TITLE
Migration "Call to Action Button" Missing from Home Screen

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/neon-wallet#2184]
**Wallet version or commit SHA:**
2.7.5

**Environment:**
Win 10

**Description**
There should be a Call to Action Migrate Button at the top of the Home Screen.

**Screenshots/Video:**
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/4341cd8a-f376-480e-b17c-40db63ce8a79)e.g.: https://example.com/screenshot.png

**Comment by lllwvlvwlll** [comment]
This behavior has been superseded by implementation in the right hand nav bar.
