### ISSUE TITLE
Migration History transaction list not clear

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/neon-wallet#2186]
**Wallet version or commit SHA:**
2.7.5

**Environment:**
Win 10

**Description**
- It's not clear what the transactions displayed in Migration History list mean.
- There's also a receive icon in the first column that does nothing.

**Screenshots/Video:**
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/30ad0df6-1fee-4447-84d6-b0fba5f82a37)

**Comment by comountainclimber** [comment]
Feature added to release 2.8.0
