### ISSUE TITLE
Migration -> N3 Wallet Creation Confirmation Screen

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/neon-wallet#2189]
**Add an extra screen in the migration flow, after the actual creation of the N3 Wallet**

This screen is intended to give the user the opportunity to confirm they have access to the newly created N3 Wallet, ensuring they're safe about where they're migrating their tokens to before proceeding.

**After "Create an N3 Wallet" Screen:**
A confirmation page with the following info:
- Congratulations your N3 wallet has been created.
- You can log in to the N3 side of Neon Wallet to test it, and return to this screen when you're ready to Migrate.
- Or you can proceed to Migration right away.

_If the user exits the migration flow and returns to it, the N3 Wallet Creation step should be replaced with an N3 Wallet Login step:_

**When coming back to the Migration Tab, with N3 wallet already created:**
The screen should display:
- The related Neo Legacy and N3 addresses connected by an arrow, showcasing the relationship between the user's Legacy and N3 accounts involved in Migration;
- The Login fields for the user to input the correct password for their N3 Wallet.

---

**[specific design directions on how to implement are still up for debate]**

**Comment by picarodias** [comment]
Wireframes:

https://lucid.app/lucidspark/53903947-25a7-464b-b9c1-ad8079c3b996/edit?referringApp=slack&shared=true#

**Comment by comountainclimber** [comment]
Feature added to release `2.8.0`
