### ISSUE TITLE
Wrong hash for 0.0.6 deb file

### ISSUE THREAD

**Issue by rolo** [CityOfZion/neon-wallet#219]
Hi all. Nice work on getting an RPX compatible wallet out in time :)

I'm seeing a different hash for the deb to the one in the release notes.

Release notes:

    Linux (deb): 5661a9ffad2c3a8c6ff24d960e8acfd288ebca6527621c56b8a1808e2285266a
    sha256sum Linux.Neon_0.0.6_amd64.deb

Downloaded file:

    $ sha256sum Linux.Neon_0.0.6_amd64.deb
    a718f352cbd66e1f3e67591d21127c48d3491d279b98b62aa35b61533362617c  
   Linux.Neon_0.0.6_amd64.deb

The hash listed is the same as the .AppImage one so I presume it's a typo, but wanted to check. Thanks.

**Comment by AdrianScott** [comment]
please fix, thanks. i got the same sha256 as you, rolo, fwiw...

**Comment by fabwa** [comment]
fixed
