### ISSUE TITLE
Encrypt a key option in settings only allows for legacy keys

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-wallet#2192]
**Wallet version or commit SHA:**
e.g.: 2.7.5

**Environment:**
OSX 10.15.4

**Prerequisites:**
None

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Encrypt a key" button
4. Enter a private key and passphrase and click "Generate Encrypted Key"
5. Log out of the current session
6. Switch the network toggle to N3 and try to log in with the newly-generated key

Logging in to N3 will show an invalid passphrase error, because the encrypted key was generated according to the Neo Legacy code flow. Since NEP-2 keys include built-in validation on the address generated by the unencrypted key, Neo Legacy and N3 encrypted keys are not compatible given the same unencrypted key.

**Recommended solution:**
There should be a toggle in the Generate Encrypted Key view to choose between Legacy and N3, or the view should just use the existing state of the Legacy/N3 login toggle.

**Comment by comountainclimber** [comment]
Should be fixed in release `2.8.0`

**Comment by lllwvlvwlll** [comment]
@hal0x2328 can you verify and close out the issue if the expected behavior is present?

**Comment by hal0x2328** [comment]
Verified fixed.
