### ISSUE TITLE
Implement N3 migration support for ledger

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#2198]
This enhancement will implement the ledger migration workflows in Neon Wallet.  This workflow can be accessed when clicking the `migration` icon on the navigation bar when a user has logged in with ledger. This feature will align to and reuse as much of the NEP2/Private Key workflow as possible.

## List of Terms
Supported Hardware Wallet - Nano Ledger S and Nano Ledger X
## User Needs
1. Users shall have the ability to migrate tokens from a Ledger Nano S managed Neo Legacy address to a Neo N3 address managed by a supported hardware wallet
2. Users shall be guided through all steps of the process to minimize room for user error
3. Users shall be presented with the status of their migration.
4. Users shall have the ability to migrate user defined quantities of NEO, GAS, CGAS, and CNEO.

The assumed state of users when they approach the tab is that they have access to a ledger with the `Neo Legacy` application installed.

## Workflow:
1. User is presented with a view to `open their N3 ledger app`.  Users will be provided with information on how to install the N3 app. A `continue` button will be disabled until the N3 ledger app is detected and an address has been selected.
2. User is prompted with the asset selection view to select how much NEO/GAS they would like to send.  This view is identical to the NEP2/Private Key view. 
3. Clicking the `continue` button presents the user with a confirmation modal outlining they transaction metadata.  Users will also be notified that they need to open their `Neo Legacy` application.  A "confirm" button will be disabled until the Neo Legacy application is detected.  Once confirmed, the transaction is sent to the ledger and users are prompted to sign the transaction on ledger.  
4. Once they have signed, the modal will close and they will be navigated to the migration summary page to track their migration.

**Comment by lllwvlvwlll** [comment]
This feature has a `finish-finish` blocked by #2147

**Comment by J-G-W** [comment]
![0 2 -ledger flow](https://user-images.githubusercontent.com/36457062/131541703-40e4986c-ea81-4046-b28d-80a051dbc1be.jpg)
![0 3 -ledger flow](https://user-images.githubusercontent.com/36457062/131541710-41141495-f91b-43c5-b969-25cf418d210c.jpg)
![0 4 -ledger flow](https://user-images.githubusercontent.com/36457062/131541713-78e654c8-7e9c-46a9-b349-6c90019462d3.jpg)
![0 5 -ledger flow](https://user-images.githubusercontent.com/36457062/131541716-97b1ee03-bef7-440a-8240-31f54a787cff.jpg)
![0 6 -ledger flow](https://user-images.githubusercontent.com/36457062/131541719-9a967d90-e67b-4e60-ad71-7a8c2f2f0879.jpg)

**Comment by taanite** [comment]
I'm on version 2.8.1 and there is no migration tab on the side?

**Comment by WilsonFlips** [comment]
> I'm on version 2.8.1 and there is no migration tab on the side?

Same here.

**Comment by lllwvlvwlll** [comment]
@taanite @WilsonFlips This is an issue for feature implementation.  You will not have these views in v2.8.1 when logged in with a ledger because they have not been released yet.

**Comment by taanite** [comment]
Thanks for the reply. For the Token Migration Incentive Program, the 1% bonus runs from Sept 1st to 14th. Will the migration tab for ledger x be released before the 14th?

**Comment by lllwvlvwlll** [comment]
@taanite You will have a way to migrate before the 14th with a ledger.

**Comment by lllwvlvwlll** [comment]
resolved in v2.9.0
