### ISSUE TITLE
where is close and minimize button

### ISSUE THREAD

**Issue by mfoolady** [CityOfZion/neon-wallet#2199]
**Wallet version or commit SHA:**
2.8.0

**Environment:**
Win 10 (64 bit)

**Prerequisites:**
Where is the close and minimize button????

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/59839339/130940482-0a05549d-4d57-43d8-b699-76e0ea41d7cd.png)

**Comment by josephj11** [comment]
Same problem on Linux. Have to use the desktop  to close the window.

**Comment by mfoolady** [comment]
fixed with version 2.8.1

**Comment by josephj11** [comment]
Close Window button is there and works in 2.8.1, but it's invisible in dark mode. Had to hover where I thought it should be to find it. Thanks for the fix, but the theme isn't quite right yet.
kubuntu 18.04 Breeze Dark desktop theme.

**Comment by lllwvlvwlll** [comment]
resolved in v2.8.2
