### ISSUE TITLE
hello, this Andy

### ISSUE THREAD

**Issue by amazingandyyy** [CityOfZion/neon-wallet#22]
Hello this is Andy from Bay Area

As a decent React developer/Node/Daap Developer, I am wondering how can I start to contribute and be a part of members? Thanks.

**Comment by amazingandyyy** [comment]
btw, I am also ANS early holder :p that's why I will continue support NEO. :) cheers

**Comment by canesin** [comment]
[join us in slack](https://neoblockchainteam.slack.com/join/shared_invite/MjE3ODMxNDUzMDE1LTE1MDA4OTY3NDQtNTMwM2MyMTc2NA) .. there is not much secret, if the electron wallet is where you feel you can contribute most ping @Ejhfast there to familiarize with current needs and you can jump in, just fork and PR..

**Comment by amazingandyyy** [comment]
thanks
