### ISSUE TITLE
[wallet connect] - Wallet Connect Designs

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#2200]
This issue implements the designs for the Neon Wallet Wallet Connect feature.  Refer to the epic #2156 for relevant requirements and workflow.

**Comment by J-G-W** [comment]
![WC-01](https://user-images.githubusercontent.com/36457062/131157914-cae8da47-da38-4d08-8558-0eb6ddf980be.jpg)
![WC-02](https://user-images.githubusercontent.com/36457062/131157920-23b8c06b-cf36-4d2a-b4ab-170a5313d953.jpg)
![WC-03](https://user-images.githubusercontent.com/36457062/131157922-f3e0c294-40f3-42e1-8798-e78b6eb132b9.jpg)
![WC-04](https://user-images.githubusercontent.com/36457062/131157923-ef149334-a330-4ef2-b0f3-1d214631cf7e.jpg)
![WC-05](https://user-images.githubusercontent.com/36457062/131157927-3243f739-c7eb-44c6-b4ca-0e7cde795ae0.jpg)

**Comment by lllwvlvwlll** [comment]
Modal design for review.  @melanke @hal0x2328, @deanragnarok  do you have any thoughts on this?

fyi @J-G-W 
![image](https://user-images.githubusercontent.com/29798928/131739903-ac644972-1701-4e6c-aeb5-c7f829057c0e.png)



@J-G-W for a reference, the fields in the `Request Details` section are referencing the `bidToken` method definition here: 
https://dora.coz.io/contract/neo3/mainnet/0xcc638d55d99fc81295daccbaf722b84f179fb9c4

**Comment by lllwvlvwlll** [comment]
resolved, thanks!
