### ISSUE TITLE
Removing N3 wallet removes all legacy wallets

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-wallet#2201]
**Wallet version or commit SHA:**
2.8.0

**Environment:**
OSX 10.15.4

**Prerequisites:**
At least one legacy wallet and more than one N3 wallet

**Reproduction steps:**
1. Start Neon Wallet
2. Log in to the N3 wallet you don't want to remove
3. Click on "Manage Wallets"
4. Click "Edit" on the N3 wallet you're not logged in
5. Click "Remove Wallet"
6. Confirm

After removing the N3 wallet, a toast message appears saying the account creation was successful ??? Now if you go back to the login screen, you have only the N3 Wallet name as an option in the legacy dropdown menu and all other previously-created wallets are gone. If you look at `userWallet.json` and `n3UserWallet.json` they both only have a single entry with the N3 address and the same NEP-2 encrypted key (which won't even work for legacy).

**Comment by lllwvlvwlll** [comment]
resolved in v2.8.1
