### ISSUE TITLE
Migration dialog doesn't show the fee for migrating NEP-5 tokens

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-wallet#2203]
**Wallet version or commit SHA:**
2.8.0

**Environment:**
OSX 10.14.5

**Prerequisites:**
Have some CGAS

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Log in to wallet that has some CGAS
3. Create N3 wallet if required
4. Click on "Select tokens to migrate"
5. Choose CGAS as the asset and 0.00000001 as the amount and click "Continue"

The migration dialog shows the transfer details but no warning of the 1 GAS fee that will be incurred if the amount is below the threshold

**Screenshots/Video:**
https://www.dropbox.com/s/10y6hpyuod20y5m/Screen%20Shot%202021-08-28%20at%2010.47.04%20AM.png?dl=0

**Comment by kinmya** [comment]
User receives "warning" that GAS is required for migration of the cgas.   v2.8.1  (on Mac app)

**Comment by kinmya** [comment]
Confirmed on MAC desktop app that the warning message on fee exists and on CGAS migration on step 2 when CGAS is selected and user hits continue.

**Comment by lllwvlvwlll** [comment]
closed as resolved in v2.9.0
