### ISSUE TITLE
Error Claiming GAS on N3 wallet

### ISSUE THREAD

**Issue by hocuspocus69** [CityOfZion/neon-wallet#2204]
everything ok...

**Comment by lllwvlvwlll** [comment]
@hocuspocus69 can you verify that this is the button you are clicking?  Your 2nd reproduction step does not align with the copy on the interface. 

![image](https://user-images.githubusercontent.com/29798928/131538214-382688cb-f868-4013-badc-7b4a9ec36085.png)

**Comment by hocuspocus69** [comment]
this is the button i clicked today i retry and i can get GAS..

**Comment by lllwvlvwlll** [comment]
I'm glad everything worked! I will close this issue out as not reproducible.  If the issue arises in the future, please reopen and post the error message you receive. Thanks!
