### ISSUE TITLE
ledger panel not resetting when switching chain

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-wallet#2219]
**Wallet version or commit SHA:**
7f262913c98eee5c30a55957ad2c565d733c5845

**Environment:**
linux/osx/windows

**Prerequisites:**
have a ledger

**Reproduction steps:**
e.g.:
1. open Ledger tab in N2 mode
2. open the ledger app such that we get an address
3. now switch to N3 mode. The data in the panel will not be refreshed and shows addresses for the wrong chain.

Same happens if you start with N3 and go back to N2.

**Comment by ixje** [comment]
> comountainclimber  16:22
The first one is an easy fix

assigned you because you said it was easy :P

**Comment by lllwvlvwlll** [comment]
resolved in #2227 ; will verify in #2147
