### ISSUE TITLE
ledger panel not recognizing ledger is connected until you open the app

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-wallet#2220]
**Wallet version or commit SHA:**
7f262913c98eee5c30a55957ad2c565d733c5845

**Environment:**
linux/osx/windows

**Prerequisites:**
have a ledger

**Reproduction steps:**
e.g.:
1. open Ledger tab in N23mode
2. connect and unlock ledger (without opening the app).
3. you'll be stuck on the first step of the ledger panel ("connect ledger") until you actually open the app

**Comment by ixje** [comment]
@comountainclimber if you can tell me where the code is that decides if the app is connected or not I might be able to help.

**Comment by lllwvlvwlll** [comment]
This is reproducible on the legacy size of the application is appear to be a breaking change as a result of ledger firmware updates between `v1.6` and `v2.x`
