### ISSUE TITLE
Ledger Migration is Here Banner

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#2223]
This task covers the creation of a banner announcing Migration for Ledger users in Neon Wallet.  It can use a special template and should have a bit more celebratory flair than our typical release banners (I am not sure if that helps with direction very well) . :)

**Comment by J-G-W** [comment]
Here's a first cut, Trying to work a celebratory element in:
![NeonWallet N3 Ledger](https://user-images.githubusercontent.com/36457062/132339478-3c6fa3cc-c6f6-43e3-b805-26e6d7f600e6.png)

**Comment by lllwvlvwlll** [comment]
resolved
