### ISSUE TITLE
NEON App GAS migration Error

### ISSUE THREAD

**Issue by morseke** [CityOfZion/neon-wallet#2232]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
2.8.1

**Environment:**
macOS Catalina 10.15.7
![GAS migration error](https://user-images.githubusercontent.com/90208161/132243697-dc1e44cd-01a6-4744-be83-7361ce479a3b.png)

**Prerequisites:**
No custom tokens were added to NEON
Error migrating GAS token to N3

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Migration" button
3. Click on "Create N3 Wallet" button
4. Click on "Select tokens to migrate" button
5. Input recipient address (N3 wallet address)
6. Select GAS from pulldown
7. Click on "MAX"
8. Click on "Continue" button

Error is generated: "This migration transaction has an excessive number of UTXO input and will require GAS in fees.  Consider sending all your (GAS/NEO) to yourself first in order to avoid the extra fee."

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
screenshot of error message attached.

**Comment by uberlance** [comment]
I had the same error and followed the instructions.  With all the "claim gas" transactions, it gets messy.  Send all your GAS (less the 0.05 GAS fee) to your own/same address.  Once it confirms, you should be able to migrate without errors.

**Comment by verkhoshi** [comment]
I have the same issue.
When I tried to send it to my new N3 Wallet I getting the error "You need to specify a valid NEO address."
Any help?

**Comment by njappboy** [comment]
I see the same message when I attempt to migrate GAS. If I try to send all the GAS to myself via the existing mainnet I receive this message in the Neon UI
```
OOPS! SOMETHING WENT WRONG...
Error: Your transaction is too big for the Ledger to sign
```

**Comment by morseke** [comment]
What I don't understand is how NEO can do a migration, with the Main NEO Wallet providing a migration process that doesn't work.  Does anyone check if their solution works?  Sure, they all might under a lot of pressure in the most important launch in the history of NEO.  But not having a complete solution is worst than not having one at all.

I'm likely just going to send my GAS to an exchange, sell them and then buy the N3 version.  Since both versions will be active for the next 12 months, it seems like the only logical solution.  I'm just grateful NEO migrated successfully.

**Comment by njappboy** [comment]
> What I don't understand is how NEO can do a migration, with the Main NEO Wallet providing a migration process that doesn't work. Does anyone check if their solution works? Sure, they all might under a lot of pressure in the most important launch in the history of NEO. But not having a complete solution is worst than not having one at all.
> 
> I'm likely just going to send my GAS to an exchange, sell them and then buy the N3 version. Since both versions will be active for the next 12 months, it seems like the only logical solution. I'm just grateful NEO migrated successfully.

I think they just didn't check edge cases that cause very large transactions or GAS claimed hundreds of times since 2017 which is a lot of UTXOs

**Comment by njappboy** [comment]
@comountainclimber is anyone going to address this issue(s)?

**Comment by njappboy** [comment]
@lllwvlvwlll can we get some 👀 on this issue? Seems like it would be an issue for anyone using the network since launch.

**Comment by lllwvlvwlll** [comment]
@njappboy yes; we are aware of the issue.  There are three different topics being discussed here.  
1. @verkhoshi you need to use the migration tab to migrate assets.  You cannot simply `send` your Neo Legacy GAS to your new N3 address.
2. The original comment is associated with UTXO buildup. @morseke did you follow the instructions in the error message?  They are clear on the mitigation approach to resolve the majority of occurrences.  You can also refer here for more info: https://medium.com/proof-of-working/psa-if-youve-frequently-claimed-gas-on-your-ledger-e3bd046b9bd2
3. @njappboy the issue you are referring to has already been resolved and will be released in a patch shortly.  Please watch for v2.9.3

**Comment by morseke** [comment]
Hi Tyler-

I read the linked article.  Thank you.  I didn’t send them to myself before, since someone else wrote in response to my original post that they sent tokens to themselves, but they still had the same error.  I just sent the tokens to myself in 4 transactions.  I kept getting an error about that it needs 0.36 gas. But breaking it up into 4 pieces allowed me to send them to myself.  I really don’t care about paying a gas fee to get this done.

Then I tried the migration again.  Same error.  

I think I’m just going to try sending them to Binance.us <http://binance.us/> and selling them and buying back the new N3 gas tokens.

Thank you,
Kevin

**Comment by verkhoshi** [comment]
> @njappboy yes; we are aware of the issue. There are three different topics being discussed here.
> 
> 1. @verkhoshi you need to use the migration tab to migrate assets.  You cannot simply `send` your Neo Legacy GAS to your new N3 address.
> 2. The original comment is associated with UTXO buildup. @morseke did you follow the instructions in the error message?  They are clear on the mitigation approach to resolve the majority of occurrences.  You can also refer here for more info: https://medium.com/proof-of-working/psa-if-youve-frequently-claimed-gas-on-your-ledger-e3bd046b9bd2
> 3. @njappboy the issue you are referring to has already been resolved and will be released in a patch shortly.  Please watch for v2.9.3

Yes @njappboy, I been using the the migration tab to migrate asset. Neo migration went fine, but GAS is stacked with this error.
