### ISSUE TITLE
Enhancement - GAS Claim less than cost of claim

### ISSUE THREAD

**Issue by kinmya** [CityOfZion/neon-wallet#2245]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
v2.9.0.RC2

**Environment:**
MAC desktop

**Prerequisites:**
NEO and GAS in wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Open a wallet with NEO and an amount of GAS greater than transaction fee
3. From the "Wallet" tab view System Assets section
4. Select the Claim GAS button 

some description (for ex. what happens after completing reproduction steps), e.g.:
GAS can be claimed, but user ends up with less GAS than before the claim

**Comment by lllwvlvwlll** [comment]
resolved in v2.10.0
