### ISSUE TITLE
Release 2.9.2 defaults to NEOSCAN instead of Dora when upgrading from really old wallet 

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-wallet#2255]
I upgraded my OSX version from `2.6.x` to `2.9.2`. `2.6.x` probably used NEOSCAN as default in its settings. The first time I opened neon-wallet 2.9.2 it would use NEOSCAN when viewing transactions. I had to go to network settings and select Dora. Funny enough DORA was the only option I could select there. So this is probably some old caching that it kept using.

**Comment by comountainclimber** [comment]
Should be resolved...
