### ISSUE TITLE
Wallet Connect for Neon Wallet static site

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#2263]
This issue covers the design and implementation of a `Wallet Connect for Neon Wallet` static site.  

## User Needs
1. An application shall have the ability to transfer users to the site with a `Wallet Connect Connection Payload`
2. The site shall have the ability to interpret a `Wallet Connection Connection Payload` for presentation to the user
3. The site shall present the user with a  Wallet Connect Connection Request formatted as raw text for input into Neon Wallet
4. The site shall present the user with a  Wallet Connect Connection Request formatted as QR Code for input into Neon Wallet
5. The site shall present the user with a  Wallet Connect Connection Request formatted as deep link for integration with Neon Wallet
6. The site shall provide inform users on How and Why to use Neon Wallet with Wallet Connect including a Neon Wallet download link
7. The site shall inform users about how to get started with integrating wallet connect in their application

**Comment by J-G-W** [comment]
@lllwvlvwlll A quick first draft before content:
![image](https://user-images.githubusercontent.com/36457062/134380494-898ccac7-cbdf-4b20-ab21-6d4ceae5d0cf.png)

**Comment by lllwvlvwlll** [comment]
Implementation of this task will also include the following:
  * Addition of this page to the neonwallet static site
  * Migration of neonwallet.com hosting to AWS
  * DNS resolution for `neon.coz.io` to target the neonwallet.com site.

**Comment by lllwvlvwlll** [comment]
avocode link: https://app.avocode.com/projects/2058387/groups/6030696

**Comment by lllwvlvwlll** [comment]
@comountainclimber If you want to handle the front-end work; I can do the site migration

**Comment by lllwvlvwlll** [comment]
Resolved at neon.coz.io/connect
