### ISSUE TITLE
Ledger S N3 login after migration does not seem to work

### ISSUE THREAD

**Issue by piedrogenius** [CityOfZion/neon-wallet#2270]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
2.9.3

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 21H1 Build 19043.1237

**Prerequisites:**
Ledger N3 (v0.1.3) app  installed. Ledger S on 2.0.0
Have migrated 1 GAS which worked flawlessly. N3 public address assigned

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Slide to N3
3. Click on Ledger tab
4. Open ledger N3 app 

No login possible, hangs on navigate to the NEO app on your device. Logon with legacy app on N3 slide or legacy slide seems to work with the legacy address.

**Comment by piedrogenius** [comment]
Further on this: re-installed everything again to no avail.

Could it be  that I need at least 1 NEO to be able to log-in, irrespective of GAS  amount

**Comment by piedrogenius** [comment]
Retried on a laptop and it worked! Noticed that a slide towards N3 also made the N3 grey-out disappear. This is not the case with the desktop. There the legacy chain stays active. So it seems not to be a ledger specific issue....

**Comment by piedrogenius** [comment]
![1633087571481](https://user-images.githubusercontent.com/29685989/135612730-3f854287-dcfd-44f0-ad5c-32004987d9ee.jpg)
![1633087544917](https://user-images.githubusercontent.com/29685989/135612752-1c8e9765-91f4-4094-9842-1960b1596843.jpg)

One greyed out after slide, the other not and working

**Comment by lllwvlvwlll** [comment]
This issue has been verified as resolved in RC5.  @piedrogenius please look for the upcoming release. :)

**Comment by piedrogenius** [comment]
Thanks. Indeed solved in RC5.

Top work
