### ISSUE TITLE
Neon not sending any gas

### ISSUE THREAD

**Issue by glwosteen70** [CityOfZion/neon-wallet#2290]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by gsmachado** [comment]
@glwosteen70 I could finally send some GAS with 2.9.4. Can you try?

**Comment by glwosteen70** [comment]
Thanks but I was able to upgrade to 2.9.4 and am still not getting any GAS. Can you tell me what's going on?

**Comment by glwosteen70** [comment]
I'm not getting any GAS.  Should that be happening? What can I do?

**Comment by oksygen** [comment]
Same, can't collect generated gas. None is earnt/offered.

**Comment by gsmachado** [comment]
@oksygen and @glwosteen70:
I can successfully claim and send GAS with [version 2.9.4](https://github.com/CityOfZion/neon-wallet/releases/tag/v2.9.4).
Maybe @comountainclimber has any thoughts?

**Comment by oksygen** [comment]
@gsmachado I am on that build, I could be barking up the wrong tree here, but I'm thinking this has started because of migration? It is also possible that the issue is my set-up & my knowledge.
I have tried to claim gas across the last few days.
Claim button greyed out, and reads Claim 0.0000000 GAS

**Comment by gsmachado** [comment]
@oksygen Are you trying to claim GAS on Neo Legacy? Or Neo N3?

**Comment by oksygen** [comment]
Legacy

**Comment by gsmachado** [comment]
> Legacy

Ah, that's why. There's no more GAS generation for Neo Legacy. Just for Neo N3.

**Comment by oksygen** [comment]
@gsmachado I'm glad I left a comment then, how long has that been the case? I don't always follow the development closely. It's normally a catch-up situation
Thanks

**Comment by ixje** [comment]
@oksygen It was announced here: https://neo-blockchain.medium.com/neo-legacy-mainnet-to-stop-gas-generation-at-block-height-8-000-000-neo-cli-node-updates-required-5af7603a8602
[Block 8 million](https://dora.coz.io/block/neo2/mainnet/8000000) was produced on September 19th.

**Comment by ixje** [comment]
Closing because OP seems inactive.
