### ISSUE TITLE
Neon can not send any amount of GAS in N3

### ISSUE THREAD

**Issue by Kirill2neo** [CityOfZion/neon-wallet#2291]
Trying to send GAS to n3 adreess, in the moment when transaction should be signed by ledger nano s, error appears:

OOPS! SOMETHING WENT WRONG...
Error: num2hexstring expected a number but got undefined instead.

**Wallet version or commit SHA:**
Neon 9.2.3

**Environment:**
Windows 10 64x
Ledger Nano S with firmware 2.0, Neo N3 app - 0.1.3

**Prerequisites:**
First transaction attempt after migration GAS to N3. No token, no NEO in wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Choose N3 ticker
3. Choose Ledger in menu
4. Unlock ledger
5. Enter Neo app on ledger
6. Login to walllet
7. Choose send menu
8. enter 2 GAS as amount and enter address (total in wallet >300)
9. Push Send button
10. Error appears after few seconds

**Screenshots/Video:**
https://prnt.sc/1w474nf

**Comment by gsmachado** [comment]
Isn't this also related to https://github.com/CityOfZion/neon-wallet/issues/2294? 😄 😓

**Comment by gsmachado** [comment]
@Kirill2neo I could finally send GAS with 2.9.4. Can you try?

**Comment by Kirill2neo** [comment]
> @Kirill2neo I could finally send GAS with 2.9.4. Can you try?

Yes, thank you, issue is resolved
