### ISSUE TITLE
"Error num2hexstring expected a number but got undefined instead" when sending from N3

### ISSUE THREAD

**Issue by epicstar7** [CityOfZion/neon-wallet#2294]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
2.9.3 and 2.10.0 as well

**Environment:**
Win 10 Home (64 bit) Version 21H1 Build 19043.1288

**Prerequisites:**

**Reproduction steps:**
1. Start Neon Wallet
2. Login into N3
3. Click on "Send" button on the left
4. Add address info and amount and try to send, error occurs

Some description (for ex. what happens after completing reproduction steps), e.g.:
Error num2hexstring expected a number but got undefined instead appears, sending won;t complete.
SEE SCREENSHOT 

(I also noticed GAS can't be claimed!

**Screenshots/Video:**
![Schermafbeelding 2021-10-16 105444](https://user-images.githubusercontent.com/47328098/137581250-76fc537f-bcd0-4e11-95f5-c0b965feb322.jpg)

**Comment by gsmachado** [comment]
I can confirm this issue as well.

![image](https://user-images.githubusercontent.com/2124276/137802728-90618003-1157-49fa-a659-5874d069e9c2.png)

**Comment by gsmachado** [comment]
@epicstar7 I could finally send GAS with 2.9.4. Can you try?

**Comment by yulyafil** [comment]
I can't send Neo and Gas for several days, error! What is the reason? 

OOPS! SOMETHING WENT WRONG...
Error: num2hexstring expected a number but got undefined instead.
