### ISSUE TITLE
Neon wallet won't let me collect GAS

### ISSUE THREAD

**Issue by faisalharianawalla** [CityOfZion/neon-wallet#2298]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c
Neon 2.6.2 

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309
Win 10

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet
Cannot collect GAS when pressing button. Claiming GAS failed.....

**Reproduction steps:**
e.g.:
1. Press Claim GAS 
2. Faills collecting GAS
some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.
Gas FAILS collecting with RED band showing the error.

https://user-images.githubusercontent.com/31812856/138212106-040e1210-865a-4596-a661-b380cb74b8bf.mp4

https://user-images.githubusercontent.com/31812856/138212154-93ba6157-ba58-4ef7-812c-1ce1cb6ff6db.mp4

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by oemer2011** [comment]
I have the same issue. Not able to claim gas in my wallet on my notebook with same error message. I also installed the latest version of wallet on another notebook. But here I can see no gas for claiming. Why I have on notebook1 e.g. 3 gas and on notebook2 0 gas for claim? What is the problem here? Can anyone explain please?

**Comment by wrapit99** [comment]
|I have same problem of not being able to claim gas after I migrated my NEO to the new Neo N3 Wallet.  The ability to claim gas was a very good source of income which now seems to be gone.  How can this be progress||?  Why the hell even start a new wallet if it can't provide the functions of the old version?

**Comment by wrapit99** [comment]
Where the hell is Neo support.  It appears that the only support is people like us texting back and forth but with no response from Neo.

**Comment by blackctxd** [comment]
I have the same problem...my GAS claim initially failed...now i see no balance in my GAS for claim even after weeks...what should I do?

**Comment by oemer2011** [comment]
On the website of neo.org it is described that after September no more gas will be produced. I transfered my neos to N3 blockchain. Now gas is produced again. You must migrate your neos to new blockchain.


________________________________
