### ISSUE TITLE
Basic Integration Test using Spectron

### ISSUE THREAD

**Issue by shawnmclean** [CityOfZion/neon-wallet#230]
We need a basic workflow testing using some UI testing tool for electron such as Spectron and executed as a step during the CI process.

Reason: We want to ensure that the app will still load with basic functionalities when there are code changes.

Suggested Workflow: `Login with known Wif on testnet` > `View Balance and Transactions`

**Comment by thuansb** [comment]
Hi @shawnmclean, I will take this task. What I need to do is just implement the test and do the pull request later right?
