### ISSUE TITLE
Feature Request: Apple Silicon (M1) Support

### ISSUE THREAD

**Issue by ghost** [CityOfZion/neon-wallet#2303]
Hi,

The current NEON works on Apples own M1 chip, using Rosetta to translate x86 to ARM. It would be nice though if there could be a new release which is build as a "Universal App" which works on both Intel en M1 Macs.

See https://github.com/electron/universal and https://www.electronjs.org/blog/apple-silicon

Cheers.

**Comment by gsmachado** [comment]
yes, I think this is gaining importance for a wide audience. (FYI, @comountainclimber @lllwvlvwlll)

**Comment by gsmachado** [comment]
Please, don't close this one. It's important. 🙏👍💪

**Comment by gsmachado** [comment]
please don't close this, it's important.

**Comment by gsmachado** [comment]
@lllwvlvwlll 😄

**Comment by comountainclimber** [comment]
@gsmachado @lllwvlvwlll @Fossil01 a little confused by this issue...

Neon currently works on all forms of MacOS including m1 and and intel chips - what exactly is the point of this issue?

**Comment by ghost** [comment]
So a native ARM app is build which doesn't need Rosetta 2 to translate it to x86 saving battery life.

**Comment by gsmachado** [comment]
yeah... so, the thing is: Neon works on all platforms. Fact. The new Macs use Rosetta to "emulate" and run x86-based apps.

However, it would be way better to have Neon compiled to `darwin/arm64` platform. It will run faster, smoother, save battery life, etc etc.

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/releases/tag/v2.16.16
