### ISSUE TITLE
Didnt recieve ONT Tokens from my NEON wallet?

### ISSUE THREAD

**Issue by McManus2MC** [CityOfZion/neon-wallet#2316]
Hey there,

I send ONT tokens from my NEON wallet to Bitvavo exchange, everything looks fine. Addresses are good but still didn't receive my tokens?
I contact Bitvavo support team and after some research they say to contact the support team of the sender side.

What to do??

**Comment by lllwvlvwlll** [comment]
ONT tokens displayed in Neon Wallet are NEP5 tokens on the `Neo Legacy` blockchain.  Bitvavo most likely supports the actual ONT tokens on the `Ontology` blockchain.  In 2018, the Ontology team deployed their own chain and hosted a migration.  You will need to contact the Ontology team to see if they still support migration of your `NEP5 tokens` onto their platform.
