### ISSUE TITLE
Neon connect with a dApp not working on quickvote.coz

### ISSUE THREAD

**Issue by Dipx** [CityOfZion/neon-wallet#2321]
**Wallet version or commit SHA:**
2.10.0

**Environment:**
Win 10 Professionnal (64 bit) Version 21H1 Build 19043.1348
Firefox browser V94.0.1 (64 bits)
Ledger nano X 2.0.0

**Reproduction steps:**
e.g.:
1. LogIn to a N3 wallet with a ledger (Didn't test other way of connection)
2. go to https://quickvote.coz.io/connectToProceed and click on connect wallet
3. Click on the button copy below the QR code
4. On ledger, on the top right corner, click on dApps, then on connect
5. Paste the url previously copied from quickvote.coz and click on "Connect"

When the click on connect is done, quickvote.coz reacts, so it sees the connection attempt, but then return to the "Home page", without actually connecting to any account

**Comment by cisengineer** [comment]
Wallet connect occurs. Both browser and Neon show the connection, but the vote page does not load. Quickvote just stays on the wallet connect page (despite showing in the top right that it is indeed already connected to the ledger through Neon)
