### ISSUE TITLE
Cannot import N3 .json wallet file into N3 but able to imported into Legacy

### ISSUE THREAD

**Issue by RawichK** [CityOfZion/neon-wallet#2334]
**Wallet version or commit SHA:**
v2.10.0

**Environment:**
Win 10 Pro (64 bit) Version 20H2 Build 19042.1348

**Prerequisites:**
Exported .json file of Neo N3 wallet from Neoline Chrome Extension version 3.4.5

**Reproduction steps:**
1. Start Neon Wallet
2. Toggle network to N3
2. Click on "Import Wallet" button
3. Click on "Recover Wallet" tab
4. Click on "Import File" button
5. Select prepared .json wallet file from file browser

Result is nothing happen, expected to be able to import the wallet from .json file.

**Screenshots/Video:*
![IMG_2303](https://user-images.githubusercontent.com/8307015/143373671-3b53697e-17ca-471a-a16d-24df46aae5cc.JPG)
*

**Comment by cypher619** [comment]
This issue still persists.  I just reinstalled wallet version 2.12.6 after doing clean install of windows 10.  Select Json file to import and nothing happens.
