### ISSUE TITLE
Feature Request: bNeo price

### ISSUE THREAD

**Issue by Ethour** [CityOfZion/neon-wallet#2336]

**Comment by comountainclimber** [comment]
We currently use crypto compare pricing API and I cannot seem to find bNEO listed on there... If you have a way of pulling pricing info we can add it

**Comment by Ethour** [comment]
I know, bNeo is not yet listed on the exchanges, but the price is the same of Neo. Doesn't it help? My request is based on the fact that, as you know, bNeo is going to be a huge use on all the Neo dApps.

**Comment by hal0x2328** [comment]
Just need to add special handling for bNEO or other wrapped tokens inside Neon to use the unwrapped token name for the price display
