### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Saint0asper** [CityOfZion/neon-wallet#2339]
Hello.
I registered the wallet in 2018 when I was Neo Legacy. Now I have a few Gala tokens there, not much, but I would like to bring them to the Binance exchange.
I have two questions:
1) Does the Neo Legacy work in a Bep20 or erc20 system? Because when transferring to Binance, you need to specify this item.
2) Why can't I transfer tokens anywhere from my wallet? I tried to withdraw to Binance, but I get an error. Then I tried to transfer the wallet to n3 inside the system through migration (because I thought that due to the type of wallet I could not transfer tokens to the exchange), but it also gives an error and it is not possible to transfer tokens.

I would be grateful if someone could explain what to do.

**Comment by comountainclimber** [comment]
What was the exact error you experienced when trying to migrate your tokens?? (NOTE: the migration only supports NEO, GAS, nNEO and cGAS more info can be found [here](https://neo.org/migration))

**Comment by Saint0asper** [comment]
> What was the exact error you experienced when trying to migrate your tokens?? (NOTE: the migration only supports NEO, GAS, nNEO and cGAS more info can be found [here](https://neo.org/migration))

In my wallet, it is displayed that the token is alive and its price changes during the day, but I cannot withdraw it to the Binance exchange. It gives me an error like in the screenshot.

What to do about it?
What is the problem and why can't I bring tokens to the exchange?
Also, the token network is not displayed in the wallet: BSC (BEP20) or ETH (ERC20)?
How to bring tokens to the exchange?
![g4URcuLSq2Y](https://user-images.githubusercontent.com/35653714/147381818-198be119-406d-4ea5-acca-260e280cd441.jpg)
