### ISSUE TITLE
Can't connect to quickvote

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neon-wallet#2347]
**Wallet version or commit SHA:**
2.11

**Environment:**
Windows 10

**Reproduction steps:**
Open quickvote.coz.io, try to connect. The app is throwing an error:
![image](https://user-images.githubusercontent.com/38396062/146997974-cbaa1a28-24c9-4814-a57c-c5e850a3671a.png)

**Comment by trancephorm** [comment]
Same problem here, Ubuntu 20.04.
