### ISSUE TITLE
Quick vote isn't working

### ISSUE THREAD

**Issue by ioannistsil** [CityOfZion/neon-wallet#2349]
Cant connect my NEON wallet version 2.11.0 after last update with quick vote

**Comment by diskooooo** [comment]
Neither `2.10.0`. I paste the connection URL, click submit, it does some short loading and then reverts back to the 'Connection URL' screen without any error/warning/message whatsoever.

**Comment by trancephorm** [comment]
Same problem here, Ubuntu 20.04
