### ISSUE TITLE
SHA256 checksums missing for 2.11.0 release

### ISSUE THREAD

**Issue by diskooooo** [CityOfZion/neon-wallet#2351]
**Wallet version or commit SHA:**
2.11.0

**Environment:**
n/a

**Prerequisites:**
n/a

**Reproduction steps:**
1. See https://github.com/CityOfZion/neon-wallet/releases

**Screenshots/Video:**
n/a

**Comment by comountainclimber** [comment]
Thanks for the reminder should be updated now 👍
