### ISSUE TITLE
Neon Wallet too high latency in almost every node, cannot see balance. My tokens i still see them on neoscan io

### ISSUE THREAD

**Issue by Altcoinseason** [CityOfZion/neon-wallet#2356]
**Wallet version or commit SHA:**
Neon Wallet 2.11.0

**Environment:**
Mac osx El Capitan version 10.11.6
 
**Prerequisites:**
I had small amount neo tokens, since the migration n3 update, my balance in Neon wallet is always 0. Never had this problem before and now almost every node is above 500 - 1000 ms or even above 2000 ms latency

**Reproduction steps:**
e.g.:
1. Start old version Neon Wallet through ledger nano s
2. i don't see token balance 
3. i updated old neon wallet to Neon Wallet 2.11.0
4. Start Neon Wallet through ledger nano s
5. i don't see neo or gas token balance, it says 0 balance. 
   on neotracker transactions and neoscan io site i still see my neo tokens.

**Comment by lllwvlvwlll** [comment]
Are you connecting to the correct side of the application?  There is a toggle for Legacy and N3 on the login screen.

**Comment by Altcoinseason** [comment]
> Are you connecting to the correct side of the application? There is a toggle for Legacy and N3 on the login screen.

I logged in through Legacy and 0 balance. I even tried N3 and 0 balance. 
I am just gonna wait untill the new updated version of neon. This issue is not new, most of the time when there is a new update hopefully it will be fixed. 

I understand the programmers work for free, so i cannot blame them for any issues that might occure when making a totally new interface with n3 and legacy combined. I will wait patiently.

**Comment by Altcoinseason** [comment]
> Are you connecting to the correct side of the application? There is a toggle for Legacy and N3 on the login screen.

I have decided to install Linux mint os and the neonwallet.deb version 2.11.0 install file. 

And now it finally works.
However it was not without hiccups, in linux i had to go to terminal and 
sudo bash 
hit enter
Typ you login pass 
hit enter
Type this command 
wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash
hit enter 

I opened Neon wallet again and now it let me login with ledger.
I see my tokens and gas, everything works.
For the people who still cannot see balance i reccommend try different os and install neonwallet.
neonwallet mac version still has the zero balance unfortunately.

Migrating ne0 tokens to n3 works.
The only small hiccup is migrating gas to n3 with ledger.
The ledger could not migrate 20 gas for free, because somehow ledger could not manage due the previous gas data.
So i had to send gas to my own ne0 legacy gas adress. The amount i did first was 0.01 gas tokens and after 10 times or so, i change it to 0.1, after couple of times sending that amount to my own gas adress, i eventually send 0.5 a couple of times to my own gas adress with ledger approval. (If you start to high amount of gas, it will require a small fee)

After that i tried the tab migrating button, logging in with n3 and then i logged in with ne0 legacy with ledger. 
I tried migrate 20 gas tokens to n3. (Be sure to check the ne0 legacy and n3 adress is correct) after pressing button migrate it worked sending it for free. If it saying cannot migrate, then you need to send again small amount of gas to your own neo legacy gas adres until your migration works.
