### ISSUE TITLE
WalletConnect: Error if wallet connect method is not supported

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#2358]
This enhancement will check the `methods` field of a walletconnect connection request and throw a toast error if the method is not supported by neon wallet.  @melanke we may consider using the wallet package of the sdk to do this check (the wallet constructor could accept a `supportedMethods` input). Thoughts @melanke @comountainclimber ?

**Comment by melanke** [comment]
There is already a list of supported methods, and there is already some checking. I think the WalletConnectContext is auto-rejecting, but we should be able to notify the user about the problem improving the experience.

**Comment by melanke** [comment]
This is the part that needs change:
https://github.com/CityOfZion/wallet-connect-sdk/blob/wallet-and-neon-packages/packages/wallet-connect-sdk-wallet/src/index.tsx#L281
