### ISSUE TITLE
Neon Wallet 2.12.3 deb for linux : White window screen at startup.

### ISSUE THREAD

**Issue by Altcoinseason** [CityOfZion/neon-wallet#2376]
Wallet version or commit SHA:
Neon Wallet 2.12.3

Environment:
Linux mint

Prerequisites:
Cannot open neon wallet 2.12.3 after install.

Reproduction steps:
1 uninstall 2.11 neon wallet
2 install 2.12.3 neon wallet
3. After opening the software, i see only white screen window, no buttons, no text, nothing.
The screen gets stuck and i cannot close it, so i need to restart. Even after restart, i tried opening and the same issue            occures.

My solution i uninstall 2.12.3 and install version 2.11 deb for linux again and now it works.
2.11 works great and thank you for the hard work.

**Comment by comountainclimber** [comment]
@Altcoinseason thank you for reporting this issue 🙏 - should be resolved as of this comment
