### ISSUE TITLE
Implement WalletConnect signMessage and verifyMessage

### ISSUE THREAD

**Issue by thiagocbalducci** [CityOfZion/neon-wallet#2382]
We can base this implementation on what was done for AeroWallet.

https://github.com/CityOfZion/web-wallet/blob/develop/src/helpers/N3Helper.ts#L159
https://github.com/CityOfZion/web-wallet/blob/develop/src/helpers/N3Helper.ts#L173

Let's also base the design on what was used for AeroWallet

**Comment by dusmart** [comment]
It seems that AeroWallet's code can not be accessed publicly. Could you please tell us what standard is based on when implementing `signMessage`.

Neoline and O3 also use the same standard while I cannot find the NEP standard for `sign` and `verify`. Is this some convention?
