### ISSUE TITLE
User Report -> not able to unwrap bNEO 

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/neon-wallet#2383]
## User report:
@tyler Users encounters a bug when using NEON. When users want to unwrap bNEO the contract requires that the data argument is null. When we try to send an invocation script with data=null NEON shows an error message. Example of invoke script:

```
[
    {
        "scriptHash": "0xd2a4cff31913016155e38e474a2c06d08be276cf",
        "operation": "transfer",
        "args": [
            {
                "type": "Address",
                "value": "NNsCaRsqr2UigVoLCQ7GVvsDRzeDTWgj4x"
            },
            {
                "type": "Address",
                "value": "NPmdLGJN47EddqYcxixdGMhtkr7Z5w4Aos"
            },
            {
                "type": "Integer",
                "value": "100000"
            },
            {
                "type": "Any",
                "value": null
            }
        ]
    }
]
```

When we force the data field to be an empty string, NEON succeeds, but the the transaction silently fails on-chain, and user never receives the NEO:
[https://dora.coz.io/transaction/neo3/mainnet/0x0916973b7100961022ce30b9bfe7d094a52a463d82a31b3a8090f152520ad993](https://dora.coz.io/transaction/neo3/mainnet/0x0916973b7100961022ce30b9bfe7d094a52a463d82a31b3a8090f152520ad993)

I have talked with WangLongLang about this, and he is not gonna change the bNEO contract to accept an empty string, so this will have to be fixed on NEON side. How fast will you guys be able to fix so that NEON accepts "Any: null"?

A lot of features of the system is tied to automatic wrapping/unwrapping of bNEO and all users using NEO will now see errors when trying to use these functions.

## Tech Report on Neon-JS side
 _by @ixje _
 
I did some analysis of the above not understanding what they mean with "unwrap bNEO".  

1.  the transaction linked does not silently fail it actually succeeds as can be seen from requesting the applicationlog (VMState == HALT and notifications have been sent).
2.  the transaction linked calls `onNEP17Payment()` on the BurgerNEO contract with the arguments `0x405e4ebaad618d82a35eb87c292eae15c24e6220`, `100000`, `00` (the last value is a `ByteString` stack item). They probably want the last item to be `null` such that they pass this statement: [https://github.com/neoburger/code/blob/2902285cd35cd4a44cec4aef27b8251cf13e18ca/BurgerNEO.cs#L59](https://github.com/neoburger/code/blob/2902285cd35cd4a44cec4aef27b8251cf13e18ca/BurgerNEO.cs#L59)

I don't know how they're creating the call, but this is the right way to build the script  

```
import { CONST, sc } from "@cityofzion/neon-core";

const script = sc.createScript({
  scriptHash: CONST.NATIVE_CONTRACT_HASH.GasToken,
  operation: "transfer",
  args: [
    sc.ContractParam.hash160("NNsCaRsqr2UigVoLCQ7GVvsDRzeDTWgj4x"),
    sc.ContractParam.hash160("NPmdLGJN47EddqYcxixdGMhtkr7Z5w4Aos"),
    100000,
    sc.ContractParam.any(),
  ],
});
```

It's a near copy/paste from the documentation. I actually verified this code by forcing transaction [0x0916973b7100961022ce30b9bfe7d094a52a463d82a31b3a8090f152520ad993](https://dora.coz.io/transaction/neo3/mainnet/0x0916973b7100961022ce30b9bfe7d094a52a463d82a31b3a8090f152520ad993) to use my fixed script instead and verifying that the `data` argument is indeed `null`.In conclusion; neon-js is fine.

**Comment by lllwvlvwlll** [comment]
@comountainclimber to reproduce, you can refer to this script to emulate the connection:
```
import {ContractInvocation, WcSdk, Signer, WitnessScope} from "@cityofzion/wallet-connect-sdk-core";
import QRCodeModal from '@walletconnect/qrcode-modal'
import Neon from '@cityofzion/neon-js'

export class WCTest {

    static async connect(): Promise<any> {

        const wcInstance = new WcSdk()

        const wcClient = await wcInstance.initClient(
            '', // logger: use debug to show all log information on browser console
            "wss://relay.walletconnect.org/" // we are using walletconnect's official relay server
          );

        wcInstance.subscribeToEvents({
            onProposal: uri => {
                QRCodeModal.open(uri, () => {
                        // @ts-ignore
                        window.open(`https://neon.coz.io/connect?uri=${uri}`, '_blank').focus();
                })
            }
        });
        console.log('connecting')
        try {
            await wcInstance.connect({
                chainId: "neo3:mainnet", // blockchain and network identifier
                methods: ["invokeFunction"], // which RPC methods do you plan to call
                appMetadata: {
                    name: "Core SDK Demo", // your application name to be displayed on the wallet
                    description: "A basic script to integrate walletconnect", // description to be shown on the wallet
                    url: "https://coz.io/", // url to be linked on the wallet
                    icons: ["https://coz.io/favicon.ico"], // icon to be shown on the wallet
                }
            })
        } catch(e) {
            console.log(e)
        }
        console.log('sleeping')
        //wait 15 seconds before sending the invocation request to allow the user to manuall connect the wallet
        console.log('done sleeping')


        ////////////////////////////////////////////////////
        /////////////////////////////////////////////////////


        const userAddress = await wcInstance.getAccountAddress()
        if (userAddress) {
            const client = Neon.create.rpcClient('[https://mainnet3.neo.coz.io:443](https://mainnet3.neo.coz.io/)');
            const balances = await client.getNep17Balances(userAddress)

            console.log(`connected to ${userAddress}`)
            console.log('balances: ', balances)

            const signer: Signer = {
                scopes: WitnessScope.None
            }
            
            const request: ContractInvocation = {
                scriptHash: '0xd2a4cff31913016155e38e474a2c06d08be276cf',
                operation: 'transfer',
                args: [
                    {
                        "type": "Address",
                        "value": userAddress
                    },
                    {
                        "type": "Address",
                        "value": userAddress
                    },
                    {
                        "type": "Integer",
                        "value": "100000"
                    },
                    {
                        "type": "Any",
                        // @ts-ignore
                        "value": null
                    }
                ]
            }
            await wcInstance.invokeFunction(request, signer)
        }
    }
}


export function sleep(ms: number) {
    return new Promise(resolve => setTimeout(resolve, ms));
}
```

![image](https://user-images.githubusercontent.com/29798928/152397956-9e1da47f-11c7-4502-b564-1585d117476c.png)

**Comment by ixje** [comment]
I believe I now understand how the input in the original report is used. I expect this to be the same issue as https://github.com/CityOfZion/neon-js/issues/817 and expect to be fixed by https://github.com/CityOfZion/neon-js/pull/818

**Comment by jseagrave21** [comment]
Is this issue resolved now?

**Comment by ixje** [comment]
from the linked PR it seems so
