### ISSUE TITLE
QR login to N3 results in Legacy address

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-wallet#2396]
**Wallet version or commit SHA:**
2.12.5

**Environment:**
Mac OS 12.1

**Prerequisites:**
A WIF private key saved as QR code

**Reproduction steps:**
1. Start Neon Wallet
2. Switch Login toggle to "N3"
3. Click on "Private" tab
4. Click on "Scan QR" button
5. Show QR code to camera

After the QR code is read and the wallet is logged in, Neon shows the N3 logo, but with a legacy address

**Screenshots/Video:**
https://www.dropbox.com/s/te2nutlep22r258/Screen%20Shot%202022-02-28%20at%202.00.02%20PM.png?dl=0

**Comment by hal0x2328** [comment]
A follow-up comment from the original reporting user: _I noticed another issue with the QR reader. It's not working properly with other functions either. Send and receive will not populate the fields. Looks like the only way right now is to manually enter the keys every single time._

**Comment by kinmya** [comment]
4 different QR codes with private key all show as invalid. "Invalid private key entered".

**Comment by kinmya** [comment]
Working as expected.  The private key QR scan resulted in expected result of N3 wallet labeled as such in the app.
