### ISSUE TITLE
Cannot recover N3 wallet using json file.

### ISSUE THREAD

**Issue by cypher619** [CityOfZion/neon-wallet#2397]
Just installed wallet version 2.12.6 after clean install of Windows 10.  When trying to recover my N3 wallet with json recovery file, I can select a file but nothing happens after that.  My json file was greated with an 2.10.0 of the wallet back on 11/05/21 when I did my N3 conversion.

**Comment by cypher619** [comment]
same issue as #2334 which has been closed due to inactivity.

**Comment by cypher619** [comment]
bump so it doesn't die due to inactivity

**Comment by cypher619** [comment]
bump so it doesn't die due to inactivity

**Comment by kinmya** [comment]
I don't have Windows 10 access, but this functioned as expected on mac version of app.
