### ISSUE TITLE
QR code reader not loading address codes

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-wallet#2402]
**Wallet version or commit SHA:**
2.12.7

**Environment:**
MacOS 12.1

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Log in
3. Click on "Send" tab
4. Click on "Enter QR code" button
5. Try to scan a QR code from the Neon Wallet Mobile app

The code does not get processed - the camera periodically attempts to take pictures but never successfully reads an address from the code.

**Comment by kinmya** [comment]
Scan of QR code on the desktop app successful when using it as the "RECIPIENT ADDRESS".  Not functional if the user sent a Receive QR Code from mobile wallet (utilizing the "Request Tokens" function).

**Comment by kinmya** [comment]
Request token function option now working as expected.  v1.0.29-2i
