### ISSUE TITLE
Use Dora as the default chain explorer instead of ancient Neoscan

### ISSUE THREAD

**Issue by gsmachado** [CityOfZion/neon-wallet#2404]
**Wallet version or commit SHA:**
2.12.7

**Environment:**
MacOS 12.3

**Prerequisites:**
None.

**Reproduction steps:**
1. Start Neon Wallet
2. "Log in" to your wallet, either a saved one or using Ledger -- it doesn't matter
3. On the top, where the address is shown, click on the address
4. A browser window should open pointing to the Neoscan explorer

The problem here is: Neoscan is ancient and should be replaced by Dora as the **default** chain explorer.

This is a super simple fix and should be done as soon as possible for usability.

**Comment by lllwvlvwlll** [comment]
This is most likely a result of user settings.  I am under the impression that new installations configure the default explorer to dora. @comountainclimber can you confirm this?

**Comment by kinmya** [comment]
Confirmed that it opens to https://dora.coz.io/address/neo3/mainnet/<address>/assets.
