### ISSUE TITLE
Wrong sha256sum for Neon.2.12.9.exe (Windows version)

### ISSUE THREAD

**Issue by zero-override** [CityOfZion/neon-wallet#2411]
**Wallet version or commit SHA:**
2.12.9

**Environment:**
Windows all

**Prerequisites:**
Download Neon.2.12.9.exe from https://neonwallet.com/

**Reproduction steps:**
Hashing Neon.2.12.9.exe with SHA256 gives 5B08C2B1199E49A535C5F6F781C74573E070BC23D3B7B41A9272B4ABE33DB66B

Description:
The SHA256 of Neon.2.12.9.exe (the windows version) is 5B08C2B1199E49A535C5F6F781C74573E070BC23D3B7B41A9272B4ABE33DB66B
and not the one from the release notes.
Also, the digital signatures in the "Digital Signatures" tab of the file's Properties window are unverified.

**Comment by comountainclimber** [comment]
@zero-override went ahead and updated the checksums thanks for opening the issue! FYI: automatic (OTA) updates always perform a checksum before applying the update from the github release page
