### ISSUE TITLE
Quickvote doesn't work any more

### ISSUE THREAD

**Issue by robme** [CityOfZion/neon-wallet#2415]
**Wallet version or commit SHA:**
2.12.9

**Environment:**
Windows 10 Pro (64 bit) Version 21H1 Build 19043.1826

**Prerequisites:**
None.

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Choose wallet and enter password and login
3. Visit https://quickvote.coz.io/ (I tried Firefox and Chrome)
4. Click "Connect Wallet"
5. In the window that opens click "Link wallet" under Deeplink or copy the URL and paste it under dApps -> Connect in Neon
6. Accept request in Neon
7. Go back to first browser tab, choose a candidate and click "Vote"
8. Go back to wallet and click the green tick in the Wallet Connect page

It then says "Transaction failed" and "An unkown error occurred please try again." (with that typo)

**Comment by robme** [comment]
Is this project abandoned?

**Comment by comountainclimber** [comment]
@robme no it is not! I am typically slow to respond (or dont respond at all) to support requests like these but I fixed the typo you mentioned - thanks for pointing that out. Quickvote is working fine in all of my testing as of version `v2.13.2` (the latest release)

**Comment by comountainclimber** [comment]
@robme does your address have a GAS balance?
