### ISSUE TITLE
Gas claim in activity tab is shown as 0 NEO transfer

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-wallet#2424]
**Wallet version or commit SHA:**
Version 2.12.11 (2.12.11.8902)

**Environment:**
OSX

**Reproduction steps:**
1. claim gas in the `wallet` tab
2. look at the entry in the `activity` tab

The activity tab seems to be able to identify "vote" and "transfer" events, but not a gas claim event. This is probably because a claim action creates a transaction with 2 notifications
1. a 0 neo transfer from self to self (which is what the activity row shows)
2. a `x` GAS transfer from `null` to self

We know the exact conditions for a "claim" event, so I think we should identify this and show the amount claimed with a "claim" type instead of what we have now.

**Comment by jseagrave21** [comment]
@ixje I would like to work on this but I have not been able to install neon-wallet using WSL. Do you have any tips? If I can get neon-wallet installed, I think I could resolve this issue.

**Comment by jseagrave21** [comment]
Can this be closed?
