### ISSUE TITLE
Let users set their own JSON-RPC nodes

### ISSUE THREAD

**Issue by gsmachado** [CityOfZion/neon-wallet#2433]
Please, I **urge** the team to implement a feature that users could select their own JSON-RPC nodes for, at least, sending signed transactions.

🙏 🙏 🙏 🙏 🙏 🙏 🙏 

**Wallet version or commit SHA:**
2.14.1

**Environment:**
All

**Comment by lllwvlvwlll** [comment]
We are implementing custom network support and can add this as a requirement.

**Comment by gsmachado** [comment]
Are you planning to add this feature? Please. 🙏
