### ISSUE TITLE
Walletconnect: signing of nns domain registration tx fails with insufficient GAS error albeit enough GAS in wallet

### ISSUE THREAD

**Issue by fabwa** [CityOfZion/neon-wallet#2434]
**Wallet version or commit SHA:**
Neon.2.14.1

**Environment:**
OSX m1

**Prerequisites:**
clean install

**Reproduction steps:**
Tried to register a NNS domain via wallet connect on https://neo.link/. Had enough GAS in my wallet. Confirmed signing -> endless spinner & error message in Neon console:

Worked OK with neoline

Uncaught (in promise) CancellationError: Polling was actively cancelled
    at t (bundle.js:88:31039)
bundle.js:37 Uncaught (in promise) Error: Failed to get system fee. Error: Script execution failed. ExecutionEngine state = FAULT. Insufficient GAS.
    at l (bundle.js:37:286820)
    at async Object.c [as addFees] (bundle.js:37:287167)

**Comment by comountainclimber** [comment]
Thanks for reporting @fabwa we will look into this
