### ISSUE TITLE
Neon hangs on Send

### ISSUE THREAD

**Issue by trancephorm** [CityOfZion/neon-wallet#2438]
**Wallet version or commit SHA:**
2.14.1

**Environment:**
Ubuntu Linux 20.04 64bit

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on Send button

After clicking on "Send" button, wallet hangs displaying that progress animation which never ends. Was able to exit Neon, now I can't even do that after resizing its window

**Comment by hal0x2328** [comment]
For the devs: another user in Discord is experiencing the same behavior on EndeavourOS Artemis Nova 22.9 (an Arch Linux derivative).

**Comment by comountainclimber** [comment]
I am not able to reproduce this on Ubuntu Linux 20.04 64bit - was able to perform sends on both n3 and legacy chains. Are you still having this problem @trancephorm ??

**Comment by trancephorm** [comment]
To be completely honest, I already switched to O3, functioning wallet was urgent for me. Gotta say I got no time to look back now.

**Comment by comountainclimber** [comment]
Ok thanks @trancephorm

**Comment by nipponski** [comment]
I reported it in discord. I've tried with arch and later even with debian and still stops when I press send. I wonder if it might be something with the computer im using AMD ryzen 5 5500 with radeon graphics, Lenovo IdeaPad Flex 5 Endeavour OS (arch) with KDE plasma. Sadly im gonna have to use windows for Neon wallet for now :( 
The last version that was working was 2.12.11
