### ISSUE TITLE
Can't access Legacy Neo anymore on Ledger hardware wallet.

### ISSUE THREAD

**Issue by trancephorm** [CityOfZion/neon-wallet#2440]
No matter if I push Legacy option at login, and choose Ledger, request to navigate to NEO3 app on device is displayed.
Ubuntu Linux 20.04.

**Comment by comountainclimber** [comment]
thanks @trancephorm will take a look at this shortly 👀

**Comment by comountainclimber** [comment]
I am not able to reproduce this issue @trancephorm are you sure you have both applications installed on your ledger device (there is an app for legacy and one for n3)?
