### ISSUE TITLE
Suggestion, it's kinda essential

### ISSUE THREAD

**Issue by trancephorm** [CityOfZion/neon-wallet#2465]
Please make Neon informative about the version that is currently installed. You just cannot find version from the interface. It's basic and it's so frustrating.

**Comment by fabwa** [comment]
<img width="576" alt="Screenshot 2023-02-02 at 09 33 51" src="https://user-images.githubusercontent.com/7439206/216272652-7cf76b7b-05a6-451e-af5d-95fe90838add.png">
