### ISSUE TITLE
Improvements to neonwallet.com

### ISSUE THREAD

**Issue by Ejhfast** [CityOfZion/neon-wallet#247]
Can edit the website source in this: https://github.com/CityOfZion/neon-wallet/blob/dev/docs/index.html

Would be great to have the page looking nicer

**Comment by comountainclimber** [comment]
I would be interested in taking this on... Do you have a mock up or some more content you would like to see here?

**Comment by Ejhfast** [comment]
No mockup, something more in line with the cityofzion.io website would be great. You can check out the `website` repo in this org for more assets

**Comment by comountainclimber** [comment]
Thanks @Ejhfast will be submitting PR in next day or two...

**Comment by comountainclimber** [comment]
How do you guys feel about this? 
![mobile portrait](https://user-images.githubusercontent.com/13072035/32017485-1b895f3e-b984-11e7-80eb-e906138f9f3b.png)

**Comment by comountainclimber** [comment]
(mobile will be very similar just stacked layout)

**Comment by comountainclimber** [comment]
Wrapping up the final touches on the new site will be submitting a PR later this afternoon. Looks identical to the mockup above 👯

**Comment by Ejhfast** [comment]
@comountainclimber looks great!

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/pull/286
