### ISSUE TITLE
Discussion: Vote from Neon Wallet

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neon-wallet#2475]
BLUF: I would like to implement voting from Neon Wallet directly. 

Background: We are now able to see our voting status since [this PR](https://github.com/CityOfZion/neon-wallet/pull/2471)  has merged. If a user saw there was a problem with their voting status, they need to open a browser and figure out how to cast a vote (e.g. using Wallet Connect and COZ Quickvote).

Implementation: I think voting from Neon Wallet would look and function much like COZ Quickvote. Votes would be cast from the settings page which is accessible already from the Network Tooltip.

Alternative perspective: I could understand if we want to limit the number of features on Neon since it is a light wallet and want users to get comfortable using Wallet Connect.

Conclusion: I would like to discuss this idea and see if there is support for it before I worked on it.

**Comment by comountainclimber** [comment]
My thoughts are that the user experience of voting via wallet connect is pretty smooth and straight forward, that being said I do think it would benefit users to have a direct link to quickvote (or an equivalent dApp) from within Neon - perhaps from that tooltip you recently worked on?

**Comment by jseagrave21** [comment]
> My thoughts are that the user experience of voting via wallet connect is pretty smooth and straight forward, that being said I do think it would benefit users to have a direct link to quickvote (or an equivalent dApp) from within Neon - perhaps from that tooltip you recently worked on?

@comountainclimber Great idea! I think that is a better implementation and still achieves an easy, intuitive method to vote after seeing your vote status.

**Comment by jseagrave21** [comment]
Up

**Comment by jseagrave21** [comment]
I'm still working on this. Haven't had time to iron out the final version yet.

**Comment by jseagrave21** [comment]
Up
