### ISSUE TITLE
Infinite Scroll on Activity Page Broken

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neon-wallet#2476]
**Wallet version or commit SHA:**
2.17 dev

**Environment:**
Linux Mint 21.1 Cinnamon

**Prerequisites:**
None.

**Reproduction steps:**
1. Click on the Activity Page
2. Scroll to the bottom

Additional transactions are not loaded.

**Comment by comountainclimber** [comment]
Thanks and excellent catch @jseagrave21 ! I believe this is due to the bump to React 18 🤔  should be fixed in the PR linked
