### ISSUE TITLE
Fix ToolTip Persistence

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neon-wallet#2482]
**Wallet version or commit SHA:**
v2.17.1

**Environment:**
Windows 10 and Linux Mint 21.1 Cinnamon

**Prerequisites:**
None

**Reproduction steps:**
1. Mouse over the `LogoWithTooltipAndBlockHeight`
2. Try to click on the `Update Settings` button on the bottom of the Tooltip

**Description of Problem**
Most of the time the Tooltip vanishes before I can select the button. Sometimes, the Tooltip persists when I mouse over it and I can push the button but this is inconsistent.

I think that we should make the Tooltip persist if the mouse enters it and then vanish when the mouse leaves it. Right now, it seems like the Tooltip is only visible if the mouse is over the `LogoWithTooltipAndBlockHeight`.

**Screenshots/Video:**
N/A

**Comment by jseagrave21** [comment]
@comountainclimber Based on the Tooltip being `interactive`, I feel like it should not vanish when I mouse over it. The `DashboardButton` from `DapiStatus` works as intended but I am not sure the exact reason why it works and the Tooltip doesn't. I can see that the `DashboardButton` uses a `Tippy` element instead of our `Tooltip` const. When I tried to replace the `Tooltip` element with a `Tippy` element, I broke it.

**Comment by comountainclimber** [comment]
@jseagrave21 is it possible that is OS dependent? I am not able to reproduce the issue on MacOS =>
![Kapture 2023-04-06 at 08 12 51](https://user-images.githubusercontent.com/13072035/230404016-b89d1a26-daed-4d6a-8c16-0a0968e84315.gif)

**Comment by jseagrave21** [comment]
@comountainclimber I thought the same thing as a possibility but I run into the same issue on Windows and my Linux VirtualBox.

Also, like I said, the Dashboard button for DapiStatus works perfectly and it is a slightly different implementation.

**Comment by comountainclimber** [comment]
Weird I can look into it, thanks for creating this issue

**Comment by jseagrave21** [comment]
Up

**Comment by jseagrave21** [comment]
Up

**Comment by jseagrave21** [comment]
Up

**Comment by jseagrave21** [comment]
@comountainclimber this issue seems to have resolved itself in the most recent version of neon wallet (2.21.3).  I am still working from the same version of Windows 10 and have updated to the most recent version of Linux Mint.  The persistence behaves normally now.
