### ISSUE TITLE
Cannot join Neo smart economy - where can I get help

### ISSUE THREAD

**Issue by heidiac** [CityOfZion/neon-wallet#249]
Hi, I have not received coins to my NEON wallet. You say below to go to the NEO smart economy slack to get support for this but I cannot join  as it says the invite limit has been reached. Please can you tell me how I can get support for this as I am going round in circles. thanks, Heidi

**Comment by canesin** [comment]
[click here](https://join.slack.com/t/neosmarteconomy/shared_invite/enQtMjU4NDAwNTIwNjQ0LTI1MjViNDBmZjJkODhjNTJmNjM1OGQ4MDI3NTMzYjUzZjg4ZGNhMDA4NjIyMTBhZDAwNjMyYzY2MzM2MjI5ZDI)
