### ISSUE TITLE
[Bug] Contacts file corruption causes network request loop

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-wallet#2496]
**Wallet version or commit SHA:**
2.17.4

**Environment:**
Mac OS 13.4

**Prerequisites:**
Corrupt/zero-byte contacts file

**Reproduction steps:**
1. Truncate n3AddressBook.json to zero bytes
2. Start Neon Wallet
3. Click on "Send"

The send tab doesn't complete loading, it just shows the spinner. In the network tab in the
developer tools console, requests to the RPC node and to the Github `latest` API are 
looping over and over, with dozens of connections per second.

**Comment by comountainclimber** [comment]
Thanks @hal0x2328 taking a look at this one this week 👍
