### ISSUE TITLE
Wrong sha256 Neon.2.17.4.arm64.dmg

### ISSUE THREAD

**Issue by ncsolar** [CityOfZion/neon-wallet#2497]
Wallet version or commit SHA:
Neon Wallet 2.17.4

Environment:
MAC

Prerequisites:
Download Neon.2.17.4.arm64.dmg from https://github.com/CityOfZion/neon-wallet/releases/tag/v2.17.4

Reproduction steps:
Hashing Neon.2.17.4.arm64.dmg with SHA256 gives:
c571993f8914407d8ce643b70c9aa3b666374660394095cc20febe55aff6e3c5

Description:
The SHA256 of Neon.2.17.4.arm64.dmg is c571993f8914407d8ce643b70c9aa3b666374660394095cc20febe55aff6e3c5
and not the one from the release notes.

**Comment by comountainclimber** [comment]
Thanks @ncsolar 🙏 keep in mind that the integrity of each release is verified via the `latest` files and no OTA update will occur without this check, I manually add the part in the release notes and sometimes make mistakes
