### ISSUE TITLE
Can't send NEO and GAS in NEO Legacy mode.

### ISSUE THREAD

**Issue by tamvm** [CityOfZion/neon-wallet#2500]
Can't send NEO and GAS in NEO Legacy mode with this error: Error: Cannot read properties of undefined (reading 'network')

**Wallet version or commit SHA:**
Version 2.17.4 (2.17.4.9310)

**Environment:**
Mac OS version 12.3.1 (21E258)

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
1. Start Neon Wallet
2. Use NEO Legacy, connect with ledger
3. Click on "Send"
4. Enter receiving address and amount, Submit

It will show the error: "OOPS! SOMETHING WENT WRONG...
Error: Cannot read properties of undefined (reading 'network')
"

**Screenshots/Video:**
My address: https://dora.coz.io/address/neo2/mainnet/AXBQFemRrGtEMVhGwPTjHrQTZSuhZEbwoQ/assets
![image](https://github.com/CityOfZion/neon-wallet/assets/344684/671db00a-0ae8-448a-b81a-15658dfaa9df)

**Comment by comountainclimber** [comment]
@tamvm thank you for reporting this issue, I was able to reproduce by logging into an N3 account and then logging into a legacy address... Things work fine if I "just" log into one or the other. I will definitely prioritize fixing this ASAP thanks again 🙏
