### ISSUE TITLE
The SHA256 hash provided for "Neon.2.17.4.exe" is the hash for "Neon.2.17.3.exe"

### ISSUE THREAD

**Issue by sempiterna** [CityOfZion/neon-wallet#2504]
The SHA256 hash provided (54d0ac6fa630f19776a98cf946a57476f00a30a919aa87dee92fbe5a2decdcc9) for "Neon.2.17.4.exe" is the hash for "Neon.2.17.3.exe". The actual hash for the Neon.2.17.4.exe i downloaded is "8856e14f8e8d1d80a00c19ed62801f33234211ea90a53f9a31aa5e142f6c97d6". Is this correct?

**Comment by comountainclimber** [comment]
`8856e14f8e8d1d80a00c19ed62801f33234211ea90a53f9a31aa5e142f6c97d6` is the correct hash for `Neon.2.17.4.exe` I will go ahead and update it, keep in mind the release notes are manually created (by me) and sometimes have errors but the `*.yml` files containing the hashes for each build are generated at build time and will always contain the correct checksums

**Comment by comountainclimber** [comment]
Thank you for reporting this @sempiterna !
