### ISSUE TITLE
Legacy Wallet not Showing Balance and not Allowing Transactions

### ISSUE THREAD

**Issue by gdatavalley** [CityOfZion/neon-wallet#2519]
**Wallet version or commit SHA:**
v2.19.2

**Environment:**
Windows 11 Pro

**Prerequisites:**
Don't have any custom tokens added before running the wallet

**Reproduction steps:**
1. Start Neon Legacy Wallet
2. Go on receive Tab
3. Send NEO or GAS tokens

Balance not displayed and not possible to make any transaction. Activity section works correctly displaying transaction, same as dora.coz.io. After I knew about the legacy wallet migration, I tried to send GAS to N3 wallet and worked correctly. 
Also it's not possible to migrate funds from Legacy to N3 wallet. 
I already went on discord, it seems to be a known issue, posting here for anyone having the same problem and struggling to find a solution

**Screenshots/Video:**
![image](https://github.com/CityOfZion/neon-wallet/assets/56619675/0966c2c9-4e96-42a8-aa39-044c12fd2248)
![image](https://github.com/CityOfZion/neon-wallet/assets/56619675/dd4eb347-8ac2-400d-b7db-f9685664937a)

**Comment by comountainclimber** [comment]
This should now be resolved 👍
