### ISSUE TITLE
Multiple sends

### ISSUE THREAD

**Issue by canesin** [CityOfZion/neon-wallet#253]
In neo-gui is possible to add many transactions to a list before sending the tx.
The UX I envision is a one where you create a "multiple recipents" transaction by clicking a "+add" button instead of the "send", and it adds the transaction to the transaction list. that appears collapsed above the QR-Code of the address.
After the user finishes adding the transactions he can click on the send button by the side of it.

That combined with #9 would make really easy to send to many destinations quickly and reliably, like when we need to send weekly rewards.

**Comment by evgenyboxer** [comment]
I’ll do it!

**Comment by canesin** [comment]
@evgenyboxer my idea of UX/UI:

![image](https://user-images.githubusercontent.com/353648/31804833-3896f3ce-b52a-11e7-889c-37eca75e6318.png)

**Comment by mhuggins** [comment]
I don't mind taking this on if no one has started on it.  I think it could be done more easily with the new UX.  I may just need help on the back-end portion with how to include multiple addresses when actually creating the transaction.
