### ISSUE TITLE
Not possible to connect Ledger device on 2.21.1

### ISSUE THREAD

**Issue by gsmachado** [CityOfZion/neon-wallet#2537]
**Wallet version or commit SHA:**
2.21.1

**Environment:**
MacOS 13.4

**Prerequisites:**
No pre-requisite.

**Reproduction steps:**
e.g.:
1. Connect your Ledger Wallet
2. Unlock the Ledger
3. Go to the NeoN3 ledger app
4. Start Neon Wallet
5. Click on "Ledger" tab

Then, what I observe is that Neon cannot detect the Ledger whatsoever. The "Connect and unlock your Ledger device..." keeps spinning, forever.

I tried to restart my laptop, I tried to disconnect the Ledger (USB), I tried to close the Neon Wallet, etc etc. Nothing solved.

Unfortunately, I can't use the Ledger with this new version of Neon Wallet -- I know it was working until 2.19.

**Comment by SRD75** [comment]
Same problem with Neon Wallet 2.21.1 on Windows.

For both Neo Legacy & Neo N3, there is a message `Connect and unlock your Ledger device`.

The Ledger is connected to the laptop, unlocked, and the Neo Legacy or Neo N3 app loaded, but the `Connect and unlock your Ledger device` message never disappears and the wallet can never be opened.

**Comment by SRD75** [comment]
NEO Legacy & NEO N3 wallets are now working with Neon Wallet v2.23.10.
