### ISSUE TITLE
Legacy claimable GAS not available to interface

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-wallet#2556]
**Wallet version or commit SHA:**
2.21.3

**Environment:**
All

**Prerequisites:**
Have claimable legacy GAS

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Log in to wallet with claimable GAS
3. Notice the claim button is greyed out and the claimable amount is 0.00000000

I did some diagnosis and it looks like Neon is trying to use an N3 endpoint name to check for claimable GAS on a legacy node, so it returns "method not found"

The cause seems to be that the check for `chain === 'neo2'` in `actions/claimsActions.js` is failing because `chain` is undefined, so it falls through to the N3 RPC call.

I suspect this might have broken when the code was modified to allow for addition of custom networks but I can't pinpoint exactly where.

**Comment by taycaldwell** [comment]
Running into this same issue. Is there a known workaround or version that allows to claim GAS?

**Comment by jseagrave21** [comment]
@lllwvlvwlll was this fixed with https://github.com/CityOfZion/neon-wallet/pull/2557?

**Comment by lllwvlvwlll** [comment]
I believe so. @melanke @thiagocbalducci
