### ISSUE TITLE
Neon Wallet Mac Update 2023 

### ISSUE THREAD

**Issue by ghost** [CityOfZion/neon-wallet#2577]
Wallet Version 2.20 

Mac OS Ventura 13.5.2 

The newest Neon Wallet dmg won't install and is flagged as malware during install.

**Comment by ggbsnowbird** [comment]
Also on Catalina. Seems common to all recent MacOS versions

**Comment by thiagocbalducci** [comment]
Hi! Sorry for this inconvenience.

Our team is working on resolving this asap, we will update this ticket once it has been normalized

**Comment by ghost** [comment]
Another issue I'm experiencing is after a transaction completes, the wallet UI will randomly freeze up and become unresponsive to commands. This means restarting the wallet.

**Comment by ghost** [comment]
I have had a transaction fail and have lost NEO. Does anyone know who I can contact at NEON Wallet to get this resolved urgently?
