### ISSUE TITLE
Neon wallet shows Zero suddenly 

### ISSUE THREAD

**Issue by celiachua** [CityOfZion/neon-wallet#258]
Hi,
Today, my wallet shows a balance of "zero" suddenly and the block is not at its latest block. Do i download a new Neon wallet or what?

Not sure if this is the right place to feedback my issues. Any help is deeply appreciated. Thanks.

Best

**Comment by sweeney-jo** [comment]
I'm having same issue, very unsettling :(

**Comment by pistofo** [comment]
Oh just posted the same issue. Hopefully it will get back to normal.

**Comment by cllonps** [comment]
me the same... WHERE are my NEOs??

**Comment by cllonps** [comment]
Who can help us ?

**Comment by cllonps** [comment]
ok - in my Wallet they are back  -hope your NEOS are back too!?

**Comment by pistofo** [comment]
Yeah it's back in mine too! pheww..

**Comment by celiachua** [comment]
Phew..... yeah back in mine too.....

**Comment by AshRolls** [comment]
The API was down, fixed now.
