### ISSUE TITLE
NEO Gas Transaction failed & not showing the right balance

### ISSUE THREAD

**Issue by Evsamsterdam** [CityOfZion/neon-wallet#259]
Today I wanted to claim my gas, but the transaction keeps failing. 
Also I sent NEO to my NEO wallet (I have version) Windows.Neon.0.0.6) but, the NEO wallet doesn't show the right balance. 
The wallet doesn't add up the coins I sent today to the NEON wallet. 
If I check the NEO blockchain (for example here: https://neotracker.io), than the right balance shows up.
I have tried to join the slack community but I can't join because the maximum number of users is reached. 

Can you help me with my issue?

**Comment by Evsamsterdam** [comment]
I now was able to join the slack community and I see that more people have the same problem as I have.
There is still no solution...

**Comment by AshRolls** [comment]
The API was down earlier, now back up. Please use slack for support, GitHub is for code issues.
