### ISSUE TITLE
Transaction failed with version 0.0.6

### ISSUE THREAD

**Issue by ansolution** [CityOfZion/neon-wallet#260]
Hi,

With 0.0.6 i can no longer claim gas. when trying to my neo is sent to myself (as i can check in the blockchain).
Restarted my computer dozens of times but a message in red stating gas claim failed, no matter how many times i tried.
heres a transaction that failed 

Please write back. 

Hope to hear from you asap.

![transaction failed 0 0 6](https://user-images.githubusercontent.com/32958452/31821479-faab14e2-b5f0-11e7-98d9-639f9854d11a.jpg)

**Comment by AshRolls** [comment]
The Neon Api is currently down. We are working on it and should be back up soon. Please use slack #support channel for help, GitHub is for code issues only.
