### ISSUE TITLE
Runs Heavy Even After Closing - Have to Kill in Task Manager

### ISSUE THREAD

**Issue by ladle3000** [CityOfZion/neon-wallet#2609]
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
2.23.10

**Environment:**
Windows 11

**Prerequisites:**
Not aware of any.

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Close Neon Wallet
3. Computer fan runs hard
4. Look in task manager and multiple neon instances still run
5. Post to Discord
6. Other users say "hey, I've noticed that too"
7. Decide to post to Github
8. Hope that they will not try to get you into believing it's just your system, since others confirmed the same

some description (for ex. what happens after completing reproduction steps), e.g.:
After closing neon, it still runs in task manager.  It is possible that it could be from making a deep link with ndapp.org while the wallet is already opened.

**Screenshots/Video:**
If you need them I'll provide them.

**Comment by jseagrave21** [comment]
I cannot repeat this in Windows 10 or Linux.  Not sure if Windows 11 is the problem?

**Comment by ladle3000** [comment]
I don't have any 10 devices left to check on. I'll try to get more exact
reproduction. Maybe I'm missing something.
