### ISSUE TITLE
Add Ledger Nano S support

### ISSUE THREAD

**Issue by canesin** [CityOfZion/neon-wallet#262]
This is a meta issue to reflect the need so we can create a proper milestone.

**Comment by m-roberts** [comment]
Does this qualify as closing this issue?
https://github.com/CityOfZion/neon-wallet/pull/244

This has a 0.0.8 milestone but if this functionality is working, it would be great to see a new release for this - this is huge!

**Comment by Satoshinaire** [comment]
I don't think it's complete. Still a little unpolished. Weird error messages and awkward method to retry depending on state of Ledger, etc.
