### ISSUE TITLE
Missing funds

### ISSUE THREAD

**Issue by hysel** [CityOfZion/neon-wallet#263]
Hi

I transferred some GAS funds from Binance

the transactions was good and i got a TXID but I am not able to see the funds in the my NEON wallet.

I look my wallet information and it does say i have 2.02 GAS unites but my actual wallet shows 0.5

Wallet Status https://neotracker.io/address/AahEC4vkkxQDE3wpE8vEcLpzUUBxpwMPbL 

screenshot of my wallet

![image](https://user-images.githubusercontent.com/32962979/31829824-67488aae-b58c-11e7-85cd-965cc4ccbc08.png)

Thanks in advance

Itamar

**Comment by AshRolls** [comment]
The Neon wallet API is currently down. Please join slack #support for help, GitHub is intended for code issues only.
