### ISSUE TITLE
Neon Wallet - Transaction Failed

### ISSUE THREAD

**Issue by eidithebaby** [CityOfZion/neon-wallet#264]
Neon Wallet Won't do any transactions. Red error message on top saying Transaction Failed. Neo are still in wallet, Gas is accumulating but it cannot be sent nor claimed. 

![error neon wallet](https://user-images.githubusercontent.com/30663996/31834580-1a8a4252-b5d7-11e7-8c12-4fe5d510c347.jpeg)

**Comment by evgenyboxer** [comment]
If you restart the wallet it works?
Need some more info to reproduce this error.

**Comment by Ejhfast** [comment]
@eidithebaby can try again now and confirm this issue was fixed with the latest db update?

**Comment by eidithebaby** [comment]
Hello, 
All is good, thank you!
