### ISSUE TITLE
I have 200 neo coins on a mac lap top and 456 neo coins on mac desk top. There are not there now. Where are they?

### ISSUE THREAD

**Issue by jerrywayne55** [CityOfZion/neon-wallet#268]

**Comment by Ejhfast** [comment]
They are still there -- the DB is having problems retrieving balance. It will be back up in a few minutes

**Comment by Ejhfast** [comment]
Your coins live on the blockchain, not in Neon wallet. There is not risk to your funds if the DB goes down, it is just retrieving public information

**Comment by sgarciafer** [comment]
Same issue here. Neo not showing on the wallet, but are there on the blockchain. Hope it will be fixed soon :)

**Comment by jerrywayne55** [comment]
Thank you so much. I downloaded the new version of Neon 0.0.6 and it seems to work. I’ll take a deep breath. You have saved my Sunday :)

**Comment by BeteVersion** [comment]
I am having the same issue.  I have upgraded to 0.06 and still no coins can you please confirm.

**Comment by Ejhfast** [comment]
We are still waiting on our DB provider to fix the problem -- should be
back up in a few minutes

**Comment by BeteVersion** [comment]
Thank you, just a quick update, I can see the coins from yesterday now, but the coins i transferred a few hours ago from Bittrex are still not showing 

Please do let me know it is fine so I can breathe a sigh of relife and I wont disturb for a few hours lollzz

**Comment by Ejhfast** [comment]
It is fine -- just wait a few minutes for the DB to update. There is never
any risk to your coins regardless of whether the DB is up or not

We are paying the DB provider even more money, so hopefully this happens
less often

**Comment by BeteVersion** [comment]
Problem resolved.   Thank you so much for such fast replies and support.

**Comment by jerrywayne55** [comment]
What is DB? Sorry for being so ignorant about all the new terms. I’m an old guy :)

**Comment by Satoshinaire** [comment]
@jerrywayne55 DB = Database

**Comment by jerrywayne55** [comment]
Thanks. When you are old like me just need a bit of help.
