### ISSUE TITLE
On 'Reload' user is logged out w/ no UI feedback

### ISSUE THREAD

**Issue by golivera** [CityOfZion/neon-wallet#27]
When you are logged into the wallet and you `Reload` the wallet then you get logged out of your account.

The transaction history is wiped and there is no balance.

Possible Improvements
- Redirect back to the login screen
- Show user logout message

![screen shot 2017-08-02 at 3 22 42 pm](https://user-images.githubusercontent.com/1169005/28897640-77f586ec-7796-11e7-88f7-61b9bd6ef539.png)

**Comment by Ejhfast** [comment]
@golivera can you give more steps to replicate? what is "reload"? the refresh button? is this version 0.0.3?

**Comment by golivera** [comment]
MacOSX
V 0.0.3

The `reload` is the native electron reload that you can see under `View > Reload`? On Mac it is `command+r`.
