### ISSUE TITLE
Warn user when address being sent to has no transaction history

### ISSUE THREAD

**Issue by Ejhfast** [CityOfZion/neon-wallet#271]
ARK addresses apparently use exactly the same naming conventions as NEO addresses, so even with all the other checks, this would still be helpful for preventing users from hurting themselves

**Comment by evgenyboxer** [comment]
Should this be first implemented in Neon-JS? How do you check for this right now?

**Comment by Ejhfast** [comment]
Not neon-js, as this is more a UI feature. Just look up transaction history
of address being sent to, if it is empty, display warning. neon-js will
allow you to do that API call to lookup

**Comment by evgenyboxer** [comment]
Right okay!
In terms of the UX of this - How do you imagine the warning to look like? Do you think it should be a sticky message at the top (one you hit "send"), or it should be displayed next to the "confirm pane" button we have?

Also, unrelated - but I would like to rework the "confirmation button" with a small confirmation modal. (Once you hit send and its valid -> I open the confirmation modal -> Repeating all the send info + the warning mentioned above for empty history)

**Comment by Ejhfast** [comment]
Yeah, maybe if we rework the confirmation we can build the warning into
that? I like the modal idea

**Comment by evgenyboxer** [comment]
Yep. sounds great! I'll work on this.

**Comment by dvdschwrtz** [comment]
closing this issue as it has been merged to dev
