### ISSUE TITLE
Close Key Combination

### ISSUE THREAD

**Issue by stevesbrain** [CityOfZion/neon-wallet#272]
Is it possible to implement a key combination to close the window/terminate the process? I use a tiling window manager, and it doesn't have any built in "X's" to close the software. The normal Ctrl+X, Ctrl+W, Ctrl+Q, and Alt+F4 don't shut it down - so would be great to have this as an implemented option, if at all possible :)

**Comment by evgenyboxer** [comment]
Strange, it should work... I just tested (on a Mac) - Command+Q and it closed the app.

**Comment by stevesbrain** [comment]
Hmm, very strange. I've tried Ctrl+Q and Alt+Q with no luck. Anyone else have a linux box and can confirm/deny the key combo works for them?

**Comment by mhuggins** [comment]
Cmd+Q works for me on Mac, but I don't have a Windows box to test again.

**Comment by shawnmclean** [comment]
Alt+F4 works on windows too.

This seems like an issue specific to your environment. Until someone else can reproduce, closing this.
