### ISSUE TITLE
Claim button does not reset between account switch

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-wallet#2726]
**Wallet version or commit SHA:**
2.23.13

**Environment:**
Mac OS Sonoma 14.4.1 Intel

**Prerequisites:**
Have two accounts with claimable GAS and enough GAS balance to pay fee

**Reproduction steps:**
1. Start Neon Wallet
2. Log in to first account
3. Click on "Claim GAS" button
4. See "Claim GAS" button become disabled
5. Log out and log back in to second account

At this point you can see that the "Claim GAS" button is still disabled even though all conditions for a claim are met.

**Screenshots/Video:**
<img width="523" alt="Screenshot_2024-05-13_at_08 20 01" src="https://github.com/CityOfZion/neon-wallet/assets/31932411/04ad260e-78bb-4798-be42-da72bd22541c">

**Comment by jseagrave21** [comment]
@hal0x2328 Does it matter if you are in legacy vs N3?

**Comment by hal0x2328** [comment]
I don't have any claimable GAS left in legacy to test with unfortunately
