### ISSUE TITLE
Can't claim gas in NEON wallet

### ISSUE THREAD

**Issue by BeteVersion** [CityOfZion/neon-wallet#282]
Hi, 

I cannot seem to claim gas in NEON wallet, I can see it accumulating, but when I try to claim it nothing happens. 

Could you please advise. 

Thanks

**Comment by Satoshinaire** [comment]
This question is more suitable for the #support channel in the NEO Slack, please go there and ask for assistance.

GitHub issues are intended for managing development tasks.
