### ISSUE TITLE
Missing Neo

### ISSUE THREAD

**Issue by mimicortez** [CityOfZion/neon-wallet#283]
When we accessed to the Neo Wallet, our neo balance showed zero. Please help me what is going on.

**Comment by Satoshinaire** [comment]
@mimicortez Please see the #support channel on the Neo Slack for technical support. GitHub issues are intended to track development tasks.

If you're using the Neon wallet, the API is currently experiencing issues. Check your address on a blockchain explorer such as neoscan.io or neotracker.io for peace of mind.

**Comment by Matov13** [comment]
I am having the same issue. My neonwallet showing ZERO

**Comment by Satoshinaire** [comment]
@Matov13 See my reply above.

**Comment by Matov13** [comment]
thank you
