### ISSUE TITLE
Shouldn't Ledger always give the same public key?

### ISSUE THREAD

**Issue by Satoshinaire** [CityOfZion/neon-wallet#284]
I had a go at implementing the new Ledger stuff into my cli light wallet, and so far it's returning a public key which I can derive the address from. 

However, I was surprised to find the address different to the one I had when I built the current dev branch of Neon Wallet.

I guess this means the public key is different? But surely this shouldn't be the case? 

Any tips?

**Comment by Ejhfast** [comment]
We resolved this issue in the slack. @Satoshinaire was using an unencoded public key, when neon-js required an encoded public key. 

neon-js supports loading from unencoded public key's in https://github.com/CityOfZion/neon-js/commit/fe464751167160c1ce1cdb4052e6ce8574549cb4
