### ISSUE TITLE
gas claim failed with 0.0.6 mac wallet 

### ISSUE THREAD

**Issue by morek84** [CityOfZion/neon-wallet#292]
Hi,
I know some people had this problem before but I think it might came back. I'm having troubles calming my GAS. I was using the 0.0.5 version (had it) so i just upgraded to 0.0.6 and still have the exact same problem : 

![screen shot 2017-10-31 at 13 54 20](https://user-images.githubusercontent.com/33258132/32228062-1e82f6d0-be45-11e7-8baa-3989a62949ea.png)

Any idea why?

**Comment by evgenyboxer** [comment]
We are working on better notifications relating to this issue/connectivity. The message you see could be caused by multiple factors.

**Comment by webofunni** [comment]
I am facing similar issue on version 0.0.7. Tried multiple times for several days and looks like the GAS is stuck

**Comment by gpascualg** [comment]
Same here! Used to be able to claim on 0.0.5 but on 0.0.7 I'm just getting "claim failed" errors. I've tried all 3 explorers (neotracker, neoscan and antchain) and no difference at all.

All I can see are transactions with 0neo value, but no claim at all on the explorers.

Any idea what can be going on?

**Comment by DURK** [comment]
Same issue here, on version 0.0.7 (Mac).
Just like @gpascualg said, you only transactions with 0 NEO value and no claim.

**Comment by DURK** [comment]
In my case, upgrading to 0.0.8 (Mac) solved it!
