### ISSUE TITLE
Update node-sass version for node 8 support

### ISSUE THREAD

**Issue by sgehrman** [CityOfZion/neon-wallet#296]
$yarn assets fails on node 8.9

update to the latest, that fixes it.

    "node-sass": "^4.5.3",

Actually many of the packages are old, is there a reason they haven't been updated?

I use ncu -a tool to update everything.

Should I do a PR?  I might want to start contributing to this.  Should I clean things up and PR?

**Comment by evgenyboxer** [comment]
Yes, you are welcome to make a PR with the npm updates.

The reason why they were not updated is because we are busy refactoring/building features :)

**Comment by evgenyboxer** [comment]
Thank you! We will review this.

I also sent a PR to clean the packages - https://github.com/CityOfZion/neon-wallet/pull/303
It was time for some tech debt :)
