### ISSUE TITLE
Hey, someone please help me. I transferred neo from exchange into my NEON wallet and it has been more than 48 hours and neo still now showing in NEON wallet. I can locate them on neo tracker. I have got the latest version of NEOn wallet 0.0.4 for MAC. I tried joining the Neo smart Economy Slack but it says limit reach for invite. 

### ISSUE THREAD

**Issue by bsareen** [CityOfZion/neon-wallet#301]

**Comment by Satoshinaire** [comment]
@bsareen I'm unsure why you can't join the Slack, but 0.0.4 is _not_ the latest version of Neon, please update to the current version, 0.0.6

You can download the latest version here: https://github.com/CityOfZion/neon-wallet/releases

**Comment by bsareen** [comment]
Thank you that worked


________________________________
