### ISSUE TITLE
Transaction Failed

### ISSUE THREAD

**Issue by cryptomd** [CityOfZion/neon-wallet#306]
Hello, i tried going to support slack but it wouldnt let me join for some reason. 
My Neon wallet will not allow me to send Neo to an exchange.  Keep getting "transaction failed' message.  Have restarted desktop neon wallet several times.
version 0.0.5
Please assist..

Thanks

**Comment by Satoshinaire** [comment]
First things first, please try updating to the latest version (0.0.6) listed here: https://github.com/CityOfZion/neon-wallet/releases

**Comment by cryptomd** [comment]
Now running 0.06 but still receiving 'transaction failed' message...

**Comment by saltyskip** [comment]
Lots of nodes are down right now 

http://monitor.cityofzion.io/

You may be connected to one of the bad nodes. Failed transactions are almost always due to network connectivity issues

**Comment by Satoshinaire** [comment]
@saltyskip Possible, but keeping in mind that Neon runs it's own nodes and is done through an API rather than the client connecting directly to nodes.

**Comment by Ejhfast** [comment]
@Satoshinaire @saltyskip Neon does not run its own RPC nodes, but it does use the API to decide which RPC node to connect to

usually this problem because a network/firewall for user is blocking non-standard ports

**Comment by saltyskip** [comment]
Right, what I'm suggesting is network management should be moved off of API and locally on to each users machine. This removes the single point of failure. Is there any reason the same service that is running on the API can't be moved onto the wallet itself?

**Comment by localhuman** [comment]
That could be done, but at that point neon would no longer be a light wallet.

**Comment by saltyskip** [comment]
I don't follow, the algorithm would just ping a list of seed nodes, theoretically they should all be at the same block number, if there is a subset of them that are behind, then ignore them, and choose from the list that is most up to date. This shouldn't require a copy of the blockchain.

This strategy doesn't protect against the situation where every node in the seed list is behind, but should be more available than fetching data from the API

**Comment by bitdom** [comment]
So i downloaded the wallet and sent neo and now it is stuck in the wallet . I tried to send it to an exchange but says transaction failed.....

**Comment by bitdom** [comment]
My wallet is neon ... not sure what to do ...pretty scared that my coins are stuck
