### ISSUE TITLE
Present error to user when encrypted key is invalid

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neon-wallet#314]
If a user tries to use an invalid encrypted key, the neon wallet keeps saying "Decrypting encoded key...". Only the developer tools show an error: `Uncaught Error: Invalid checksum`. This should probably be presented to the user.

**Comment by evgenyboxer** [comment]
@metachris Could you share the invalid encrypted key? I'm not able to reproduce.

**Comment by metachris** [comment]
Sorry @evgenyboxer -- I did not see an email from Github for your reply!

To reproduce this on 0.0.7, just click on "Login using private key" and enter `invalid`.
