### ISSUE TITLE
how can I change my gui wallet to neon with ledger adding ?

### ISSUE THREAD

**Issue by holod123** [CityOfZion/neon-wallet#317]
Do I have to transfer all neo from gui wallet to ledger wallet adress? And this is the only way ? there is no way to save old wallet ?

**Comment by stevesbrain** [comment]
I'm not really sure what you're asking here. Essentially, if you're using Neon wallet with the Ledger, the Ledger calculates a new Private WIF + Public Key based off your seed on your Ledger. You use your old wallet to transfer the funds to the new address, and then continue to use the new address from then on. This is fee free, as per usual.

Is there any reason you wouldn't want to use the new wallet? What do you mean by "save old wallet"? You never lose your transaction history on the hold wallet, that will always exist.

**Comment by CryptoJim** [comment]
@stevesbrain If I change from the wallet to Ledger will my Gas be transferred along with my Neo? What about any unclaimed Gas?

**Comment by stevesbrain** [comment]
@CryptoJim You can certainly transfer Gas, however, this is a separate transaction. The way I'd do it is this (steps 1 to 3 are optional, and are just good practice for making sure everything works):

1. Transfer a small amount of Gas to Ledger to test you can receive fine
2. Transfer a small amount of Gas from Ledger to test you can send fine
3. Wipe the Ledger and then restore from recovery key - check transaction history. This will make sure you can restore the same key fine.
4. Send all your Neo over to the Ledger - this will stop you from generating any new Gas
5. Claim all your unclaimed Gas; you will then have all Gas and 0 unclaimed Gas, and no more Gas will generate in your old wallet
6. Send all Gas over to Ledger

At this point you will be completely transferred :)

**Comment by CryptoJim** [comment]
Thank you Steve, and Steve's brain!

**Comment by stevesbrain** [comment]
Haha, no worries at all @CryptoJim :)
