### ISSUE TITLE
Replace Bittrex API method ANS => BTC => USD with single Coinmarketcap query

### ISSUE THREAD

**Issue by Ejhfast** [CityOfZion/neon-wallet#32]
Single query is better than the two we have now: https://api.coinmarketcap.com/v1/ticker/NEO/?convert=USD

**Comment by vergilbg** [comment]
Does anybody know how bittrex gets the conversion rate from btc to usd?  
In the UI,  when you look at a market,  for example neo,  above the btc value shows (last) the usd value is shown too,  but this usd value is not available through the api. It would be useful either making usd value available on api or if bittrex can share the api they use for the conversion (assuming they use external data for the conversion). 

The above url wouldn't  be very accurate. I have tested and there is difference in btc values coming frim bittrex and from coinmarketcap. 

Whatb I have done to make this bit more accurate,  is getting btc and usd values from coinmarketcap,  find the conversion for 1 btc (btc/usd)  then apply that to the btc fetched from bittrex (btc*usd).  That still gannot guarantee the accuracy.  Requests must be fired simultaneously. If there is something better,  please let me know.

**Comment by babatundebusari** [comment]
@vergilbg interested in this as well...will like to know how to get the conversion on bittrex as well...not sure if they use USDT for their conversion
