### ISSUE TITLE
Sending NEO/GAS - Ledger Communication Mix Up

### ISSUE THREAD

**Issue by aadon94** [CityOfZion/neon-wallet#322]
I noticed a bug where I went to send X amount of NEO from my ledger via the Neon wallet but when check on the ledger it showed GAS instead of NEO being sent. I then cancelled and tried to send the same amount of GAS from Neon and it didn't let me (I didn't have enough). So the ledger/Neon communication definitely got mixed up somewhere. I'd clicked on the NEO/GAS toggle button a few times before hitting send. Sorry I can't provide more info.

**Comment by msrinu143** [comment]
I have my neo not showing in NEON wallet, please help me what's happening with coins.

I feel terrible now. I have NEON wallet 0.0.5 version.

**Comment by aadon94** [comment]
msrinu143 I believe your issue is not being up to date. Update your neon wallet from here: https://github.com/CityOfZion/neon-wallet/releases

**Comment by stevesbrain** [comment]
Also @msrinu143 - as mentioned, user support issues like this need to be in the #support channel of the Slack; the GitHub is used for tracking development tasks, not usage/user support.
