### ISSUE TITLE
GAS claim failed with 0.0.7 Windows wallet

### ISSUE THREAD

**Issue by donnyque** [CityOfZion/neon-wallet#323]
Hi, has anyone had this problem? 
I haven't claimed my GAS since it was called ANC and Antshares back in June, when I first bought in. Now whenever I try to claim in the NEON wallet, the button greyes out, and it says claim failed. I then tried claiming in the NEO-GUI wallet, and it acquired some small amounts. But the majority of the GAS remains unclaimed. Also on Neotracker.io. 

What can I do?

**Comment by evgenyboxer** [comment]
@donnyque I have removed your screenshot, as this isn't a good practice to post your balance.
We're looking into the connectivity issue, and this will be address in the next version.

Could you try to reclaim and tell me if that worked out?

**Comment by donnyque** [comment]
@evgenyboxer Hi, okay sorry. I just tried again and it still said claim failed.

**Comment by donnyque** [comment]
@evgenyboxer Update. I succeeded! By downloading the mobile wallet and importing my private key there I was able to claim the GAS. I don't know what the issue with NEON was though. But I can see the GAS in NEON now.

**Comment by JCardenete** [comment]
This is happening to me too, Neon 0.0.7, MacOS 10.13.1. An error message shows up on top of the screen saying "Claim failed".

**Comment by rj23z** [comment]
I am having the same issue. 
Neon 0.0.7, Windows edition. 
I can not claim gas, the transaction can not be processed. A value of 0 Neo transferred shows up in my wallet ledger.

**Comment by saltyskip** [comment]
Something funky is going on with either NEO or the CoZ API. Here we can see issue when I query claims of random address.

![image](https://user-images.githubusercontent.com/14796429/33227265-2ad44908-d154-11e7-9b93-527c4edaee0e.png)

Although there is a non-zero claim amount here, the actual array which contains the claim data is empty. If this were to be empty than one would not be able to build up the claims in sendRawTransaction

@lucianoengel @Ejhfast any thoughts?

**Comment by ixje** [comment]
For what it's worth it's not related to `neon-wallet-db` that's used in the 'backend'. I just claimed gas using `neon-wallet-react-native` that uses `neon-wallet-db` as well, and it works fine.

**Comment by saltyskip** [comment]
It could be related to some users and not all. @ixje can you query the claims route on the CoZ API and see if the claims array is non-empty?

**Comment by elessarts** [comment]
I have similar problem - cannot claim gas. Upon further investigation, i can't send NEO either. I set up another wallet in my NEON to test it and I cannot send any NEO, which explains why I can't claim gas because you have to send NEO to yourself to get gas (apparently). Also note my button doesn't get greyed out it just says "sending NEO to yourself" at the top for hours. As someone suggested, I removed the program and installed 0.0.5, but it did not help. I was using 0.0.7 and i think i originally had 0.0.6 and couldn't claim gas in any of those. Please help <3

**Comment by ixje** [comment]
@elessarts it's probably best to join the neo slack channel (specifically #support) to get a more responsive interaction going. Do note that people might be at work/school/busy so getting a reaction might not be instant.
