### ISSUE TITLE
Why can't I paste my private/encrypted key into the provided space when I want to accesss my wallet?  I have Windows 7 and have no problem pasting anywhere else.  If i have to type in all the characters each time I sign in..that wouldn't be good.

### ISSUE THREAD

**Issue by Whiplash1000** [CityOfZion/neon-wallet#328]

**Comment by stevesbrain** [comment]
@Whiplash1000 There's no reason why you shouldn't be able to copy and paste, but, as the edit says, visit the Slack channel for support - GitHub issues are for development only :)

**Comment by Whiplash1000** [comment]
Steve, 

Thank you for responding.  The trouble is, when I tried to join Slack Channel by entering my email address, this was the response:  Failed! invite_limit_reached

I've tried multiple times with the same response.  I don't want to bother you, but, I do need a solution...

So, what am I to do?  I tried again to paste and it won't even come up when I right click.

**Comment by stevesbrain** [comment]
@Whiplash1000 I don't believe there's any right-click functionality in it, however, have you tried the keyboard shortcut to paste? Should be Ctrl+V at the same time :)

**Comment by Whiplash1000** [comment]
That worked!!  Thank you so much!!

**Comment by stevesbrain** [comment]
You're welcome @Whiplash1000 :)
