### ISSUE TITLE
Can't make a transaction after the update!

### ISSUE THREAD

**Issue by Lachris42** [CityOfZion/neon-wallet#334]
Hi.
After the update it is not possible to right click in the address field to paste in a address.
And after the tedious job of entering the address manually with check and double check,
I get the message that the address is not valid. 
That is a big problem when you need to do a transaction, and I hope it will be fixed ASAP

**Comment by evgenyboxer** [comment]
What operating system are you using? Windows?

**Comment by Lachris42** [comment]
Windows 10 - Version 1709 (OS Build 16299.64)
Didn't have any problems with NEON 0.0.6

**Comment by Joseph-Tortorelli** [comment]
Same thing here.  Worse is that its on Ledger.  Cannot access coins

**Comment by Japh** [comment]
@Joseph-Tortorelli Does Ctrl+V work for you to paste the address in?
