### ISSUE TITLE
Sending Neo from Ledger Nano S to Exchange

### ISSUE THREAD

**Issue by crypto365** [CityOfZion/neon-wallet#335]
Hi I feel there is a bug when sending neo from the Neon wallet using the Ledger Nano S. No matter what amount I enter I get a message saying "Transaction Failed" it has to be a whole number which I understand but why is it not allowing to move Neo from the Wallet to a different address? 

I am using version 0.0.7

Thank you in advance

**Comment by stevesbrain** [comment]
@crypto365 This definitely works with the Nano S + version 0.0.7. I've done it multiple times. Can you clarify if you're ever getting prompted to sign the transaction on the Ledger? Are you using the simultaneous press of both buttons to sign this transaction?

**Comment by NewWorldBC** [comment]
Hello, I put RPX on my ledger Nano S with Neonwallet, now I can't move them out of there , Can't reach my funds now .. how Is this possible ? please help ... Thanks in regards.

**Comment by cryptickt** [comment]
Hi there, can someone please help? Im using a ledger nano s to connect to my neon wallet, just yesterday I was able to send neo to an exchange with success, and today I am trying to send neo again to an exchange, however it keeps giving me a "transaction failed" message, wont even be prompted by the nano s with latest updated versions..What can I do to fix this guys?? Thanks for your assistance in advance

**Comment by dvdschwrtz** [comment]
Here are some possible causes of your problems. The ledger won't send NEO if there is already a NEO transaction in progress on the same block. This is the same with non-ledger transactions. Also, there is a bug in the ledger app code that causes certain transactions to fail. you will never lose NEO because of this, but it might not return a successful transaction. These cases are very rare and it should not be a consistent problem, but coranos is in the process of fixing it now and will be updated soon. Most likely your ledger is working fine and the next time you logged in everything was working. If not, please open another ticket with more details or preferably, visit support in the NEO slack

**Comment by dwigon** [comment]
I have the same problem and its already December 19 come on guys fix this.

**Comment by aquakul** [comment]
Facing the same issue with my Ledger Nano S. I was successful in sending it from my exchange to ledger but not able to send it the other way. Any ETA as to when this would be fixed

**Comment by stevesbrain** [comment]
@dwigon Please remember this is a volunteer project. You can't really be so demanding when these folks are working on this project for nothing but donations (which I'm sure are few and far between)

**Comment by dwigon** [comment]
So losing all my money because this a volunteer project is good? wtf?

**Comment by stevesbrain** [comment]
> So losing all my money because this a volunteer project is good? wtf?

@dwigon Haha, wow, way to put words in my mouth. No, I'm not saying in any way that losing your money is good. I'm saying that you've got no leg to stand on demanding they do certain things in your time frame - they owe you nothing. Don't be so ungrateful - just wait patiently. You chose to use a project that hasn't even hit a v1.0 milestone; you knew the risks.

**Comment by karl-chedda** [comment]
Sending neo from exchanges to nano wallet simply was as easy as using a round number of neo in addition to exchange fee.( Example : bittrex sending 200 Neo +.025= total send 200.025. Hence receiving 200 round number of neo to offline nano s. YET; WHEN attempting to send any amount of neo back to any exchange has cost me a neo EVERY TIME ( AND ITS GETTING expensive w this mistake!) .  My first send was back to bittrex (used as ex. Bc well aware of .025 fee added to round number of any neo amount chosen to send. Neo comes the nano s transfer problem! It's states as expected ' use round number'( bc I was attempting to pay fraction ex..025 etc. To PREVENT THE LOSS OF FULL NEO! BUT nano repeated MUST be round number. So I tested by sending simply 2 to ' friend' exchange and he only received 1! Of coarse I tried again now using original site ( bittrex and sent 3 and nice again lost a FULL NEO!!) FOR INFORMATIONAL purposes; my friends site was binance as a test run. So from 1st hand experience, sending to nano from bittrex/ binance etc. Is EZ and yes ! You don't take a full neo loss bc you simply enter the added fraction to round number and it goes to nano w zero issues! Can anyone help me by providing me w the info it takes to ship virtually anywhere from nano w/o taking a FULL NEO HIT? LOSING 2 WAS NOT PLEASANT at all! But if any of you can learn from my personal experience : I'd feel better saving the poor next guy/ girl the loss! Any feedback much appreciated!  It's to the point I'm not willing to send any small amounts back off nano to exchange bc unlsee a bulk load it really stings losing 1 of 2 or 3 shipped! Anyone have a helpful hand to lend some info re this matter? Thanks in advance! Any/ all response are welcome! Expensive learning curve! Lol

**Comment by zulfh** [comment]
Guys I am having the same issue. I transferred NEO to kucoin from neon wallet and I don't see it in kucoin yet. It's been 1 hour. I was able to successfully transfer from Kucoin to neon though. Anyone else have the same issue ?

**Comment by stevesbrain** [comment]
@zulfh Is it on the blockchain? If so, message Kucoin. If not, resend. Either way, not a lot of good replying to a closed issue - not many people will see it.

**Comment by zulfh** [comment]
Hi Steve, 

Thanks for reaching out. Yes I do see it on my kucoin wallet now. It just took some time to show up for some reason.

**Comment by zulfh** [comment]
Hi Steve,

I am having another issue now. I had previously transferred TNC from Kucoin
to my NEON wallet without any issues. I did this last night again and it
doesn't show yet after 8 hours. The transaction confirmation just keeps
incrementing on the NEON tracker page.

Please advice.

Thanks

**Comment by stevesbrain** [comment]
@zulfh I always check the blockchain if in doubt. If it doesn't show on blockchain, then it's an issue with Kucoin (maybe taking a while to broadcast). If it does show on blockchain, but not on the NEON, then good news is the funds haven't been lost! Likely, in that case, it's possible NEON's blockchain servers are lagging behind (happens occasionally).

**Comment by zulfh** [comment]
How can I check on blockchain?

**Comment by stevesbrain** [comment]
@zulfh I am not familiar with any of the tokens, so I'm not sure if this is normal - however, compare that to your last successful transaction, and see if it looks similar :)

**Comment by zulfh** [comment]
Thanks Steve. I don’t see any difference. I have contacted Kucoin customer service for now.

**Comment by stevesbrain** [comment]
No worries - sorry I can't provide more info. If you view your wallet, rather than the transaction, you may see the balance of any tokens listed there!

**Comment by zulfh** [comment]
Yea. I see the other balances.

**Comment by stevesbrain** [comment]
If you see no TNC listed there at all (including your previous successful ones) then I'd contact Kucoin, likewise if you see your previous transaction TNC but not your current, I'd contact Kucoin. It's only if you see all expected TNC that you don't need to contact Kucoin.

**Comment by zulfh** [comment]
I see everything except the one from last night. So I have contacted Kucoin.

**Comment by stevesbrain** [comment]
No worries - hope it gets resolved!
