### ISSUE TITLE
Can no longer copy/paste "send to" address.

### ISSUE THREAD

**Issue by summertooth** [CityOfZion/neon-wallet#336]
I used to be able to copy my send to address from an exchange and paste in Neon, can no longer do this.  Seems like this should be enabled as typing these addresses will lead to many errors.  Thank you for your time.

**Comment by comountainclimber** [comment]
What version are you running? Neon => About Neon

**Comment by rockaBil-E** [comment]
i upgraded v006 two weeks ago, and now7, and found this 'paste' bug in both (on my machine).  I re-loaded 5 (pastes fine) and will wait for an resolution in 8.

**Comment by summertooth** [comment]
v7, newest version, just installed yesterday.  @comountainclimber

**Comment by stevesbrain** [comment]
@rockaBil-E @summertooth Are you both trying to right click and user copy + paste via right click menu's? Try Ctrl+C shortcut for copy, and Ctrl+V shortcut for paste.

**Comment by chris40taylor** [comment]
Hi, I had the same problem with the cut and paste but followed stevesbrain above and it worked.
Will this issue be rectified?

**Comment by bleach182** [comment]
Okay so has this been solved? I am new to this and don't really understand what @dvdschwrtz  commits are about. I when to the #336 and #376 but do not understand what I am supposed to do with that code..

**Comment by Satoshinaire** [comment]
@bleach182 You don't need to do anything, but the issue should be resolved in the next release.
