### ISSUE TITLE
Windows command line call to validate file hash has a typo in the exe file name

### ISSUE THREAD

**Issue by sixside** [CityOfZion/neon-wallet#337]
On this page: https://github.com/CityOfZion/neon-wallet/releases/tag/0.0.7 the command for Windows to check that the file hash matches is:

`certUtil -hashfile "Neon Setup 0.0.7.Windows.exe" SHA256`

but the downloaded file name is actually: "Neon.Setup.0.0.7.Windows.exe" so if people blindly copy/paste it will fail due to ERROR_FILE_NOT_FOUND

**Comment by totalvm** [comment]
Fixed
