### ISSUE TITLE
OK to Stay With the 0.0.5 Wallet Until All The Issues Are Resolved With This New Wallet?

### ISSUE THREAD

**Issue by Hoffacurse** [CityOfZion/neon-wallet#340]
I can't get an answer over on the NEO reddit, so I thought I'd try here. Is it OK to stay with the 0.0.5 wallet for now? I'm getting notices that I need to update every time I open it, but I am a little leery about updating at this point.

**Comment by stevesbrain** [comment]
@Hoffacurse In as far as I know, there's nothing major that's changed which requires updating the app at this stage. If it still works, I'd say it's fine to use.
