### ISSUE TITLE
Not able to claim GAS

### ISSUE THREAD

**Issue by webofunni** [CityOfZion/neon-wallet#341]
I tried to claim gas in https://neotracker.io/address/AKE1ohvSpVcgsVdonykCj4ed9m732gWAht using this wallet and it failed, now it looks like no other wallet is able to claim that GAS. How can I resolve it ?

**Comment by stevesbrain** [comment]
@webofunni Some people have had troubles claiming gas with current release, but have been able to claim with 0.0.5 - you could try that.

**Comment by DURK** [comment]
Have you tried version 0.0.8? In my case, that did the trick
