### ISSUE TITLE
Password is displayed as visible text when creating wallet

### ISSUE THREAD

**Issue by leafcutterant** [CityOfZion/neon-wallet#342]
When creating a new wallet, the client asks for a password, and both fields (defining a password and confirming it) have their contents displayed as readable text when the user types into it.

This is quite a security hazard. The contents of those fields should be visible only as bullets.

**Comment by Satoshinaire** [comment]
Good point.

The "Login using a saved wallet", "Login using an encrypted key", and "Login using a private key" screens all support showing / hiding sensitive input.

This should be added to the "Create a new wallet" and "Encrypt an existing key" screens too, I would think.

**Comment by evgenyboxer** [comment]
Thanks, will make a quick fix for these in our next release.
