### ISSUE TITLE
Windows 64bit compatibility issue - Impossible to install Neon Wallet 

### ISSUE THREAD

**Issue by Mediator08** [CityOfZion/neon-wallet#344]
Hi, 
When will you release an update of Neon Wallet compatible with Windows 64bit. 
The present version does not execute on Windows 64bit therefore I cannot get gas nor can I store my NEO keys on my Ledger nano.
Any way around ? 
Thanks

**Comment by totalvm** [comment]
Neon Wallet works on 64bit windows, as almost everyone I know uses windows with 64bit version.

What errors are you getting?
