### ISSUE TITLE
yarn install fails with libusb.h: No such file or directory

### ISSUE THREAD

**Issue by chatch** [CityOfZion/neon-wallet#349]
Apologies for posting here however "Neo Smart Economy Slack." invite screen is broken (https://slack-helper.cityofzion.io/invite/T656BRXQ8). Gets stuck in a permanent Captcha <-> click Invite button redirect cycle ....

----------------------------------------------------------------------

yarn install fails on both tag "0.0.7" and branch "dev" and:
   Node v6.11.3 and Node v9 latest
   Yarn 1.3.2

-----------------------------------------------------------------------
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.1.1: The platform "linux" is incompatible with this module.
info "7zip-bin-win@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "react-icons > react-icon-base@2.1.0" has unmet peer dependency "prop-types@*".
warning " > stats-webpack-plugin@0.6.1" has incorrect peer dependency "webpack@^1.0||^2.1.0-beta||^2.2.0-rc".
[4/4] Building fresh packages...
$ electron-builder install-app-deps && electron-rebuild --force --module_dir . -w node-hid -v 1.7.9
electron-builder 19.37.2
Rebuilding native production dependencies for linux:x64
Rebuilding native dependency node-hid
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.11.3 | linux | x64
gyp http GET https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http 200 https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http GET https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/hatch/projects/neo/neon-wallet/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hatch/projects/neo/neon-wallet/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hatch/projects/neo/neon-wallet/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hatch/.electron-gyp/.node-gyp/iojs-1.7.9/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/hatch/.electron-gyp/.node-gyp/iojs-1.7.9',
gyp info spawn args   '-Dnode_gyp_dir=/home/hatch/projects/neo/neon-wallet/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/hatch/.electron-gyp/.node-gyp/iojs-1.7.9/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/hatch/projects/neo/neon-wallet/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/hatch/projects/neo/neon-wallet/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
compilation terminated.
hidapi.target.mk:96: recipe for target 'Release/obj.target/hidapi/hidapi/libusb/hid.o' failed
make: Leaving directory '/home/hatch/projects/neo/neon-wallet/node_modules/node-hid/build'
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/hatch/projects/neo/neon-wallet/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.4.0-98-generic
gyp ERR! command "/usr/local/bin/node" "/home/hatch/projects/neo/neon-wallet/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=1.7.9" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /home/hatch/projects/neo/neon-wallet/node_modules/node-hid
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.11.3 | linux | x64
gyp http GET https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http 200 https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http GET https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/hatch/projects/neo/neon-wallet/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hatch/projects/neo/neon-wallet/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hatch/projects/neo/neon-wallet/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hatch/.electron-gyp/.node-gyp/iojs-1.7.9/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/hatch/.electron-gyp/.node-gyp/iojs-1.7.9',
gyp info spawn args   '-Dnode_gyp_dir=/home/hatch/projects/neo/neon-wallet/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/hatch/.electron-gyp/.node-gyp/iojs-1.7.9/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/hatch/projects/neo/neon-wallet/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/hatch/projects/neo/neon-wallet/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
compilation terminated.
hidapi.target.mk:96: recipe for target 'Release/obj.target/hidapi/hidapi/libusb/hid.o' failed
make: Leaving directory '/home/hatch/projects/neo/neon-wallet/node_modules/node-hid/build'
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/hatch/projects/neo/neon-wallet/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.4.0-98-generic
gyp ERR! command "/usr/local/bin/node" "/home/hatch/projects/neo/neon-wallet/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=1.7.9" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /home/hatch/projects/neo/neon-wallet/node_modules/node-hid
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/hatch/projects/neo/neon-wallet/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/home/hatch/projects/neo/neon-wallet/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.error (/home/hatch/projects/neo/neon-wallet/node_modules/rxjs/Subscriber.js:197:26)
    at Subscriber._error (/home/hatch/projects/neo/neon-wallet/node_modules/rxjs/Subscriber.js:128:26)
    at Subscriber.error (/home/hatch/projects/neo/neon-wallet/node_modules/rxjs/Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (/home/hatch/projects/neo/neon-wallet/node_modules/rxjs/Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (/home/hatch/projects/neo/neon-wallet/node_modules/rxjs/Subscriber.js:102:18)
    at SafeSubscriber._next (/home/hatch/projects/neo/neon-wallet/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrSetError (/home/hatch/projects/neo/neon-wallet/node_modules/rxjs/Subscriber.js:247:16)
    at SafeSubscriber.next (/home/hatch/projects/neo/neon-wallet/node_modules/rxjs/Subscriber.js:187:27)
error Command failed with exit code 255.

**Comment by slipo** [comment]
Could you try the instructions here and see if that help?
https://github.com/node-hid/node-hid#compiling-from-source

Specifically this command may help you:
`sudo apt install libusb-1.0-0 libusb-1.0-0-dev`

**Comment by chatch** [comment]
yep that's got it. installing those 2 dependencies and it now completes.

**Comment by chatch** [comment]
build docs now add this step
