### ISSUE TITLE
Idea: prepare app for localizations (translations)

### ISSUE THREAD

**Issue by RadekSip** [CityOfZion/neon-wallet#357]
Move hardcoded strings from code to allow community localization.

**Comment by evgenyboxer** [comment]
Thanks! I got some ideas around this.
Would you like to work on this? Or suggesting a feature?

**Comment by jmsaulnier** [comment]
@evgenyboxer I can have a look

**Comment by anfn101** [comment]
@evgenyboxer Any update?

**Comment by Sqeeki55** [comment]
All four participants a big thumbs up     Squeeki55

**Comment by Sqeeki55** [comment]
Evgenyboxer Do you need help? Not sure how much I can contribute

**Comment by comountainclimber** [comment]
Closing in favor of https://github.com/CityOfZion/neon-wallet/issues/1935
