### ISSUE TITLE
Balance not appearing in NEON

### ISSUE THREAD

**Issue by ojsimon** [CityOfZion/neon-wallet#359]
I can see the balance on Neotracker.io but I cannot see my balance in NEON wallet for one of my wallets, but I can see the balance for another separate wallet. What is causing this?

**Comment by wedwo** [comment]
For the same reason it's done it for ages.  I haven't seen my balance in Neon for a while now.  No idea how one is supposed to take this software seriously.

**Comment by clayt0nk** [comment]
Humble apologies? Why? I have no problem asserting that money should never disappear spontaneously  from any SERIOUS project's crypto wallet. On top of that, I see no comment here from project devs on what seems to me to be quite a serious issue.

I seem to be in the same predicament: my Neon balance is suddenly zero. I don't have the neo-gui app installed, is this https://github.com/neo-project/neo-gui/releases it? If so, not really an easy option for me, I am a Linux guy and I have zero Windows machines.

Devs, is there an easier option? If I go to https://neotracker.io/wallet/open-wallet and try to load my ~/.config/Neon/storage/keys.json file as a "Keystore file" I get the following error:

"Keystore file upload failed: Invalid Keystore file."

**Comment by evgenyboxer** [comment]
There are a number of reason why a balance might show 0. This will be addressed in future releases. Right now we are focusing on supporting NEP5.

If in doubt about the zero balance, please check the explorers.
