### ISSUE TITLE
neon 0.0.7 can not install to windows 10 64bit

### ISSUE THREAD

**Issue by cripperera** [CityOfZion/neon-wallet#366]
Hi,

cannot install neon 0.0.7 wallet to windows 10 operating system. I used version 5 for since last month without any interruption. 
please advice me.

thanks,

crip

**Comment by BluBoy** [comment]
Win10 x64 and Neon 0.0.7 are working fine here.

You might need to see if you have anything else preventing installation (or provide additional details for the devs to work off)

**Comment by DrBruceR** [comment]
I have the same problem. 0.0.5 was fine.  Tried to update to 0.0.7 and install hangs.  Re-downloaded .exe file several times and re-tried several times.  Then tried to re-install 0.0.5 and THAT hangs.  Had to install 0.0.5 on a Win 7 machine to access wallet.
