### ISSUE TITLE
NEON Wallet & 32 Bit Windows 7?

### ISSUE THREAD

**Issue by Trader914** [CityOfZion/neon-wallet#367]
Is there a 32-bit version of the NEON Wallet?

**Comment by rzkuvya** [comment]
I am interested in the 32-bit version of NEON Wallet too.

**Comment by Serg23** [comment]
I am interested in the 32-bit version of NEON Wallet too.

**Comment by matej1985** [comment]
Hello I’m allsow having problem to install application, because my windows are 32bit. What can I do. I’m nano ledger s user. Please help.

**Comment by anfn101** [comment]
NEON is not 32 bit and 32 bit support is not planned at this point.
