### ISSUE TITLE
I downloaded the new wallet to windows. I selected log in with private key, but when I click to paste in the private key I have no functionality to paste? It worked fine in the previous wallet version.

### ISSUE THREAD

**Issue by DavidRaw** [CityOfZion/neon-wallet#368]

**Comment by slipo** [comment]
I don't have windows for testing but this appears to potentially fix this:
https://github.com/CityOfZion/neon-wallet/pull/376

If you can compile from source with that PR to try and let us know, that'd be great. Otherwise it should be in the next release.

**Comment by Sangacious** [comment]
Hi, I received the same problem today. So I didnt bother to check my wallet again. Now that I open my wallet after 3 hours..... i see my Neos are gone.....  can someone help?

**Comment by DavidRaw** [comment]
Sorry i'm not technical enough to understand what you have asked me to do.
How long will it be until the next update so I can see if the problem is
fixed.
Thanks you
David

**Comment by stevesbrain** [comment]
@DavidRaw For now, paste with Ctrl+V keys pressed simultaneously

**Comment by DavidRaw** [comment]
Thank you Steve


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Steve Divskinsy <notifications@github.com> Date: 02/12/2017  11:07  (GMT+00:00) To: CityOfZion/neon-wallet <neon-wallet@noreply.github.com> Cc: DavidRaw <davidjraw@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [CityOfZion/neon-wallet] I downloaded the new wallet to windows. I selected log in with private key, but when I click to paste in the private key I have no functionality to paste? It worked fine in the previous wallet version. (#368) 
@DavidRaw For now, paste with Ctrl+V keys pressed simultaneously

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CityOfZion/neon-wallet","title":"CityOfZion/neon-wallet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CityOfZion/neon-wallet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stevesbrain in #368: @DavidRaw For now, paste with Ctrl+V keys pressed simultaneously"}],"action":{"name":"View Issue","url":"https://github.com/CityOfZion/neon-wallet/issues/368#issuecomment-348684878"}}}

**Comment by emanon7** [comment]
Hello can somebody tell me if they are having issues entering the new version 0.0.7 of the wallet?
Seems you can't copy paste and once entered your private key is entered manually...nothing happens??

**Comment by reobnevarb** [comment]
pasting with Ctrl+V keys pressed simultaneously worked for me, thanks.
But to see my balance I have to use the old private key from the previous version wallet.

**Comment by stevesbrain** [comment]
No worries @DavidRaw :)

@emanon7 As above, try pasting with Ctrl+V, instead of right click + paste.

**Comment by emanon7** [comment]
Thank you very much !
Take care


*Emmanuel EYSSAUTIER*
Nstra. Sra. del Rosario 1057, Dpto. 208 - Vitacura
Santiago-CHILE
Fono: 56-2-27245767
Cel: 56-9-97589727


2017-12-04 23:56 GMT-03:00 reobnevarb <notifications@github.com>:

**Comment by emanon7** [comment]
Thank you, worked fine with Ctrl+V... weird though....!

*Emmanuel EYSSAUTIER*
Nstra. Sra. del Rosario 1057, Dpto. 208 - Vitacura
Santiago-CHILE
Fono: 56-2-27245767
Cel: 56-9-97589727


2017-12-04 23:57 GMT-03:00 Steve Divskinsy <notifications@github.com>:

**Comment by reobnevarb** [comment]
stevesbrain Not sure if I do understand. Are you saying that when I set up the new version wallet, I did not have to create a new private key?

**Comment by stevesbrain** [comment]
@reobnevarb I am saying that, yes. The private key is the same always - you create it once, and use that for every wallet version :)

**Comment by reobnevarb** [comment]
stevesbrain  
Thank you, 
Can you also tell me if this latest version Neo wallet can also hold Red Pulse token?

**Comment by Satoshinaire** [comment]
Your address can hold it, but Neon 0.0.7 cannot display your balance, nor can you transact.

Neon 0.0.8 should be bringing this functionality though.

**Comment by reobnevarb** [comment]
Hi, Can anyone tell me if there is a fully functioning desk top wallet available for Red Pulse token?
Thanks.
