### ISSUE TITLE
[Feature] Private network option

### ISSUE THREAD

**Issue by evgenyboxer** [CityOfZion/neon-wallet#372]
# Feature #

Add an option to select a private network in the settings page.

## Specifics ##

- Add the ability to enter the url of another Neon API to connect to (localhost, or private net deployed publicly)
- NeonJS needs to support this.

**Comment by brianlenz** [comment]
Just curious: does closing this indicate it's done or won't be implemented? Thanks!

**Comment by comountainclimber** [comment]
Tracking the issue here => https://github.com/CityOfZion/neon-wallet/issues/871#issuecomment-407035590
