### ISSUE TITLE
Wallet "freezes" in dock after being closed

### ISSUE THREAD

**Issue by wouterbruinings** [CityOfZion/neon-wallet#38]
OS: macOS Sierra 10.12.6 

After closing the wallet window, clicking on the icon in my dock no longer opens the wallet.  

Currently I need to "Quit" the application and restart the wallet in order to use it again.

**Comment by Ejhfast** [comment]
I think this is default electron behavior, will fix in next release

**Comment by Alexintosh** [comment]
Well spotted, I'll make a fix for it.
