### ISSUE TITLE
let me create wallet but not log back in 

### ISSUE THREAD

**Issue by coopsscoop** [CityOfZion/neon-wallet#39]
app let me create a wallet I transferred a few shares over logged out now won't let me log back in...seems like a scam to me

**Comment by Ejhfast** [comment]
This is how you generate a wallet, look at what it says!

<img width="738" alt="screen shot 2017-08-06 at 12 08 17 pm" src="https://user-images.githubusercontent.com/89618/29006195-f646905c-7a9f-11e7-99d1-5874118a4964.png">

You need to save the private key to log back in

**Comment by coopsscoop** [comment]
Wasn't born yesterday bud I did that still won't let me log in

**Comment by coopsscoop** [comment]
I could show you the multiple ways I chose to save that information so I
wouldn't lose it

**Comment by Ejhfast** [comment]
You are probably typing the key wrong (this has happened to others), we are
happy to help in slack -- contact us before posting about scam

**Comment by Ejhfast** [comment]
Also what version of wallet are you using, version 0.0.1 had a login button
that was hard to click (had to click on text in center)

**Comment by coopsscoop** [comment]
Okay apologize for post frustrating losing any amount of money sure you can
understand

**Comment by Ejhfast** [comment]
Yes, I understand, and it is 100% safe as long as you are still holding the private key. (Even if you don't want to use Neon, you can import that to a different wallet).
