### ISSUE TITLE
Wallet issue, my Neo is not appearing!

### ISSUE THREAD

**Issue by roycebox** [CityOfZion/neon-wallet#394]
Hello,

So, I bought Neo the other day on Bittrex exchange. After downloading the neo app on android, I setup a new wallet by creating a password and then saved my wallet (I was never given a private key). After pressing on receive in the menu, I got my public key and had my new neo transferred. Since then I have not seen any neo show up in my android app neo wallet. When I double check my public key on neotracker.io, it is all there, although does not show up in wallet, still shows 0.

I have tried to log onto my wallet from neotracker.io, although when I upload my JSON file (since I did not get a private key) I keep getting the same error: "**Keystore file upload failed: Invalid Keystore file**" 

Please if anyone has experienced this and has any advice would be great. I cannot seem to find any info about this anywhere.

**Comment by stevesbrain** [comment]
Not sure what wallet you're using on your phone, so you're unlikely to get any support from here (given this is for a computer wallet). However, the basic troubleshooting would be:

1. Check your public key - if the balance is there, provided you have the corresponding private key, all is not lost
2. Get a copy of your private key - export it from the application
3. Use that private key to log in with something like neon-wallet - that way you still have control of your balance and can send it to a more reliable wallet

What was the wallet you did use?

**Comment by roycebox** [comment]
Sorry, I did not realise this was only fot computer wallets.

I never got a private key when I created a new wallet. I tried using the encrypted pruvate kry i found in the json file although it did not seem to work either.

The wallet I am using and used to creare my wallet is Neo App by PeterLinX.

I even tried creating a new wallet and using that json file to log in on neotracker.io but it still gave me the same error.

Thanks for the help.

**Comment by roycebox** [comment]
Ok, I figured out how to get my private key with the app, managed to log in using that on the neon app on PC and now can see my neo appear on there. Still does not show up on android app but at least I can access it!

Thanks for the help 👍

**Comment by stevesbrain** [comment]
Excellent - well done @roycebox - good troubleshooting :)

**Comment by tgtcph** [comment]
Just found this question, and I give it a shot here as well. 
I was using NEON wallet version 0.0.6 for an ICO crowdsale, and uploaded 11 NEO-s in this wallet. Ever since then I cant login to my NEON wallet. Tried to download the 0.0.7 version, but still, logging in is not working out. I have my KeyStore file saved, also my private key, but the wallet keeps tellin me those are not valid. 

Checked my address on NEOTracker, and tried to login to my wallet through NEOTracker, using the KeyStore file, but got the same error message.

Can you guys help me with this issue?

Thanks a lot!
T

**Comment by Satoshinaire** [comment]
See #436 for the resolution to @tgtcph's issue.
