### ISSUE TITLE
NEON Wallet is not syncing 

### ISSUE THREAD

**Issue by hariharanpalani** [CityOfZion/neon-wallet#395]
Hi, 
  I can successfully install the wallet in my windows 10 desktop. After transfer the NEO from binance to this wallet, it is not getting credited. It always shows 0 value. 

Even Block at top right also shows 0. Can you please let me know what will be problem? Is it not able to communicate with the server and the way to identify the problem (may be place to check for log files)

**Comment by superenart** [comment]
try to add an exception to your firewall
