### ISSUE TITLE
Unable to login using private key for Neon Wallet 0.0.7 but 0.0.6 accepts same private key?

### ISSUE THREAD

**Issue by ricksanchez777888** [CityOfZion/neon-wallet#399]
First, I apologize if this is not the correct place to ask for support, but I am out of options;

I tried going to the Slack channel for NEO for support but am unable to access it. (Sorry but this Slack is currently unable to send invites as Slack has disabled this feature)

I've posting on Neo Reddit but no has been able to help me.

Issue: My WIF private key doesn't work on 0.0.7, but it DOES still work on 0.0.6 (although I can't see my GAS balance since the client wallet says this version is outdated. A quick check on neoscan shows that my gas is still there.

I've tried using 0.0.6 export .json and import into 0.0.7. 
I've tried encrypting my existing key on the 0.0.6 but it gets stuck on "Generating encoded key...",
I've tried using the web wallet,
I've tried uninstalling/reinstalling 0.06>0.0.7 on both a Mac and Windows,

Nothing works, does anyone else have this issue? Any ideas or solutions?

**Comment by stevesbrain** [comment]
This is very strange; are you typing the key in manually, or copying + pasting? If copying + pasting, have you ensured there's no spaces etc in the key?

**Comment by Satoshinaire** [comment]
I was wondering this too @stevesbrain, until he mentioned exporting and importing the JSON... surely no room for a copy/paste error there.

**Comment by ricksanchez777888** [comment]
I've done both manually typing and copy+pasting. I've been trying for about 7 days straight now hoping for a bug fix. Everyday it's been the same; I can access 0.0.6 but not 0.0.7, so surely my private key has no errors.

**Comment by stevesbrain** [comment]
@ricksanchez777888 Unfortunately I don't have any guesses for you there :( I've been able to use the same private key since version 0.0.3 or 0.0.4 without issue :/ What if you generate a new test private key in 0.0.6 and paste that into 0.0.7 - same issue then?

**Comment by ricksanchez777888** [comment]
That did the trick! Weird. I really appreciate the help! @stevesbrain, @Satoshinaire, do you guys take donations? Send me your Gas address.

**Comment by stevesbrain** [comment]
Very kind @ricksanchez777888 :) Happy to accept donations on AQy3nW4ZPrJuws3NPavSZH4b3hxdTXSc8C 😄

**Comment by ricksanchez777888** [comment]
Sent! I'll close out this ticket for now. @Satoshinaire send me your gas address when you get the chance.

**Comment by stevesbrain** [comment]
@ricksanchez777888 Very kind of you - thanks very much :) Glad it's been a happy resolution for you!

**Comment by Satoshinaire** [comment]
@ricksanchez777888 It's not necessary, but if you insist, you can find my donation addresses listed here: https://www.satoshinaire.com/

**Comment by ricksanchez777888** [comment]
Sent! Thanks fellas! I see you guys do a lot more than just replying to these tickets, keep up the great work! Cheers!
