### ISSUE TITLE
Type of encryption 

### ISSUE THREAD

**Issue by Berend-B** [CityOfZion/neon-wallet#402]
Hey guys,

I was wondering if it was possible for me to retrieve my passphrase. I saved my passphrase in a different location that I lost now (LastPass). I still have the public key en my encrypted private key, but no way to retrieve the passphrase. So now, I can't login again and my NEO seem to be lost.

Thanks in advance!

**Comment by evgenyboxer** [comment]
Have you saved your unencrypted private key somewhere?

**Comment by stevesbrain** [comment]
@Berend-B If you haven't saved a copy of your unencrypted private key, and it's impossible to recover your LastPass, then unfortunately it's lost. However, how has it come about that you lost your password in LastPass? As far as I know, they have a "recycle bin" and password history?

**Comment by Berend-B** [comment]
I guess I didn't save the LastPass entry properly before my computer stopped working and I can't recover my private key anymore. I guess it's lost forever. 

Thanks for helping though!

**Comment by stevesbrain** [comment]
Oh man, that's unfortunate :( Sorry to hear it @Berend-B

**Comment by evgenyboxer** [comment]
I’m closing this issue.
Best of luck @Berend-B
