### ISSUE TITLE
NEO/GAS is not appearing

### ISSUE THREAD

**Issue by Guybrush26** [CityOfZion/neon-wallet#403]
I've been using NEON for a long time now and today I wanted to claim some GAS but my NEO and GAS balance is not appearing. Everything works fine on neotracker. Is this just a visual bug?

**Comment by evgenyboxer** [comment]
Seems like the neon wallet api is down at the moment - http://monitor.cityofzion.io/

**Comment by stevesbrain** [comment]
Can confirm - it is down at the moment. Everything will appear again when it's back up :)

**Comment by slipo** [comment]
It's back up.
