### ISSUE TITLE
Ledger Nano S passphrase support?

### ISSUE THREAD

**Issue by rexii2300** [CityOfZion/neon-wallet#410]
How is the NEON wallet's compatibility with Ledger's extra passphrase feature described here? https://ledger.zendesk.com/hc/en-us/articles/115005214529-Advanced-Passphrase-options.

I created a temporary passphrase and opened Neon Wallet (address B). I can see a different address to my initial wallet address (address A).

To retest, I re-powered up the device and then setup a temporary passphrase again and Wallet address B is displayed correctly.

A different passphrase appears to create generate a different Neo wallet address, which is the desired behaviour.

I then tried using this Recovery Site https://coranos.github.io/neo/ledger-nano-s/recovery/ to recovery my address+WIF key. address A is a success with the standard 24 word phrase. However there is no ability to recover with an optional passphrase.

Is the passphrase functionally officially supported? If yes, can this be added to the Recovery Site? I can't find a BIP39 Mnemonic Code Converter that works with NEO anywhere.

**Comment by stevesbrain** [comment]
Can also confirm the expected behaviour with the Nano S, however, I have not tried with the recovery page generator (haven't let me "real" seed touch a PC yet). I did test adding an extra word to the recovery page/seed, and it did generate a different WIF - are you saying this WIF doesn't match the Ledger's though?

**Comment by rexii2300** [comment]
I have tried adding the extra word at the end of the 24 word mnemonic in the recovery site, but the address & WIF doesn't match the Ledger's.

From what I can gather, the extra passphrase is not an extra word (24 +1), but rather a separate word to encrypt the 24 word mnemonic. I think it's part of the BIP39 standard. For example, this converter here allows you to input an optional passphrase https://coinomi.com/recovery-phrase-tool.html

**Comment by rexii2300** [comment]
coranos updated recovery site with passphrase support. so issue closed
