### ISSUE TITLE
Gas claim when logged in with WIF and a Ledger is connected

### ISSUE THREAD

**Issue by notatestuser** [CityOfZion/neon-wallet#414]
I'm "logged in" with a WIF and have a Ledger Nano S connected with the Neo app open. Neon Wallet is trying to sign a transaction on the device when I try to claim GAS. Obviously that key is not associated with the Ledger so nothing happens.

Here's a screenshot of the message I get:

<img width="1015" alt="screen shot 2017-12-14 at 01 01 25" src="https://user-images.githubusercontent.com/1255926/33951629-73d238b6-e06a-11e7-8b52-918506f6e88f.png">

**Comment by anfn101** [comment]
Try latest version 0.1.2
