### ISSUE TITLE
Starting window is white blank - win10

### ISSUE THREAD

**Issue by MattSom** [CityOfZion/neon-wallet#417]
As I download the win10 .exe and run it, the NEON window appears, but everything is white. If I select the text with mouse it shows, that the input fields and button options are there, but I cannot see them.

**Comment by shawnmclean** [comment]
Is this still an issue? Closing until further information.

**Comment by zaryk** [comment]
getting this as well.  cursor changes while hover over areas indicating the input fields are there.

![image](https://user-images.githubusercontent.com/593015/35420948-57a8bfaa-020e-11e8-81ef-b88c2fbfae21.png)

**Comment by maxkaplan** [comment]
I'm also getting the same error is Neon_0.1.2_amd64.Linux.deb

![image](https://user-images.githubusercontent.com/200634/35658575-dd28297a-06b6-11e8-8f82-e5d288d46c7c.png)

**Comment by zaryk** [comment]
I believe it has to do with drivers or graphics card settings.  my laptop has intel as primary, but also has some functionality related to related to nvidia, which apparently, i don't need.  once i removed the nvidia drivers, i was able  to see the screen.  Can't give much more information than that.
