### ISSUE TITLE
Neo on Ledger Blue

### ISSUE THREAD

**Issue by SHarlov** [CityOfZion/neon-wallet#418]
Hey, guys.

Just wondering if anyone has had any problems with installing Neo on the Ledger Blue?  Every time I do it, the Neo logo DOESN'T appear on the Dashboard -- only the word 'Neo'.  However, the wallet itself seems to be working, but I'm hesitant to use it to safe guard any funds if it hasn't installed properly.

Any help would be great.

Thanks.

**Comment by Zlerp** [comment]
I am having the same issue and question. Myself.

I beleive you are ok, but hesitant to use.

Just posted on r/ledgerwallet also: https://www.reddit.com/r/ledgerwallet/comments/7kg934/is_neo_fully_functional_on_the_ledger_blue/?ref=share&ref_source=link

**Comment by anfn101** [comment]
Blue is not supported yet.
