### ISSUE TITLE
mac os 10.13.2 neon 0.0.7 shows "0" balance

### ISSUE THREAD

**Issue by headude** [CityOfZion/neon-wallet#420]
Cannot find any balance on my Neon app. It has always been there, now no NEO or GAS. ??? I have refreshed, restarted, etc.

**Comment by d0ngit** [comment]
@headude Has your NEO address been changed?

**Comment by headude** [comment]
No, not by me. Nothing has changed since I updated with a new router. I am exploring that avenue today. I have always had the same balance for months in my Neon wallet for NEO, and of course, growing for GAS; now nothing.

**Comment by headude** [comment]
Solved. Thank you. Problem appeared to be in a router.
