### ISSUE TITLE
Send button broken - Neon Wallet 0.0.7

### ISSUE THREAD

**Issue by zenmonster76** [CityOfZion/neon-wallet#423]
The "Send" button seems to be broken on Neon Wallet 0.0.7.  The button literally does nothing, it doesn't even move or change color in a satisfying way, let alone send my NEO.  It's maddening.  Please tell me a way to fix this, thank you.

**Comment by zenmonster76** [comment]
The invite limited has been reached, so I CAN'T join the Slack.  Please change the limit on that.

**Comment by zenmonster76** [comment]
I am deeply concerned that my NEO is now irreparably "stuck."  Anyone else using version 0.0.7?

**Comment by hounded** [comment]
Yes same problem, seriously if they are going to launch a public ico, they need to at least have the code working [sentence enhancers removed]

**Comment by Satoshinaire** [comment]
@zenmonster76 I'd recommend you join the [NEO Discord](https://discord.cityofzion.io) instead.

@hounded What ICO are you referring to? And given that Neon is still in pre-release stage and makes no claims at being production-ready software, teething hiccups are to be expected. Just hold onto your hats and wait for the next update to resolve your issues, or use a different wallet.

**Comment by zenmonster76** [comment]
I would love to use a different wallet, but my coins are stuck in the NEON Wallet.  Or can I use any wallet with the same private key?  I will join the Discord, thank you.

**Comment by TechniumUnlimited** [comment]
Any update on this

**Comment by zenmonster76** [comment]
Actually yesterday I was able to send 1 NEO from the Neon Wallet to an exchange, so perhaps all is good here now!  Thank you.   

    On Monday, January 22, 2018 9:51 PM, TechniumUnlimited <notifications@github.com> wrote:
 

 Any update on this—
