### ISSUE TITLE
When will Red Pulse PRX supported

### ISSUE THREAD

**Issue by teovmy** [CityOfZion/neon-wallet#424]
Hi Team,

I can't see my RPX? When can we expect a version update which hold RPX besides GAS and NEO?

**Comment by fluchtreflex** [comment]
This would be great because it means that RPX (and other tokens) aren't accessible at all when using the ledger nano s for accessing the wallet.

**Comment by 2ge** [comment]
I got RPX in my NEO, but can not see in NEON. Before there was "Participate in Token Sale", now it is gone. What is solution, how I can check my RPX ?

**Comment by teovmy** [comment]
No comment yet?

**Comment by dennish007** [comment]
Please make this a general issue to support NEP5 tokens. Than RPX, DBC, ... will be supported automatically

**Comment by slipo** [comment]
Closing this out. Main issue for this here: https://github.com/CityOfZion/neon-wallet/issues/146
