### ISSUE TITLE
NEON wallet empty running 0.0.7 shows no transactions and zero in account ??????????

### ISSUE THREAD

**Issue by Roanunicorn** [CityOfZion/neon-wallet#427]
<img width="921" alt="screen shot 2017-12-20 at 9 24 23 am" src="https://user-images.githubusercontent.com/34704956/34195699-a12d8b38-e567-11e7-8906-e52df2608f57.png">

**Comment by maahno** [comment]
I have the same issue - wallet zero and no transaction history (ledger nano s)
Also my Block showed: NaN 
But i checked my balance via neotracker and seems everything ok with my neo
only I cant see it on my ledger wallet
![img_2049](https://user-images.githubusercontent.com/34722300/34225944-32b26e9a-e5d9-11e7-9260-7361c3203771.JPG)

**Comment by fabwa** [comment]
Please use discord or reddit for wallet support. Your screenshot indicates a network issue (firewalls? vpn?)
