### ISSUE TITLE
Ledger Nano S transactions failing 

### ISSUE THREAD

**Issue by ecryptoz** [CityOfZion/neon-wallet#429]

**Comment by ecryptoz** [comment]
Hello,

Whenever I attempt to send an asset/claim gas and hit confirm the transaction, the "please sign transaction on hardware device" flashes right to "transaction failed!" Sign tx now never appears on my ledger screen.

I have uninstalled and reinstalled the NEO app on the ledger, uninstalled and reinstalled Neon wallet, and restarted my computer all with no results.

Please let me know if there's anything I'm missing that will fix this.

Thanks

**Comment by ecryptoz** [comment]
Hello,

Whenever I attempt to send an asset/claim gas and hit confirm the transaction, the "please sign transaction on hardware device" flashes right to "transaction failed!" Sign tx now never appears on my ledger screen.

I have uninstalled and reinstalled the NEO app on the ledger, uninstalled and reinstalled Neon wallet, and restarted my computer all with no results.

Please let me know if there's anything I'm missing that will fix this.

Thanks

**Comment by ecryptoz** [comment]
Now it's allowing me to claim GAS, but I'm still getting "transaction failed!" when trying to send asset.

Any help would be greatly appreciated.

**Comment by subzero788** [comment]
I cant claim gas on NEON either using a nano S.

When I try, I sign the transaction on my ledger, but then NEON says "Transaction Failed!"

**Comment by wbuc** [comment]
I am also getting the same behavior. Did you guys manage to get it to work?

**Comment by subzero788** [comment]
Yeah updating to the newest version of neon fixed it

**Comment by wbuc** [comment]
Weird, I did that and not working. I must say, I am using my mobile hotspot to connect. I think this might the cause because at my home pc I was able to claim the gas. Guess I'll have to wait to get back home and get on my machine to see if that is the case.

**Comment by niranjans** [comment]
I have the same issue. Cannot claim gas. Updated to the latest Neon version 0.1.2 but that did not fix this. Any suggestions?

**Comment by anfn101** [comment]
Github is used to report code issues. Any support can be found in the Discord #support channel. Make sure your firewall is not the issue.
