### ISSUE TITLE
use english blockchain tracker

### ISSUE THREAD

**Issue by jaminNZx** [CityOfZion/neon-wallet#43]
Hi
Just wondering if you could use the english blockchain explorer as an option?
The one I'd prefer is : https://neotracker.io
Thank you for your hard work!
J

**Comment by fransyozef** [comment]
yeah .. would be very nice indeed :)

**Comment by Alexintosh** [comment]
Great idea! I'll make a PR for this.

**Comment by totalvm** [comment]
was fixed in 0.0.4
