### ISSUE TITLE
Zero balance in neon wallet using ledger nano S

### ISSUE THREAD

**Issue by Crypton85** [CityOfZion/neon-wallet#432]
I've been using Neon wallet for the past few days after acquiring my Ledger Nano S and it had been fine till now. Somehow, today the wallet seems to be showing ZERO balance in it with all my Neo and gas disappearing. I've done a check using https://neotracker.io/ and the coins are indeed still in my public address.

Can someone please advice on this?

**Comment by Dooctoore** [comment]
I have the same issue mate. Please advice..

**Comment by BluBoy** [comment]
I had this issue, and it was caused by an overzealous firewall blocking the app from connecting to the internet.

DEV: If there is no internet connectivity, an error message should be displayed, instead of a zero balance.

**Comment by marcokofi** [comment]
Hello guys, l'am also facing the same issue my balance shows zero but i notice my coins are still on my public address using  neotogas.com, any help would be much appreciated thanks

**Comment by francescofarina** [comment]
Same problem here. Showing 0 balance on neon wallet used with the ledger nano s. Checking my address on neotracker gives the exact balance.
I cannot send neo in this way.
Solutions?

**Comment by blockmike** [comment]
hi, same problem here - thanks to @francescofarina as i checked the neotracker and see that the balance is still there....phew. I hope it is a slight but which Leger nano S will sort out quickly!

**Comment by wbnben** [comment]
i have also the same problem, zero balance on neon wallet using ledger nano s, by checking my address on neotracker i see the right balance.

**Comment by lukaszek1988** [comment]
I have the same problem. I also use ledger Nano S but my colleagues on the group have the same problem with the NEON wallet. Let's hope it's just a synchronization problem

**Comment by wbnben** [comment]
it's working now.

**Comment by lukaszek1988** [comment]
Ufff thx friend 

;-)

⁣Wysłano z TypeApp ​

W dniu 31 gru 2017, 13:29, o 13:29, użytkownik wbnben <notifications@github.com> napisał:

**Comment by blockmike** [comment]
mine too. thanks for letting me know!

**Comment by francescofarina** [comment]
SOLVED: just wait, it seems to be due to a slow synchronisation.

**Comment by slinkytronic** [comment]
Same problem here.  Seem to be stuck on an old block.  Synchronisation issue I guess then.  I'll keep trying to reload it and hopefully it'll synchronise at some point.  Frustrating to have my NEO inaccessible - when it normally transfers quickly between exchanges.  Hope the wallet continues to develop and synchronises more frequently in future.

**Comment by marcokofi** [comment]
My Neo are safely showing in my wallet now, I guess it was due to the delay in synching at a point in time I thought I had lost them because they took too long.

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 12, 2018 at 17:20, slinkytronic<notifications@github.com> wrote:   
Same problem here. Seem to be stuck on an old block. Synchronisation issue I guess then. I'll keep trying to reload it and hopefully it'll synchronise at some point. Frustrating to have my NEO inaccessible - when it normally transfers quickly between exchanges. Hope the wallet continues to develop and synchronises more frequently in future.
