### ISSUE TITLE
Did i loose my NEOS? 

### ISSUE THREAD

**Issue by tgtcph** [CityOfZion/neon-wallet#434]
I was trying to participate in a NEO based ICO crowdsale for the first time and managed to make a wrong transaction I think. After filling my NEO balance on a wallet version 0.0.6, when the crowdsale opened I didnt send my NEOs under the “participate” in crowdsale column, but from my wallet. So they announced the hash script and i copy pasted it into my wallet and sent 11 NEOs from there , insted the other column. Ever since then it says my NEO balance is 0 and cant log in wuth my encrypted /private key anymore it keeps saying its not valid. 

Can you give me a heads up what happened? 
Thanks a lot! 
Tamas

**Comment by AshRolls** [comment]
This isn't a NEON wallet issue. Please email contact@neo.org for help with your ICO claim.
