### ISSUE TITLE
Windows Defender quarantines Neon 0.0.7 for Windows 

### ISSUE THREAD

**Issue by holymio** [CityOfZion/neon-wallet#438]

**Comment by shawnmclean** [comment]
Check to make sure you downloaded it from github. This should not happen.

**Comment by holymio** [comment]
Downloaded it from github. Someone on Reddit has/had the same problem: https://www.reddit.com/r/NEO/comments/7bc69i/neon_wallet_007_release_with_support_for_nano/dpi5c38/

WIth the 0.0.9 Version this is not happening anymore.
