### ISSUE TITLE
Neon Wallet showing 0 balance and 0 block - Solution?

### ISSUE THREAD

**Issue by cdbbazza** [CityOfZion/neon-wallet#439]
Hi All,

My Neon wallet v7 is showing 0 balance and 0 block on the mainnet, i have checked my public address and the neo and gas is still there.

Do you know why this is happening and a solution? havent heard anything on the neo reddit.

Thanks,

**Comment by rroyster** [comment]
Hi,

I am getting the same thing.  Not able to see my NEO and the NEON wallet keeps telling me that I have to upgrade.  PLEASE HELP.  Thanks.

**Comment by Neddy1** [comment]
Mine is showing a block#, a Neo and Gas Balance but zero dollar value

**Comment by ryanmcgrath** [comment]
At a cursory glance, it's (at least for me) due to CoinMarketCap's API returning an endless 301 loop (via CloudFlare). In a sense, this is a bug for `neon-js` I believe, not this project...

But regardless, it's strange, as it's only the requests from the wallet that have issues. Probably some Electron issue that I'm not familiar with re: caching.

**Comment by francescofarina** [comment]
Same problem here. Showing 0 balance on neon wallet used with the ledger nano s. Checking my address on neotracker gives the exact balance.
I cannot send neo in this way.
Solutions?

**Comment by kogovsekj** [comment]
I have the same problem. 0 balance and no transaction history. I see all my NEOs on neotracker.
I am also using ledger nano s.

**Comment by Frederickvc** [comment]
I'm having the same issue.
Nevertheless checking neotracker.io I can still find my neo back...

Upon opening the ledger app, i was on block 0. Upon checking, while writing this post, block moved to 1.762.423, hope it's just syncing and i'm about to find back my Neo...

**Comment by francescofarina** [comment]
SOLVED: just wait, it seems to be due to a slow synchronisation.

**Comment by vinabraun** [comment]
Facing a similar problem, but it says "Block NaN" and "Claim NaN GAS".

**Comment by cdbbazza** [comment]
Hey Guys, this has happened to me a few times, it seems to be a syncing issue, i gave it sometime and it appears. Just ensure on neotracker using your Public address that the neo and gas is still there, if so i wouldn't worry, just give it sometime

**Comment by vinabraun** [comment]
@cdbbazza some time logged in, you mean?

**Comment by anfn101** [comment]
Try latest version 0.1.2

**Comment by marius-sage** [comment]
Same problem
