### ISSUE TITLE
Cannot Transfer NEO Asset using Ledger Nano S

### ISSUE THREAD

**Issue by mesnia** [CityOfZion/neon-wallet#442]
I cannot transfer my NEO Asset using NEON Ledger Nano S login. How can I make it work?

**Comment by coranos** [comment]
Use the recovery site to recover your WIF, then use your WIF to complete the transfer.

https://coranos.github.io/neo/ledger-nano-s/recovery/

**Comment by mesnia** [comment]
Thanks so much. That worrked

**Comment by mesnia** [comment]
I will close this thread
