### ISSUE TITLE
Neo has been lost from Nano s to exchange

### ISSUE THREAD

**Issue by straightforwardgas** [CityOfZion/neon-wallet#443]
Sent my Neo on my Ledger nano S to an exchange and it has been a full day. Thinking its gone, but my transaction shows its been sent and received by the wallet on the exchange. However is not showing up so where did it go?
https://neotracker.io/tx/9ce1bc6d97da7eeb77c2368fc5c9a1e06c7c6e4da601d73d58211c8958d67bd3
my account on the exchange wallet is showing I sent my Neo out after I received it?
https://neotracker.io/address/ASZJHuHuG4J68VqF9VdhRRReAegKu1uWq8

**Comment by Kmpec** [comment]
Have you contacted the exchange? If the transaction shows up on the blockchain it has been send. But the exchange hasnt credited you the coins.

**Comment by anfn101** [comment]
Github is used to report code issues. Any support can be found in the Discord #support channel. This is likely an exchange issue.
