### ISSUE TITLE
Version 0.0.7 on Windows 10 not opening

### ISSUE THREAD

**Issue by thmstm** [CityOfZion/neon-wallet#445]
I try to use Neon Wallet 0.0.7 on Windows 10 (64 bit). However, after installation from https://neo.org/download the wallet does not open (neither automatically, nor with double click on its icon). Actually, I see it in the Task Manager as running, but no window comes up and no way to switch to it. If I try to open it again, a new (second) running instance appears in the Task Manager. I rebooted, uninstalled and reinstalled a couple of times (also tried installing 0.0.6), but nothing helps. Windows Defender does not catch / quarantie it.

**Comment by codopatr** [comment]
Same issue with version 0.08 and version 0.0.9
also running windows 10 (64 bits)

**Comment by codopatr** [comment]
Ok, I solved my problem

there was a conflict between "Neon Wallet" and another application started in the background

The guilty application is :
- ePowerEvent

this application is part of a group of 3 applications deployed on my computer
- ePowerEvent (Stands for Acer ePower Management Event Handler)
- ePowerSvc (stands for Acer ePower Service)
- ePowerTray (stands for Acer ePower Tray Process Management System)

you have to disable / uninstall this application (or the group)  and it works perfectly

If you do not have this application, I advise you to do a "clean boot"
http://www.thewindowsclub.com/what-is-clean-boot-state-in-windows

if "Neon Wallet" starts after the "clean boot", it means there's a conflict with an application started in the normal boot mode, in this case, restart the PC in a normal boot mode, then kill application after application until finding the conflict (do not forget to kill services also)

Good trading to you

NEO donations : Af6RezPqW3gjQ1gcToXAgUdEahDiaC9FJD

**Comment by thmstm** [comment]
You are great, codopatr!
That was the problem, Acer ePowerEvent.
Thanks a lot!
