### ISSUE TITLE
US $ values zero beginning (I think) at 00:00 UTC Jan 1 2018

### ISSUE THREAD

**Issue by anastrophe** [CityOfZion/neon-wallet#450]
I don't know the exact time, but it seems to coincide with the clock rolling over to New Year's day UTC (I'm in PST, and noticed it early this afternoon.  

Anyway, it's pretty self-explanatory. Instead of showing the approx USD value underneath my NEO and GAS totals, it' just shows $0. 

Screenshot attached.
<img width="325" alt="2018-01-01 01_01_07-neon wallet" src="https://user-images.githubusercontent.com/1012545/34466667-93ec869a-ee90-11e7-95c6-903b3ecb96f3.png">

**Comment by slipo** [comment]
Is this still the case for you/anybody else? I'm seeing dollar values in 0.0.7 + the development branch.

We get that data from coinmarketcap. Maybe they had a little downtime?

**Comment by rgingery23** [comment]
I have had this problem for the last 2-3 days and it continues.  I have the 0.0.7 version downloaded a couple months ago.  Any suggestions.  Thanks.

**Comment by cryptonerd2** [comment]
I have exact same issue for the the past week... I also have the 0.0.7 version for MAC and only see a $0.00 dollar value underneath my NEO. I also have stopped trying to claim my GAS because its getting stuck in transmission. Hope i will be able to move NEO if problem persist.

**Comment by anastrophe** [comment]
Ah - I should add as cryptonerd2 did - my wallet is on Windows, so the issue is cross platform.

**Comment by cyamasaki8** [comment]
Reporting same issue,  $0 value.  First, it was stuck at a value at some point in time a week ago.  I relaunched NEON and it is now zero.

**Comment by anastrophe** [comment]
Just upgraded to 0.0.8. USD balances now showing again. Thanks.
