### ISSUE TITLE
Access to NEON wallet / Decrypt private key?

### ISSUE THREAD

**Issue by jonasrocket** [CityOfZion/neon-wallet#453]
Hi guys, 

sorry for posting this issue here but I hope you can help me or clarify this. 
I think the support channel on the NEO Slack is no longer existing? 

Here's my Issue:
I'm using NEON Wallet 0.0.6 and I did not save my private key. But I do have my encrypted private key and my passphrase. So I can still access the Wallet via the desktop client. But I can't send tokens or participate in a token sale. Is there any way to recover the private key by using the encrypted key and the passphrase.

Any help is very much appreciated!
Thank you,
Jonas

**Comment by YuiRakjit** [comment]
I have a same issue, please help

**Comment by HugoBrynner** [comment]
I have the same problem. Forgot to save the private key. I can still loging with the passphrase

**Comment by jonasrocket** [comment]
Hey guys,
so if you have the decrypted private key (you can check for that in NEON) and the passphrase, you can use this tool: https://snowypowers.github.io/ansy/ to decrypt your private key. 
so just put in the encrypted key, the address of your wallet and your passphrase to recover the private key. hope this helps.

**Comment by YuiRakjit** [comment]
Jonasrocket, Thank you so much.

**Comment by mistermoney83** [comment]
Hi Noob here. I also have a encrypted key that i am trying to decrypt. I got my encrypted key from a wallet-backup from the https://app.antshares.org/ wallet a couple of months ago. I backed it up as a word document, and it shows a couple of keys and also a encrypted key. When i try it on ansy (link above) it doesnt work. Cant figure it out. If someone knows what to do please let me know. And does anyone knows how long a encrypted private key is supposed to be?

**Comment by haklhl** [comment]
@jonasrocket 
I have a same issue, please help
https://snowypowers.github.io/ansy/   why this tool can't accept encrypted key？

**Comment by haklhl** [comment]
I'm already solve this problem，by export&import wallet file(exchange encrypt key),     hahahaha....

**Comment by AdamGeeman** [comment]
I have this issue too. The tool asks for private key not encrypted. How did you solve by export and import wallet file?

**Comment by anfn101** [comment]
Github is used to report code issues. Any support can be found in the Discord #support channel.

**Comment by gilmourjack** [comment]
@jonasrocket you say that i can check for my decrypted private key on neon. how do i go about that so then i can follow the steps that you've provided? im a little confused and worried as i have about 45 neo at stake here
