### ISSUE TITLE
If I'm using the NEO wallet with Ledger, do I have to create a new wallet first on the Neo wallet client?

### ISSUE THREAD

**Issue by jaydee888** [CityOfZion/neon-wallet#457]
I have my NEO with Bittrex and intend to send it to the Ledger. But Ledger works with the Neo Wallet. I like to know if I have to create a new wallet with the Neo wallet client first or I do not need to.

Can I send my NEO using the receiving address that I get from the Ledger?

Note: My assumption of using the Ledge is that it is more secure, because if it is the same, I don't see why I should need to use the Ledger.

**Comment by anfn101** [comment]
Github is used to report code issues. Any support can be found in the Discord #support channel.
