### ISSUE TITLE
If I have sent 1 NEO to my Ledger, how can I send this 1 NEO to an exchange to sell it?

### ISSUE THREAD

**Issue by jaydee888** [CityOfZion/neon-wallet#458]
NEO only accepts sending and receiving of whole number.

Now I have sent ! NEO to my Ledger. I intend to send this 1 NEO to Bittrex or Binance to sell it.

However, I assume there will be transaction fee involved. Deducting the transaction fee off, I will be left with a fraction of 1 NEO. Surely I will end up not able to send a fraction of NEO or it will be lost.

What is your advice for a situation like this?

**Comment by martijnlaan** [comment]
As Readme.md says support questions "should be asked in proper support channels such as the [NEO subreddit](https://www.reddit.com/r/NEO/), or the official [NEO Discord Channel](https://discord.gg/R8v48YA). You should also check the list of [frequently asked questions (FAQ)](https://github.com/CityOfZion/awesome-NEO/blob/master/resources/faq.md) to see if your question has been answered there already."

From the FAQ:

"_Is there a transfer fee between NEO wallets?_
There is no transfer fee for now. You can transfer NEO or GAS without extra costs. This might change in the future.

_Is there a transfer fee between NEO wallets and exchanges?_
It depends on the exchange rules; right now, there is no transfer fee in the NEO system. However, exchanges can take a fee when transferring from an exchange."
