### ISSUE TITLE
Can't copy/paste the addresses on Ubuntu Linux.

### ISSUE THREAD

**Issue by jaronfitz** [CityOfZion/neon-wallet#46]
I can click the copy buttons and highlight/use copy shortcuts, but it doesnt actually capture.

**Comment by Ejhfast** [comment]
also, would be great to allow right click copy/paste on windows/mac

**Comment by dop89** [comment]
Hi,

I have experienced the same issue. The reason is the second parameter of the `clipboard.writeText()` function. Without this "type" parameter, everything works fine on Arch Linux. I can create a PR for this fix.
