### ISSUE TITLE
White screen after using 'MAX' function on send screen [0.0.8]

### ISSUE THREAD

**Issue by Freekje** [CityOfZion/neon-wallet#469]
Found replicable issue in 0.0.8 : 

Go to Send , use the 'max' function & select recipient , press send and screen goes white.
Tested this for gas & neo. Manually filling in the max number lets you go to the next page.

**Comment by mhuggins** [comment]
Thanks for reporting.  @dvdschwrtz found the cause and is working on a fix.  Stay tuned.

**Comment by evgenyboxer** [comment]
This is now fixed on 0.0.9
