### ISSUE TITLE
Total NEO not showing correctly

### ISSUE THREAD

**Issue by bouncyenemy** [CityOfZion/neon-wallet#47]
I transferred 3.0 NEO from my Bittrex account to my NEON wallet. After the Bittrex fee, what shows is that 2.9 NEO was sent to my wallet, but in my NEON wallet only 2 NEO show.

Does this wallet round up or something? Where did the other 0.9 NEO go?

Thanks for your help. I hope this question makes sense.

**Comment by Ejhfast** [comment]
This is not a problem with Neon. Unfortunately, Bittrex took your Neo. Their policy on fees is horrible terrible. See: https://www.reddit.com/r/NEO/comments/6s2ttd/bittrex_transfer_fee_is_now_01_ans/dl9q4oy/
