### ISSUE TITLE
Cannot login to wallet after 0.0.8 update (Windows)

### ISSUE THREAD

**Issue by greenstreetbud** [CityOfZion/neon-wallet#470]
When I try to access my desktop wallet it gets stuck on loading screen. Already tried to un and re-install but did not work, I keep getting two errors on screen "could not retrieve XRP"/DCB balance and from there it seems stuck in a loop. 
Any advice?

Thanks,
PM

**Comment by qazman250** [comment]
I am having this issue as well. Any help would be appreciated. Thanks

**Comment by jameejay** [comment]
Same issue here. My private key no longer allows me to log into wallet.

**Comment by anfn101** [comment]
Try version 0.1.2
