### ISSUE TITLE
Hi, I sent 5 NEO to 0xb951ecbbc5fe37a9c280a76cb0ce0014827294cf when trying to fund my DeepBrainChain Token Sale on Dec 15, but it is missing.  Any help would be appreciated, cheers

### ISSUE THREAD

**Issue by Peter13k** [CityOfZion/neon-wallet#474]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by valdor27** [comment]
You sent NEO to an Ethereum address. NEO must be sent to a NEO address (starting with A). I'm afraid there is no way to recover your 5 NEO.
