### ISSUE TITLE
My online Neo Tracker and Neon Wallet are showing a balance of $0

### ISSUE THREAD

**Issue by Simone1248** [CityOfZion/neon-wallet#476]
Hi,

I sent one Neo coin from Coinspot to my Neon Wallet yesterday and the status says sent. 

I looked on my online Neotracker account and my neon wallet and they both say $0.00 and have no transactions recorded.

Can you please help?

**Comment by rohanstas** [comment]
reinstall the wallet and it should work.

**Comment by Dhackers101** [comment]
Has this issue been resolved I am having the same issue today
