### ISSUE TITLE
Transaction failed

### ISSUE THREAD

**Issue by mvg-tinus** [CityOfZion/neon-wallet#481]
Hi, when I log in using a ledger Nano S and try to claim gas (NEON version 0.08) I receive the error 'Transaction failed'. This also appears when I try to send GAS. Please advise.

**Comment by valdor27** [comment]
Hello, you have to uninstall & install again the app on your ledger nano S.

**Comment by mvg-tinus** [comment]
Hi, I just did. I reinstalled both on my PC (and Mac) the app, as well as the app on my Nano S. But unfortunately, on both devices I get the Transaction failed message. Thanks in advance for your help.

**Comment by valdor27** [comment]
maybe have a look here #466. Developpers are working on a fix.

**Comment by valdor27** [comment]
maybe have a look here #466. Not sure if this applies to you though, but I know you're not the only one with this bug.

**Comment by mvg-tinus** [comment]
Can you update once developers have a bugfix released? Thanks again for your good support.

**Comment by mortyblack** [comment]
I have the same problem. Today release did not help.

**Comment by Bybloz** [comment]
I too have the same problem.  I cannot send any GAS out of my Nano S.  May I know how do you re-install the app on the Nano?

**Comment by anfn101** [comment]
Try version 0.1.2, and reinstall both the Neo app and Neon wallet. Make sure your firewall is not the issue. ALSO NOTE: Github is used to report code issues. Any support can be found in the Discord #support channel.
