### ISSUE TITLE
0.0.9 Linux AppImage: transaction history fails to load + no QLC token

### ISSUE THREAD

**Issue by abstrakct** [CityOfZion/neon-wallet#487]
I just downloaded the 0.0.9 Linux AppImage from the Releases page. When I login to my wallet, it shows the correct balance, but the program seems to be stuck on trying to load the transaction history. The animation in the top right corner plays, but transaction history says "No transactions". If I use the 0.0.8 AppImage, the transaction history shows up correctly right after logging in.

Also, the QLC token isn't displayed, neither in the list below the "Claim GAS" button, nor in the list of assets to choose from when I click the Send button.

In the top of the window it says the version is 0.0.9.

Maybe the appimage build didn't include this commit: 710936d6a9176854fb87cba4434620c5ace8984a  ?

**Comment by evgenyboxer** [comment]
This is now fixed! Please redownload the file.

**Comment by abstrakct** [comment]
Thank you! Just tested it, all good now!
