### ISSUE TITLE
Neon processes still running in the background after app closes

### ISSUE THREAD

**Issue by geraldhorn** [CityOfZion/neon-wallet#49]
When Neon (Win) starts, 2 processes appear to be running in the background and persist even after the app has been closed.

The processes stack indefinitely every time the app is opened, using roughly ~50mb of memory per instance.

**Comment by canesin** [comment]
electron (the framework used) starts two processes, one nodejs and one blink .. blink grabs ~35mb ram just to start... that is the price for multi platform and other niceties .. The issue here is only killing the process correctly on window close.

**Comment by ob7** [comment]
I confirm that the process stays open until manually killed via CTRL C ( if launching Neon from terminal )

**Comment by shawnmclean** [comment]
We won't have control over this as its an electron issue. Closing.
