### ISSUE TITLE
Claiming gas after a long time not claiming

### ISSUE THREAD

**Issue by bharathor** [CityOfZion/neon-wallet#495]
Hi,

i had some problems claiming gas on a account where i didnt claim the gas for about 5 month. After using the "claim gas" button in the neon wallet i just got a error stating "transaction failed". I tried some other wallets, for example neotracker.io wallet, where i wasnt been able to claim the gas as well. What did work for me was using the wallet under https://neowallet.cn/, even though the neo values there where at least 12 hours old.
It looks like im not the only one with that problem, at least one other person had the exactly same problem. That person documented it on reddit as well: https://www.reddit.com/r/NEO/comments/7opssi/daily_discussion_january_8th_2018/dsbcrwf/

Regards,

Bharathor

**Comment by DalderupMaurice** [comment]
Same problem.
I was able to claim gas a couple times - left for a good 2 months and tried to claim again. Now it never actually works. I got a success message, but no actual transaction was made and I have never ever received my GAS

**Comment by jperezov** [comment]
+1, same problem.

![neo-failed-claim](https://user-images.githubusercontent.com/5150308/34652281-2c1d4850-f3aa-11e7-8e76-7fa05e4fec5a.png)

**Comment by DalderupMaurice** [comment]
Fixed it with moving all my NEO to a new wallet @jperezov @bharathor 
After a couple tries (in the 20 tries) I was able to claim the GAS on the old account using: https://neotracker.io/wallet and also sent the GAS to my new account!

**Comment by jperezov** [comment]
Thank you so much @DalderupMaurice! That worked for me!

**Comment by jayddaniels** [comment]
Same problem, claiming doesnt work on any neo wallet, be it web or desktop

**Comment by DalderupMaurice** [comment]
Tried creating a completely new wallet as I stated above? 
It is possible you still have an old address!

**Comment by Blckhd** [comment]
If you use nano must say yes on dev
