### ISSUE TITLE
No Balances are showing since yesterday (Ledger All Versions Updated)

### ISSUE THREAD

**Issue by nyyn** [CityOfZion/neon-wallet#502]
Hey,

I updated the Ledger App over the App Manager (Ledger Nano S) and updated to 0.0.9 on Mac

At first i could still only send max 999 DBC. But DBC, RPX, NEO & GAS showed up. Sometime yesterday DBC didn't show up anymore and now nothing shows up. The Wallet gives an orange warning on the bottom: "Warning
Error checking wallet version! Please make sure you have downloaded the latest version: https://github.com/CityOfZion/neon-wallet/releases"

Checked my Wallet Adress all funds seem to be there.

Thanks for your help, i attached a Screenshot.

![screen shot 2018-01-09 at 11 06 33](https://user-images.githubusercontent.com/5766074/34715499-2fc74b16-f52d-11e7-83e3-67989007704e.png)

**Comment by nyyn** [comment]
Re installed Application on Mac & on Ledger multiple times. Can't retrieve any Balances.

**Comment by neocommunitynate** [comment]
I am also facing the same issue. I joined the discord and searched through the support channel and still cannot find a resolution. Upon upgrading the wallet from the link provided by neon the new wallet is version 0.0.9 and the tokens do not reflect in this version. The pop up states to upgrade to version 1.1 but cannot seem to find that..

**Comment by michel242** [comment]
same problem here updated the app on my ledger to 1.1. and using the 0.0.9 neon wallet but no balance rpx

**Comment by advisor65** [comment]
same problem here also... Why is this happening? yesterday it was fine and i had no problem....

**Comment by neocommunitynate** [comment]
There are also a few of us in the discord support channel with the same issues. Is your issues only with DBC or are you having troubles having other tokens reflect in the wallet? I have also tried my encrypted key/ private key with no luck. Would love some additional insight. Thanks for your time!

**Comment by BazkieBumpercar** [comment]
I have the same problem, with 0.0.9, both the Linux and the Windows version.
Can't see my DBC balance (same error as op, that red popup thingy), but I can see the Neon+Gas balance. It also gives me an error for the RPX balance (but I don't have any of that anyway).

**Comment by LindyLo** [comment]
MacOS 10.13.2 (17C88)
Ledger NEO 1.1
NEON 0.0.9
Only shows NEO & GAS balance.

**Comment by neocommunitynate** [comment]
Thank you Lindy. With regards to QLC/ DBC how do we have visibility then? Is it a patch we have to wait for or something?

**Comment by tarung379** [comment]
I am facing the same issue with RPX.

**Comment by LindyLo** [comment]
To anyone who is concerned about the status of your assets : 
You can always check you wallet address https://neotracker.io/

**Comment by Jmanman** [comment]
Same issues with showing NEP5 tokens. I tried to claim gas and will not send the signed transaction prompts to the ledger. Need this fixed so i can participate in TheKEY public release sale. haha talk about bad timing. I haven't tried sending any Neo to an exchange though. anyone able to send Neo coin?

**Comment by LazyInDFW** [comment]
The network seems to be dragging.  It took forever in the 0.0.7 wallet for my balance to show up.  I still can't claim GAS because my ledger isn't getting the signal to confirm for like 5 minutes after I initiate the transfer.

**Comment by Jmanman** [comment]
Hmm so I made the wrong choice for using the neon wallet for transferring neo to thekey project. It's going to sell out in 10 secs. Hopefully this isn't an issue in a couple days .🤞

**Comment by LazyInDFW** [comment]
Is it the NEON wallet or NEO nodes in general?  Maybe they're slammed BECAUSE of THEKEY?  Don't forget what cryptokitties did to Ethereum.  :)

**Comment by Jmanman** [comment]
When I joined the telegram for TheKey there was 9 k members now there is 22k. So maybe that's what happen.

**Comment by BazkieBumpercar** [comment]
hey, could be! my balance is back now :)

**Comment by neocommunitynate** [comment]
Yep, working. Everything should be fine now! All my nep5 tokens are working and gas is accumulating.

**Comment by marcell32** [comment]
I confirm, at this moment all ok, good work

**Comment by joocru** [comment]
yeah its okay now. working smooth.

**Comment by nyyn** [comment]
Same here, all smooth!

**Comment by JohnChangUK** [comment]
Currently experiencing the problem, the transaction ID won't even show in NEO Tracker. Anyone with the same problem?

**Comment by bincy4776** [comment]
cant claim gas.transaction not prompting on ledger

**Comment by malkazoid** [comment]
This is occurring for me in Neon 0.1.4 on Macos.

**Comment by destrocci** [comment]
same issue here, 0.1.4 mac OS X, Ledger Nano

**Comment by tomasdev** [comment]
@anfn101 why was this issue closed? i'm on 0.2.3, which is the last release and have this issue.
<img width="993" alt="screen shot 2018-04-18 at 6 01 14 pm" src="https://user-images.githubusercontent.com/364033/38960443-8493d1a2-4332-11e8-89d5-71378da36267.png">
