### ISSUE TITLE
Dollar and other currency balance for NEP5

### ISSUE THREAD

**Issue by Melicio** [CityOfZion/neon-wallet#503]
Hello COZ,

Could a function be added to make the dollar or other currency balance visible for NEP5 tokens? Including Total amount combined with NEO and GAS.
This will ensure extra overview comfort for users.

**Comment by csggene3** [comment]
I'd like to look into this. I'm interested in helping valuate the NEP5 tokens and building out the wallet to be able to represent holdings in other currencies as well via the cross-chain framework, but obviously NEO assets first.

**Comment by anfn101** [comment]
@shawnmclean Do you know the state of this?

**Comment by mhuggins** [comment]
@anfn101 @shawnmclean This is a WIP as part of the `design-v2` branch.  See @asalib's mockups here: https://projects.invisionapp.com/share/PAFA74G3T#/screens/274898721

**Comment by Melicio** [comment]
Looks gorgeous, can't wait to actually use this version of NEON Wallet!

**Comment by snowypowers** [comment]
As this is targeted in design-v2 closing the issue as a dup.
