### ISSUE TITLE
Can't upgrade the new version

### ISSUE THREAD

**Issue by Jaeinn** [CityOfZion/neon-wallet#504]
Currently I have the 0.0.8 version on my macbook, i tried to download the new version but for some reasons it does not open on my macbook. I deleted it and tried redownload it, this time it opens a map. But this map is empty, and shows the titel 0.0.8? 
  
![schermafbeelding 2018-01-09 om 15 55 49](https://user-images.githubusercontent.com/35262949/34726886-97e5cac4-f555-11e7-98d2-3dede2473221.png)

**Comment by anfn101** [comment]
Github is used to report code issues. Any support can be found in the Discord #support channel.
