### ISSUE TITLE
Can't retrieve token balances or transactions

### ISSUE THREAD

**Issue by cryptocreep** [CityOfZion/neon-wallet#508]
My GAS balance shows up but my DBC balance can't be retrieved in wallet. Shows no transactions ever taken place.

**Comment by ris0** [comment]
Hello - I would also like to second this. I'm not able to view any of my NEP5 tokens with Neon 0.0.9 for Windows.

**Comment by cryptocreep** [comment]
Same OS and Neon version.

**Comment by P2NPoison** [comment]
Same here

**Comment by joocru** [comment]
after i tried 5 times to login neon with ledger nano s. 5th time i can see my balance. so dont worry. cant refresh nep5 tokens only. We dont loose our funds dont worry guys only sync problem i think.

**Comment by cryptocreep** [comment]
If you're looking to move your DBC before it opens on the other exchange I used NeoTracker to access my wallet with private key and xfer my DBC to another wallet.

**Comment by joocru** [comment]
neontracker also doesnt work atm. cant use retrying to send RPX but failed.

**Comment by P2NPoison** [comment]
joocru, its pretty obvious that we do not lose our funds just because the wallet cannot display them, but is not too comfortable don't being able to send them if we need to. 

PS: Your funds are not in your ledger! Your funds are in your wallet, in each blockchain of each coin you own. You just store the private keys in the ledger, not tokens.

**Comment by joocru** [comment]
yea mate i know our tokens are in blockchain ledger just a ambassador. but it doesnt feel comfortable. when its not syncing and cant see our balances :) i feel bad when its happening.

**Comment by P2NPoison** [comment]
indeed haha

**Comment by Adie56** [comment]
Cannot Retrieve GAS either

**Comment by marcell32** [comment]
I have the same problem, gas/neo/rpx end other

**Comment by Niels1990** [comment]
@P2NPoison but what if I update my neon app version on my ledger? Will a new private key be generated and therefore I lose all of my funds? I need to update my neo app version to 1.1.1 on my ledger. But I am anxious about losing my funds when updating it... help me please

**Comment by P2NPoison** [comment]
Your fund will be in your neo wallet, in the blockchain. Don't worry.

**Comment by Niels1990** [comment]
@P2NPoison alright. But the private key is generated by my ledger nano s. I am afraid that when I update the neo app on my ledger, my ledger will generate a new private key and therefore I cannot access my "old" wallet with all my funds.

**Comment by P2NPoison** [comment]
I don't think so. Let someone answer the question!

**Comment by sbglive** [comment]
Any news on this topic ? I am still having the issue after the update. It is quite annoying such a bug on a dedicated NEO wallet ... for more than 20 days.

**Comment by vinny76** [comment]
on Mac I found I hadn't ejected the new dmg loader,when  I ejected the loader my DBC Tokens showed up
