### ISSUE TITLE
Neon wallet keep on loading

### ISSUE THREAD

**Issue by ikashi08** [CityOfZion/neon-wallet#509]
The new version of neon wallet is keep on loading and it prompt me to install the new version though i already use the newest version of the wallet.

**Comment by joocru** [comment]
getting this error . -------- Error checking wallet version! Please make sure you have downloaded the latest version: https://github.com/CityOfZion/neon-wallet/releases …  


i am using 0.0.9 also neo 1.1.1 ledger app. latest firmware also.

**Comment by Adie56** [comment]
I am having the same issue. it just keep loading over and over again. I downloaded the latest version this morning for Mac. version 0.09 Screen shot available.

**Comment by Badass888** [comment]
I'm getting the saem issue too - it was working fine yesterday

**Comment by mihavidakovic** [comment]
Same issue, also error loading all of the 3 tokens values (could not retrieve RPX balance). MacOS High Sierra, Neon wallet v0.0.9

**Comment by FalnoX** [comment]
Same issues here:
- Loading takes ages
- Message about not being able to retrieve GAS/DBC/RPX balances
- Cant send GAS

Versions:
- Neon wallet v0.0.9
- MacOS High Sierra 10.13.2

**Comment by puffidredz** [comment]
getting same error. it was just working 8 hours ago

**Comment by SolomonAlma** [comment]
Same issues as mentioned above. version update request although version is already updated, and could not retrieve gas/dbc/rpx balance

**Comment by fazzx** [comment]
I got the same issue at above, any fixes?

**Comment by SolomonAlma** [comment]
Not yet. Refrain from ledger neon combination till issue is adressed.
Consider using neon desktop wallet solo

בתאריך 15 בינו' 2018 4:17,‏ "fazzx" <notifications@github.com> כתב:

**Comment by whi5key123** [comment]
same issue here

**Comment by hvson2010** [comment]
![capture2](https://user-images.githubusercontent.com/35896422/35605012-56a24928-0678-11e8-9edc-253f66eccdc6.png)

I use laptop Dell and install neo app v0.1.0, then v0.1.1 and then v0.1.2 but I still met error "Error checking wallet version....". Please help me fix it :(

**Comment by stevesbrain** [comment]
@hvson2010 I've opened a ticket for the same; #638
