### ISSUE TITLE
Upgraded Ledger Nano to v 1.1.1 and NEON to 0.0.9 - Now cannot claim GAS and "Cannot Retrieve Token balances" appears all the time

### ISSUE THREAD

**Issue by Thieazs** [CityOfZion/neon-wallet#511]
Hello - Updated Ledger Nano 1.1.1 and Neon to 0.0.9 - First says check wallet version (which is the new one), then Error could not retrieve DBC balance, same for RPX and QLC.  Correct balance and Gas shows.  Click claim gas and it says sign transaction 1 of 2 but there is no option to sign on the ledger device - it just remains saying "Wake up Neo" - Can you help?

Mac OS High Sierra v 10.13.2

**Comment by joocru** [comment]
ledger and neon sync problem atm. neon team will solve this problem soon dont worry mate.

**Comment by Thieazs** [comment]
Thanks joocru good to know 
- always terrified when I cant see it working - love my sweet NEO :)

**Comment by joocru** [comment]
you are welcome. yeah same lol :) i allways checking my balance like crazy haha

**Comment by amirardat86** [comment]
any word yet on the problem?Cant seem to find any help.

**Comment by Niels1990** [comment]
@Thieazs how do you update the neo app on the Ledger? I am so afraid of losing my private key when uninstalling the current neo app version and then updating it. Coul dyou please help me which steps to take?

**Comment by stechico** [comment]
@Niels1990 I did this yesterday. Based on my experience, I had to delete the NEO app from my Ledger using the Ledger app. Then, installed NEO app 1.1.1 into the Ledger.

Also, private keys never leave the Ledger.

**Comment by amirardat86** [comment]
I did all that already,I can seem to send anything under 1000 but over no?

**Comment by amirardat86** [comment]
Just looking there I’ve got version 0.0.9 where do I get the new one?

**Comment by stechico** [comment]
@amirardat86 0.0.9 from what I have/know is the latest NEON client. v1.1.1 is for the Ledger-NEO app from LedgerHQ

**Comment by Jmanman** [comment]
Same I have neo to send for an ico aswell. I'm worried the 25k people drag down the neon wallet server and will cause me to miss this opportunity. I was able to claim gas but didnt try to send any neo yet.

**Comment by Jmanman** [comment]
I still have issues seeing DBC and my qlc tokens. It was working for a brief moment but is now showing a zero balance. I can transfer one Neo at a time though and I can claim neo gas

**Comment by dc51111** [comment]
i couldnt claim my gas, and failed to transfer my gas to kucoin.

**Comment by brtausi** [comment]
I have the same problem, I installed both the latest Ledger Nano S app and uninstalled, re-installed the NEON program for windows. I get 3 red pop-ups saying it could not retrieve the balances, while I got RPX on that address. It does shows the right amount of NEO and GAS.

**Comment by JohnChangUK** [comment]
Got the same problem for Mac. Got the latest NEO 1.1.1 on the ledger, 0.0.9 Neon Release, sent QLC to the NEO public address but won't show. Also the transaction ID doesn't seem to be valid when i check on NEO Tracker.

**Comment by Jmanman** [comment]
Mine is working fine for windows. Great! hope she lasts for TheKEY sale. fingers crossed

**Comment by Con7e** [comment]
Mac OS "El Capitan" here. I was able to send/receive NEO/GAS on my ledger fine for like 1 day. Now I am unable to send NEO/GAS as every time I sign the transaction oin my ledger the app on the mac says "transaction failed".

Also, my DBC balance shows now 0 as it's not able to show it for some reason.

The app is now basically holding hostage my entire balance... I should have left it on the web wallet instead of this extremely buggy app :(. No idea what to do exactly as I have the latest updates...

**Comment by b3hemoth** [comment]
need access to qlc but still showing zero in neon/nano s... where are my coins? anyone have a fix for this?

**Comment by anfn101** [comment]
Try latest version, 0.1.2
