### ISSUE TITLE
RPX shows 0 (zero) balance - SOLVED

### ISSUE THREAD

**Issue by gripin** [CityOfZion/neon-wallet#512]
same here.
just updated NEON wallet to 0.0.9 and my ledger app to 1.1.1 - latest versions. 
i see my NEO and claimed my GAS - so far so gut
but all my RPX shows 0 (zero) balance. 
there were visible in the pre-pre-ico-verision of NEON (0.0.6)
is this issue know? 
thank you

**Comment by hysel** [comment]
same here

**Comment by Setemi** [comment]
Same here

**Comment by Lynaj** [comment]
same here =c

**Comment by gripin** [comment]
hello to all
i just solved my problem - oh - silly me :-/
i opened NEON wallet 0.0.9 with my previous private key (not with ledger ) - and there are all my coins - i will now try to send them to my ledger wallet - cross fingers
