### ISSUE TITLE
Neon 0.0.9 - "hold at least 1 drop of GAS" error when sending QLC

### ISSUE THREAD

**Issue by martellalex** [CityOfZion/neon-wallet#515]
Steps to reproduce:
- log in to Neon wallet with private key
- click on send button
- select QLC asset

Error experienced:
See screenshot below.  UI disables sending of QLC asset with an error that says "Sending NEP5 tokens requires holding at least 1 drop of GAS"
 
![image](https://user-images.githubusercontent.com/8480779/34808136-00514fca-f6e1-11e7-9889-3f459f921d21.png)

GAS balance is 0.2 in the account.  Also using Neotracker I can send QLC asset with the current GAS balance.

**Comment by Asubayo** [comment]
Got the same issue while trying to send DBC from the neon wallet. Why 1 GAS is needed ? Do we really need to hold at least 1 GAS or does that mean that the fee to send DBC is 1 GAS (hope not^^) ?

**Comment by anfn101** [comment]
The smallest amount you can have. Try 0.1.2. Also note: Github is used to report code issues. Any support can be found in the Discord #support channel.
