### ISSUE TITLE
Cannot install Neon.Setup.0.0.9.Windows.exe on Desktop running Windows 10

### ISSUE THREAD

**Issue by Kuinuka** [CityOfZion/neon-wallet#516]
I cannot install Neon.Setup.0.0.9.Windows.exe on Desktop running Windows 10 

**Error description:** 

"This app can’t run on your PC. 
To find a version for your PC, check with the software publisher." 

**See screenshot of error description below:** 

![neon setup issue windows 10](https://user-images.githubusercontent.com/35321599/34808243-4d93a012-f696-11e7-9a08-57ab8fabfea6.png)

**Comment by jhepkema** [comment]
Please ask questions such as these in the #support channel of the [NEO Discord](https://discord.gg/R8v48YA); there are more people available to help you there.

Have you tried installing the newer wallet (version 0.1.1)?
