### ISSUE TITLE
Cannot Send GAS out of my NEON wallet v0.0.9 in Ledger Nano S

### ISSUE THREAD

**Issue by fylim** [CityOfZion/neon-wallet#517]
Hi all,

I am unable to send out gas from my NEON wallet in Ledger Nano S. 

I get the error "Transaction failed" after signing the transaction on the ledger. 

Please help. Thank you.

**Comment by GvidoKarlis** [comment]
SAME HERE :/

**Comment by stevesbrain** [comment]
Have you guys tried different USB cables by any chance?

**Comment by fylim** [comment]
Just an update. It worked after using recovery. Connecting to testnet and back to mainnet didn't help

**Comment by fylim** [comment]
Apologies pls ignore previous comment about using recovery. Was not related. 

The actual fix for me was to use a direct internet connection rather than my office proxy.  Perhaps a network connection status in the client would be helpful. However note the client was able to read my address and contents but just cant send.

**Comment by stevesbrain** [comment]
@fylim Haven't looked at the code, but perhaps balance is retrieved from neotracker, and sending is done by connection to CoZ's blockchain servers (which are therefore blocked)?

**Comment by ToeJamathon** [comment]
I'm having this issue also. Neon wallet 0.1.1 + Ledger Nano S. I can send NEO from the wallet, but not GAS. How would I know if my home Internet is blocking the GAS transactions? As soon as I try to send the GAS, it just shows the red error, and doesn't transmit to the Ledger, so it seems like it immediately hits a wall.

**Comment by GvidoKarlis** [comment]
@stevesbrain i just tried, same conclusion
