### ISSUE TITLE
enhancement: login with encrypted keyfile. 

### ISSUE THREAD

**Issue by dennish007** [CityOfZion/neon-wallet#52]
I generated a wallet with former web wallet interface which created a password encrypted key file. 
Login with key file makes it more secure.

**Comment by canesin** [comment]
see #29

**Comment by dennish007** [comment]
That is not why I intended. I was not suggesting saving the private key file in the NEON app so that NEON is responsible for storing (issue #29). NEON just should support opening and reading a keyfile, ask for the password, descrypt it and use that private key for the session just like login with the privatekey.

**Comment by totalvm** [comment]
fixed in 0.0.5
