### ISSUE TITLE
Can Trinity NEP-5 tokens(TNC) be Listed on NEON Wallet,Please?

### ISSUE THREAD

**Issue by LolaXIE07** [CityOfZion/neon-wallet#521]
Hi , Neon Team

I am from the Trinity

I am wondering if you can help me with the trinity tokens (NEP-5) listed on Neon Wallet

Our website is https://trinity.tech/

And our script hash is:0x08e8c4400f1af2c20c28e0018f29535eb85d15b6

Please if you see this request and have some other requirements about adding the tnc to the NEP-5 Tokens, please contact me at: lolaxie_shanghai@163.com

Have a nice day~

Lola

**Comment by harrybenc** [comment]
Hi there

I still did not see TNC in Neon Wallet 0.1.1
Do you plan to add this token?

Tks

**Comment by tsaiDavid** [comment]
@LolaXIE07 - the "script hash" you included doesn't seem to be valid [correct me if I'm wrong, anyone]. It appears the Trinity contract address is:
`08e8c4400f1af2c20c28e0018f29535eb85d15b6`

https://neotracker.io/contract/08e8c4400f1af2c20c28e0018f29535eb85d15b6

@shawnmclean - I can help with this, would be happy to

**Comment by Stanley-Lim** [comment]
Hi all, 

can anyone confirm whether the hash is correct for trinity token storage on NEON wallet?

Cheers,
Stan

**Comment by LolaXIE07** [comment]
Hi. When u add script hash , please delete the front first 2 digits'ox' and try again




| |
Lola Xie
邮箱：lolaxie_shanghai@163.com
|

签名由 网易邮箱大师 定制

On 01/29/2018 13:56, Stanley-Lim wrote:

Hi all,

can anyone confirm whether the hash is correct for trinity token storage on NEON wallet?

Cheers,
Stan

**Comment by tsaiDavid** [comment]
@LolaXIE07 @Stanley-Lim - Gotcha, I'll take care of it

**Comment by mhuggins** [comment]
Users can add their own tokens through the settings screen now, so anyone can add TNC as long as they have version 0.1.0 or above.

**Comment by brianlenz** [comment]
@mhuggins, just trying to understand how this will work: does this mean that every user who wants to view/transfer TNC will have to manually add the script hash to the Neon wallet? And therefore the same goes for any other new tokens? Just thinking about usability and how users will participate in new token sales and view the tokens in their wallet. It would be neat if everyone didn't have to manually copy & paste the script hash to use a new token, but I can also see how it becomes a bit of a scalability problem as many new tokens get added to the ecosystem...

**Comment by Stanley-Lim** [comment]
Apparently, it cost 1 GAS to withdraw TNC from the NEON wallet? That is insane. Is there another option to get around this? Please advise.

@LolaXIE07 Is there other wallets for TNC that do not require fee for transactions? Please help. 

This is inconvenience as you need tons of GAS just to transfer NEP-5 tokens back and forth to be safe. 
Also, I lost half of my NEO tokens when sending tokens from NEON wallet to KuCoin. Any advise what I can do to get the rest back?

The NEON wallet initially said the transaction with the NEO token failed, then I did it again and it went through successfully. However, the first try apparently also went through. The problem is KuCoin did only receive the second transaction. 
When I checked on Neotracker, it says "spent" for the first transaction but "unspent" for the second transaction. Any idea what that means? 

Appreciate any help to solve this problem.

**Comment by mhuggins** [comment]
@Stanley-Lim No, it does not cost GAS.  The GAS will be sent to your own address, but sending a token right now cannot be done without 0.00000001 GAS in your wallet.

**Comment by Stanley-Lim** [comment]
@mhuggins thank you for the info. I just tried. Now, a bigger problem occured. I lost all my Trinity Tokens when I tried to sent it to Kucoin. Any advise?

**Comment by mhuggins** [comment]
@brianlenz 

> does this mean that every user who wants to view/transfer TNC will have to manually add the script hash to the Neon wallet?

Yes, this can be done through the settings screen in newer versions of NEON Wallet.

> I can also see how it becomes a bit of a scalability problem as many new tokens get added to the ecosystem...

That's exactly why we did it this way.  We don't want to have to get a new release out for every single NEP-5 token that is launched.  This behavior is similar to other wallets such as MyEtherWallet.

**Comment by mhuggins** [comment]
@Stanley-Lim That's not enough info to work from.  How did you send them?  What address did you send to?  Does the address you sent to match Kucoin?  What is the transaction ID?  How much time did you give Kucoin to notice the transaction in the blockchain?

**Comment by Stanley-Lim** [comment]
@mhuggins Appreciate your help. The same way I send NEO tokens but indeed to my trinity wallet at Kucoin instead.
 
It only took a few minutes for NEO to be deposited and I could see the transaction history on the NEON wallet. For TNC nothing is shown in the transaction history in the wallet. 
Now, I just checked the NEOtracker wallet and apparently the TNC are still shown there (but my NEO mentioned before in the previous post is still missing).

What do you mean by "How much time did you give Kucoin to notice the transaction in the blockchain?" - correct, me if I am wrong, my understanding is that TNC should be faster than NEO?

**Comment by mloots** [comment]
Hi all.

I sent 17 TNC twice yesterday to my Neon wallet. I gave it a day now, but the TNC balance in the wallet is still 0.00.

I can believe it arrived properly and is not lost in limbo, but the wallet does not show it... :(
I don't know if it helps: this is one of my transactions yesterday: 82135aca97a74fd6ebc769b3051851b9ac116a9302653442ad6fe3910d60a829

-Martijn

**Comment by Stanley-Lim** [comment]
@mloots Did you add hash "08e8c4400f1af2c20c28e0018f29535eb85d15b6"?
else check your balance on Neotracker.

**Comment by mloots** [comment]
@Stanley-Lim Thanks for the reply. Yes; when I added the hash, the token TNC showed in the list of the wallet. Hmm, I sent it from Kucoin and it does not show in my balance on Neotracker. I don't know how to read the transaction details on there, I only see data in the invocation and verification scripts having some information.

**Comment by Stanley-Lim** [comment]
@mloots When I send TNC tokens (also from Kucoin to Neon wallet), I can see the TNC transfer data under transfers and not transactions. 

However, I lost a good portion of NEO tokens when I transfered my NEO from NEON to Kucoin. What I can tell is that it is somehow stucked in the system. Learning from other post, I have not seen people were able to retrieve their coins/tokens. Sadly enough.

**Comment by mloots** [comment]
@Stanley-Lim Okay, good thing I tried with just a small amount then. Can we conclude that the combination Kucoin/NEO is not optimal and other exchanges have no or less issues? Or is this more common in the NEO realm at the moment?

**Comment by mloots** [comment]
I moved it via ETH to gate.io exchange and withdraw from there. No issues now. All in all, it cost me TNC 100 in missing withdrawals and fees, but it had cost me the entire balance if I hadn't tried it first with small amounts... IMHO: just use gate.io for TNC.

**Comment by anfn101** [comment]
Github is used to report code issues. Any support can be found in the Discord #support channel.
