### ISSUE TITLE
0.0.9 Neon Wallet - Claim Gas "Claim Failed"

### ISSUE THREAD

**Issue by XxXGyverXxX** [CityOfZion/neon-wallet#522]
I am writing to confirm a gas claim fail on the Mac - 0.0.9v of the Neon wallet.  I have seen this issue in text multiple times however, i am having trouble finding a solution.

**Comment by mrz1836** [comment]
I am having the same issue, however my hunch is that the wallet address was from AntShares before it was NEO. I constantly get "Claim failed" and the gas claim is not in the neo block explorer. I'd love to work with someone on debugging this issue, as I feel a lot of people might be experiencing this issue.
