### ISSUE TITLE
NO coins in the wallet.

### ISSUE THREAD

**Issue by Evgeny1986** [CityOfZion/neon-wallet#523]
Hello!
Help me please. I bought 19 NEO on the exchange and sent them for storage in a purse NEON. 
The address of my purse: AN4FMbGefBGpBYCMJW1dKjEbm9kPjdghao
A couple of days ago I went to the purse and found I had no coins.
I went to https://neotracker.io/tx/8202dc123540d009c20ce3b7eb1b4e6944b39ad7b4a5074cfaf1a026f7ec0c37
I discovered that my coins transferred to the wallet AKL1VMWPsW9qHWrwh8TYz9NJGU6GC561ca
I coins never been transferred!!!
my coins stolen.

**Comment by Evgeny1986** [comment]
I also wrote in contact@neo.org

**Comment by OrEagle97327** [comment]
Thank you for posting to #524. Were you using the Neon wallet with Ledger Nano S?

**Comment by OrEagle97327** [comment]
What exchange did you transfer from?

**Comment by MorganLester** [comment]
Same issue happened to me. setup everything fine. Sent one test then another 6 coins. Connected nano to same machine and everything and zero balance and new address.

Address: https://neotracker.io/address/AQVkV9SxYVxDJfyturJwzD7w38gtWnBzkV

**Comment by MorganLester** [comment]
I sent from Binance fwiw, and have all records...

**Comment by OrEagle97327** [comment]
"Evgeny1986"  I am trying to compare notes. 
(Before the problem) Using the Ledger;  Did you go into Ledger settings or security settings at all?  Even if you did not make any changes?

**Comment by Evgeny1986** [comment]
Hello! On the forum I can't write as beginners there is a restriction. To my problem I went to the wallet and everything was in order. I can't understand how did my tokens. The tracker shows that my tokens were sent to another wallet.

**Comment by OrEagle97327** [comment]
It is free to join Gethub do not wait to sigh up

we can compare notes better

thnx

**Comment by OrEagle97327** [comment]
Is your Neo Issue solved?
Did you open a support ticket with Ledger?
Are you one of the people Caronas has on his support list?
Ledger has been in touch with my support ticket and I am making sure everyone involved knows.

**Comment by Evgeny1986** [comment]
OrEagle97327  
Hello!
My problem is not solved. With no one contacted me. Maybe tech support knows about my problem.

**Comment by Evgeny1986** [comment]
Hello!
No my problem is not solved. With no one contacted me. May be my problem I do not know. I find it very difficult to navigate here as I badly know English.

"Did you open a support ticket with Ledger?"
And how to do it?

**Comment by OrEagle97327** [comment]
Do you have any contact with @coranos on this?

I opened a Ledger support ticket a month ago.  They are in touch with me today. I am getting all together in my response.

**Comment by Evgeny1986** [comment]
Hello!
No my problem is not solved. With no one contacted me. May be my problem I do not know. I find it very difficult to navigate here as I badly know English.
"Did you open a support ticket with Ledger?"
And how to do it?

**Comment by Evgeny1986** [comment]
OrEagle97327 
I have no contact with @coranos.
He stands alone to write?

**Comment by Evgeny1986** [comment]
I have no contact with @coranos.
He stands alone to write?

**Comment by coranos** [comment]
This isn't a ledger problem. I'd appreciate if you didn't tag me with every problem.

In this case his coins were transferred out of his account. So it's clearly not a ledger app problem, as the ledger app problem prevents transferring at all.

**Comment by Evgeny1986** [comment]
It turns out that my wallet as been hacked because I coins never been transferred. And who do I contact if there is a theft?

**Comment by coranos** [comment]
for theft, you contact the police.

**Comment by Evgeny1986** [comment]
It turns out that Neon wallet does not guarantee the safety of the coins?

**Comment by coranos** [comment]
You may want to look at the license agreement.

https://raw.githubusercontent.com/CityOfZion/neon-wallet/dev/LICENSE.md

**Comment by Evgeny1986** [comment]
I am disappointed in crypto. I thought cryptocurrency reliable if they get stolen, you can trace their journey and return.

**Comment by coranos** [comment]
That's why you call the police.

**Comment by Evgeny1986** [comment]
I think it will not help. The case will lead. But such cases in Russia, I think seriously will not be engaged.


>Воскресенье, 28 января 2018, 22:23 +03:00 от coranos <notifications@github.com>:
>
>That's why you call the police.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
DD Gjgjd

**Comment by Glenormiston** [comment]
[Efect  ICO.pdf](https://github.com/CityOfZion/neon-wallet/files/1822542/Efect.ICO.pdf)

**Comment by monax33349** [comment]
Hello! Help me please. I bought 20 NEO on the exchange and sent them for storage in a purse NEON. The address of my purses: ANeTCFPG5Xa3hsKaftJVy3vi83yzdyHCsP
AcXRHjtQhCsJ8r3KbJjpyY1AM71e88DC2o
I went to the purse and found I had no coins. I went to https://neoscan.io/transaction/4d7d7be0bec2bb581bc42552d86021e4a58305beceb9eb49f29da8f58e9508d8
https://neoscan.io/transaction/d9363a4418db3e2d0b7ed59fc661e0de989afec9ca029d11f60c7a144b50448a
I discovered that my coins transferred to the wallet AVdGk4Q3J3XUxNnwnAi6QnUSbJpmvVsXT8 
I coins never been transferred!!! my coins stolen.
