### ISSUE TITLE
Neo transaction stuck

### ISSUE THREAD

**Issue by ravi6098** [CityOfZion/neon-wallet#525]
Sir, I sent noe from binance to neo Wallet but didn't receive..
I have made to transactions details of which is given below.
1st..
Address - AbJ31CWbf1cGCrc919LMPiRgRLHC3oLCL3
Txid - e7e170c0be413f0412f3d51708b29cbd2b6fd78102f5a8a4520e22bb3be7e956
2nd
Address - AWqjfCDcVRFqAJM8BZPpxaUJZmdVjGf29q
Txid - 48051c3ae9085df54b974f8c92d848d150d48d966f98fe5e9e08e17969d2cdd1

**Comment by mhuggins** [comment]
These are both on the blockchain.  The first is for 10 NEO, the second is for 5 NEO.

**Comment by ravi6098** [comment]
What to do.. to accelerate?

**Comment by mhuggins** [comment]
Nothing, they're already on the blockchain:

* https://neotracker.io/tx/e7e170c0be413f0412f3d51708b29cbd2b6fd78102f5a8a4520e22bb3be7e956
* https://neotracker.io/tx/48051c3ae9085df54b974f8c92d848d150d48d966f98fe5e9e08e17969d2cdd1

**Comment by ravi6098** [comment]
Then how much time it will take?

**Comment by ravi6098** [comment]
It's already been 24 hrs

**Comment by sandeepkrsony** [comment]
sent GAS 4.7xx binance to poloniex.. not showing in poloniex.. after that when i checked in neotracker.. there are dhowing me UNSPENT..almost 10 days completed.. what should i do.. anybody have an idea please tell me

txid- e1b75ec230c7f6ee87d60cf54d73a88952e9d3b11dd3b2b4761507ba49c2179a
