### ISSUE TITLE
Ledger Nano S not responding after confirming transaction in 0.0.7, neither 0.0.9.

### ISSUE THREAD

**Issue by Tristan1986** [CityOfZion/neon-wallet#526]
Hi there,

I want to send Neo to another adress. I logged in, chosed amount and clicked send asset. After this I confirm transaction and the message is up ''please sign the transaction on your hardware device''. However, my ledger is not responding to this, still ''wake up neo'' what I see., so I cant sign.

Wallet is also responding slower today. Version 0.0.7 AND 0.0.9. 

Can anybody help me out? Thanks!

**Comment by gripin** [comment]
for 0.0.9 you have to update NEO firmware on ledger up to 1.1.1 (latest) - maybe this helps

**Comment by Tristan1986** [comment]
I already did :). Went to the ledger manager, removed Neo en reinstalled the app. Which is 1.1.1.

But it still doesnt work :(

**Comment by Tristan1986** [comment]
I gave it another try, it works now 🍡

**Comment by gripin** [comment]
cool :-)
