### ISSUE TITLE
Enhancement: Hide private key string when login. 

### ISSUE THREAD

**Issue by dennish007** [CityOfZion/neon-wallet#53]
for security reasons the private key is in fact a password like string. better hide it as it is copied from clipboard most of the time. 
Make it an option to show private key.

**Comment by flavoredtaco** [comment]
I agree with this. Although minor, you can never be too secure with security.

**Comment by heobo** [comment]
Every login need private key? I hope can input a password instead of private key when login.

**Comment by dennish007** [comment]
@heobo see enhancement #52, like the webwallet an encrypted keyfile is used to access your wallet account which is secured by your own password. In my opinion login with private key should be deprecated.

**Comment by tester2011** [comment]
I think this is pretty much an essential feature. Exposing the private key every time you log into the Neon wallet is asking for trouble.
