### ISSUE TITLE
Force all API calls to api.wallet.cityofzion.io to use HSTS

### ISSUE THREAD

**Issue by Frogz1** [CityOfZion/neon-wallet#531]
## All API calls should be forced HTTPs preferably on the server side with HSTS configuration.

**Expected result:**
all api endpoint calls use https regardless if content is public
**Actual result:**
endpoints are not forcing https

_**notes**_: see https://www.eff.org/https-everywhere/deploying-https

**Comment by anfn101** [comment]
Any update? @shawnmclean

**Comment by tomasdev** [comment]
May be related with my last update at https://github.com/CityOfZion/neon-wallet/issues/502 ("Warning
Error checking wallet version! Please make sure you have downloaded the latest version: https://github.com/CityOfZion/neon-wallet/releases")

**Comment by comountainclimber** [comment]
Closing this issue as `api.wallet.cityofzion.io`is no longer used in neon-wallet `https://api.neoscan.io/api` is now the source of balance and transaction data
