### ISSUE TITLE
Zero Balance Neo and Gas on version 0.0.9

### ISSUE THREAD

**Issue by Ghewij** [CityOfZion/neon-wallet#532]
Hi,
Since end of Version 0.0.7. my Neon wallet shows zero balance, installed version 0.0.9. but the issue persists. 
Balance in Neoscan with my public address is OK!
AQybw3G1cuXHfxDusRQd1ECN96pQpcM8PF 

Could you please check the wallet/account?
Kind regards.
Phil

**Comment by jhepkema** [comment]
Did you make sure you are on the MainNet? (you can change between the MainNet and Testnet in the top right corner when you have unlocked your wallet).

**Comment by shawnmclean** [comment]
Sometimes the API may be slow or down.
