### ISSUE TITLE
Neon old release installers, please do not remove!

### ISSUE THREAD

**Issue by bargom** [CityOfZion/neon-wallet#534]
Hello,

For some of the ICO's only 0.0.6 is required, but on the older version the executables are removed, which makes impossible for non-developers to attend to these ICO's. Please add the executable installers of the previous versions starting from 0.0.6.

Kind regards,
Baris Gomleksizoglu.

**Comment by shawnmclean** [comment]
We do not recommend using older versions. It will be buggy.

We are working on a release that will allow this.
