### ISSUE TITLE
Cant send out GAS from my Ledger Nano S

### ISSUE THREAD

**Issue by GvidoKarlis** [CityOfZion/neon-wallet#535]
I get the "Transaction Failed" message every time I try to send out Gas on Main using 0.0.9. or any other version. I can successfully send Neo, claim my gas, and receive both Neo and Gas. It's only sending Gas that I cannot get successfully. I have tried different amounts, decimals, unplugging/replugging in, reopening the Nano app, unistalling, reinstalling ,etc. I have also tried sending to many different wallets to check if maybe one exchange was incorrect but it still didn't help.

It shows up in a wallet - https://neotracker.io/address/Aad5dom6pHuB8qirFxHxnTkzvMhZBRqjmk

**Comment by jhepkema** [comment]
This is a duplicate thread; please remove one.
