### ISSUE TITLE
Claiming Gas (not Ledger or "Claim Failed" issue)

### ISSUE THREAD

**Issue by KSY006** [CityOfZion/neon-wallet#537]
Using Neon Wallet 0.0.9

Past few days clicked "Claim Gas" and it says processing, then completes. In transaction history it shows there was a transaction.

However, in the tracker, when I click on each transaction (contract/hash) it just shows "x NEO (Unspent)"  and nothing else.

Transaction on the wallet shows:
0 NEO
0.00000000 GAS

Quantity of Gas still builds up, but it never claims it. 

Am I doing something wrong? Is there a minimum?

**Comment by KSY006** [comment]
For some reason it magically worked, this afternoon!

**Comment by Thebigmeany** [comment]
I have the same problem. Says its processing, and then says claim failed. 0 Neo, 0 gas showing in the transaction.

**Comment by raphaotten** [comment]
Same here. Version 0.1.1
