### ISSUE TITLE
Auto Update Wallet

### ISSUE THREAD

**Issue by shawnmclean** [CityOfZion/neon-wallet#545]
Implement Electron Updater on wallet: https://www.electron.build/auto-update

**Comment by notatestuser** [comment]
We appear to be missing a `*-mac.zip` file in our releases which squirrel.mac relies on. Could we include this next time @evgenyboxer?

**Comment by comountainclimber** [comment]
Closing this for now due to licensing requirements for auto update functionality in electron that we are not going to take on at this point in time.
