### ISSUE TITLE
Neo Balance not showing? version 0.0.3 

### ISSUE THREAD

**Issue by jaffa1991** [CityOfZion/neon-wallet#549]
Hello Everyone, 

I have the neo wallet v 0.0.3 I sent coins from binance to the wallet, coins not showing but gas is building up??

neo tracker says all is ok I think?
https://neotracker.io/address/AQAJg82qNgxdGFSG4nuEDKdgWRYeqH6c1L

can anyone recommend how to fix this issue? 

I am seeing similar issues with newer wallets do I need the newest wallet?
if so which one? 

cheers guys

**Comment by Satoshinaire** [comment]
@jaffa1991 You know what to do already, you gave hints in your message :)

Update to the latest version: [0.0.9](https://github.com/CityOfZion/neon-wallet/releases)

**Comment by jaffa1991** [comment]
Okay I thought so just wanted to make sure, and I use the same private key to open the wallet to ensure I keep all my neo. 😊
