### ISSUE TITLE
Miss NEO currency with transfer

### ISSUE THREAD

**Issue by teovmy** [CityOfZion/neon-wallet#55]
I transfer 7 NEO from Bittrex to NEON. It shows me only a transfer of 6. The fee for for this transfer on Bittrex is 0.1. In the order it shows 6.9. But as mentioned NEON shows me 6. This can't be happening right, losing money this way?!?!

**Comment by Ejhfast** [comment]
This is not a problem with Neon. Unfortunately, Bittrex took your Neo. Their policy on fees is terrible.

See: https://www.reddit.com/r/NEO/comments/6s2ttd/bittrex_transfer_fee_is_now_01_ans/dl9q4oy/

**Comment by teovmy** [comment]
Wow is this for real?!?! Still, why is it that I can see 6.9 transferred

**Comment by Ejhfast** [comment]
It is for real, unfortunately. Happened to me as well, long, long ago, when 1 ANS was worth much less than it is now. I recommend sending angry emails to Bittrex. Their policy is unacceptable.

**Comment by teovmy** [comment]
Thanks for the quick info. And thanks for the wallet on OSX. Any roadmap?

**Comment by anfn101** [comment]
For the wallet we are planning many new features. For NEO, read the whitepaper. Also be reminded that Github is a place to open technical issues related to code. This is not a support channel. For that, please visit Reddit or our support channel on Slack. Thanks.
