### ISSUE TITLE
Clicking on Transaction IDs in the list of Transaction History opens URL with testnet.neotracker.io domain

### ISSUE THREAD

**Issue by brandosaurus** [CityOfZion/neon-wallet#554]
Clicking on any transaction will open a browser page with the testnet.neotracker.io domain. Most transactions I assume will not be available there - produces a 404 error on web page.

Edit: Verified that I am running on MainNet option on the top right dropdown.

**Comment by derawi** [comment]
Same error for me.

**Comment by brandosaurus** [comment]
Can confirm that this is fixed in 0.1.1. Thanks!
