### ISSUE TITLE
My NEON wallet does not show any blocks, NEO and GAS balance all zero, Error Can not retrieve NEO/GAS Balance

### ISSUE THREAD

**Issue by stephenng1** [CityOfZion/neon-wallet#561]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by stephenng1** [comment]
Did not work even if I used NEON 0.0.6 or 0.1.0 same problem, no blocks showed, already turned off my firewall

**Comment by louloops** [comment]
Same issue observed for me for 0.1.1 on Mac (no blocks, balance all zero with same error message as mentioned in the title)
