### ISSUE TITLE
Getting error your wallet out of date.

### ISSUE THREAD

**Issue by joocru** [CityOfZion/neon-wallet#562]
downloaded 0.1.1 latest version of neon but getting this your wallet is out of date error. why ? and cant see rpx and other nep5 assets in my new neon wallet ?

**Comment by Sajjon** [comment]
I got the same message.

**Comment by segovius** [comment]
Me too

**Comment by Germaneo** [comment]
same problem here, want to participate in Elastos Tkoen Sale but the transaction is failed. Someone able to help?

**Comment by a8lex** [comment]
I'm also getting the same issue any help would be appreciated

**Comment by FomoINC** [comment]
is this resolved? can anyone see their tokens? i barely updated today and i can't see my dbc's or any  tokens.
