### ISSUE TITLE
SAME PROBLEM, NEW PATCH

### ISSUE THREAD

**Issue by GvidoKarlis** [CityOfZion/neon-wallet#564]
I get the "Transaction Failed" message every time I try to send out Gas on Main using 0.0.9. or any other version(0.1.0). I can successfully send Neo, claim my gas, and receive both Neo and Gas. It's only sending Gas that I cannot get successfully. I have tried different amounts, decimals, unplugging/replugging in, reopening the Nano app, unistalling, reinstalling ,etc. I have also tried sending to many different wallets to check if maybe one exchange was incorrect but it still didn't help.

It shows up in a wallet - https://neotracker.io/address/Aad5dom6pHuB8qirFxHxnTkzvMhZBRqjmk

**Comment by jhepkema** [comment]
Please ask questions such as these in the #support channel of the [NEO Discord](https://discord.gg/R8v48YA); there are more people available to help you there.

**Comment by ToeJamathon** [comment]
@GvidoKarlis I'm also having this exact same issue (and have tried all the same stuff you have).

_Any_ help would be much appreciated!
