### ISSUE TITLE
Neon 0.1.0 and 0.1.1 does NOT support signing transaction when in "Participate in token sale"

### ISSUE THREAD

**Issue by prvyo** [CityOfZion/neon-wallet#565]
When logged in using Ledger Nano S.

**Comment by prvyo** [comment]
![neon](https://user-images.githubusercontent.com/35568172/35101901-82f7d6a8-fc61-11e7-8d00-3bd390d86059.png)

**Comment by Walterdbone** [comment]
I encountered the same issue trying to participate in the Zeepin (ZPT) ico.

**Comment by Walterdbone** [comment]
Reinstalling the NEO ledger app solved the problem for me

**Comment by prvyo** [comment]
for me too
