### ISSUE TITLE
on new version 0.1.1 of Neon Wallet (I'm on Mac) it still says there is a newer version available at the bottom

### ISSUE THREAD

**Issue by mfoxgreen** [CityOfZion/neon-wallet#566]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by mirzap** [comment]
I can confirm that for Mac and Ubuntu.

**Comment by brandosaurus** [comment]
I can confirm in Windows 10 Professional

**Comment by zajebancija** [comment]
I can confirm for Windows 10 x64

**Comment by shawnmclean** [comment]
I'm unable to replicate, can you provide a screenshot?

**Comment by mfoxgreen** [comment]
Nope, working now - mot there anymore.

**Comment by FomoINC** [comment]
can you guys see your tokens on 0.1.1 and macbook and ledger nano s?

**Comment by mfoxgreen** [comment]
No.
