### ISSUE TITLE
No decimal places on NEO funds. Always rounded down to lower number

### ISSUE THREAD

**Issue by StillRivers** [CityOfZion/neon-wallet#57]
When transferring an amount of e.g. 28.9 NEO, the amount shown in the balance is 28. Are the additional funds there, just not shown?

**Comment by StillRivers** [comment]
Should have said, I am running mac OS version.

**Comment by samfranz** [comment]
Here there bud, it's been answered a few times. Sorry, but it's happened to me too and I've lost around 2 NEO when I was first moving to my wallet as this information wasn't as readily available.

https://github.com/CityOfZion/neon-wallet/issues/47
https://github.com/CityOfZion/neon-wallet/issues/55

**Comment by StillRivers** [comment]
Hey samfranz, thanks for the quick reply. Yeah that is a real pain, I shall be complaining to Bittrex about this, especially now that each NEO is starting to be worth a considerable amount! Have a good one :)
