### ISSUE TITLE
Neon wallet with Ledger not staying in sync with blockchain

### ISSUE THREAD

**Issue by Jammmmin** [CityOfZion/neon-wallet#576]
Neon wallet with Ledger not staying in sync with blockchain - totally unusable. 

If I leave the wallet for a few hours, eventually it catches up with the blockchain and I am able to process one single transaction (such as sending Neo or gas to another wallet). I then have to wait for several hours for the wallet to catch up and the new balance to display. If I attempt any other transaction before this has happened then it just fails.

For Gas claims, after approving the claim on the Ledger (step 1) nothing happens. The wallet does not sync in time to get to step 2 and I can never claim the gas.

I have tried resetting the Ledger, reinstalling the Neo app to Ledger, uninstalling and reinstalling Neon wallet (after deleting program files and rebooting PC).

Nothing works, it's totally unusable and I am supposed to be taking part in upcoming ICO. 

Any help would be much appreciated, it's driving me nuts!

Thanks.

**Comment by hugoryder** [comment]
i'm having the same problem, but today I cant even claim gas without and error. I have balance on the blockchain but completely different on the neon wallet? Is this a general problem?

**Comment by anfn101** [comment]
Try latest Neon version. Also note: Github is used to report code issues. Any support can be found in the Discord #support channel.
