### ISSUE TITLE
Neon 0.1.0 and Neon 0.1.1 don't show custom tokens

### ISSUE THREAD

**Issue by benno12345** [CityOfZion/neon-wallet#578]
Hello community,
either wallet version doesn't show balances when I add a custom token via script hash. I tried with ZPT hash and ACAT hash. Only the preset tokens DBC, RPX, RHT and QLC. I am using Ubuntu Linux, but also had the issue on Mac system.
Thank you very much!

**Comment by benno12345** [comment]
Hi there,
I manage to integrate the tokens. Had a space in the script hash.

**Comment by el1748eth** [comment]
Anyone know what the script hash is for Qlc Token? They show on my wallet but are not displayed as an option to send out of the wallet. I have tried everything but deleting the hash and readding it.
