### ISSUE TITLE
Login using the Ledger Nano S section becomes unresponsive when plugging in device.

### ISSUE THREAD

**Issue by iLemon1** [CityOfZion/neon-wallet#579]
All in the title. When I go to 'Login using the Ledger Nano S', then plugin the ledger, the Neon Wallet becomes unresponsive.

**Comment by Lundborg1** [comment]
Same problem here. Worked fine around 20:00 (CET +1), stopped working again at around 00:00 (CET +1). Tried reinstalling neon, didn't work.

**Comment by anfn101** [comment]
Make sure the Ledger Neo app is up to date and reinstalled. Also note: Github is used to report code issues. Any support can be found in the Discord #support channel.
