### ISSUE TITLE
neon wallet update question

### ISSUE THREAD

**Issue by bethmo245** [CityOfZion/neon-wallet#580]
#where do you download the new version?  I have .0.9  and says warning out of date.  I just downloaded it last week.  go to the link and  does not work.

**Comment by jhepkema** [comment]
Please ask support questions like these on [Discord](https://discord.gg/R8v48YA), in the #support channel.

In the sidebar of the official [NEO subreddit](https://reddit.com/r/neo), you can find the latest download link for the NEON wallet.

**Comment by comountainclimber** [comment]
@bethmo245 https://github.com/CityOfZion/neon-wallet/releases or neonwallet.com
