### ISSUE TITLE
I updated to Neon wallet 0.1.1 and is using ledger nano s

### ISSUE THREAD

**Issue by FomoINC** [CityOfZion/neon-wallet#581]
I cannot see my nep5 tokens, specifically DBC in the wallet.

It is available at my address if i check it manually but the wallet will not show any tokens.

Anyone have an idea why?

**Comment by rm107** [comment]
That is my question as well.  I could see Nep5 coins in the earlier version 0.9.0 but not in the new version

**Comment by adrianhara** [comment]
same here, worked in 0.0.9
