### ISSUE TITLE
Token balance not appearing in 0.1.1

### ISSUE THREAD

**Issue by jayk293** [CityOfZion/neon-wallet#583]
After installing 0.1.1, I am unable to view any tokens and their amount. 
All I see is the Token and Balance header, but no values.
I can confirm I have DBC using _neotracker_ but is not appearing in the wallet.

![screen shot 2018-01-20 at 17 50 25](https://user-images.githubusercontent.com/12047220/35186340-6caaecc8-fe0a-11e7-914b-ab80b29855f3.png)

Is this a problem for anyone else?

**Comment by FomoINC** [comment]
did you even see the other tickets that were opened? i just asked the same question.  But yes we are all experiencing this.

**Comment by mindlapse** [comment]
Everything seems good here - I installed the 0.1.1 version on my Mac and was able to see all balances, including my DBC tokens.  I also upgraded to 0.1.1 on Ubuntu and can see all balances there as well.

**Comment by jayk293** [comment]
Hi @FomoINC, Just had a look at your ticket. I see that you did ask the same question. Did not consider checking your ticket as the title did not allude to an issue with the tokens not appearing, but just an issue with the wallet and ledger, which is something I do not have an issue with in this update.

I am glad that its not just me with this issue!

**Comment by FomoINC** [comment]
ok it is resolved now.

**Comment by jayk293** [comment]
I can see the tokens now. Closing issue.
