### ISSUE TITLE
I just downloaded this wallet and "participated" got screwed

### ISSUE THREAD

**Issue by armanbcoin** [CityOfZion/neon-wallet#587]
#Why was this update made and that file added to participate if the ICO COIN SALE had already been over since before this update? why are you stealing like that man? bro cmon please im not rich like that I need my neo back. its only 2 but still man thas more to me than youknow! please someone make this right. please someone help me. man if it were me I would have done the same. but cmon please im sorry for being like this but that 2 took me a lot to get. my neo have been earned with sweat and tears dont do me like that and not even return my neo. cmon please im sorry I assumed something but dude this is straight theft. please someone help me.

**Comment by armanbcoin** [comment]
you guys are smart please someone has to know how to help me im begging you!
1 neo went to -
e24772187556f251b1689e463f1a9f3f
cd66b87df0784adc72df77d188064e6d

please im begging you guys

**Comment by jhepkema** [comment]
Hi @armanbcoin, quick reminder, taken from the readme from this very repository: 

> A gentle reminder, github issues is meant to be used by developers for maintaining and improving the codebase, and is not the proper location for support issues. Questions such as
> 
> "Why can't I log in?"
> "I lost my private key, is there anyway to recover it?"
> "Why is my balance not showing?"
> should be asked in proper support channels such as the NEO subreddit, or the official NEO Discord Channel. You should also check the list of frequently asked questions (FAQ) to see if your question has been answered there already.


Please take your issues up somewhere else. Issues are meant to improve the code, not for support. Like the text above states, if you want support you're better off asking in the #support channel of the CoZ Discord. 

That being said, I feel for you and I'm sorry that you lost your NEO. For a next time, please don't skip the big red box with urgent looking text at the top of the Token Participation screen, especially point 3: 

> <b>If you send NEO/GAS to a token sale that has already ended, you will
>             lose your NEO/GAS and will not be refunded.</b>
> </li>

Your best chance right now is to contact the owner of the address you posted (the token sale owner), to see if they are kind enough to go through the trouble to send your NEO back to you. Other than that, I'm afraid no one from CoZ can help you.

**Comment by armanbcoin** [comment]
thank you, I emailed tham after that. I appreciate everyones help and
input. I was having a shit day and freaking out over that.

**Comment by jhepkema** [comment]
Alright, best of luck, hope they get back to you.
Please close the issue so the list gets shorter :)
