### ISSUE TITLE
Unable to send NEP5 tokens using a Ledger Nano S

### ISSUE THREAD

**Issue by ronaldmannak** [CityOfZion/neon-wallet#589]
Sending NEP5 tokens like TNC consistently produces a Transaction Failed Error when trying to send the tokens to another account. (The tokens have been added to NEON and the balances are visible)

<img width="471" alt="screenshot 2018-01-18 12 18 36" src="https://user-images.githubusercontent.com/455476/35198101-7d62c8ee-fe9e-11e7-8217-248678047a4a.png">

**Comment by harrybenc** [comment]
I have the same issue with TNC tokens and I see this message:
"Sending NEP5 tokens requires holding at least 1 drop of GAS"
Please assist

**Comment by rossrans** [comment]
I'm having the same issue with trying to send DBC. Could the city of Zion please update and correct this issue??

**Comment by harrybenc** [comment]
I have just transfered some GAS to mywallet and it works now (after 2 trials)
I did not get charged for the transaction

**Comment by stevesbrain** [comment]
@rossrans They certainly won't be stuck on there forever. At the very worst, you can always use the recovery generator and turn your seed into a WIF that you can use to login.

**Comment by Luke1899** [comment]
Wishing this would get fixed too. We were told in Trinty it would be fixed after 1-2 days,..........a week ago

**Comment by rossrans** [comment]
I’ve found the solution..you have to delete and re-install the actual neo ledger app. So you’re looking for the neo ledger version 1.1 where you add the various coins. Worked like a charm. :)

**Comment by ronaldmannak** [comment]
Yes, @rossrans' solution seems to work, someone on Telegram suggested the same. Delete and reinstall the Neo app from the Ledger using the Ledger Management software. After reinstalling, I had to disconnect and reconnect my Ledger a few times, but then it worked well.
