### ISSUE TITLE
Did I Lose my NEO's by buying QLC in the NEON wallet after the ICO has ended / completed?

### ISSUE THREAD

**Issue by AKHB66** [CityOfZion/neon-wallet#590]
Today I noticed the possibility for buying some altcoins in my NEON Wallet. 
So I made the buy transfer on QLC with some NEO's in my wallet. 
Well the NEO's have been withdrawed on my balance but no QLC balance appears in the NEON wallet. 
I found out the QLC ICO has been completed, could this be the reason I just lost my NEO's?

Can anyone help me to sole this issue please? Does anybody know if I really lost my NEO's here or I can solve this somehow?  Thanks in advance

**Comment by anfn101** [comment]
You can contact the QLC team.

**Comment by AKHB66** [comment]
I did contact QLC, even Susan Zhou, but they argue not to have received my payent/buy. And how can it be, because the QLC public adress was pretexted in my NEON wallet. So I am confused and just lost 2 NEO...
