### ISSUE TITLE
[URGENT] Need resolution to transfer NEP-5 coinS from Ledger - Neon wallet to Exchange

### ISSUE THREAD

**Issue by cryptoblack1** [CityOfZion/neon-wallet#593]
Hello,

Serious issue for Ledger users here. There's no way of transferring Qlink, Deepbrain & Redpulse coins from your Neon wallet - ledger to an exchange. Neo tracker can not be used and essentially there will be many people with trapped funds if the error is not amended.

Can we clarify for everyone what is the amount of GAS needed to be held.

- Transaction failed message after asking to authorise of ledger device.

- Requiring 1 drop of gas is vague holding 0.2 this does not even allow me.  

Regards,

Cryptoblack

**Comment by Luke1899** [comment]
Yes . This needs fixed ASAP. Its wrong not to have a functioning wallet that you can send tokens with. People lock in a lot of money with these tokens.....not being able to even transfer them can cost many people lots of money

**Comment by mforce** [comment]
@cryptoblack1, @Luke1899 Try updating the app on your Ledger Nano S, I was having the same issues. What I did is uninstall the App on the Nano S and install it back again. After that it started working again.
