### ISSUE TITLE
neon 0.1.1 not showing Token balances

### ISSUE THREAD

**Issue by Pmensah12** [CityOfZion/neon-wallet#594]
Hi i have just updated my neon wallet from 0.0.9 to 0.1.1 and now i cant see my DBC, QLC and RPX tokens. Can anyone help give some guidance?

**Comment by Pmensah12** [comment]
helloo anyone willing to help?

**Comment by jonashaefele** [comment]
Same here, on logging in, I get two toasts:

**Success**
Received latest blockchain information.

and:
**Error**
Could not retrieve NEO/GAS balance

Updated from 0.0.7 that used to work great, then stopped showing the balance so I updated to 0.1.0 and then 0.1.1 both still not showing balance... 

Where as checking my wallet address on https://neotracker.io still shows my balance just fine.

**Comment by tsaiDavid** [comment]
@Pmensah12 @jonashaefele - just for clarity's sake, what operating system?

I seem to get this problem intermittently on my Windows machine - upon hitting the refresh and re-logging in using my Ledger and giving the wallet a minute, it seems to reappear without a hitch.  I don't have any NEP5 tokens at all, so the balances are all 0, FYI.

**Comment by adrianhara** [comment]
I have the same, 0.1.1 not showing any DBC coins, though they are there if i check on neotracker.

**Comment by jonashaefele** [comment]
I'm running Mac OS. Tried it both on Sierra and High Sierra.
NEON Wallet versions 0.1.0 and 0.1.1
I updated the wallet to v0.1.1 so I could use the Ledger Hardware Wallet integration.

Got the errors above logging in with a private key (or encrypted key + passphrase) generated by version 0.0.6 of the wallet originally.

It also seems like it's not getting blocks (Blocks in the header doesn't show any block numbers)

Where as back on version 0.0.7 (on my other Mac at home, also running High Sierra) I can log in, get Blocks loaded (Header showing block numbers) and I can claim GAS.

**Comment by douglasdeodato** [comment]
got the same issue too, just upgraded to 0.1.1. I am using ledger nano.

in the first try, tokens not showing at all.

second try I turn off and turn on again the wallet and the tokens appeared for few seconds and disappeared and kept doing this for a while.

it is any bug on this version? I think I will downgrade, very disappointed .

**Comment by adrianhara** [comment]
I got the appearing and then disappearing tokens issue too. They showed up briefly after some logins/logouts then just disapeared.

**Comment by vbokser** [comment]
On my mac NEON clinet 0.1.1 no tokens showing up in the wallet. 
they are on the blockchain on https://neotracker.io
sometimes they appear for a second and disappear as mentioned above,

**Comment by beerphilipp** [comment]
same issue. MAC OS 10.13 + Ledger + NEON 0.1.1. No tokens showing at all

**Comment by lu84** [comment]
#depose28 same problems same tools

**Comment by nabilove** [comment]
Anybody found a fix I'm using windows 0.11 wallet no ledger getting same errors

**Comment by SeverMM** [comment]
Hi guys, posting to bump this, tokens no longer show up. They did so, sporadically at first, and now they won't show up at all. I'm not worried that they're not there, I can see them in the address just fine at NeoTracker, but NEON is currently unusable for tokens.

Keep up the good job guys, I trust you will address this critical issue soon.

**Comment by forexpiphunter** [comment]
Same issue here,  they show up for few minutes and disappear.  I do see my tokens on blockchain address.  I transferred only small amount to test.  I hope they don't get lost...

**Comment by Midnite1004** [comment]
I am having the same problem. All tokens in Neon (via ledger) gone. Come on guys please resolve this issue. I have two ledger wallets and neon tokens are not visible in either.

**Comment by willwynne76** [comment]
I had the same issue starting last night with the version 0.1.1 Neon wallet.
Last night I noticed I had success switching to testnet and back, but even that was sporadic.
Its a bug boys, please kindly fix it.

**Comment by willwynne76** [comment]
Im having the same experience as you today.



Sent via the Samsung Galaxy S8+, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by Couch7** [comment]
I am having the same issue using windows 10 an a laptop. I sent a small amount of TNC tokens, to my NEON wallet, and nothing is showing. Prior to the update I could see zero balances for 4 other tokens, now those other tokens don't even show.

**Comment by superclarkan** [comment]
Same issue - I'm on MacOS and no token balances show up at all.  See attached screenshot
<img width="367" alt="screen shot 2018-01-28 at 10 04 51 pm" src="https://user-images.githubusercontent.com/3200348/35495821-bdb4fba4-0477-11e8-8b66-e476167439fb.png">

**Comment by sp3** [comment]
Same here - no tokens are rendered 
<img width="239" alt="screenshot 2018-01-29 07 42 03" src="https://user-images.githubusercontent.com/391108/35496854-09f1c4e8-04c8-11e8-8634-f7f024b6e959.png">
MacOS 10.13.2 neon 0.1.1 :(

**Comment by Jodymcl** [comment]
Same issue here on Windows 10 PC.  Initially tokens were not appearing in neon 0.1.0 so updated to 0.1.1 but still not success.  Pls help in fixing this
Kind regards

**Comment by Pmensah12** [comment]
If this helps...mine now show every so often I think s long as they're in
the blockchain even if they're not displayed they're still there so you can
view them on neo tracker

**Comment by Jodymcl** [comment]
Thanks,  yes certainly still there and could check on https://neotracker.io  Looking to move some soon

**Comment by douglasdeodato** [comment]
are the developers aware of this issue? looks critical. it is already opened for 7 days, someone could ping them here? thanks.

**Comment by Pmensah12** [comment]
Ive tried but no response :-(

**Comment by arnaudds88** [comment]
same here, mac , ledger and latest neon and nothing .... :(

**Comment by Baxeisindi** [comment]
I installed it yesterday and now not showing token :-(  What are the real alternatives before us ? 
https://coinsutra.com/best-neo-wallets/
