### ISSUE TITLE
[URGENT] Unable to send NEP-5 coins from Ledger - Neon Wallet to Exchange - Update Req

### ISSUE THREAD

**Issue by cryptoblack1** [CityOfZion/neon-wallet#597]
Hello,

Serious issue for Ledger users here. There's no way of transferring Qlink, Deepbrain & Redpulse coins from your Neon wallet - ledger to an exchange. Neo tracker can not be used and essentially there will be many people with trapped funds if the error is not amended.

Can we clarify for everyone what is the amount of GAS needed to be held.

Transaction failed message after asking to authorise of ledger device.

Requiring 1 drop of gas is vague holding 0.2 this does not even allow me.

Regards,

Cryptoblack

**Comment by anfn101** [comment]
Make sure you have reinstalled both Ledger Neo apps and Neon wallet. ALSO NOTE: Github is used to report code issues. Any support can be found in the Discord #support channel.
