### ISSUE TITLE
neon wallet transaction failed

### ISSUE THREAD

**Issue by japs1985** [CityOfZion/neon-wallet#598]
Hi, I just downloaded Neon wallet version 0.1.1 in my desktop. I sent my 1 Neo from an exchange to my wallet and every time I claimed my gas I encountered "Transaction failed" error and now I tried sending back the 1 Neo to an exchange but same error persists. Anyone with the same experience? :(

**Comment by ypascal** [comment]
Same here. All worked well, suddenly the program indicated "Transaction failed" after a gas claim and refused every subsequent action. I restarted, loaded from a WIF key, reinstalled the neon wallet... nothing to do. Ended up using neotracker.

**Comment by christhorp** [comment]
Same here!
