### ISSUE TITLE
Can't claim GAS

### ISSUE THREAD

**Issue by mortyblack** [CityOfZion/neon-wallet#599]
Last update haven't fixed problem with claiming GAS.
Transaction failed every time.
I try to uninstall and install app on my Mac, Linux and Windows and on Ledger Nano S.

**Comment by Dano890** [comment]
I have the same problem. Any resolution? Been like this for 3 weeks now.

**Comment by ZedsterX** [comment]
Add another to the list. Is anyone looking at this?

**Comment by esheds** [comment]
same problem here

**Comment by jcrXO** [comment]
same problem here.

**Comment by karneaud** [comment]
+1
