### ISSUE TITLE
NEO coins not showing up

### ISSUE THREAD

**Issue by chancy088** [CityOfZion/neon-wallet#60]
I sent 4 NEO coins yesterday and 25 coins today to my neon wallet, but even though it shows up in the transaction history it hasn't shown up in my wallet. Is this normal? How long does it take? Thank you.

**Comment by anfn101** [comment]
GitHub issues are for code only. Please refer to Reddit or the Slack #support channel. Make sure you update to 0.0.3c Neon wallet found on the sidebar of Reddit.

**Comment by chancy088** [comment]
How can I get help on slack?

**Comment by anfn101** [comment]
Just ask in the support channel.
