### ISSUE TITLE
Can't install. Image not recognized. Help.

### ISSUE THREAD

**Issue by cryptoinvestor100** [CityOfZion/neon-wallet#600]
<img width="372" alt="screen shot 2018-01-22 at 16 35 41" src="https://user-images.githubusercontent.com/35771743/35338598-9fcab5d6-011e-11e8-9dfd-4ef9ec66161c.png">

**Comment by stevesbrain** [comment]
Have you verified the checksum is correct? Could be a corrupt download

**Comment by cryptoinvestor100** [comment]
Do you have a link to a proper download?

**Comment by stevesbrain** [comment]
@cryptoinvestor100 The official link is the proper one; just try redownloading it. It may have corrupted during the download process.

**Comment by fartnipplegiblets** [comment]
I'm having the same issue as cryptoinvestor100 and I have tried downloading the dmg file many times

**Comment by stevesbrain** [comment]
@fartnipplegiblets Did you verify the checksum? @cryptoinvestor100 never confirmed if he did or not.

**Comment by fartnipplegiblets** [comment]
Hello. Thanks for getting back to me! I don’t know how to verify the checksum. I’ve never needed to do anything this technical before when opening a dmg file.

Jon Beinart  |  Gallery Director

Beinart Gallery <http://beinart.org/>

Melbourne, Australia  |  P +61 438 568 762 <tel:%2B61%20438%20568%20762>  |  E jon@beinart.org <mailto:jon@beinart.org>

Facebook <https://www.facebook.com/beinArtGallery>  |  Instagram <https://www.instagram.com/beinartgallery/>  |  Twitter <https://twitter.com/beinartgallery>  |  Tumblr <http://beinartgallery.tumblr.com/>

**Comment by fartnipplegiblets** [comment]
Hello. Thanks for getting back to me! I don’t know how to verify the checksum. I’ve never needed to do anything this technical before when opening a dmg file.

**Comment by stevesbrain** [comment]
@fartnipplegiblets Are you at all familiar with the terminal? You'll need to open the terminal, then type the following:

```bash
cd Downloads
openssl sha -sha256 Neon-0.1.1.Mac.dmg
```

You are hoping for it to say:

`814200bfe0523a387f89a71b27716b4f023359ff61053d824d46ba234919e036`

Let me know if you get stuck!

**Comment by fartnipplegiblets** [comment]
Thanks for that! I opened Terminal and followed the instrucitons and got this:

SHA256(Neon-0.1.1.Mac.dmg)= 77ee0d5863697405ff4c17ed38196b3eeb2ea7020779df986699abca12a14f5d

**Comment by stevesbrain** [comment]
@fartnipplegiblets I can confirm that means the file did not download correctly. I've just downloaded the same file, and verified that the correct checksum was there for me.

This can happen for many different reasons - however, I suggest redownloading the file, and verify the checksum again - if it matches the one I'm posted, the file will work! If you need me to host a copy elsewhere, I can do that for you. Let me know! Thanks

**Comment by fartnipplegiblets** [comment]
I've tried downloading it multiple times and this issue keeps recurring. I just tried another couple of times and checked it out on terminal and I'm still not getting the correct checksum. It would be greatly appreciated if you could host a copy for me to download. Thanks!

**Comment by stevesbrain** [comment]
@fartnipplegiblets No worries - just uploading now! Will send you another message when ready.

**Comment by stevesbrain** [comment]
@fartnipplegiblets I've uploaded it now - the link is:

https://f001.backblazeb2.com/file/public-downloads/neon-wallet/Neon-0.1.1.Mac.dmg

If this *still* doesn't work, let me know and I can upload it to my personal website. However, I'd prefer to use this to maintain some privacy if possible :)

**Comment by stevesbrain** [comment]
@fartnipplegiblets Glad it worked! I haven't heard actually, but I do see that is the case. Hopefully they fix it up soon!

**Comment by fartnipplegiblets** [comment]
I hope so too! I can't find any information about this suspension anywhere. Very strange!

**Comment by stevesbrain** [comment]
Maybe worth sending them a support request, or tweet or something?

**Comment by fartnipplegiblets** [comment]
I already sent them a support request. Fingers crossed!

**Comment by malkazoid** [comment]
This happens A LOT when downloading through the Neon browser, which opens by the github link by default when you click on it inside Neon wallet.
If you use Chrome, Safari or Firefox, or whatever other browser you use for day to day browsing, you won't encounter this problem - at least, that has been my systematic experience.
