### ISSUE TITLE
Cannot send NEO or claim GAS with v 0.1.1. Tried both Ledger Nano S and a saved wallet. 

### ISSUE THREAD

**Issue by WorfTheDog** [CityOfZion/neon-wallet#605]
When using the Ledger Nano S, it says Transaction Failed after I try to sign the first trx. 

When using a separate saved wallet, it immediately says Transaction Failed. 

I have uninstalled and reinstalled the NEO app on my ledger nano s.

Using Mac 10.11.6

**Comment by lu84** [comment]
I have the same problem. Using a MAC and a ledger nano S

**Comment by superenart** [comment]
I have same problem on windows 10 (same with last 3 patches) / can't claim gas or send neo tokens

**Comment by ruthvik23** [comment]
Same exact issue - cannot claim Gas or send Neo from Ledger Nano S. 

This is an incredibly scary issue and needs to get a response pretty quickly as I cannot access my funds at all.

**Comment by hugoryder** [comment]
same issue, what do we do?

**Comment by ZedsterX** [comment]
So we are not enough people complaining about this yet?

**Comment by mikel2005** [comment]
I can see my transaction on the blockchain but not in my wallet please advise.

**Comment by anfn101** [comment]
Github is used to report code issues. Any support can be found in the Discord #support channel.
