### ISSUE TITLE
Does Neon wallet team even listen?

### ISSUE THREAD

**Issue by cryptoblack1** [CityOfZion/neon-wallet#608]
Genuine question lots of people unable to move alt nep 5 tokens from ledger wallet due to errors. When will this be resolved?

**Comment by jonnyfreesh** [comment]
yep me too. token balances dont display, NEO balance outdated, can't claim gas. apex token sale coming up in a couple days too. perfect timing right

**Comment by nabilove** [comment]
I can't even see my balance  no block either ,wath about you guys

**Comment by transformationlabs** [comment]
Do you have the latest firmware app within ledger: 1.1.1?
You need gas to send NEP-5 tokens.

**Comment by jonnyfreesh** [comment]
Mine is working now. I'm not 100% if i have the latest ledger app version, how can I tell? And if I need to update that, I need to delete the ledger app and then re-install the new one right? Just to confirm (apologies if this is dumb), that won't delete the neo address on my ledger right?

**Comment by sbglive** [comment]
Is there anybody from NEON team able to reply to all these opened topics about missing funds ?
