### ISSUE TITLE
How do I open the neon wallet and use it? None of my desktop apps will open it correctly

### ISSUE THREAD

**Issue by Alfredo66** [CityOfZion/neon-wallet#61]
I have a windows 10 computer

**Comment by saltyskip** [comment]
You should reach out on the slack support channel, github is primarily for coding related topics.

https://neosmarteconomy.slack.com the channel is here

**Comment by canesin** [comment]
https://join.slack.com/t/neosmarteconomy/shared_invite/MjIyOTc2OTU4NDk3LTE1MDIxNzE2NTctZTE1Mjg5ZWE3Yw
