### ISSUE TITLE
Participate in Toke Sale

### ISSUE THREAD

**Issue by wchance** [CityOfZion/neon-wallet#610]
I was able to click on participate in a token sale and actually sent 1 NEO to RHT.   RHT refunded the NEO.   They said they have no ICO Presale going on and that this option should not be available.

**Comment by nabilove** [comment]
I can't see my balance on windows 0.11 wallet can you! Wallet not syncing

**Comment by wchance** [comment]
I can see my NEO and GAS balance fine.
