### ISSUE TITLE
neo gas

### ISSUE THREAD

**Issue by twomilrichie** [CityOfZion/neon-wallet#612]
Can't claim gas in neo wallet keep receiving error message "transaction failed" is anyone else having the same problem as I believe from previous posts this has been a ongoing issue
Could anyone please offer some assistance?
Thanks Twomilrichie

**Comment by danielalgra** [comment]
I have the same issue, I can't send to my Neon Wallet it states "Invalid address"
I cant pull out Neo or Gas from my wallet either, it states "Transaction Failed"

Please resolve issue.

**Comment by wokem** [comment]
Having the same problem! Would love to get some help or comments on this... pretty lame. I can't transfer out any neo either.

**Comment by RenchChua** [comment]
Facing this issue too. I can't claim any GAS. Though I've been able to send some GAS out to Binance.

**Comment by wokem** [comment]
Could you send any neo out too? I can’t send neo either. Haven’t tried sending gas. Pretty frustrating.

**Comment by d4designstudios** [comment]
Same problem here "Transaction failed"...  trying to claim gas.

**Comment by jcrXO** [comment]
Same problem here. Can't claim gas either.
