### ISSUE TITLE
Installed NEON 0.1.1 - issue Block NaN

### ISSUE THREAD

**Issue by ohlastijn** [CityOfZion/neon-wallet#614]
Hi, I just installed the Neon Wallet and I'm able to connect it to the Ledger Nano. I've sent as a test 1 NEO from another wallet to my new wallet address. So far so good, but I'm not able to receive this Neo to my new wallet, the balance is still 0, **Block: NaN**. Fortunately I've verified my new public address on Neotracker and there I see my Neo - transactions 1: transfers: 0. (i'm using Windows Enteprise)
What can I do to solve this issue because I would like to store my other Neo's to my "ledger". thanks in advance, best regards Ronald

**Comment by curatedcryptocurrencynews** [comment]
Same issue: https://github.com/CityOfZion/neon-wallet/issues/621
