### ISSUE TITLE
Windows Portable Edition (Feature Request)

### ISSUE THREAD

**Issue by Ardakilic** [CityOfZion/neon-wallet#615]
Hello,

I'm keeping my offline wallets in an encrypted flash drive, and use them regularly on more than one computers. So I'd appreciate if there could be a Windows portable edition (something like Electrum has), so I won't have to install on every machine I use.

I tried extracting app-amd64.rar from setup.exe, but I wonder if that'll work as portable.

I'd appreciate if this could be considered.

Thanks in advance,

**Comment by comountainclimber** [comment]
@Ardakilic Have you tried the export feature in settings? This should allow you to share data about shared accounts across devices (there is however a small UX issue that still needs work https://github.com/CityOfZion/neon-wallet/issues/1621)

**Comment by Ardakilic** [comment]
@comountainclimber Hello, thanks, but exporting data is another thing. What I want to achieve is that just to doubleclick to app and run instantly, which I can do across devices. This way, I will be carrying the app on an encrypted flash drive and don't have to bother with installing etc.

But they, thanks for the heads-up, backup-restore will also be useful because I'm also accessing my wallet from macOS.
