### ISSUE TITLE
NEON Wallet Laptop Crash

### ISSUE THREAD

**Issue by jerrechen** [CityOfZion/neon-wallet#616]
Hi, please help me out here. A few days ago, I had my laptop crashed on me and I had 22 NEO in my NEON Wallet. I did not save my private keys (my stupid fault, I know) I took out my harddrive but I could not find anything that resembles a private key I could use. I was accessing through Saved Wallet. I still know my Pass Phrase. If I repair my faulty computer, any chance I can open up NEON Wallet again and login like the old way to access my NEO?

This is the account with my 22 NEO. https://neotracker.io/address/AUHTs4VyFqHBBusn5Asn3r1XACCfaDNuU5

Please help.

**Comment by stevesbrain** [comment]
@jerrechen What country are you in? I only ask because I do help/recovery in situations like this.

Aside from that, in what way did the laptop crash? What OS are you using? Which version of the wallet/app are you using? Can you see your other files properly?

**Comment by numero41** [comment]
@jerrechen 
if you have passphrase and password, no need to repair your computer, it's very easy to get back into your wallet.

**Comment by jerrechen** [comment]
@stevesbrain I am from Singapore. I spilled water on the laptop and it it sort of cannot turn on anymore. :(
I am using Windows 10 and the version of NEON Wallet at that time was 0.09.

 When I opened the 'userWallet' or so called 'keys' .json file in AppData/Roaming/Neon/storage, inside was showing just this:
'{}' Now I am scared that I might have accidentally overwritten the .json file.

Pls advise. Thank you so much.

**Comment by jerrechen** [comment]
@numero41 
I have the passphrase. What do u mean by Password? Pls help. Thank you so much.

**Comment by stevesbrain** [comment]
@jerrechen Yeah, userWallet.json should have contente similar to the following:
`{"name":"userWallet","version":"1.0","scrypt":{"cost":16384,"blockSize":8,"parallel":8,"size":64},"accounts":[{"address":"ANLSY3HW7sBgPoXc6FQDvHKfUqxEg8LRcY","label":"Herman","isDefault":false,"lock":false,"key":"6PYKzhkt7d7QsbUU9n3SJMfTYyhGxK83zY4ijCH9Gfna6bfGMBvUGdAEJz","contract":{},"extra":null}],"extra":null}`

Definitely looking at the correct user's AppData?

**Comment by jerrechen** [comment]
@stevesbrain 
Yes. Anyway I just managed to retrieve my NEO! :D Apparently somehow my .json file got overwritten. I managed to recover the old file with the encrypted keys using a Data Recovery app. Anyway thank you so much for your replies. I sincerely appreciate it. 👍

**Comment by stevesbrain** [comment]
@jerrechen Awesome, glad you were able to get it back; that would have been a dreadful feeling for a while! :)

**Comment by jezzaN** [comment]
What was the software you used to recover to do the data recovery as I am have a very similar issue. please help me

**Comment by stevesbrain** [comment]
@jezzaN There are a variety of solutions - Recuva is a popular free one, otherwise, R-Studio by R-TT is one I've had a lot of success with (but does cost a small amount of money).
