### ISSUE TITLE
Token and Balances not showing up

### ISSUE THREAD

**Issue by rflight23** [CityOfZion/neon-wallet#617]
In the screenshot below, you can see that there are five tokens listed in the Manage Token field:
![screen shot 2018-01-29 at 10 18 19 am](https://user-images.githubusercontent.com/4447366/35490902-c923b820-04dd-11e8-83ca-eb63ac35423e.png)

However, when I log into my wallet, you can see that each coin is not listed nor is their respective balances - see below:
![screen shot 2018-01-29 at 10 18 06 am](https://user-images.githubusercontent.com/4447366/35490908-ce1afd34-04dd-11e8-9909-2fab6944d3a6.png)

I've restarted my laptop, as well as the NEON wallet, but the token names still do not appear. Please advise on how to fix. Thanks.

**Comment by BIMEnergy1978** [comment]
I have the same problem, all my nep-5 tokens are not showing....... please advise..... need to withdraw to particepate in ICO

**Comment by hvredevoort** [comment]
I see same issue this morning using Ledger Nano S and NEON 0.1.1 and before I added the TKY hash. Adding TKY hash did nothing for me either.

**Comment by thepauljones** [comment]
Same here @BIMEnergy1978, this is a real shame.

**Comment by atcolombian** [comment]
I have the same issue, any update on this?

**Comment by iTarjei** [comment]
Same for ZPT. Tried 06, 07, 1.0, 1,1, mac, added ac116d4b8d4ca55e6b6d4ecce2192039b51cccc5,
ZPT is on neotracker, but not in neon.

**Comment by alexgolfy** [comment]
same problem here..and the NEO & GAS balances are not updating to reflect the transactions..however, I can see the transaction on the NEON Tracker

**Comment by hadv** [comment]
Cannot show the token and cannot claim GAS either :(

**Comment by DrRedShift** [comment]
Yep, same issue here, nothing showing up, transaction verified.

**Comment by hadv** [comment]
it seems that it stuck on the `1867982` block; latest block at the time of this post is `1,868,526`

**Comment by alexgolfy** [comment]
Indeed

**Comment by pacm92** [comment]
Same problem. Still have a 0$ balance… and transaction verified on neoscan ?

**Comment by hugoryder** [comment]
same problem

**Comment by hugoryder** [comment]
yes as hadv says its stuck on 1,867,982 block on my wallet too

**Comment by sbglive** [comment]
Same here. Feels like the team is not in a rush to reply - a similar issue was opened on this topic 20 days ago.

**Comment by hadv** [comment]
I'm using neon with ledger nano s then now cannot export private key to use on another wallet on neo tracker 😢

**Comment by hugoryder** [comment]
is there another neo app that could be used with the ledger s
ive got the same problem

**Comment by hadv** [comment]
I still cannot find any neo wallet can be used with ledger nano s :(

**Comment by rflight23** [comment]
The weird thing is once in a while when I check NEON, the other token names
and their respective balances will appear, but they disappear shortly after
(usually within 10 seconds or so)

**Comment by curatedcryptocurrencynews** [comment]
same issue: 

https://github.com/neo-project/neo/issues/158

retweet this tweet as well!! 
twitter: https://twitter.com/curatedcoinnews/status/958002771977912321

**Comment by pacm92** [comment]
it's stuck in block 1.868.181… I've checked the public address, it's the same on Neoscan VS Neon wallet ?? Maybe just a kind of Neon Wallet "refresh" bug ?

**Comment by esheds** [comment]
same problem here

**Comment by pacm92** [comment]
Fixed ! It just appeared on Neon, so I've sent it back straight away to Binance

**Comment by hadv** [comment]
yes, now the token appeared but the GAS claim seem still error.

**Comment by rflight23** [comment]
looks like the issue is resolved

[image: Inline image 1]

**Comment by hadv** [comment]
the token show but cannot send out :(

**Comment by hadv** [comment]
I have below error when sending out token/GAS

![neon-wallet-error](https://user-images.githubusercontent.com/941411/35551035-dd9580a8-05bf-11e8-9b23-3c33ee104699.png)

**Comment by pacm92** [comment]
I had a few "transaction failed" too, just start again (…and again) 'till it works

**Comment by hadv** [comment]
re-install neo on ledger nano s as following guide then it worked perfectly now 💯 

```
Okay to all who are having issues sending with NANO LEDGER 0.1.1. I fixed the issue. You need to reinstall the NEO application on your ledger using the Ledger Manager APP (Chrome Extension) from www.ledgerwallet.com/appsmanager . After this, you will be able to confirm a TX on your ledger itself (I couldn't which is why it failed).
```

**Comment by outlawza** [comment]
just noticed this on 0.2.5 and 0.2.6. Hopefully there is a simple fix out there?????

**Comment by BIMEnergy1978** [comment]
Try to use the Aphelion wallet.... Aphelion.org

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by kcmagicdata** [comment]
> Try to use the Aphelion wallet.... Aphelion.org 

This is what i was trying to do. Move my Thor tokens to Aphelion however cant do that when my tokens disapear or just never show up. I have no idea how to get them to show. Close reopen. Refresh or claim, nothing causes them to show up. So cant move them.

**Comment by kcmagicdata** [comment]
I just installed the O3 wallet, and life is good again. Neon wallet failed me.

**Comment by BIMEnergy1978** [comment]
I think I know your problem is. New coins need to be added in the wallet by using the menu. There is an Aphelion video guide that shows you how to de that.

But now your problem is solved, that advice is not worthy any more :-) . Good luck!

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________
