### ISSUE TITLE
Let Users Specify Node not only network

### ISSUE THREAD

**Issue by saltyskip** [CityOfZion/neon-wallet#618]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

For a variety of reasons nodes may be selected as a best node, but are still non responsive. This leads to the vast majority of issues where a transactions fails or a balance does not show up. A user should be able to manually connect to a node that they know works

**Comment by MediaServe** [comment]
As a temporary and dirty workaround you could add the hosts to `/etc/hosts` and NEON will connect to your IP address. I've successfully used this during ICO to make NEON more reliable.

```127.0.0.1	seed1.neo.org
127.0.0.1	seed2.neo.org
127.0.0.1	seed3.neo.org
127.0.0.1	seed4.neo.org
127.0.0.1	seed5.neo.org

127.0.0.1	seed1.cityofzion.io
127.0.0.1	seed2.cityofzion.io
127.0.0.1	seed3.cityofzion.io
127.0.0.1	seed4.cityofzion.io
127.0.0.1	seed5.cityofzion.io

127.0.0.1	api.otcgo.cn
```

It would be a lot better if this was a setting in NEON of course.

**Comment by comountainclimber** [comment]
Tracking this issue here https://github.com/CityOfZion/neon-wallet/issues/618 will be implemented in v2
