### ISSUE TITLE
Neon wallet 0.1.1 does not shown any tokens

### ISSUE THREAD

**Issue by jayvidgold** [CityOfZion/neon-wallet#619]
Hi,

Yesterday, I installed the latest and greatest version of the wallet and also added one custom token. Till yesterday it was visible though time to time the whole list used to vanish but today I don't see any tokens.

Help required at the earliest.

**Comment by livesloridefast** [comment]
I think it is failing to update. I transferred in tokens today, but the wallet shows yesterday's total.
online wallet / Neotracker.io show correct value. v0.1.1

**Comment by jayvidgold** [comment]
I don't see any tokens, with old version at least it used to show me, NEO, QLC and RPX with 0 tokens, which was correct. in fact, I added tokens day before yesterday and now I don't see any tokens.

**Comment by livesloridefast** [comment]
my wallet GAS is up to date but Claiming GAS now causes an error.
definitely something awry.

**Comment by curatedcryptocurrencynews** [comment]
I just started experiencing the same issue. Here are two posts touching on this topic:

1) https://github.com/neo-project/neo/issues/158
2)  https://github.com/kvhnuke/etherwallet/issues/1528

**Comment by issie81** [comment]
My balance is totally blank nothing there, going to Neotracker i can see i have the tokens, something very wrong with 0.1.1 and alot of users are experiencing this

**Comment by dennish007** [comment]
Tokens balance is updated every X seconds. Sometimes balance not shown (no tokens at all), sometimes balance is ok. This issue follows through when sending tokens. NEON says that there is no balance. 
This is a real annoyance. Must fix.

**Comment by anfn101** [comment]
Try version 0.1.2

**Comment by livesloridefast** [comment]
0.1.2 works fine.
