### ISSUE TITLE
Problem with Ledger Nano S & NEON Wallet

### ISSUE THREAD

**Issue by esheds** [CityOfZion/neon-wallet#620]
Hi guys, since this morning I cant withdraw, deposit or claim gas using my NEON wallet and my Ledger Nano S. When I'm asked to confirm a transaction (clicking both buttons in the Ledger Nano S) I get a failed msg in the wallet. What's going on? can someone help?

**Comment by curatedcryptocurrencynews** [comment]
I've been experiencing the same issue today

https://github.com/neo-project/neo/issues/158

Twitter: https://twitter.com/curatedcoinnews/status/958002771977912321

**Comment by sgehrman** [comment]
same problem

**Comment by stevesbrain** [comment]
Mine has done the same, but only on a proxied/filtered network. Tested today on an open/unfiltered network minutes later, and it works fine for me.

**Comment by cryptomd** [comment]
i have tried everywhere to get an answer to this issue but just get blown off.  Clearly the developers have no idea

**Comment by mhuggins** [comment]
Unfortunately the Ledger is on backorder, which makes it hard for the full CoZ team to support.  There will be more support in the near future once they have more in stock to fulfill backorders.

**Comment by KingVerso** [comment]
Okay, after playing around this is what worked for me, open up ledger manager on your laptop/pc, then uninstall the neo wallet and reinstall it. Worked first time after doing this :) Let me know if this works for you!

**Comment by Niels1990** [comment]
@KingVerso I tried to send CPX tokens, but it says: required 1 drop of GAS

What does that mean? And will my tokens be lost aftet uninstalling the neo app on my ledger?

I'm very scared about this whole situation...

**Comment by KingVerso** [comment]
@Niels1990 no ofc they won't be lost! I wouldn't reccomend it if it got your tokens lost! I did it myself and didn't lose a single thing!
