### ISSUE TITLE
NEO / Token Balance(s) missing or showing $0? -- Ledger Nano S Wallet NOT reflecting correct balance & GAS claim "error" received 

### ISSUE THREAD

**Issue by curatedcryptocurrencynews** [CityOfZion/neon-wallet#621]
I sent two (2) NEO from Binance to my Ledger Nano S wallet, however after approximately an hour, my balance is still not reflected on my NEO Ledger Nano S. When i check the scan, it shows that it was successfully sent and Binance shows a "successful" confirmation on their end as well.

Txid: e1aa2ceaabcd774d60fe2e65938f950a315d1c18ca7a04dad986aa9fbbf17f6d
Link: https://neoscan.io/transaction/e1aa2ceaabcd774d60fe2e65938f950a315d1c18ca7a04dad986aa9fbbf17f6d

My issue just occurred today. Two NEO were sent from Binance to a Ledge Nano S this morning. A confirmation was received, and the NEO is trackable here: https://neoscan.io/address/AJzkU2n7g52z6PYnEzQVgmFBQM3mNSYeoj

I seems as though NEOSCAN has been stuck on block 1,867,982 on my wallet, but in reality and at the time of writing this response the NEOSCAN shows 1,868,927. I was been able to successfully use a Ledger nano S for the last few months without issues.

I now also (as of a few hours ago) cannot claim GAS from the Ledger Nano S either. I received a "failed" error message.

Has anyone else been experiencing this issue?

Let us know of twitter too: https://twitter.com/curatedcoinnews/status/958020416873754624

**Comment by nazimbeyy** [comment]
Again almost same as i sent 1 neo and blockchain shows its done but 0 neo on my neon wallet

**Comment by curatedcryptocurrencynews** [comment]
I just refreshed my ledger nano wallet and now my block has rolled to 1,868,110.

Originally stuck on: 1,867,982
Now stuck on: 1,868,110

**Comment by curatedcryptocurrencynews** [comment]
Originally stuck on: 1,867,982
Second refresh stuck on: 1,868,110

Now on block 1,868,173

**Comment by curatedcryptocurrencynews** [comment]
FIXED!!!! Showing up now! :-)

**Comment by nazimbeyy** [comment]
Fixed in the end =)

**Comment by rreuss79** [comment]
same problem here: 
txid: f5c670f63ab4cb5ba9a895ecb6105830ffc5b93a5e256452affdbe117516603c

now stuck on wallet , public adress: AHk7t8cKGDM2sARMFUw7F5zjPdqNCbnnjj 

Do I wait or can I do something active ?  - 
my transaction was a withdrawal from neon wallet 0.1.1 to binance neo deposit address:  AFtowZi6HdpNgSo1d2QiT2yJ4YtzFJRPBo

**Comment by sgehrman** [comment]
same problem

**Comment by rreuss79** [comment]
which wallet were you using ?

**Comment by rreuss79** [comment]
which wallet were you using? - and is it same adress like this one
AHk7t8cKGDM2sARMFUw7F5zjPdqNCbnnjj

2018-01-30 2:12 GMT+01:00 Steve Gehrman <notifications@github.com>:

**Comment by Totof-92** [comment]
Hello,

I think I have the same issue...
No transaction appear into the software (sync with ledger nano s)

**Comment by rreuss79** [comment]
beware of coin hijack on neotracker.io 
Hijack wallet ID : AHk7t8cKGDM2sARMFUw7F5zjPdqNCbnnjj

**Comment by OrEagle97327** [comment]
Have you solved your issue?

in the last couple of days, we have Ledger trying to be involved.

Looking for all to be on the list (hopefully with Ledger support number, if possible)

We have Eth, Neo and Xrp involved.

**Comment by Stanley-Lim** [comment]
I sent NEO from NEON wallet to Kucoin and lost half of my tokens. Any advise what I can do?
I can see in the NEOTracker that it says "unspent". How can I solve this? or should I just wait?

**Comment by JanMooMoo** [comment]
To the Hacker AHk7t8cKGDM2sARMFUw7F5zjPdqNCbnnjj

If you are seeing this please give me back my Tokens im begging you.. 😭i am poor and  thats all i have... I am new to crypto and i saved money just to buy 3 neos to participate to token sale hoping that it could make my shitty life a little bit better, please im begging you i need it so much. You ptobabky don't need it but i really really do..  That is my only hope and you took it away from me. Please from the bottom of my heart im begging you i hope you see this..  I have no way to contact you but i will try.. This is the wallet that you've stolen from

AXifDecenvXmpeWUjfSwPGCkQCJLxwVtp8

Please.....

**Comment by aballan3** [comment]
https://neonwallet.com/

I reinstalled the neon wallet to make sure I had the latest version and my neo appeared.
