### ISSUE TITLE
NEO unspent after 8 hours with NEON 1.1

### ISSUE THREAD

**Issue by vladesca91** [CityOfZion/neon-wallet#622]
Hi, I sent today 5 NEO from one adress of my neon wallet to my ledger s adress with neon wallet. After 6 hours I can see the balance on neoscan but the tx is still unspent and not generating gas. What should I do?

**Comment by curatedcryptocurrencynews** [comment]
There is a current issue with the wallet showing balances, claiming gas, etc.. 

See here: https://github.com/CityOfZion/neon-wallet/issues/621
