### ISSUE TITLE
Neon wallet 0 balance

### ISSUE THREAD

**Issue by nazimbeyy** [CityOfZion/neon-wallet#623]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by curatedcryptocurrencynews** [comment]
Same issue: https://github.com/CityOfZion/neon-wallet/issues/621

**Comment by curatedcryptocurrencynews** [comment]
Fixed now?

**Comment by nazimbeyy** [comment]
Fixed in the end =)

**Comment by nabilove** [comment]
nazimbeyy  wath di you do to fix issue please
