### ISSUE TITLE
Transfer NEO from wallet to Bifinex

### ISSUE THREAD

**Issue by psimone1982** [CityOfZion/neon-wallet#626]
hallo, i sent my neos from wallet to bitfinex exchange platform 22 hours ago.
the confermations number continue to grown up but no one neos was transfer to the platform.
into the wallet the neos have been removed but i can't see on the exchange.
what i can do?

**Comment by mhuggins** [comment]
For support using the software or concerns about the status of your funds, please go to the #support channel on the [NEO Smart Economy Discord Server](https://discord.cityofzion.io).

GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.
