### ISSUE TITLE
Forgot to save my private key

### ISSUE THREAD

**Issue by ahnr** [CityOfZion/neon-wallet#63]
Hello, 

I just signed up for my neo wallet yesterday, but I forgot to save my private key. Is there any way I could recover it? I have the transaction history from bittrex to validate the transaction.

**Comment by canesin** [comment]
Nobody can help you if you lost your private keys, that is a feature.

**Comment by ahnr** [comment]
Really? There's no log within the neon wallet directories that would have my key? Please, I need help. I put 250 neo in my wallet.

**Comment by anfn101** [comment]
No. A log would be a terrible idea and be extremely unsecure. People would have their money stolen very easily if this were the case.

**Comment by ahnr** [comment]
Is there anything in the neon folder that could lead to my private key?
Anything? Can I get a 2nd opinion from a senior engineer/developer?

**Comment by canesin** [comment]
I'm so sorry for your loss @ahnr, I have also lost about 200 bitcoins by loosing my keys in the past. This is math, not a simple rule that can be broken - this is the result of the so called hiding property of cryptographic hash functions.

**Comment by ahnr** [comment]
Fabio,

Could the private key be stored in any type of log or folders within the
neon folder? Can we 100 percent validate this?

**Comment by canesin** [comment]
@ahnr no, it is not stored.
1000 percent validate: you can look at the code for the reducer here: https://github.com/CityOfZion/neon-wallet/blob/master/app/modules/account.js .. it is held only on memory, if you logout the structure is destroyed from memory.

**Comment by anfn101** [comment]
Yes, exactly- if it was stored that would be a horrible security risk. Obviously unwanted.
