### ISSUE TITLE
Unable to claim gas - Neon v9 & Nano

### ISSUE THREAD

**Issue by olivergray24** [CityOfZion/neon-wallet#630]
I've been unable to claim gas for about 1 week now with Neon v9 and Nano (100% failure rate) and have also had a high failure rate of sending neo and gas, getting the error Transaction Failure. I do not think this is a Win7 PC issue as I have zero trouble with a different wallet (non-Nano) using the same Neon v9 client instance when claiming gas and sending neo/gas. I do not believe it is a problem with the Nano either since  cloned my Nano to a brand new one (restored the seed) to get to the same wallet with a fresh install of Ledger Neo app, same exact problem. No other app problems with the Nanos and they are at firmware 1.3. Also tried re-installing the Neon client on the PC and also on a Win7 laptop, and tried from various networks (home, 2 work locations), same problem. I also see many people have similar problems with latest version 1.1 so I'd rather not upgrade and get a the same or new problems. I'd really like to get this fixed asap, I have a good amount of Neo and I'm accruing a of gas that I can't claim, plus concerned about the frequent transaction failures as well. I'd rather not go back to using just Neon and not the Nano but if it means not losing a lot of unclaim-able gas I might have to weigh that risk. Please help.

**Comment by olivergray24** [comment]
Also tried the new version of Neon, 0.1.2, it seems to try harder & longer but still fails with "Claim failed" message.

**Comment by anfn101** [comment]
Make sure to have both Ledger Neo app and Neon wallet reinstalled. Make sure there is no firewall issue. You can check on the status of your funds at Neoscan or Neotracker. Also note: Github is used to report code issues. Any support can be found in the Discord #support channel.
