### ISSUE TITLE
Build neonwallet.com website and auto-deploy from source

### ISSUE THREAD

**Issue by Ejhfast** [CityOfZion/neon-wallet#635]
The neonwallet website is currently stored in compiled/built form. This means that changes to the website need to be built somewhere else and PR'd to master, or edited manually in the minified JS. We would like to change this to have a build pipleline directly in the project, such that the source for the website lives in the repo in a clean form. neon-js provides good inspiration here (look at how it compiles the documentation).

**Comment by comountainclimber** [comment]
I propose the following... 
1.) We remove `/NEON Website Design` and `/docs` from neon-wallet 

2.) put `/NEON Website Design` into https://github.com/comountainclimber/neon-website

3.) Either A.) create a new repo under the coz repositories or B.) leverage what already exists in the repo above. Using github pages (which is already built into the deployment of the react application of the repo) we can simply change DNS settings on github to configure them for `neonwallet.com`.

Once item number 3 is implemented any merge into `gh-pages` branch will automatically update the production website.

**Comment by Ejhfast** [comment]
this sounds good to me -- lets move the neon-website repo to the CoZ org? @comountainclimber I added you to the org, can you setup the repo there? we can then move the DNS

**Comment by mhuggins** [comment]
I agree, sounds good to me.

**Comment by comountainclimber** [comment]
🎉  https://github.com/CityOfZion/neon-wallet-website and http://cityofzion.io/neon-wallet-website/
`npm run deploy` deploys the latest to that second url. DNS settings can be configured for the repo for neonwallet.com

**Comment by comountainclimber** [comment]
@Ejhfast we can probably close this guy all we should need to do is update DNS settings on https://github.com/CityOfZion/neon-wallet-website

**Comment by anfn101** [comment]
Any update? @Ejhfast @comountainclimber

**Comment by comountainclimber** [comment]
@anfn101 If I can get the DNS settings from someone with that knowledge we will be all set

**Comment by mhuggins** [comment]
This has been done for a little while now. 😄
