### ISSUE TITLE
New version claims wallet is out of date

### ISSUE THREAD

**Issue by stevesbrain** [CityOfZion/neon-wallet#638]
Hi all,

Just updated to 0.1.2 on Linux via the .deb file. The wallet has now started claiming it is out of date, and needs to be updated. I have confirmed via the releases page that 0.1.2 is definitely the latest version. Any indication of why this might be happening? Thanks!

**Comment by stevesbrain** [comment]
Appears they must have updated something server-side. This no longer occurs. Closing the ticket.

**Comment by welcomyou** [comment]
Version 0.1.2 on Windows still get this problem

![image](https://user-images.githubusercontent.com/36091703/35761370-3ccc47da-08ba-11e8-87ba-79a9210a91e9.png)

**Comment by jackson-sandland** [comment]
Just saw this as well.

**Comment by stevesbrain** [comment]
@welcomyou I mean, 0.1.2 is 2 months old, so that is to be expected
