### ISSUE TITLE
Lost NEO during deposit

### ISSUE THREAD

**Issue by zstern9190** [CityOfZion/neon-wallet#64]
I deposited some NEO into your walled and I was shorted 1.5. They are just not there. Can someone help me retrieve them?

**Comment by zstern9190** [comment]
Just another note. I transferred from bittrex and they take .1 so I should have only lost .2 since I did two transfers.

**Comment by canesin** [comment]
This is not related to neon, this is due to bittrex police. Please read this thread https://github.com/CityOfZion/neon-wallet/issues/55
