### ISSUE TITLE
Suggestion: Neon Wallet over HTTPS intead of HTTP

### ISSUE THREAD

**Issue by Dan-Richards-1985** [CityOfZion/neon-wallet#642]
Hi,

I've noticed that the Neon wallet is using HTTP to query the api's of api.wallet.cityofzion.io and seed.cityofzion.io .
It creates several security concerns because the data is present as plain text between the Neon wallet and the server.
Is there an option to transmit the data via HTTPS for enhanced security?

**Comment by anfn101** [comment]
Duplicate issue
