### ISSUE TITLE
Fuck this NEO wallet you cant even take-out your GAS !!!! 

### ISSUE THREAD

**Issue by billethekid** [CityOfZion/neon-wallet#645]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by mhuggins** [comment]
For support using the software or concerns about the status of your funds, please go to the #support channel on the [NEO Smart Economy Discord Server](https://discord.cityofzion.io).

GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.
