### ISSUE TITLE
Initial issues yesterday

### ISSUE THREAD

**Issue by jmiller2152** [CityOfZion/neon-wallet#65]
So I was having issues and had to get a private key a few times yesterday while testing a deposit of 1 neo, when I finally got it to work I did not store my private key and when I went to login this morning I was locked out....is there anyway to recover? I have the public key from the withdrawal but that is it. I know it is just 1 neo but any help?

**Comment by canesin** [comment]
unfortunately we cant help you, see https://github.com/CityOfZion/neon-wallet/issues/63. We are implement new features to avoid this.
