### ISSUE TITLE
After clicking the trash bin icon in Manage Neon Settings, all wallets with same key were deleted.

### ISSUE THREAD

**Issue by zubik669** [CityOfZion/neon-wallet#652]
Thanks for providing this wallet.
I'm using Neon wallet 0.1.2. 

I accidentally reproduced 3x the issue #601: neon saving wallet multiple times (with the same name).
Now I got the idea to remove the extra 2 wallets. After clicking the trash bin icon in Manage Neon Settings, all three wallets were deleted.

Now, I'm able to recover the wallet with Passphrase and Encrypted Key, but I can't find how to store the wallet locally again.

Upsetting.

**Comment by joshrio** [comment]
I reproduced the error myself. 

A way to prevent this would be to prevent created a disabled state on the button once a name is successfully saved.

**Comment by comountainclimber** [comment]
This issue is resolved in v2 wallet manager UX closing this now
