### ISSUE TITLE
hi, i created 2 neon wallets and saved all the details e.g passphrase and keys but stupidly when icreated the second wallet i forgot my passphrase and didnt save the keys. i saved the wallet but cant access it. is there anything i can do as i have funds in it??

### ISSUE THREAD

**Issue by carlos696969** [CityOfZion/neon-wallet#653]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by mhuggins** [comment]
Unfortunately not.  You need to have the passphrase to decrypt the encrypted WIF or the WIF itself.  This is the basis of the security of a wallet address, so you will not be able to access the wallet without one or the other.
