### ISSUE TITLE
Withdrew NEO tokens from Binance to Nano Ledger S. Showing ZERO BALANCE

### ISSUE THREAD

**Issue by alboogs** [CityOfZion/neon-wallet#659]
Hello, I recently withdrew my NEO tokens from Binance and sent it to my Nano Ledger S Neo Wallet. Binance had a confirmation saying it was sent. However, when I logged into my Nano Ledger S, it said ZERO BALANCE. It is because now I found out that I have a different NEO ADDRESS.  It was sent to my ORIGINAL NEO ADDRESS but it's no longer my current address when I log into my Nano Ledger. Why did my 'sent address' change?? Can someone please reply back with the proper steps to help me retrieve my tokens. Thanks in advance.

**Comment by numero41** [comment]
Hello, is your issue the same as here?

https://github.com/CityOfZion/neon-wallet/issues/524

If so, you can fill this form, it will be analysed by Ledger support.

https://docs.google.com/forms/d/e/1FAIpQLSfgEim2xICDBcpL6tL5q0_BKYCNevT5Q6-qVyegJhe4tdz6cw/viewform?usp=sf_link

**Comment by alboogs** [comment]
@numero41 Thank you! I filled out the online form and submitted. I hope we can get this issue resolved soon.

**Comment by OrEagle97327** [comment]
My thread is #524. 

Ledger wants to claim it is the software wallets.

We need to gather as many users, as possible. who lost tokens of any kind, in one list

This "undocumented feature" (bug) in the Ledger Nano S is causing users to loose assets.

When we show the same symptoms across several tokens, that takes it back to one common denominator. The hardware. The Ledger Nano S.

**Comment by ayanca** [comment]
How did you found out that you have a different adress? I have a similar problem...I withdrawal from binance 150 neo ,sent in to my neo ledger adress,my neo showed in there,but after a few hours my neo were transferred to another adress...I didn't made that transfer....but when I log in to ledger I have the same adress as I had before....is it possible that I ve been hacked or it's a bug??please help!!!

**Comment by zenderady** [comment]
This is happening to me too.. using ledger nano s. I see the block is far behind and would not update to the present one. I think this is why the balanace does not show up.. because the neon wallet did not reach the transfer block yet.

**Comment by OrEagle97327** [comment]
We are asking users who lost tokens using the Ledger Nano S input here (any and all token)
https://docs.google.com/forms/d/e/1FAIpQLSfgEim2xICDBcpL6tL5q0_BKYCNevT5Q6-qVyegJhe4tdz6cw/viewform?usp=sf_link

Results can be viewed here : https://docs.google.com/spreadsheets/d/1afBgZ5yvr6FHN1CBl2bSlJIEfbpNtHukQSqW731gXmE/edit?usp=sharing

Anyone who has suggestions of where to go with this please give us you input!

**Comment by anfn101** [comment]
Please consolidate in thread #524 . Also note: Github is used to report code issues. Any support can be found in the Discord #support channel.
