### ISSUE TITLE
My wallet is at 0

### ISSUE THREAD

**Issue by emilieleblanc** [CityOfZion/neon-wallet#66]
I dowloaded the wallet on my mac today. Transferred my neos successfully. Came back tonight and had trouble to open the app. Finally opened it and it's now empty...

**Comment by hbentel** [comment]
same issue here

**Comment by hbentel** [comment]
ah, this version fixed it
https://github.com/CityOfZion/neon-wallet/releases/tag/0.0.3c

thx!

**Comment by Ejhfast** [comment]
@emilieleblanc please install the latest version linked above, bittrex API change broke the balance display in the old version

**Comment by emilieleblanc** [comment]
I just did and it still doesn't work. It's empty. Yesterday when i opened it, it blink an 8 (the amount i am supposed to have) and then went back to 0. I tought i had it but it disappeared.

**Comment by stevesbrain** [comment]
@emilieleblanc What does the block explorer say? Is it an issue where your wallet has no balance according to blockchain, or, is it an issue with neon?

**Comment by emilieleblanc** [comment]
I don't know what you mean. It's all new for me. The funds were transferred yesterday. After i closed it, when i reopened, it was gone.

**Comment by emilieleblanc** [comment]
It's the new wallet on mac

**Comment by emilieleblanc** [comment]
I did. Still at 0.


Emilie Leblanc
514-886-9818
www.azuraevenements.com<http://www.azuraevenements.com>

Le 2017-08-10 à 01:26, Ethan Fast <notifications@github.com<mailto:notifications@github.com>> a écrit :


@emilieleblanc<https://github.com/emilieleblanc> please install the latest version linked above, bittrex API change broke the balance display in the old version

**Comment by stevesbrain** [comment]
@emilieleblanc Do you know your wallet address? If so, visit http://neotracker.io/address/YOURADDRESS (for example, http://neotracker.io/address/AJnuMArKJV548E1H2B3X8wK99b6yR7qfxn ) and check the balance listed there. Is it zero, or is it a positive balance?

**Comment by emilieleblanc** [comment]
Public key i guess…
It’s searching… It’s been 15 minutes and still searching.


@emilieleblanc<https://github.com/emilieleblanc> Do you know your wallet address? If so, visit http://neotracker.io/address/YOURADDRESS (for example, http://neotracker.io/address/AJnuMArKJV548E1H2B3X8wK99b6yR7qfxn ) and check the balance listed there. Is it zero, or is it a positive balance?

**Comment by emilieleblanc** [comment]
Ok. So my public address displayed in my wallet is different than the one on bittrex where i can see the transfer. Since i only have one wallet, why is this happening? My wallet displayed it yesterday. When i put the public address i have on bittrex, it shows me my balance. When i use the current public address on my wallet, it cannot find the page.



@emilieleblanc<https://github.com/emilieleblanc> Do you know your wallet address? If so, visit http://neotracker.io/address/YOURADDRESS (for example, http://neotracker.io/address/AJnuMArKJV548E1H2B3X8wK99b6yR7qfxn ) and check the balance listed there. Is it zero, or is it a positive balance?

**Comment by stevesbrain** [comment]
@emilieleblanc Are you saying the address you withdrew from Bittrex to is not the address in your wallet? Where did you get the address from that you put into Bittrex? Did you change your private WIF at some stage, and see a different public address from there? If your WIF is the same, the address will be the same. 

I'm thinking either the WIF was entered differently, or, you copied a public address from somewhere else. If you're happy to, and it makes it easier, feel free to provide your public addresses + screenshots and it may shed some more light. If you don't want to do it in the public eye, let me know and I'll happily give you a private means to contact me.

**Comment by emilieleblanc** [comment]
I copied the link of my public address directly in my wallet. And no, it's not the same on bittrex than the one in the app. I took care of printing and stored the links... I have no idea how that could happen. I would really like to send it to you in private. I didn't change the wif. I did exactly what i was supposed to do. As far as i know...
Thank you so much for your help.


@emilieleblanc<https://github.com/emilieleblanc> Are you saying the address you withdrew from Bittrex to is not the address in your wallet? Where did you get the address from that you put into Bittrex? Did you change your private WIF at some stage, and see a different public address from there? If your WIF is the same, the address will be the same.

I'm thinking either the WIF was entered differently, or, you copied a public address from somewhere else. If you're happy to, and it makes it easier, feel free to provide your public addresses + screenshots and it may shed some more light. If you don't want to do it in the public eye, let me know and I'll happily give you a private means to contact me.

**Comment by stevesbrain** [comment]
No worries @emilieleblanc - send me an email to: github-contact :at: tuxcon dot com    (obviously, take the :at: and "dot" and substitute them - anti-spam measures). Talk soon :)

**Comment by emilieleblanc** [comment]
I just sent you an email.

Talk soon.

Emilie Leblanc



No worries @emilieleblanc<https://github.com/emilieleblanc> - send me an email to: github-contact :at: tuxcon dot com (obviously, take the :at: and "dot" and substitute them - anti-spam measures). Talk soon :)

**Comment by emilieleblanc** [comment]
I know my post is considered as « closed », but i still cannot recover my coins and my app will not open again… I click the icon and nothing happens.
What is this wallet?? A scam?? Have i been scammed?

Emilie Leblanc


Le 2017-08-10 à 23:52, Steve Divskinsy <notifications@github.com<mailto:notifications@github.com>> a écrit :


No worries @emilieleblanc<https://github.com/emilieleblanc> - send me an email to: github-contact :at: tuxcon dot com (obviously, take the :at: and "dot" and substitute them - anti-spam measures). Talk soon :)
