### ISSUE TITLE
TKY token visible on neotracker, not on NEON , even after 24 hrs.

### ISSUE THREAD

**Issue by Silvershad6w** [CityOfZion/neon-wallet#662]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

Using latest 0.1.2 version of neon with nano ledger s (also latest firmware and neo app

**Comment by mhuggins** [comment]
Have you added the token's scriptHash on the wallet settings screen?

**Comment by Silvershad6w** [comment]
Yes I have added the correct scripthash. Tried removing it and adding it back on couple of times.
The weirdest thing is that I had 2 deposits. One of 100 TKY which was done on feb 2nd. And one of larger amount done yesterday (tx confirmed and visible on neotracker).

Only the first one shows up in Neon. Second one does not.
Both are available on neotracker though.
Something is seriously wrong, I heard many others having same issue with Neon client and TKY.

**Comment by simossss** [comment]
I have the exact same problem. 
TKY ticker shows in NEON after adding the hash, balance is 0. Neotracker shows balance.

**Comment by numero41** [comment]
Did you check that your public address is still the same you had at the time you made the transaction?

**Comment by simossss** [comment]
Of course. As I said, the same address shows a balance on neotracker - which is correct - and 0 balance on NEON.

**Comment by Silvershad6w** [comment]
Any updates?

**Comment by brianlenz** [comment]
@simossss, @Silvershad6w: I'm looking into this issue. Would either of you mind sharing your NEO addresses so I can take a further look?

**Comment by IanBlacktar** [comment]
Have the same situation as @Silvershad6w with transferring small amount 100 TNC from KuCoin as a first transaction and few minutes after larger transaction. Neon showing only first balance 99 TNC. 
@Silvershad6w is your isuue is solved?

**Comment by Silvershad6w** [comment]
My issue was solved. Looked to be a failed tx which was seen as successful in Neotracker, hence the discrepancies between the Neon balance and the one shown on neotracker. The failed tx never deducted the balance from the originating wallet. So in short: my issue was a bug in neotracker and not in Neon it seems.

**Comment by IanBlacktar** [comment]
Ok, so my case is a little bit different. Kucoin is showing two of withdrawals as "Succeeded" but only first is shown on Neo Tracker. Any clues where my second transaction gone?

**Comment by mhuggins** [comment]
@brianlenz Curious where this left off.  Is this something that can be closed now?

**Comment by brianlenz** [comment]
@mhuggins I would close it. I never heard back, so couldn’t investigate their specific issues. I’m not aware of any ongoing balance issues/discrepancies at this point...

**Comment by IanBlacktar** [comment]
My case was solved with Kucoin support after few @. So finally I got back my TNC’s :)
