### ISSUE TITLE
TKY funds show perfectly fine on Neotracker, but does not on NEON

### ISSUE THREAD

**Issue by quagmireccg** [CityOfZion/neon-wallet#665]
Many users are experiencing the same problem with NEON 0.1.2 or lower version.

TKY tokens are visible perfectly on neotracker, but on NEON wallet they show up as 0 balance.

What is the root of this?

**Comment by sp3** [comment]
This is a bug that currently a lot of people are facing against. Newest NEO Ledger app, NEON 0.1.2 - same scenario, tokens are visible on neotracker but the TKY account balance on NEON displays 0, that prevents every holder from moving their assets.

**Comment by Volodymyr2929** [comment]
Same with TNC tokens even worst ,tokens are not even visible on neotracker.

**Comment by Silvershad6w** [comment]
Guys is any developer looking into this now ?

**Comment by Easaaaaaaaa** [comment]
same problem

**Comment by zenderady** [comment]
This is happening to me too.. using ledger nano s. I see the block is far behind and would not update to the present one. I think this is why the balanace does not show up.. because the neon wallet did not reach the transfer block yet.

**Comment by anfn101** [comment]
Duplicate

**Comment by brianlenz** [comment]
@zenderady, @Easaaaaaaaa, @Volodymyr2929, @quagmireccg: Would any of you who are still having this issue mind sharing your NEO address? I am doing some investigation into these 0 balance issues. Thanks!

**Comment by Easaaaaaaaa** [comment]
thanks a lot brian, but I found out that the problem was neotracker, and not yours :) thanks for your work!
