### ISSUE TITLE
NEON 0.1.2 - Unable to claim GAS and unable to withdraw NEO

### ISSUE THREAD

**Issue by olingki** [CityOfZion/neon-wallet#666]
I am using NEON Wallet 0.1.2 and I am unable to perform the following actions:

1. To claim the GAS balance

2. To withdraw NEO from my NEON Wallet

I noted this is a very common issue...could somebody help to resolve...?

**Comment by anfn101** [comment]
Duplicate #660

**Comment by derwen** [comment]
You closed all issues related to this as duplicates. You didn't leave a single one open. What the hell?

This is not closed or solved!!!

**Comment by mhuggins** [comment]
#660 is still open to track this issue.

**Comment by olingki** [comment]
Alan - My issue has two elements, 1) cannot claim GAS and 2) cannot withdraw NEO. #660 duplicated the first element only.

I understand closing issues makes things look better but please be more sensible.
