### ISSUE TITLE
cannot send tky tokens from neon wallet

### ISSUE THREAD

**Issue by lulime** [CityOfZion/neon-wallet#667]
trying to send tky and zpt tokens from neon wallet, but tky or zpt are not on the asset dropdown.  I can write it but it automatically changes it to NEO.  I added the tokens and can see my balance in the wallet, but when I try to send any of them, it doesn't allow me.  I do have GAS, have the Neon wallet version 0.1.2, and use a nano ledger.

**Comment by buddhaman8** [comment]
I am also unable to send my QLC tokens from my NEON wallet (0.1.2) I have GAS  but QLC isn't in the drop-down menu to send.....Any clues guys?

**Comment by anfn101** [comment]
Duplicate

**Comment by lulime** [comment]
@anfn101  If it's duplicate, where can I find the answer?

**Comment by mhuggins** [comment]
#662 is related to TKY

**Comment by lulime** [comment]
That doesn't answer my question. I still have the same problem. Uninstalled and installed Neon again the newest version and nothing. Uninstalled and installed a previous version and nothing.

**Comment by brianlenz** [comment]
@lulime: I'm looking into this issue. Would you mind sharing your NEO address so I can take a further look? Thanks!

**Comment by lulime** [comment]
Hi, I was able to use a friend’s laptop to send my tokens to an exchange. I can still give you my Neo address if that helps, but there are no tokens anymore.

**Comment by brianlenz** [comment]
@lulime no that's OK. We're just looking for anybody else who is still experiencing the 0 balance issue in Neon wallet. Thanks anyway!

**Comment by Ipodbob** [comment]
Same I do not have any tokens showing up either, annoyingly I do not have my tx hash... but I do have my receiving address and it shows nothing
