### ISSUE TITLE
neon wallet 0.0.6 private key not working on versions after

### ISSUE THREAD

**Issue by jezzaN** [CityOfZion/neon-wallet#673]
hi so i created my wallet on version 0.0.6 and have the private key and encrypted key written down. i also had it save to my wallet on my laptop but my laptop did an update and has forgotten my wallet on the neon wallet. my private key and encrypted key only work on version 0.0.6 but do not show my balance is there anyway i can get my computer to remember these files so i can access my wallet in a later versions? as my private key and encrypted key are not valid on later version as i don't think the are long enough. if any one can help me fix this would be much help and appreciated 

## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by jezzaN** [comment]
i will also give some neo to anyone that helps me fix this problem

**Comment by Cerv4ntez** [comment]
Hi jezzaN,
You can easily work around this problem. Create a new wallet with the most recent Neon Client. Write down all the key info, address and password. deinstall, install the 0.0.6 version which works with your wallet and transfer your funds to the new wallet. I did that when i moved to store my neo on my ledger.

**Comment by jezzaN** [comment]
It does not show my balance on my 0.0.6 account tho and I have participated in an ico which got sent to my account when I had access through my pc wallet. What can I do to make it show my balance on the 0.0.6?

Sent from my iPhone

On 11 Feb 2018, at 17:51, Cerv4ntez <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi jezzaN,
You can easily work around this problem. Create a new wallet with the most recent Neon Client. Write down all the key info, address and password. deinstall, install the 0.0.6 version which works with your wallet and transfer your funds to the new wallet. I did that when i moved to store my neo on my ledger.

**Comment by Cerv4ntez** [comment]
check your address on neotracker, you can check your balance and all transactions there, simply search for your address (no private keys are ever needed to check the blockchain)

**Comment by jezzaN** [comment]
Yes I can see all that I have in my wallet on there but my private key doesn’t work on there either as that wallet was from 0.1.1 so what should I do now?

Sent from my iPhone

On 11 Feb 2018, at 20:38, Cerv4ntez <notifications@github.com<mailto:notifications@github.com>> wrote:


check your address on neotracker, you can check your balance and all transactions there, simply search for your address (no private keys are ever needed to check the blockchain)

**Comment by Cerv4ntez** [comment]
are you sure you wrote the key and password down correctly? if you install the last version that worked for you, you should be able to transfer your funds to another wallet you own and thats working with the recent neon wallet. if there is no version that works with your key, there must be something wrong with your key

**Comment by jezzaN** [comment]
Ok say I have the key down wrong I have my public jay and password can I do anything with that?
Also my private key opens the 0.0.6 wallet just doesn’t show the balance

Sent from my iPhone

On 12 Feb 2018, at 04:56, Cerv4ntez <notifications@github.com<mailto:notifications@github.com>> wrote:


are you sure you wrote the key and password down correctly? if you install the last version that worked for you, you should be able to transfer your funds to another wallet you own and thats working with the recent neon wallet. if there is no version that works with your key, there must be something wrong with your key

**Comment by jezzaN** [comment]
Also when you hit save file when creating a new wallet where does that file get stored and what is the file type?

Sent from my iPhone

On 12 Feb 2018, at 04:56, Cerv4ntez <notifications@github.com<mailto:notifications@github.com>> wrote:


are you sure you wrote the key and password down correctly? if you install the last version that worked for you, you should be able to transfer your funds to another wallet you own and thats working with the recent neon wallet. if there is no version that works with your key, there must be something wrong with your key

**Comment by Cerv4ntez** [comment]
that your key unlocks the old wallet is good news. i guess where the files get stored varies by platform used, good idea to figure that out and make a backup of those files. As for your key, this https://snowypowers.github.io/ansy/ might be able to help you to decrypt your key. Be careful though and do this offline. as far as i know this project is legit but you never know. So download the webpage go offline and open in browser and try to decrypt your key

**Comment by jezzaN** [comment]
Ok I will try that when I get home, I am using windows platform so what sort of file would it be?

Sent from my iPhone

On 12 Feb 2018, at 06:14, Cerv4ntez <notifications@github.com<mailto:notifications@github.com>> wrote:


that your key unlocks the old wallet is good news. i guess where the files get stored varies by platform used, good idea to figure that out and make a backup of those files. As for your key, this https://snowypowers.github.io/ansy/ might be able to help you to decrypt your key. Be careful though and do this offline. as far as i know this project is legit but you never know. So download the webpage go offline and open in browser and try to decrypt your key

**Comment by jezzaN** [comment]
So it just say private key not long enough on that website.
[image1.jpeg]
This is what comes up when I use the private key on 0.0.6 what else can I try to restore it?

Sent from my iPhone

On 12 Feb 2018, at 06:14, Cerv4ntez <notifications@github.com<mailto:notifications@github.com>> wrote:


that your key unlocks the old wallet is good news. i guess where the files get stored varies by platform used, good idea to figure that out and make a backup of those files. As for your key, this https://snowypowers.github.io/ansy/ might be able to help you to decrypt your key. Be careful though and do this offline. as far as i know this project is legit but you never know. So download the webpage go offline and open in browser and try to decrypt your key

**Comment by jezzaN** [comment]
sorry i dont think you can see the image but all it show is my neon wallet with please update in red at the top and a green send button under it and thats it.

**Comment by jezzaN** [comment]
i have my encypted key written down to but that doesn't seem to work on the later versions either

**Comment by Cerv4ntez** [comment]
well, did you try to decrypt your key with ansy? a decrypted key should let you back into your wallet on all versions of neon

**Comment by jezzaN** [comment]
so if it manages to decrypt it on 0.0.6 what do i do with it then to save it to the pc? and can i access my private key from there?

**Comment by jezzaN** [comment]
how long shold it take to decrypt it? its been going a while now

**Comment by Cerv4ntez** [comment]
i think it should decrypt it almost instantly

**Comment by Cerv4ntez** [comment]
when you have your key decrypted you should be able to import it to recent versions of neon. i would advise against keeping it that way, as soon as you have control over your wallet again, consider reincrypting your key or getting yourself a ledger nano s for savekeeping

**Comment by jezzaN** [comment]
well thats not happening :( its still trying anyway. Is there anything else i can try?

**Comment by Cerv4ntez** [comment]
where is it stuck, in ansy or neon wallet?

**Comment by jezzaN** [comment]
sorry i have only been trying in neon wallet what is ansy?

**Comment by jezzaN** [comment]
i have tryied ansy with my private key not with my encrypted key tho

**Comment by Cerv4ntez** [comment]
you have your key both encrypted and unencrypted? and both of them do not work?

**Comment by Cerv4ntez** [comment]
are you talking about a key or a password? from what i gathered you had an encrypted key(which may be incomplete) and a password used to decrypt it. i pointed you to ansy in order to enable you to decrypt your encrypted key with your password and use the decrypted key to import to a newer neon version

**Comment by jezzaN** [comment]
my private key is to short on ansy, i now my password/phase for sure. on ansy there isnt anywhere i can see to put my encrypted key in

**Comment by Cerv4ntez** [comment]
you put the encrypted key where it says private key and also supply the password then press convert

**Comment by Cerv4ntez** [comment]
jezzaN, there should be a userWallet.json file in c:\Users\(YOURUSERNAME)\AppData\Roaming/Neon/storage directory, back this up immediately to a safe place then open it with notepad, your encrypted key should be written down there

**Comment by jezzaN** [comment]
na man that doesn't work either i have two wallet i created on the same version that have the same problem to

**Comment by jezzaN** [comment]
i had done an update on my computer and i wiped the wallet off my pc i then restored it and i dont think these files have came back, unless they are hidden very deep on the hard drive. is there any other thing i can try?

**Comment by Cerv4ntez** [comment]
according to your story, you currently can login to neon wallet 0.0.6 but dont see your balance, therefore the files have to be currently on your computer
i hope you're not just trolling me, that would be very bad for your karma and my mojo

**Comment by jezzaN** [comment]
Not I am not trolling you I really want to get back into my wallet I spent my whole evening trying and i will try again to night is there a good program I can down load to find files or should it be fine in my computer?

Sent from my iPhone

On 12 Feb 2018, at 21:45, Cerv4ntez <notifications@github.com<mailto:notifications@github.com>> wrote:


according to your story, you currently can login to neon wallet 0.0.6 but dont see your balance, therefore the files have to be currently on your computer
i hope you're not just trolling me, that would be very bad for your karma and my mojo

**Comment by Cerv4ntez** [comment]
No need to download any additional software, i told you where to look for it. You might have to turn on visibility of hidden files. Is there anyone you know and trust who is more tech savvy than you who might give you a hand with this? Since this is about your money you should handle this with appropriate care. While its true there are hackers and malware and technical faults of the software we are using out there more often that you might think an insufficiant grasp of basic technical skills or lack of care in handling things like keys and passwords lead to loss of funds.

**Comment by totalvm** [comment]
are you 100% sure you are using the right way to enter your key? I assume you tried every way to enter it?
Encrypted and Private.

The way to encrypt hasn't changed at all so your address should work

**Comment by jezzaN** [comment]
so i have had a friend round to have a look at it he managed to find the new wallets that i have created but still couldn't find either of my two original wallets. yes i have tried the private key and encrypted key in both places. is there anything else i can try? im really not sure what happened to my pc when it did an update it seems to have lost alot of history files. is the anything i can do with my public address and password?

**Comment by Cerv4ntez** [comment]
There is some related thread here where someone found his original wallet with data recovery software, you might try that. Public address and password alone wont get you anywhere i'm afraid

**Comment by jezzaN** [comment]
Do you now what recovery software they used? If not what was the thread so I can ask the person what they used

Sent from my iPhone

On 14 Feb 2018, at 02:24, Cerv4ntez <notifications@github.com<mailto:notifications@github.com>> wrote:


There is some related thread here where someone found his original wallet with data recovery software, you might try that. Public address and password alone wont get you anywhere i'm afraid

**Comment by Cerv4ntez** [comment]
this is the thread:
https://github.com/CityOfZion/neon-wallet/issues/616
you need some tool to undelete the wallet that was overwritten, so when you have your recovery tool set up, look for .json files

**Comment by jezzaN** [comment]
i took it to a shop and they manage dto recover the files i had lost thanks very much for all your help what is your address for donations?

**Comment by Cerv4ntez** [comment]
good move! glad it workes out for you! AUn38uieBKiaEE9Gq1v1K6vJoGfuKAJYSe
