### ISSUE TITLE
Ledger Nano S and NEON wallet.  Not getting prompts on Ledger.

### ISSUE THREAD

**Issue by marcelo-mason** [CityOfZion/neon-wallet#675]
When I try to send or claim gas itt doesn't ask me to sign the tx on the Ledger it simply says "Transaction Failed" on NEON.  When I try another Ledger that one works fine.  I compared the firmware on both Ledgers and they match (1.3.1/1.1) so thats not it.  Also I tried to delete and re-install the NEO app in Ledger Manager, but this doesn't fix it.  

Another thing that is happening is the Ledger gets real hot in minutes when left plugged in after this stuff fails.

Any ideas on how to fix this?

NEON: 0.1.1 / 0.1.2 
NEO App: 1.1.1

**Comment by sbglive** [comment]
Same issue here, NEON 0.1.2, NEO app 1.1.1

**Comment by rwgalive** [comment]
I have the same problem, reinstalled both Neon wallet and NEO app on Nano S . I get a brief request to sign the device then it immediately displays the transaction failed message. I would appreciate advice.

**Comment by nbgith** [comment]
i al so have the same problem, has anyone found a fix?

**Comment by mhuggins** [comment]
There are two known issues with claiming GAS.

One relates to a bad GAS amount calculation in the neoscan API that it sounds like there is a fix for (just needs to be tested and deployed).

The other issue relates specifically to Ledger and the fact that the amount of memory it has is too small for creating some transactions if there are "too many" txin's before creating another txout. There's a GitHub issue related to that at #882.

**Comment by mhuggins** [comment]
This issue should be fixed in [version 0.2.4](https://github.com/CityOfZion/neon-wallet/releases/tag/0.2.4).

**Comment by MatthewFraley** [comment]
Still getting errors when attempting to Send ONT. Getting "Transaction failed: Ledger device" as soon as I hit send. No prompts on my ledger to allow the transaction, it just automatically fails.
