### ISSUE TITLE
Transferred GAS to my (legder nana S) Neo wallet adress without succes ....

### ISSUE THREAD

**Issue by stefanxg** [CityOfZion/neon-wallet#679]
Problem: I transferred 5 GAS to my (legder nana S) Neo wallet adress from Poloniex.
Nothing showed up 3 hours later... ? Transaction on Poloniex is completed normally.
Can somebody please give an advise ? Thanx in advance.
Note 1)  I transferred 7 Neo to my (legder nana S) Neo wallet adress from Bittrex, all oke!
Note 2) How can I use the gives TXID number (seen on my Poloniex withdrawel box), for tracking the transfer ?
Thanx in advance.

**Comment by stefanxg** [comment]
ps:  Ledger nano S is it and latest versions were installed: Neon wallet and on the ledger.
+  for tracking the transfer of my GAS ?  (seem adress as Neo) .

**Comment by valdor27** [comment]
Check the transaction status on https://neotracker.io/ by entering the TXID. 

Check your wallet on neotracker.io too by entering the public address and check your balance.

**Comment by stefanxg** [comment]
@valdor27 , thanx I will do that and give some feedback later on!

**Comment by stefanxg** [comment]
@valdor27 , thanx again, worked out by time ....took 6 hours the GAS in the neon wallet !? 
Q: which link on neotracker.io. I see more opions ? And the first gave no info ....(so Q is for the next time ;-))
