### ISSUE TITLE
Copied wrong private key!

### ISSUE THREAD

**Issue by catt1111** [CityOfZion/neon-wallet#68]
As I was trying to figure out how to use the wallet I copied down a private key, then made a new account and transferred my NEO to that new key that I didn't have copied down.   Someone please tell me there is some kind of solution to get it back. Please!

**Comment by robertohegeler** [comment]
always send small amounts first... test first and get familiar with everything.
anyway, you created a wallet I assume, and you set a password to that wallet. Open the wallet from within the app and type in your password. You will see your funds and the Address and Private Key.

**Comment by catt1111** [comment]
It doesn't allow you to make a password.  You log in every time with the private key.  Im trying to see if I can go back to my "copy & paste" history on my computer

**Comment by robertohegeler** [comment]
oh, so it does not have a wallet?

**Comment by robertohegeler** [comment]
wish you good luck!#

**Comment by catt1111** [comment]
It is the Neon wallet that I downloaded as an app to my computer. It is a wallet, but not able to find my private key...

**Comment by robertohegeler** [comment]
You actually download the Node and create a wallet within the node when it is synchronized. At least that is how it works with the original NEO Node

**Comment by ahnr** [comment]
I appreciate the input from support, but I would like 2nd opinion from Ethan himself. He developed a great wallet, and I'm sure he will find a solution since he is the actual developer. Please have support escalate this to him.

**Comment by anfn101** [comment]
This is not a business nor a company. We can not "escalate" anything. Furthermore, Github is a place to discuss code, not be tech support. I recommend looking for help on Reddit or the support channel on Slack. Ethan is very busy and is not always available to answer every wallet question people have.

**Comment by ahnr** [comment]
I'm sorry Alan, but if we want this issue resolved wouldn't we want to discuss it with the people who actually made the code? I really don't see how users on reddit and slack would assist us, with them being users themselves. I understand Ethan is busy, but this seems like a prevelant issue that needs to be addressed. Of course, at his earliest convenience.

**Comment by anfn101** [comment]
1. Many on Reddit have had the same issues and have managed to solve them. 2. The support channel has developers that also had a part in helping make the wallet (including Ethan!), and we have solved many user issues over the past week. As I said before, Github it not the proper venue for these questions. Thanks.

**Comment by ahnr** [comment]
1. I have actually checked on Reddit and no on has resolved this issue.

2. What would be the proper channel to join for slack?

**Comment by anfn101** [comment]
The Slack link is on the sidebar of our Reddit. And please, in the future, do not just create a Github account just to post an issue here unless you have actual input into code itself. In fact, nobody should be creating Github accounts in an attempt to gain attention from developers. It takes away our time, clutters the project, and makes it harder to work. We have proper channels of support. Please have everybody you know be aware of this.

**Comment by Ejhfast** [comment]
@ahnr i'm very sorry, but unfortunately there is no way to recover your private key. on the page that generates the keys, the wallet mentions that it will never show you the keys again. by only ever generating the key once, and not saving it anywhere, the wallet ensures that no one else can access your account

if i were able to solve your problem, that would mean that i would be able to get access to the private key your wallet generated, which would be very bad from a security standpoint

**Comment by Wojciechburger** [comment]
I opened my neon wallet paid neo with bittrex I got a transaction confirmation. The funds came and the portlet worked. I logged in. I logged in and it is about the funds. As I check Txld is the address of my public key and the one I sent the funds from bittrex is different. But how do you log on to it is another public key. How to change it. I have all the withdrawal confirmation from bittrex.

**Comment by anfn101** [comment]
There is no way to change your public/private key or your address.
