### ISSUE TITLE
Missing NEO transfer - Neon Wallet + Ledger Nano S synchronisation issue?

### ISSUE THREAD

**Issue by slinkytronic** [CityOfZion/neon-wallet#681]
Looks like the Neon wallet isn't synchronising with the MainNet - stuck on block 1917311.  I've tried rebooting, re-opening, resynching, refreshing and flicking between testnet and mainnet... but no NEO funds appearing and still stuck on the old block.

Worried about uninstalling and reinstalling, as there's no private key I can use to connect to the same wallet (as I logged in via my Ledger Nano S).  Is there any way to extract a private key and access the funds through the online wallet whilst this is buggy?

**Comment by stevesbrain** [comment]
@slinkytronic You can always use the coranos utility to generate your private WIF from your Ledger seed, however, there's no issue with uninstalling + reinstalling the Neon app, or the applet that lives on your Ledger, as the private key lives on the Ledger and never changes.
