### ISSUE TITLE
Neon Wallet 0.1.2 Participate Token Sale

### ISSUE THREAD

**Issue by volkansahiner** [CityOfZion/neon-wallet#683]
Friends i tried to buy NEO alts DBC, RPX, QLINK with 3 NEO by clicking participate token sale. MY 3 NEO gone but i didnt receive any token 3 NEO is a big money for me. i send transcations id. Ty for ur heps

https://neotracker.io/tx/6c308c79f0dce9f40b2ba63f04e6d76bceccc8ac1d6b250973d018faab08df76
https://neotracker.io/tx/5b930af9bde1342eca4bb24cc0f61aab3021c35a96166737acdd5974d6bffdc2
https://neotracker.io/tx/0a63ee73988cf62969801c34fba5057be4f99bd31f46dd666360b03a32223d37

**Comment by mhuggins** [comment]
Those token sales ended long ago. You will have to reach out to RPX, DBC, and QLink individually to see if they can return your NEO.
