### ISSUE TITLE
bit beyond a joke now Coz this is a major issue, and its been like this for quite some time, can we get this fixed? cheers lads

### ISSUE THREAD

**Issue by Marto15** [CityOfZion/neon-wallet#687]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by mhuggins** [comment]
There's no indication from your message what this issue is about.  Please note that there is a [Discord channel](https://discord.cityofzion.io/) for support questions, GitHub is intended for tracking code issues.
