### ISSUE TITLE
Neon Wallet Seems Frozen When Using With Ledger Nano S

### ISSUE THREAD

**Issue by stoutlabs** [CityOfZion/neon-wallet#691]
Nothing seems to happen when connecting my Ledger Nano S with Neon Wallet. (I have the NEO app installed via Ledger Manager.)  

Sometimes I get the "Looking for USB Devices. Please plugin your device and login" message, but nothing ever happens... other than 'Wake Up, NEO...' on my Ledger's display.

1. I have tried starting the app on my Ledger first, before opening Neon Wallet. 
2. I have tried starting the app after opening Neon Wallet.
3. I have tried starting the app after clicking the 'Login using a Ledger'

Regardless of what I try, nothing seems to be happening... and there's no indicators/progress bar/status messages to know for sure. (But I've sat here waiting for at least 15 minutes with each of the above methods, at least twice each.)

Am I missing something here? I just want to move my newly purchased coins from an exchange to my Ledger... haha!

Thanks for your time & help!

**Comment by amdempse** [comment]
Hi! Did anyone get back to you on this? I'm having the same issue. My ledger was working fine yesterday (was sending and receiving Neo) but today I've the same issue as you and I've no idea why its not picking it up.

Thanks

**Comment by stoutlabs** [comment]
Hey, no unfortunately I never received a response... so I ended up selling my NEO at the most recent spike a couple days ago. (I **_really_** don't like the idea not being able to hold it on my Ledger. I'll likely re-purchase when this bug is ironed out, though!) 😄

**Comment by stevesbrain** [comment]
@stoutlabs Definitely works with Ledger Nano S; I've been using it for many months :) What OS are you trying this on? Have you reinstalled (delete + installed again) the Neo app on your ledger itself? Are you running the latest version of both Ledger App + Neon wallet? Have you tried tried opening Neo on the Ledger first, before launching Neon wallet? Conversely, have you tried launching Neon wallet first, then opening the Ledger app? If Linux, do you have the Udev rules installed/set up? :) 

Btw, the only time it says anything other than the "Wake up, NEO" is when you're signing a transaction.  I think this was a poor design choice (to make it so different from other Ledger apps), but despite that, it does work well!

**Comment by amdempse** [comment]
Hi,

Thanks a lot for getting back to me! I actually figured out the issue....a
silly one!! The issue was that I wasn't using the micro USB cable that came
with the ledger. I thought any micro USB would work but this doesn't seem
to be the case! I'd tried absolutely everything and realized I'd swapped
the cable. The ledger seemed to be working fine but just couldn't connect
to my Neo wallet with the alternative cable.

Crisis averted. Sorry for taking up your time and thanks a lot for your
help :))

**Comment by stoutlabs** [comment]
@stevesbrain Hey! I'm on Win10 64bit. I definitely tried uninstalling/reinstalling the app on the ledger (3 times, actually.) I was running the current version at the time, which was 0.1.3. I tried various combos of which one I turned on first. (When not using the Ledger, all activity in the wallet app was responsive/instantaneous.) Haha, the whole experience was pretty frustrating! 

(And yes, some sort of on-screen indicators, messages, something... would be super helpful! I wish I were more familiar with Electron – I'd volunteer to look into it.)

**Comment by stevesbrain** [comment]
@amdempse Yeah, it can be relatively common to find Micro USB cables that are "charge only", even if not advertised as such. Glad you figured it out :) 

@stoutlabs Might be worth giving 0.1.4 a shot now that it's out, as well as disabling any active anti-virus temporarily. It's possible that it's interfering? I've only used it on Linux, so can't say for certain, but I've seen AV interfere with stranger things! Also, try another cable too :)

**Comment by mhuggins** [comment]
Please try downloading the latest version, a number of Ledger issues have been addressed.

**Comment by amdempse** [comment]
Hi Matt. Thanks for help but I resolved the issue. You can hence close this
case, thanks. I've also the latest version downloaded.

Thanks and have a nice day!
