### ISSUE TITLE
No token balance in NEON 0.1.3 using ledger

### ISSUE THREAD

**Issue by KyleConstantin** [CityOfZion/neon-wallet#692]
I installed and reinstalled the NEO app from ledger app manager. I sent some RPX and some GAS to the ledger wallet through NEON.  The gas shows up but the RPX does not. The RPX transaction is fully viewable on the blockchain. I am using Mainnet and I have added the RPX contract hash to both mainnent and testnet. 

I'm not sure what else to do. I assume this is some bug.

The whole time the ledger displays "Wake Up, NEO...." not sure if it should be doing something else.

**Comment by stevesbrain** [comment]
Same issue on 0.1.3? The "Wake Up, NEO..." only changes if you are verifying/authorising a transaction; otherwise it just displays that error the whole time.

**Comment by KyleConstantin** [comment]
no this has been fixed with 0.1.3

**Comment by KyleConstantin** [comment]
this issue still exists on 0.1.3

**Comment by mhuggins** [comment]
Please try downloading the latest version, a number of issues around token retrieval been addressed.
