### ISSUE TITLE
NRV token visible on neotracker, not on NEON , 0 balance after 48hrs

### ISSUE THREAD

**Issue by cryptorez** [CityOfZion/neon-wallet#693]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by brianlenz** [comment]
This isn't a bug with the Neon wallet. Please see our recent announcement regarding the Narrative token sale:

https://blog.narrative.network/narrative-public-sale-to-be-rescheduled-cd31040206ba

We will be providing another update tomorrow with more details.

**Comment by brianlenz** [comment]
@anfn101 feel free to close!
