### ISSUE TITLE
[0.1.3] Warning message wallet outdated

### ISSUE THREAD

**Issue by valdor27** [CityOfZion/neon-wallet#694]
Hello, since I updated NEON wallet I get this Warning message whenever I open NEON 0.1.3 : 

![capture](https://user-images.githubusercontent.com/32811219/36150369-c4e5a7ae-10c3-11e8-96ac-f29ecd52546b.JPG)

**Comment by andandre** [comment]
Me to!

**Comment by yunuseven138** [comment]
Same here

**Comment by mxx82** [comment]
It says "version": "0.1.1" in package.json, maybe old source package uploaded as 0.1.3?

**Comment by coloradocarrie** [comment]
I also get this warning... Now, just after updating to 0.1.3.

And... when logging into the wallet, I now have a ZERO balance. Help!

**Comment by KyleConstantin** [comment]
same here

**Comment by mxx82** [comment]
the Linux binary package works, it's "only" the source that's outdated

**Comment by mhuggins** [comment]
Please try downloading the latest version, this issue has been addressed.
