### ISSUE TITLE
Would it be possible to hide any coins that have zero in the wallet? i.e. RBX etc, and just show ones that have an amount inthem?

### ISSUE THREAD

**Issue by klik6** [CityOfZion/neon-wallet#695]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by KyleConstantin** [comment]
this would be greatly appreciated for sure! don't care about tokens I have zero balance of.

**Comment by MudWar** [comment]
Please allow hiding tokens on the Neon wallet display. Under manage tokens, currently cannot be changed

**Comment by mhuggins** [comment]
I'm going to close this, as we'll track it under #746 which includes a little more detail.

**Comment by klik6** [comment]
Many thanks Matt

Regards

Chris

Sent from my iPhone 

Chris May

Mobile   + 49 1725 280 550
