### ISSUE TITLE
Neon Wallet White Screen for NVIDIA machines

### ISSUE THREAD

**Issue by howmuchgq** [CityOfZion/neon-wallet#696]
**Neon Wallet Loads up to a totally white screen on a Windows 10 Pro x64 bit machine**
![neon-wallet](https://user-images.githubusercontent.com/19564931/36178489-da48bc12-10cd-11e8-8b12-cfbc353219db.jpg)

It seems that _if you have an Nvidia Graphics Card_, your Neon Wallet graphics may not render correctly and show an all white screen 

**Fix**

- Download and install the most up to date Nvidia Driver for your Machine: https://www.nvidia.com/Download/index.aspx (I suggest selecting the 'clean install' option when updating so that things don't get messy) 
- Reboot machine
- Control Panel -> Nvidia Control Panel
- Click Manage 3D Settings on the left -> Program Settings -> Add Neon
- Use the Integrated Graphics option

![neon-fix](https://user-images.githubusercontent.com/19564931/36178395-811b7e4a-10cd-11e8-9d3d-65000b7314a6.jpg)

Voila! Neon wallet should display now

**Comment by Che741** [comment]
Hi good day my Neon wallet also shows a blank screen, but i do not have Nvidia and also tried to install on another pc but the same issue remains?I am running a radeon machine?it just suddenly stopped working and cannot access wallet now for more than a week?

**Comment by mhuggins** [comment]
Are you on Acer?  It's possible you're running into [point 3 from here](https://github.com/CityOfZion/neon-wallet/issues/993#issuecomment-383001502):

> Based on electron-userland/electron-prebuilt-compile#36, do you have ePowerEvent.exe process in task manager? If yes, can you kill it and try to run wallet again?

**Comment by mhuggins** [comment]
@howmuchgq Thanks for the workaround for NVIDIA users!

**Comment by Che741** [comment]
Hi no unfortunately i have a Lenovo, i have tried everything from reinstalling, removing user data and then reinstalling, run as admin,run in compatability mode, i have no antivirus installed aswell, windows defender but did an exception for neon?That is the reason why i installed on another computer, but also same issue?is there maybe any other suggestions?thank you for your help :)

**Comment by titanomachy** [comment]
This has not much to do with NVIDIA, but is a Webkit issue. You will notice it here, because the Neon wallet is electron based. GPU issues also persist on Chromium or the Atom editor in a virtual machine. If you open the properties of the shortcut with which you open Neon you can add "--disable-gpu" (without the quotes) in the Target field after the Neon.exe, like this:
C:\Users\%YourUserName%\AppData\Local\Programs\Neon\Neon.exe --disable-gpu

That should fix your issue.

**Comment by EncinoMan01** [comment]
I'm having the same issue. Running an AMD card and AMD processor (no integrated graphics). Tried a new graphics driver but no good. Any ideas?

**Comment by titanomachy** [comment]
@EncinoMan01 Did you check your antivirus settings? If you open NEON and press F12 you get the developer tools. Mine is blocking URL http://api.wallet.cityofzion.io/v2/version hence the white screen. If you manually go to this URL in your browser, can you access that domain? It's probably a false positive, but I would verify it with the owner of that domain.

**Comment by EncinoMan01** [comment]
I can't see the issue. What antivirus settings should I be looking for?
Where can you see the blocked URL? And I can't access that domain...

Thanks for your help

**Comment by titanomachy** [comment]
@EncinoMan01 please join the NEO Discord channel here: https://discordapp.com/invite/R8v48YA 
You can find a "#support "channel there and I or somebody else can help you. Github is not the best place for these type of questions.

**Comment by pinkynrg** [comment]
This should not be closed is still an issue on some computers... :(
