### ISSUE TITLE
Deleting duplicate saved wallet deletes all with the same name.

### ISSUE THREAD

**Issue by owenlilly** [CityOfZion/neon-wallet#697]
## Overview
Deleting duplicate saved wallet accounts deletes all with the same name, tested in v0.1.3 and v0.1.2.  This is significant because it's possible to accidentally save multiple accounts with the same name _(this might be another bug too)_ after generating a new wallet, but deleting the duplicate will result in all saved wallet accounts of the same name being deleted.

## Steps to reproduce
1. Open the Neon Wallet app and select "Create a new wallet"
2. Enter and confirm a passphrase then select "Generate keys"
3. In the text input "Name this account", enter a name then click the "Save account" button two or more times.
4. Click the "home" button then select "Manage Neon settings" button
6. Click the delete button _(the trash can icon)_ next to one of the duplicate wallet accounts
7. Notice all saved accounts of the same name gets deleted despite only clicking one

**Comment by mhuggins** [comment]
Thanks for the steps to reproduce.  Will track this under #652 since these are the same issue.

**Comment by Raynor27** [comment]
I actually lost access to my newly created wallet this way. 
Unfortunatelly I had not saved the PK anywhere... is there any way to recover access? 
This is extremely frustrating.
