### ISSUE TITLE
Neon, computer crashed

### ISSUE THREAD

**Issue by slater39** [CityOfZion/neon-wallet#698]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by slater39** [comment]
Hi there, windows on my computer crashed and I had to replace windows, how can I access my neon wallet now? my wallet doesnt appear in the saved wallet and I only have the passphrase.
Thanks for your help

**Comment by mhuggins** [comment]
You need to have the private key stored somewhere, otherwise you cannot access your wallet.  For support questions, please refer to the Discord link provided above.

**Comment by slater39** [comment]
Thanks for the answer, so support whatsoever??


________________________________
De : Matt Huggins <notifications@github.com>
Envoyé : jeudi 15 février 2018 01:35
À : CityOfZion/neon-wallet
Cc : slater39; Author
Objet : Re: [CityOfZion/neon-wallet] Neon, computer crashed (#698)


You need to have the private key stored somewhere, otherwise you cannot access your wallet. For support questions, please refer to the Discord link provided above.
