### ISSUE TITLE
error .. ?

### ISSUE THREAD

**Issue by dancampean** [CityOfZion/neon-wallet#700]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.
![capture](https://user-images.githubusercontent.com/36476220/36203450-4cb38238-1190-11e8-95b5-a0e73b63be6d.JPG)

**Comment by mhuggins** [comment]
Please try re-downloading, as it appears to not have downloaded completely.  Also, please note that GitHub issues are for code-related issues, not support.
