### ISSUE TITLE
Lost 2 NEO's at buying QLC tokens in my NEON wallet

### ISSUE THREAD

**Issue by AKHB66** [CityOfZion/neon-wallet#705]
Jan 27 I bought with 2 of my NEO's some QLC tokens in my NEON Wallet.

Till now my balance is lost. I couldn't have send the 2 NEO's to a wrong adress because the public adress was pre-texted (programmed) in the NEON wallet!!
I was suggested to contact QLink which I did. Even emailed with Susan Zhou and the servicedesk, but they did not receive any NEO's they informed me. That's quite embarrasing and no one could seem to help me in this strange issue to my opinion.
With the NEOtracker I also cannot trace where my NEO's have been send to, other than this proces went automatically in the NEON wallet.

Can anyone help me with this and/or has any further suggestion?
Thanks kindly in advance!

**Comment by AKHB66** [comment]
Jan 27 I bought with 2 of my NEO's some QLC tokens in my NEON Wallet.

Till now my balance is lost. I couldn't have send the 2 NEO's to a wrong adress because the public adress was pre-texted (programmed) in the NEON wallet!!
I was suggested to contact QLink which I did. Even emailed with Susan Zhou and the servicedesk, but they did not receive any NEO's they informed me. That's quite embarrasing and no one could seem to help me in this strange issue to my opinion. 
With the NEOtracker I also cannot trace where my NEO's have been send to, other than this proces went automatically in the NEON wallet. 

Can anyone help me with this and/or has any further suggestion? 
Thanks kindly in advance!

**Comment by mhuggins** [comment]
The QLC team are the only people who have access to the wallet that received your NEO.  The script hash for QLC in neon wallet is correct.  No one within CoZ will be able to help with this unfortunately.
