### ISSUE TITLE
Mac won't let me open Neon Wallet

### ISSUE THREAD

**Issue by CryptoChik** [CityOfZion/neon-wallet#71]
I've downloaded the Neon Wallet but my Mac says it can't open it because I didn't get it from the Mac App Store??? See link.
What am I doing wrong?
<img width="393" alt="screen shot 2017-08-10 at 10 43 18" src="https://user-images.githubusercontent.com/29843188/29165021-45800da8-7db9-11e7-9741-f8a22985ee7b.png">

**Comment by amoebatron** [comment]
go to System Preferences > Security & Privacy on your Mac.

Then...  where it says Neon was blocked, select Open Anyway.

**Comment by Alexintosh** [comment]
Not really a Neon Wallet issue. This should be closed.

**Comment by CryptoChik** [comment]
Thank you very much amoebatron, much appreciated x
