### ISSUE TITLE
Lost $5k, Thoughts on saving generated wallets by default? (Feature Request)

### ISSUE THREAD

**Issue by sirrodgepodge** [CityOfZion/neon-wallet#710]
Just lost a cool $5k because I assumed that this was how this would work, it was awesome.

Is there any advantage to not automatically saving generated wallets with a default name (perhaps just the first couple characters of the public address)?  Users can remove them from the Neon wallet later if they'd like.

**Comment by comountainclimber** [comment]
@sirrodgepodge sorry to hear that you have lost your funds... this is actually functionality built into the new application (v2) UX - the saving of addresses to local storage by default on creation and import. Happy to report your requested feature will actually be released in the next few weeks https://github.com/CityOfZion/neon-wallet/pull/1267
