### ISSUE TITLE
Neverending Loading Animation For Nano Ledger S On 0.1.3

### ISSUE THREAD

**Issue by KyleConstantin** [CityOfZion/neon-wallet#712]
The loading animation never ends and I am never able to enter the wallet. The ticker prices of NEO/Gas at the top do load the proper values.

ledger is running the latest Neo application on the lastest firmware.

<img width="1002" alt="screen shot 2018-02-15 at 11 03 05 am" src="https://user-images.githubusercontent.com/4979135/36238789-d83ef832-123f-11e8-8da5-2212bf58be37.png">

**Comment by robertftw** [comment]
Had same issue, but loaded after 2-3min.
