### ISSUE TITLE
Ledger Nano S + Neon 0.1.3 Windows 10 Can't send GAS

### ISSUE THREAD

**Issue by ned-robinson** [CityOfZion/neon-wallet#713]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by ned-robinson** [comment]
No answers on Discord. COZ, please respond.

**Comment by GHuser357** [comment]
This is not a "general usage" problem, this is a broken wallet problem.

**Comment by mhuggins** [comment]
Duplicate of #685.
