### ISSUE TITLE
I put wrong address and sent NEO to donate address

### ISSUE THREAD

**Issue by via32** [CityOfZion/neon-wallet#714]
Hi,
13.02.2018 I install you wallet and I accidentally send my NEO money to your donate adress instead of my. :-( I purchased 5 NEO from www.ccshop.cz and copy wrong adress to my order. I want sent money to AeJE9UUaKDiHbzkcxGWJRV3WzEwkQNYQ4C instead of Adr3XjZ5QDzVJrWvzmsTTchpLRRGSzgS5A. Do you think you can sent me that 5 NEO back? Thanks. I pretty new in this bussiness. Thank you very much.
V.R.

**Comment by via32** [comment]
Has anyone contact directly to NEON wallet creators? Thanks.

**Comment by via32** [comment]
![wallet](https://user-images.githubusercontent.com/36498895/36327415-e1b7db70-135e-11e8-80aa-ffed9a2a7674.jpg)
@ @

**Comment by mhuggins** [comment]
@via32 Can you provide the source address you sent from and the transaction ID?  I will reach out to the CoZ team to ask, but I imagine that if it's doable, it would have to be returned to the address it came from, not the one you meant to send to, for security reasons (too many scammers out there).

**Comment by via32** [comment]
Hi, for now I have only this:
https://neotracker.io/tx/0f4b1a135bb53c9e81c2b611b70865ef6f053bf9fce820464e188e4666991343
But I will contact my exchange for more information and let you know. So, thank you again.

**Comment by Ejhfast** [comment]
@via32 I just sent the 5 NEO back to the address it came from. if you bought from a provider, hopefully their support team can now route it back to your address if you link to this comment

https://neoscan.io/transaction/f65c826f5e9d80a387f6bdf4fee54fbd084177c71242096efb73aed2eb35a738

**Comment by via32** [comment]
Thanks. I hope so.
