### ISSUE TITLE
Feeback when trying to log in with a wrong key

### ISSUE THREAD

**Issue by Alexintosh** [CityOfZion/neon-wallet#72]
**NEON version:** 
alpha 0.0.3c

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Current behavior:**
When an invalid key is provided to the login input clicking on the login button will do nothing.

**Expected behavior:**
When an invalid key is provided to the login input a visual feeback is shown by clicking on the login button.
The feedback will inform the key is not valid or could'nt be loaded

**Steps to reproduce:**
Try inserting some random string in the login input.
<img src="https://media.giphy.com/media/l1J3T6da7eDUNQzWU/giphy.gif" />

**Comment by wouterbruinings** [comment]
Apart from a simple verification based on the string length of the key, shouldn't it be technically impossible to verify whether a private key exists or not?
