### ISSUE TITLE
Nano Ledger S and TNC token transfer issues 

### ISSUE THREAD

**Issue by m0om0o45** [CityOfZion/neon-wallet#722]
My issue is I updated new wallet and nano ledger s is up to date i was able to add the TNC token hash i see the balance but when I go send the token isnt available to send in the assets. Ive tried everything with no avail it just doesnt show up and also even when i tried to type in the assets TNC and click on it it goes back to neo or gas and i do have gas in there too so that isnt a issue.

**Comment by mhuggins** [comment]
Please try downloading the latest version, a number of Ledger issues have been addressed.
