### ISSUE TITLE
I put wrong address and sent bounty ZPT tokens to donate address

### ISSUE THREAD

**Issue by paradox669** [CityOfZion/neon-wallet#723]
Hi,
10.02.2018 I install you wallet and I accidentally send my bounty 170 ZPT tokens  to your donate adress instead of my. copy wrong adress to my order. I want sent money to   AbxoN9WJX4fU3SxGW8sLkHFNtwJdDAsRhj instead of Adr3XjZ5QDzVJrWvzmsTTchpLRRGSzgS5A. Do you think you can sent me that ZPT tokens back? Thanks. I pretty new in this bussiness. Thank you very much.
please help me ! :(

**Comment by paradox669** [comment]
Has anyone contact directly to NEON wallet creators?

**Comment by mhuggins** [comment]
Please reach out on the NEO Discord channel for help.  CoZ has been good about returning accidental donations.
