### ISSUE TITLE
Ledger not connecting to ANYTHING

### ISSUE THREAD

**Issue by ZrMd30** [CityOfZion/neon-wallet#724]
I haven't done anything. I wanted to check my balance on the neon wallet using my ledger, wasn't detected. Went to ledger manager to reinstall app, couldn't log into ledger manager. Ether/BTC wallets, nothing is working! I have a lot of NEO (to me it's a lot). Ledger is basically invisible to everything. I tried to change the date back and logging in but nothing changed. I'm lost now.

**Comment by the-zimmi** [comment]
Make sure you are using the official Ledger USB cable. I used a random USB i had laying around and had the same issue of nothing connecting to the ledger. Changed to the original and straight into neon.

**Comment by mhuggins** [comment]
Please try downloading the latest version, a number of Ledger issues have been addressed.
