### ISSUE TITLE
NEO not reflecting in NEON wallet

### ISSUE THREAD

**Issue by Arkadion** [CityOfZion/neon-wallet#726]
I've installed the NEON wallet 0.1.3 yesterday and transferred some NEO but it is still not reflecting.  I've tried rebooting, re-opening, resyncing, refreshing, reinstalled and flicking between testnet and mainnet... but no NEO funds appearing.  
Any advice? - Thanks

**Comment by stevesbrain** [comment]
@Arkadion Do they show up when checking your address on the blockchain?

**Comment by Arkadion** [comment]
Thanks for getting back to me. I actually managed to find it.
The new version of the wallet (version 0.1.4) was released the following
day and as soon as I updated the wallet it appeared.

Thanks
Arkadion

**Comment by stevesbrain** [comment]
Glad to hear it :)
