### ISSUE TITLE
Neon generated unknown transactions

### ISSUE THREAD

**Issue by ghost** [CityOfZion/neon-wallet#727]
Hi guys, I think I have the same issue. Let me know if this is the wrong place. I transferred my NEO from Kucoin and Binance back to Neon Wallet after update and can see it in the wallet. Just went to check it and its gone. There is actually a transaction out for the full amount...

I have checked Binance and Kucoin again and can see that they both ended up in the wallet. I did see the total in there but when I had come back to check it was gone.

I can see my 2 separate ones in, 90 NEO and 86 NEO, but now one for 176 NEO out and my 1 GAS out.... WTF

I can see it sitting in another wallet but I didn't send it or ever create a 2nd wallet.. I have spent hours today seeing if I have been hacked and I can't see any sign, if I had been hacked all my stuff will be taken not just this. I think its a glitch with the wallet and really angry ATM. I have seen other topics and people dismissed from saying that because of FUD.. But seriously that is the only thing I can think of .

Yes I should have a hardware wallet. But was only moving off exchange because it supposed to be safer...

Devastated, been in since AntShares $8....

https://neotracker.io/tx/9c942c2aa3046c11fc4db3f621222c5ed09ff5f1c45c467e99734bb5e9f5b276

**Comment by mhuggins** [comment]
This is not an issue with the wallet.  Your private blockchain information has been acquired by a third party, whether through phishing or some other mechanism.
