### ISSUE TITLE
Still Can't SEND GAS!!!

### ISSUE THREAD

**Issue by ned-robinson** [CityOfZion/neon-wallet#728]
A little support WOULD BE APPRECIATED!

- NEON wallet v0.1.3
- WIndows 10 latest updates
- Nano Ledger S all latest firmware updates

All functions work EXCEPT FOR SENDING GAS. The error message is Transaction Failed. NEON tries to send Please Sign Transaction to Nano Ledger S but the Nano never wakes up.

PLEASE ADVISE - You have TRAPPED my Gas and it is now UNUSABLE.

A little support would be appreciated.

**Comment by mhuggins** [comment]
Duplicate of #713.
