### ISSUE TITLE
balance not showing using version 0.1.3 with ledger nano s on windows 7

### ISSUE THREAD

**Issue by teabar** [CityOfZion/neon-wallet#730]
sent funds from an exchange to the ledger nano s, using version 0.1.3 of NEON wallet.

balance is showing correctly on https://neotracker.io/
NEON wallet seems to work fine aside from that.

anything I can do to fix the problem?
thanks

**Comment by mhuggins** [comment]
Please try downloading the latest version, a number of issues have been addressed.
