### ISSUE TITLE
Make version more visible

### ISSUE THREAD

**Issue by michaelf318is** [CityOfZion/neon-wallet#731]
It is hard to determine what the version of neowallet is without logging into a wallet.

Consider putting Version also in "Manage Neon Settings"  or on the "Home" screen at the bottom.

**Comment by mhuggins** [comment]
Good suggestion.  @asalib What do you think about including the version number on the new login screens before getting to the dashboard?

**Comment by comountainclimber** [comment]
Fixed in `design-v2` branch
