### ISSUE TITLE
Restrict 'Amount' field to only accept numbers

### ISSUE THREAD

**Issue by liamaharon** [CityOfZion/neon-wallet#735]
![1](https://user-images.githubusercontent.com/16665596/36368882-badf3f72-1505-11e8-8a32-ff294f86d0b2.png) 

I don't know in what scenario somebody would need to send aldsjfasld NEO or GAS

**Comment by mhuggins** [comment]
This is a very old version of NEON Wallet and has been fixed already.  Please download the latest version from the [releases](https://github.com/CityOfZion/neon-wallet/releases) page.
