### ISSUE TITLE
Can't install 0.1.4 on Mac: Image not recognized.

### ISSUE THREAD

**Issue by Kleetz** [CityOfZion/neon-wallet#736]
I can't install the 0.1.4 update. I keep getting this "warning":
![screen shot 2018-02-19 at 1 28 44 pm](https://user-images.githubusercontent.com/36643043/36392416-10f7a318-1579-11e8-8961-490bbb167a50.png)

I'm on OS X Yosemite 10.10.5

**Comment by malkazoid** [comment]
Did you download this image via the Neon app, or via your usual web browser?
I've had this happen a lot when I download via the Neon app's browser.
Give Chrome, or Safari or Firefox a twirl and see how you go?

**Comment by Kleetz** [comment]
Via the Neon App. I'll try it in Chrome, thanks!

**Comment by Kleetz** [comment]
Used Safari browser to download and install. Install was successful, thanks!
