### ISSUE TITLE
Where has my NEO gone?

### ISSUE THREAD

**Issue by davidmoldenchen** [CityOfZion/neon-wallet#737]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by mhuggins** [comment]
Please refer to the Discord channel for support.

**Comment by PerformanceArt** [comment]
You have to go on a 'gaming' forum to try to find your funds?  Is Neon Wallet a 'gaming' program?

**Comment by mhuggins** [comment]
It's the community chat channel.  https://discord.cityofzion.io

**Comment by himeywho** [comment]
i have not found a way to get an answer on dischord! There is no support for this wallet I was made to use to "safely" keep my NEO and due to a forced upgrade have NOTHING but someone telling me to go to dischord which has NO HELP and no way of finding it!
