### ISSUE TITLE
Danger! Running 0.1.4 Puts Your Computer and Funds At Risk!

### ISSUE THREAD

**Issue by PerformanceArt** [CityOfZion/neon-wallet#738]
Or so Windows 10 tells me.  It also tells me that it has been created by an 'unknown publisher.'  
This should put a lot of fuel on fire of the posts wondering why their NEO has apparently been stolen. 
There are a lot of places in the chain where things can go south, but you can expect the fingers to be pointed in the direction of those whose software sets off warning signs while being installed.

**Comment by PerformanceArt** [comment]
And those missing funds are referred to a 'gaming chat site' ( discordapp ) to try to find out what happened to their missing NEO crypto?  Why is GitHub allowing 'gaming' people to host an alleged 'crypto wallet' software on the site?  This isn't passing the 'smell test'...

**Comment by mhuggins** [comment]
> Why is GitHub allowing 'gaming' people to host an alleged 'crypto wallet' software on the site?

Discord is simply the service being used for City of Zion's community chat and support.

**Comment by PerformanceArt** [comment]
Might as well use a 'casino' chat site...

**Comment by mhuggins** [comment]
The application is marked as being from an unknown publisher simply because it is self-published by City of Zion.  As long as you verify the SHA against the binary you download from the [releases](https://github.com/CityOfZion/neon-wallet/releases) page, then the app itself is safe.

**Comment by PerformanceArt** [comment]
0.1.3 didn't result in an error message.  It has the same properties/information as 0.1.4.  
What is the difference in one being marked as dangerous, and the other not?
