### ISSUE TITLE
NEON 0.1.4 - Unable to claim GAS for months, posting this for months too everywhere, no one wants to help

### ISSUE THREAD

**Issue by derwen** [CityOfZion/neon-wallet#742]
It's actually an issue for me since a few previous versions, I am not able to claim GAS for months now. Everything else works normally, sending NEO, GAS and tokens, but when I try to claim GAS and sign the first transaction it either fails or when "sign second transaction" comes on Neon, nothing happens on Ledger - it's stuck on "Wake up NEO" and the second signing fails in a few seconds at most. Tried reinstalling Neon, tried multiple Neon versions, tried reinstalling NEO app on ledger. Tried another computer. Tried another cable, tried everything. Nothing works. Have quite a few GAS stuck by now. Solution? Why does no one care to even try to help?

So once again:
1. Claim GAS
2. Asked to Sign transaction 1 of 2, I sign it
3. Waiting for transaction to clear...
4. Sign transaction 2 of 2 to claim GAS --> shows up briefly, for maybe half a second (but nothing happens on Ledger, stays on "Wake up NEO"
5. Error Claim failed immediately shows up

DO NOT CLOSE THIS ISSUE AS A DUPLICATE!

**Comment by Hope-its-ok** [comment]
Hello,

I'm having the exact issue as Derwen.
Can someone kindly help us. I'm worried and stressed about my NEO coins.

Thank you very much.

**Comment by ianaz** [comment]
This happens to me about 2 times every 3 too but then works. There should be something wrong

**Comment by brianlenz** [comment]
If you're still having issues claiming GAS on your Ledger with Neon 0.1.4, make sure you are running the latest version 1.1.1 of the Ledger Neo app:

https://support.ledgerwallet.com/hc/en-us/articles/115005530425-How-to-install-and-use-Neo-NEO-

You need to delete the current Neo app from your Ledger (using the Ledger Manager Chrome app) and reinstall in order to complete the upgrade.

**Comment by icemat23** [comment]
I have the exact same issue. I suspect it's a problem with my Ledger because even after I reset my Ledger it still won't let me claim any gas. I've even used Windows and different versions of NEON wallet as well. These are the steps that I've also done:

- Tried reinstalling Neon
- Tried multiple Neon versions
- Tried reinstalling NEO app on Ledger
- Tried another computer
- Tried another cable

I'm not even able to sign any transactions (it just skips straight to 2 of 2 failed). I'm copying your problem verbatim because it's the same as my problem:
"Everything else works normally, sending NEO, GAS and tokens, but when I try to claim GAS and sign the first transaction it either fails or when "sign second transaction" comes on Neon, nothing happens on Ledger - it's stuck on "Wake up NEO" and the second signing fails in a few seconds at most. "

Please help!

**Comment by anarhie** [comment]
I have the same issue! I can't claim gas with Ledger. I sign the transaction and is stuck in a verification of the second approval or Error. The transactions are shown in history as 0 Neon.

![screen shot 2018-02-22 at 2 34 03 pm](https://user-images.githubusercontent.com/36732938/36538843-86d1fdac-17dd-11e8-8928-eb3adfde1c45.png)

**Comment by derwen** [comment]
![neo gas issue](https://user-images.githubusercontent.com/32641583/36540685-9be97456-17db-11e8-8fc5-bfc694f49fc5.jpg)

**Comment by derwen** [comment]
So once again:
1. Claim GAS
2. Asked to Sign transaction 1 of 2, I sign it
3. Waiting for transaction to clear...
4. Sign transaction 2 of 2 to claim GAS --> shows up briefly, for maybe half a second (but nothing happens on Ledger, stays on "Wake up NEO"
5. Error Claim failed immediately shows up

**Comment by ulmer22** [comment]
I have similar issue here... since updating to  0.1.4 I'm unable to claim gas on Ledger Nano S, but I was able to before the update. I've tried logging out and back in, I'll sign transaction 1 of 2 >> receive processing prompt >>after 15-30 seconds says "Error - transaction failed"

**Comment by tradebully** [comment]
Having same issue here as well. I upgraded to all the updatedversions on Neonwallet and Ledger. First, it takes long time to load the neonwallet itself. Second, when I try to claim the gas it gives me an error message after first sign off. Please help!!!

**Comment by ncooksammy** [comment]
I am having the same problem. Cannot claim gas. Tired updating the wallet and re-installing on Ledger. Still doesn’t work. Using version 0.1.4

**Comment by NeilSayer-Eduserv** [comment]
I also am having this problem with version 0.1.4

**Comment by mhuggins** [comment]
A new version of the wallet is coming soon that should fix a number of issues, including GAS claiming.

**Comment by derwen** [comment]
NEW Ledger hardware wallet.
NEW firmware 1.4.1
NEW Neon Wallet 0.2.1

Issue still exists. Can't claim GAS. Same thing happens. You didn't fix anything. :(

**Comment by mhuggins** [comment]
Have you received a number of transaction since the last one you sent? What's possibly happening is that the new transaction (needed for calculating unclaimed GAS) is attempting to be comprised of NEO across various transactions, and the number of previous transactions exceeds the memory limit of the Ledger.

**Comment by derwen** [comment]
Can you please be more clear? I don't understand what you wrote or how to fix it if that's an issue. What is the "number of transaction since the last one I sent"? And if previous transactions exceed the memory limit of the Ledger, how would that be fixed? I don't think I have a particularly high number of transactions on my wallet, except a lot of unsuccesful GAS claims, and a lot of unclaimed GAS. Thanks.

**Comment by Parallelism** [comment]
I just created an account because I'm experiencing the EXACT same issue.

I sign the first Tx and there is no second Tx.... It just lingers then immediately says "GAS CLAIM FAILED." 

I literally made an account to voice my support of fixing this bug. I'm not a technical person with computers, so I don't know what to do. 

I'm not an idiot however. I have the latest Neon Wallet version, I have the recent firmware for Ledger S, I have the recent manager App.... 

I have not been in since Antshares, but I bought around September of 2017, so my wallet is somewhat old.

Any help would be appreciated. For those of you who are lurking with the same issue, PLEASE register an account like I did to voice our concern as a community. Glad to see I'm not the only one with this problem....

**Comment by icemat23** [comment]
I also created a new account just to voice my support of fixing this bug.

Is there anything I can do to help resolve this bug?

**Comment by derwen** [comment]
I get a new error now sometimes before I'm able to even sign the first transaction:

Calculating claimable GAS failed.

And when it doesn't come up, then it's as it was before, I'm never given the chance to sign the second transaction before GAS claim fails.

**Comment by Stokiesteve** [comment]
I had been having a similar problem. I signed the first transaction (click both buttons), then nothing. I just managed to claim the GAS however. Not sure if it was a fluke. After signing the 1st transaction and presuming nothing was going to happen I started browsing google looking for solutions. Several minutes later the sign 2nd transaction notification popped up on the screen. I clicked both buttons again and it worked. Maybe will work again, we will see. Try giving it plenty of time for the 2nd sign notification to pop up.

**Comment by derwen** [comment]
If you get a gas claim fail, you will not get a second sign notification. What probably happened in your case was network congestion so blocks were slow.

**Comment by ulmer22** [comment]
Gas claim Success - I updated to Ledger 1.4.1 and the latest Neon 0.2.2 and I'm successfully able to claim GAS again.

**Comment by icemat23** [comment]
I had my hopes up and updated to the latest Ledger 1.4.1 and I'm using the latest Neon 0.2.2 but it still doesn't work for me...

I'm pretty sad now...

**Comment by Erikdeperik** [comment]
Had same problem. Tried unplugging device, then as soon as "sign transaction"appears in screen i accepted. Did the same thing when the second approval was asked. Then it worked. Maybe if we wait too long, it has problems?

**Comment by derwen** [comment]
That is not the same problem. If you are able to get "Sign 2d txn" and get it on your ledger you are not having the same problem.

**Comment by Erikdeperik** [comment]
I couldn't. Even get to the second txn before. It just gave the "failed" msg. Did you try ?

**Comment by anarhie** [comment]
After 16th tries it worked! I didn't tried everyday and it took a 42 days!

**Comment by icemat23** [comment]
Just tried this with a brand new computer with a brand new ledger and while it did have the option to sign 1/2 transactions, when it got to the 2/2 transactions it failed.

So yeah... maybe it takes multiple times? I haven't been successful yet though.

**Comment by derwen** [comment]
Neon wallet 0.2.3

- Claiming GAS failed.
- Calculating claimable GAS failed.

Again, Ledger will not let me sign the second transaction. Will you ever fix this?

**Comment by derwen** [comment]
Why do you guys even come here and troll with such "advice"?

I have tried this LITERALLY 200+ times on various setups and more than one ledger with my seed. I lost countless hours trying to do this for MONTHS (well almost half a year now). You are telling me to hope for my GAS/money to be magically unlocked and to try again and again when it's OBVIOUS it's a software issue on Ledger side with a ton of people affected with a cause unknown to us and zero communication from Ledger? Are you serious?!

**Comment by icemat23** [comment]
Hey derwen so I think it has something to do with that specific Ledger you have. I used another Ledger on the SAME computer and the SAME neon version that I was having trouble with and yet I was able to sign the two transactions. Note that the Ledger that I have problems with was bought some time in August 2017, while the newer one that works was bought recently after January 2018...

**Comment by Oneplus1** [comment]
I feel your pain derwin, I'm having same issues now.  
Really annoying how this issue is not being addressed.

**Comment by derwen** [comment]
icemat23 - I wrote multiple times, including  in the last message you replied to, that I tried MULTIPLE (3) Ledgers, and they were from different batches, including the latest one. It's not a hardware issue. And again - while I appreciate that you are trying to help (if you are not trolling), if you don't even read the problem you are replying to, you are NOT helping.

Oneplus1 - Yes it's getting more frustrating every day. It's mindblowing Ledger support is still ignoring this after months and months. No one freaking cares to at least try and fix the problem. I guess people having their funds locked/lost on a device that's created to prevent that is something they are comfortable with. Is someone from support even reading this messages?! Please let us know that you exist.

**Comment by stwbitcoin** [comment]
Hey guys,
I'm having the same problem. I don't use a Ledger. I'm running on Win10 and the version 0.0.7 of Neo Wallet. This is an old version, I mention this only because the problem only recently started. The problem must be in the NEO network. This is a problem for the devs to solve.

**Comment by michaelvf** [comment]
Wait, why did you close both this and the 1019 while referencing each other? What has been solved?

**Comment by AuronDark** [comment]
we need a fix to this , a administrador or staff  fixed please , i cant reclaim my gas ,w happen whit neo wallet

**Comment by B00mGit** [comment]
MeToo

**Comment by katomm** [comment]
Hello, it looks like version 0.2.4 fixes this problem. Thank you.

**Comment by derwen** [comment]
Closed the issue and trolls posting new version fixes this problem when it doesn't?

Good job covering up.

**Comment by d5heilman** [comment]
This did not fix the issue, I am using 0.2.4, I updated my Ledger today, still getting this error. Tried 15-20 times.

**Comment by michaeljs1990** [comment]
Strange. I haven't changed anything from last time I did it and it now fails.. Did the core protocol change? Hopefully I am able to send the coins still but I am leaving it alone for now until this gets resolved.

**Comment by BruinsM** [comment]
Have you already tried sending 1 NEO to your own address before claiming te GAS? I don't know why exactly, but for me that helped. Maybe it's because of what mhuggins said, the GAS needs a transaction to be calculated on, so maybe a fresh transaction works better. 
You can always try, it didn't cost me any transaction fee

**Comment by mattiasghodsian** [comment]
I have a similar problem, it "Asked to Sign transaction 1 of 2, I sign it"I did that on the ledger after that nothing happens or a blank page.

neo wallet: 0.2.5 (linux)
ledger nano s ; 1.4.1

**Comment by tbull152** [comment]
i am having the same problem with brand new ledger nano s all the latest software and firmware!!

**Comment by maslovsa** [comment]
I'm having the same issue.

neo wallet: 0.2.6 (Mac os)
ledger nano s: 1.4.2

**Comment by stevesbrain** [comment]
@keslerm NEON wallet uses "Neotracker" as its block explorer by default, and Neotrack is currently down for maintenance. Go to your Neon settings, and change block explorer from Neotracker to something else (or, wait for Neotracker maintenance to be done).

**Comment by tbull152** [comment]
Thank you I will try that 

Sent from Mail for Windows 10
