### ISSUE TITLE
Opening links in a new window should open the default system browser

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neon-wallet#743]
When I get the "new version is available" popup, with the link to GitHub from here, it's opening a new Electron window: https://github.com/CityOfZion/neon-wallet/blob/b70de8b40c961db544638069a0270b3b63d69525/app/modules/metadata.js#L20

It would be better if it would open those links in the default system browser. There I would get download progress for instance, which I don't get in the new Electron window.

This could be done by adding an event catcher in main.js here: https://github.com/CityOfZion/neon-wallet/blob/dev/main.js#L37

It would look similar to this to open all external URLs inside the default system browser:

    mainWindow.webContents.on('will-navigate', (e, url) => {
        console.log('will-nav', url, mainWindow.webContents.getURL())
        if (url.substr(0, 21) !== 'http://localhost:3000') {
            e.preventDefault()
            shell.openExternal(url)
        }
    })

**Comment by drptbl** [comment]
Re-tested, it's fixed.

**Comment by lllwvlvwlll** [comment]
# THIS IS JUST AN EXAMPLE WORKFLOW
Please Award:

@metachris : 500
@drptbl : 200

**Comment by lllwvlvwlll** [comment]
(Presending to be @canesin )
@metachris https://neoscan.io/transaction/a11a5ac8ae835f75348b79640ae74424fced637e1ef89a1bd5e1d13e6d9faa16

@drptbl 
https://neoscan.io/transaction/a11a5ac8ae835f75348b79640ae74424fced637e1ef89a1bd5e1d13e6d9faa16
