### ISSUE TITLE
Token sale participation will send both GAS and NEO

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neon-wallet#744]
An issue we ran into with a few of our contributors during our token sale is that they inadvertently sent both GAS and NEO when invoking `mintTokens`. If you first select GAS and enter an amount and then change to NEO and enter a new amount, the old value of GAS is still sent even though it's not present in the UI. This is an undesirable and unexpected side effect that users would not expect.

It's probably best to limit ICO participation to _either_ GAS _or_ NEO? Alternatively, if some ICOs need to support both, the user experience should be improved to make it clear what's being sent, similar to the multi-recipient approach when sending funds in Neon wallet.

**Comment by mhuggins** [comment]
That is definitely unintended!
