### ISSUE TITLE
Add server-side registration of ICOs

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neon-wallet#747]
In order to avoid needing to deploy a new version of Neon wallet for every new ICO that needs to be registered and every ICO that has completed, it would be ideal to handle the "registration" and "de-registration" of ICOs through a dynamic, server-side registration system. This way, the wallet client can simply fetch the list of ICOs that are currently active without needing an upgrade every time.

It would also be useful to track the following:

1) Whether the ICO supports NEO only, GAS only, or both. The options in the UI should be limited to only the allowed asset type(s) to prevent people from accidentally contributing funds that are not allowed (see #744).
2) Whether the ICO supports Verification? It's possible this may not even be necessary since really every ICO should be using Verification going forward (see #745).
3) The ICO start time when the token should appear in the token sale participation dropdown.
4) The scheduled ICO end time when the token sale is will end.
5) The ability to "end" an ICO early (i.e. once it has sold out).

This will make the ICO process much smoother for both ICO contributors and ICO companies.

The obvious implication is that there would need to be some kind of official "registration" system whereby ICOs "apply" to be included. The Neon team/CoZ would need to validate the authenticity and legitimacy of each request, but this really is no different than the current process of ICO companies requesting to be hard-coded into Neon wallet. Having some kind of an official approval process will also limit the ability for scammers to take advantage of unsuspecting users.

With this approach, I think it would be worthwhile to _remove_ the current ability to add arbitrary NEP5 script hashes into the client for ICO purposes. Currently, any NEP5 script hash manually added to Neon is automatically assumed to be in an ICO, which is not a safe assumption. It makes sense to support adding NEP5 token script hashes for token management in your wallet, but I don't think these should become automatically available for participation in ICOs. Having the manual script hash ICO tool also presents an attack vector for scammers.

This server-side component could be used as a comprehensive NEP5 index so that if a non-ICO wants to their NEP5 token to be included in Neon wallet, they would formally register it in the same system. At that point, every NEP5 token that Neon wallet supports could be derived based off of the server registry (without any need for users to manually add script hashes to their wallet). And Neon would only need to show NEP5 tokens that actually have a balance (see #746).

One thing is for sure: the current process is likely the best ICO process out there already. We had numerous compliments from our users about how smooth the process was and how it was the best and easiest ICO they've ever participated in. The changes above will help make it that much better for ICOs in the future and almost make the contribution process "bulletproof" from a scam perspective (short of people being duped into sending funds to an address, which is unavoidable and will happen with every ICO).

**Comment by brianlenz** [comment]
The consensus here is to use a simple GitHub pages hosted JSON file for this.

**Comment by mhuggins** [comment]
I've created the repo for this here: https://github.com/CityOfZion/tokens.  I'm in the process of hooking up neon-wallet to use this for allowing ICO contributions.

**Comment by brianlenz** [comment]
That's great! I don't think we should limit to to ICOs only, though. That's how my idea here originally started (following our ICO), but I think this JSON file makes sense to drive _all_ NEP-5 tokens in NEON wallet, including those that have not done an ICO. That way, it can completely drive the wallet (e.g. for including NEP-5 balances), and we don't have to hard-code any tokens into the wallet anymore (and thus don't need to do releases in order to add/update/remove tokens).

Do you agree @mhuggins?

**Comment by comountainclimber** [comment]
Fixed as of 0.2.7 🎉
