### ISSUE TITLE
Can not see NEO or GAS values on MainNet

### ISSUE THREAD

**Issue by companyhen** [CityOfZion/neon-wallet#75]
See screenshot.

![screen-shot-2017-08-10-at-10 39 36](https://user-images.githubusercontent.com/1679107/29175920-65fb462a-7db8-11e7-8c19-ebd19edc72f8.png)

**Comment by marinersouthampton** [comment]
Same here. Have transferred NEOs from Bittrex several hours ago. Still cant see in the Wallet. Here is the tracker: https://neotracker.io/tx/e30f19221d985a11347b864a46e350a682e8bae1527895182d114658bbc39d05

**Comment by companyhen** [comment]
@marinersouthampton I resolved the issue by installing this: https://github.com/CityOfZion/neon-wallet/releases

**Comment by marinersouthampton** [comment]
Thanks is it version 0.0.3?

**Comment by companyhen** [comment]
Yes the latest alpha.

**Comment by marinersouthampton** [comment]
Somehow I still cant figure out whats wrong with my walllet :(

**Comment by marinersouthampton** [comment]
Whats the Block size for you now?
