### ISSUE TITLE
ICO Participation token dropdown empty

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neon-wallet#750]
One common issue we heard reported during our token sale today is the token dropdown in the ICO popup would appear empty (i.e. no NRVE listed). Sometimes restarting Neon wallet would fix it, but other times not. There didn't seem to be a rhyme or reason to why/when it would be broken, but it affected at least 1% of our users (on the order of 10-15 out of about 1k have reported the issue so far). We had also seen the issue infrequently in our testing prior to the public sale.

It doesn't seem to be platform-specific, as we heard complaints from both Mac and Windows users.

One user reported upgrading from macOS Sierra (10.12.6) to High Sierra (10.13.3) fixed the issue, but that could be a red herring.

**Comment by road2b** [comment]
Hi brian, i want to get  into the token sale but it gives my the following error;
Error, sale participation failed,
please check your script hash again.
I copy, refresh, restart....it wont let me buy. Can you advise me?
Tnx

**Comment by brianlenz** [comment]
@road2b please email support@narrative.network for further assistance. Thanks!

**Comment by road2b** [comment]
check mail

**Comment by mhuggins** [comment]
Fixed in version 0.2.1.
