### ISSUE TITLE
problem in transfer of neo

### ISSUE THREAD

**Issue by yasin305** [CityOfZion/neon-wallet#754]
I transferred neo from Bitbns to Kucoin but it has been a hour, my Bitbns wallet shows the transfer has been completed, but it has not yet arrived to my Kucoin wallet. can someone tell me what's the issue??

**Comment by mhuggins** [comment]
This is not a neon-wallet issue.  Please reach out to Kucoin for support.

**Comment by yasin305** [comment]
ok, thanks
