### ISSUE TITLE
MISSING 10 neo, sent to wallet, never showed up. Any ideas. How do l update my wallet w/o loosing everything>? thx

### ISSUE THREAD

**Issue by abeau007** [CityOfZion/neon-wallet#758]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by abeau007** [comment]
MISSING 10 neo, sent to wallet, never showed up, How do l update  wallet w/o loosing everything. very disappointed, and out a thousand $. l have all the printouts.

**Comment by stevesbrain** [comment]
@abeau007 Does the address you sent to match the address that you see in Neon-wallet? Can you see the transaction on the blockchain? On the blockchain, what does the balance of your wallet show?

**Comment by mhuggins** [comment]
If it's in the blockchain, then it made it to the address.  What is the address and transaction ID?

**Comment by mhuggins** [comment]
Stale issue, closing.

**Comment by abeau007** [comment]
hi matt,l was able to recover them.thx,armand
    On Tuesday, March 13, 2018, 9:31:07 PM PDT, Matt Huggins <notifications@github.com> wrote:  
 
 
Stale issue, closing.
