### ISSUE TITLE
I bought NRVE yesterday, it showed my purchase under tokens but today no tokens?

### ISSUE THREAD

**Issue by u0087966** [CityOfZion/neon-wallet#759]
Where did my NRVE tokens go?  They were there yesterday and this morning but now there's no token balances showing.

**Comment by mhuggins** [comment]
@u0087966 Make sure you add the ScriptHash for the NRVE token under the "Manage Neon Settings" screen.

**Comment by u0087966** [comment]
Thanks mhuggins.  The scripthash was there with the other tokens.  I think I just needed to log out and wait before logging in again (or maybe going to the scripthash setting retrigger it?).  They're showing in my wallet now.
