### ISSUE TITLE
Balance Rounding

### ISSUE THREAD

**Issue by ShaneAsel** [CityOfZion/neon-wallet#76]
When transferring from Bittrex, my new NEO balance shows a rounded number which is less than what I transferred (minus the Bittrex fee). 

Also, since my NEO balance isn't extremely large, the GAS balance isn't large either but all my transactions show 0.0000

Is there a way to show your balance like in the exchanges (e.g. 10.XXXXXXXX)?

**Comment by FreshDS** [comment]
I'd like to know this as well. Sent x.4 and now the .4 is gone?

**Comment by canesin** [comment]
See #64 this is not a neon/neo problem, the token can only be sent in integers. Please consult bittrex support.
