### ISSUE TITLE
Sending MAX balance GAS fails with "Transaction failed" in certain cases

### ISSUE THREAD

**Issue by dennish007** [CityOfZion/neon-wallet#764]
sending MAX balance of GAS fails in some wallets. Decreasing the amount with a drop of GAS will solve the problem. 
Might be a rounding off issue.

Version 0.1.4 OSX version

**Comment by tradebully** [comment]
Keep getting error messages when trying to claim gas. Neon wallet is also slow to load up when using Nano ledger S

**Comment by mhuggins** [comment]
Please try downloading the latest version, a number of issues have been addressed.
