### ISSUE TITLE
Can't send out DBC tokens to Exchange from my NEO neon wallet.

### ISSUE THREAD

**Issue by esco37** [CityOfZion/neon-wallet#765]
I have my DBC tokens on the NEO Neon wallet that i access through my Nano Ledger S. I am able to see my DBC balance on the Neon wallet , but i'm not able to send them out to the exchange. I have enough GAS in my wallet so that is not the issues, nor the exchange wallet. When i'm prompted to sign the transaction on my ledger it does not give me that option. I've contacted Nano and they said to contact NEO Neon wallet. nothing but back and forth. Please help anyone.

**Comment by maginso** [comment]
same with all my nep5 tokens

**Comment by jazy510** [comment]
Same here. All NEP5 tokens give the error about needing 1 drop of GAS, tho the wallet has plenty of GAS in it.

**Comment by esco37** [comment]
How can we fix this.

**Comment by RoyLee** [comment]
This is also happening to me. When I try to send NEP-5 tokens (not NEO or GAS), I don't even see the transaction it in neotracker, the amount is subtracted from the total amount I own according to the Neon Wallet app, and it never ends up in the destination address.

**Comment by Niels1990** [comment]
@jazy510 so delete and install the NEO app on the ledger and we should be fine? What about the funds, are they lost when deleting the NEO app on the ledger?

**Comment by jazy510** [comment]
@Niels1990 correct.  Funds remain secured, and are derived from your Ledger's seed key, which doesn't change, so you're free to update and re-install.

**Comment by mhuggins** [comment]
Please try downloading the latest version, a number of Ledger issues have been addressed.
