### ISSUE TITLE
Unable to Receive GAS -- wallet version 0.1.4

### ISSUE THREAD

**Issue by cryptodiddler** [CityOfZion/neon-wallet#766]
Processing
Sending NEO to Yourself...

The transaction will stall and then fail.

Sent GAS from exchange to wallet several hours ago. Has yet to arrive although the exchange shows it has completed. In the past, NEO/GAS arrived within minutes.

Previous version of NEON wallet worked great. Problems arose soon after upgrading to new version.

Refresh account balance does not work, either.

UPDATE: Feb. 24 -- everything seems back to normal. Wallet is functioning smoothly. Sometimes all you need is a little patience...

**Comment by leafcutterant** [comment]
Same problem here.

How much gas do you need for a simple NEO transfer?

**Comment by tradebully** [comment]
Still having same issues here. I upgraded to newer Neon wallet version and ledger as well. I still can't claim any gas and it gives me the error message. Can someone please address this problem?

**Comment by leafcutterant** [comment]
My Neon Wallet also creates transactions in the transaction history, but if I try to look up the hash in an explorer, it can't locate such transaction.

**Comment by leafcutterant** [comment]
Okay, it just credited my gas to me. I have no idea why it succeeded. It just inserted a new transaction in the middle of my failed ones.

**Comment by erickneverson** [comment]
Is there a minimum amount of GAS required before you can claim?
