### ISSUE TITLE
Can't log into NEON wallet via Ledger in version 0.1.4 

### ISSUE THREAD

**Issue by millsmovies** [CityOfZion/neon-wallet#767]
Everytime I try to connect to my NEON wallet through my ledger nano S (on MainNet version), it just continues doing the loading icon in the middle and doesn't go through. When I change it to TestNet version (which I have no idea what that means), it goes through but then it says my balance is 0... 

What can I do? I'm hearing of people losing all their NEOs completely with these software updates and worried that happened to me too? When I tried to log in before it told me I had to upgrade to 0.1.4 version and I did but now I can't even get in... 

FTR on my Ledger it just keeps saying "Waking up Neo..."

**Comment by pesplanus** [comment]
Same issue. Ubuntu 16.04LTS, Neon 0.1.4. Tried changing block explorer in the Neon settings which doesn't solve it either.

**Comment by bpullen1** [comment]
Same issue here. Worked this morning, now just keeps loading

**Comment by Neon267** [comment]
I have just sent a neo coin to my wallet but it does not show up using my ledger   on the neon wallet, ive got the same issue cant claim gas and blocks do not update stuck at 1955932

Any solution guys  ?

**Comment by robertftw** [comment]
Stuck on block 1955932 too...

**Comment by bogglemcgee** [comment]
Same problem here too.

**Comment by usbitcp** [comment]
Same here........what is it all about?

**Comment by memph2810** [comment]
I thought I was having the same problem but just let it load and reopen the ledger app anytime it times out in the process. Took about 10 minutes.

**Comment by Shakufighter** [comment]
seems like NeonWallet server is down.
you can check your balance on neoscan, your balance is still on the chain.

dunno whats wrong, neotracker.io is also down (beeing updated since yesterday)

**Comment by usbitcp** [comment]
just a question...if Neon Wallet disappears, what happens to the funds? As Ledger works with Neon Wallet...

**Comment by Shakufighter** [comment]
usbitcp dann ist dein private key ja immernoch in deinem Ledger gespeichert und könnte über umwege ausgelesen werden, oder eben ein anderes Wallet dann benutzen, was dann ja schon kommen würde.
Aber so schnell wird NeonWallet ja nicht einfach off gehen.
Und deine Coins sind ja nicht auf dem Wallet, sondern auf der Blockchain und die ist ja auch safe :)

**Comment by Shakufighter** [comment]
Oh damn wrong language i guess :dagger:
then it's to read out your private key, its saved in the ledger and can work, their are ways around it to read out the private key (but that destroys the purpose of the ledger, so its like worst case)
Or another wallet would just come and also work with it then. but why would NeonWallet go offline?
Don't think that would happen so fast without a reason.
Your Funds are on the Blockchain and not on the Wallet as you know :dancer:

**Comment by Neon267** [comment]
Seem to be working now the fix was successful

**Comment by usbitcp** [comment]
good work neon.
I am trying to understand what 'FREE Gas" is?
Is it something like staking that for keeping your coins in wallet you get interest i.e. Free gas?
or is it something else, please clarify.

**Comment by Shakufighter** [comment]
Yea, its like staking it, but not like Ethereum the "gas" is the same token "ether", NEO has ot split in two different tokens, for holding NEO in your wallet it will generate NeoGas, which u can claim every 5 minuits. 
Can be traded on Kucoin ect. And has round about 1/2 the price of the Neo coin. 
U can calculate on websites how much Gas your coins accumilate per day/year ect.

**Comment by usbitcp** [comment]
so in simple words its 'interest payment'?

**Comment by mhuggins** [comment]
Please try downloading the latest version, a number of Ledger issues have been addressed.
