### ISSUE TITLE
Can't login into Neon Wallet

### ISSUE THREAD

**Issue by smilingsunray** [CityOfZion/neon-wallet#768]
I can not log into my neon wallet. After I enter pass phrase all I see is a white screen and loading sign

## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by DEANOBO** [comment]
Same problem

**Comment by DEANOBO** [comment]
Same problem, getting nothing from Discord.

**Comment by DEANOBO** [comment]
Had the same problem, let it just sit and load for about 20 minutes and it opened and all was correct, so don't know what's up but seems just super slow to load.

**Comment by mhuggins** [comment]
Please try downloading the latest version, a number of issues have been addressed.
