### ISSUE TITLE
Neon wallet won't open 23 FEB 2018 ,discord no help

### ISSUE THREAD

**Issue by DEANOBO** [CityOfZion/neon-wallet#769]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by to-kra** [comment]
My wallet wont read any NEO. i see 0.

**Comment by DEANOBO** [comment]
Okay, so my wallet opened after about 20 minutes of sitting on loading screen, so I'm assuming everything is okay, just super slow for whatever reason. BTW, I just use the desktop version so don't have same issue as Nano users are having.

**Comment by fortunato777** [comment]
hello ,how can i update my walle ??? only download the last version ????

**Comment by memph2810** [comment]
I thought I was having the same issue but after reading DEANOBO's post I let my wallet load and reopened the nano app any time it closed. Took me 8-10 minutes to open the Neon wallet.

**Comment by mhuggins** [comment]
Please try downloading the latest version, a number of issues have been addressed.
