### ISSUE TITLE
Neon Wallet not displaying NEO coins

### ISSUE THREAD

**Issue by marinersouthampton** [CityOfZion/neon-wallet#77]
See screenshot and link to the transaction made several hours ago. I still cant see the NEOs on my Wallet but they appear to have been transferred from Bittrex. Please advise. 

https://neotracker.io/tx/e30f19221d985a11347b864a46e350a682e8bae1527895182d114658bbc39d05

![neo](https://user-images.githubusercontent.com/28981981/29181053-a42b7288-7df1-11e7-9db4-049f06d87df8.PNG)

**Comment by iconartus** [comment]
I'm having the same problem. Also, my Block number is not syncing at all. Stuck at 'Block 0'. Trying to figure out how to whitelist the application.

**Comment by Ejhfast** [comment]
please install the latest release! this is a well documented problem, bittrex broke the API and we had to update. search before posting a new issue

**Comment by substation41** [comment]
I downloaded the windows wallet unzipped the files...nothing loaded...no exe files to be seen
So I downloaded the web version fine. My Bittrex transfer (test) of 2 NEO show 1.9 leaving .Only 1.0 show up in my wallet. Is it going to show up if I transfer the re4maining 148 NEO balance?

**Comment by Ejhfast** [comment]
download the exe file directly! and don't try to transfer fractional amounts with bittrex, they will take your money. this is not the place to post about these issue

**Comment by substation41** [comment]
Directly from where...link? So my $30 Canadian is gone? 'Please advise and I'm sorry for posting here.

**Comment by anfn101** [comment]
It is on the sidebar of the Reddit, and all updated versions will be posted there. Please do not use Github as a venue for tech support! It is very frustrating for us! Make sure everyone you know knows to NOT CREATE A GITHUB ACCOUNT JUST TO POST ON OUR REPOSITORY FOR HELP. There are proper channels of support!

**Comment by marinersouthampton** [comment]
Hi there, I have downloaded the latest alpha version of the Wallet and still dont see my Wallet with the transferred amount. Please advise!!
