### ISSUE TITLE
Finding Neo

### ISSUE THREAD

**Issue by cosmic-springs** [CityOfZion/neon-wallet#773]
Hi.
I have now lost 9 NEO and around 2000 DBC. They disappeared from my wallet and the NEO are showing in my transaction history (-9). However, no transaction was made by me?? I accessed neotracker.io the previous day. 
It’s everything i had :( so disappointed. I realise that people have lost much more than me and I feel bad for them but it doesn’t make me feel better. it makes me so mad that people can get away with peoples hard earned money with what appears like very little effort. This was also a link that you assume is legit as it seems to be endorsed/embeded in the NEON wallet.
It would be great if rather than many different wallets we could access 1 or 2 that are solid and safe?
Unfortunately I am currently unemployed but used work with computers and i know that most issues users have are user error related and very frustrating constantly defended and justifying your work. The issues i have encountered are not simple user error. I cant help thinking that in order to catch many of the culprits of these scams/thefts wallet developers should look closer to home?? 
I’m not trying to get rich (9 NEO are unlikely to do that especially as I bought very high) I’m just trying to put a little by for when my kids get older.

Hash: 49774c05a3c7a7d9e90912f168e834077988f58f806441469f04bca0ffa3021c
Time: 07/02/2018, 17:17:19
Wallet: AU6GkGRt4jeESJnM56mz9uJiwacNMTHjzH

Have I been hacked/Phished/will I ever see my coins again?
Is this just part of the mysterious disappearing and often reappearing of NEO from various wallets and ledgers (I lost one around a month ago but it reappeared a week later)?
I may be a little naive but I’m not a complete idiot and I do take precautions to maximise security.

Any assistance/advice/HELP! Would be greatly appreciated.

**Comment by mhuggins** [comment]
@cosmic-springs I'm sorry about your loss.  Unfortunately this is not an issue with the NEON Wallet, but instead appears that someone got ahold of your private key.  It looks like this was already addressed/responded to in #680.
