### ISSUE TITLE
Unable to send NEP5 tokens, neither to claim GAS

### ISSUE THREAD

**Issue by P2NPoison** [CityOfZion/neon-wallet#774]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by mhuggins** [comment]
Duplicate of #765.

**Comment by P2NPoison** [comment]
Why do you close the issue?
The problem is still alive.

**Comment by mhuggins** [comment]
Because it's a duplicate.  By opening multiple duplicate issues, it makes it difficult to track specific bugs.  Also, for clarity, this is a bug tracker, not a support tracker.
