### ISSUE TITLE
Neotracker.io

### ISSUE THREAD

**Issue by cosmic-springs** [CityOfZion/neon-wallet#781]
Neotraker.io had phishing software last week, 8000 NEO and loads of Nep tokens were sent from other peoples wallets to (AcQZuoHPUCRvdLogJLA3WtGoHBGaM1NzgP) I know because  i lost 9 NEO and 2000 DBC. They left me 0.7551 DBC, so that's nice?
Is Neotraker.io safe to use? Neo and Nep are still being sent to this wallet. 

The Neo website states: It is EXTREMELY important you record and store your private key somewhere safe, and NEVER reveal it to anyone. Also, always double check the URL of any site you visit via a link to ensure it is authentic, legitimate and the site you intended to visit. Even when being linked from us! 

how can we possibly tell if a link is dodgy when it has the exact same address as the (legitimate one)
I'm sure that this isn't the correct place to post this, it seems like nowhere is, i keep getting told i need to visit neo.org but the site is down. This is all very dodgy in the extreme!

Has anyone been warned about this?
Will the phishing software be shutdown?
Will Neo/Neotracker adopt a more secure framework, perhaps with a secondary verification like exchanges?
Will people ever see any of the 2 million dollars plus and growing in the wallet again?
Are NEO likely have a support mechanism for users that isn't ambiguous and obtuse?

**Comment by cosmic-springs** [comment]
<img width="739" alt="screen shot 2018-02-28 at 9 53 54 pm" src="https://user-images.githubusercontent.com/22673394/36795940-3d74112a-1cdf-11e8-9535-8a55b795bda5.png">

**Comment by mhuggins** [comment]
This is not related to the neon-wallet.  Please reach out on Discourse if you need support around third party NEO projects.

**Comment by cosmic-springs** [comment]
Discourse told me the same thing, they only do NEO GUI, Thanks for your prompt reply.....I get the decentralised bit but does that mean that no one is ever responsible for any mistakes, great business model but not one that will have longevity.

**Comment by mhuggins** [comment]
That's probably because these are City of Zion projects, but Neotracker is not related to City of Zion.  You would have better luck discussing with Neotracker.  More than likely you hit a spoof site rather than neotracker.io since those keep cropping up.

**Comment by cosmic-springs** [comment]
Definitely neotracker.io<http://neotracker.io> which as I’m sure you know is an insecure online wallet directly linked to NEON wether you like it or not. If you are not affiliated why force people into using neotracker?

Sent from my iPhone

On 28 Feb 2018, at 11:56 PM, Matt Huggins <notifications@github.com<mailto:notifications@github.com>> wrote:


That's probably because these are City of Zion projects, but Neotracker is not related to City of Zion. You would have better luck discussing with Neotracker. More than likely you hit a spoof site rather than neotracker.io<http://neotracker.io> since those keep cropping up.

**Comment by cosmic-springs** [comment]
They said contact you! I’m just going to assume that NEO security and support is so poor that if everyone ignores all issues regarding the chronic theft of NEO it might go away.

Sent from my iPhone

On 28 Feb 2018, at 11:36 PM, Matt Huggins <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #781<https://github.com/CityOfZion/neon-wallet/issues/781>.

**Comment by mhuggins** [comment]
> If you are not affiliated why force people into using neotracker?

No one is forcing you to use NEO Tracker.  You have a choice about what to use.  This repo is for NEON Wallet, I would recommend using that.

> They said contact you! 

Who is "they"?

**Comment by cosmic-springs** [comment]
Hi.

I was wondering if you could help me.
I sent 1 Ontology to my Neon wallet from Exodus wallet to test but it didn't arrive. Exodus helpline said that it had indeed been sent to the correct Neon address but it is not showing in my Neon wallet. Any idea why? The transaction hash was 803a1c4f4c90017739f54cb09f2dba7c6df4336bd49f04435d0cd57bad020646

Kind Regards,

Andy.

On 1 Mar 2018, at 12:58 AM, Matt Huggins <notifications@github.com<mailto:notifications@github.com>> wrote:


If you are not affiliated why force people into using neotracker?

No one is forcing you to use NEO Tracker. You have a choice about what to use. This repo is for NEON Wallet, I would recommend using that.

They said contact you!

Who is "they"?
