### ISSUE TITLE
Feature: Add a saved wallet based on existing encrypted/private key

### ISSUE THREAD

**Issue by mischkl** [CityOfZion/neon-wallet#783]
At the moment Neon can only save credentials (the "Login using a saved wallet" feature) for wallets that were created with Neon. It would be nice if there were an option to "save" wallets that were not created in Neon, either via an option on the home screen, or via an option that lets you save a wallet once you've logged in via encrypted or private key.

**Comment by comountainclimber** [comment]
This work is implemented in v2 🎉

**Comment by mm999222** [comment]
I was trying to encrypt my private key in my NEON wallet (I move from NEO to NEON and logged into NEON with my private key) so I don't have to use my private key to log in, but I have this issue...

On the "Encrypt a Key screen" when I put my private key onto the private key box (and set my pass phrase) the button "Generate Encrypted Key" becomes inactive. If I leave my pass phrase in but remove my private key that button becomes active. I don't want to get locked out. I can't find any info on line about this :(
