### ISSUE TITLE
neonwallet.com is insecure and doesn't use https

### ISSUE THREAD

**Issue by KelseyDH** [CityOfZion/neon-wallet#784]
With opportunities for malicious man-in-the-middle downloads, it strikes me as very odd the main website for neonwallet isn't set up with basic TLS encryption.  Why is this?  This introduces a security risk for any user visiting the site and trying to download a wallet.

**Comment by mhuggins** [comment]
Thanks for reaching out.  We've got a story on the neon-wallet-website repo to track this: https://github.com/CityOfZion/neon-wallet-website/issues/1
