### ISSUE TITLE
Unable to receive ONT airdrops

### ISSUE THREAD

**Issue by relativityE** [CityOfZion/neon-wallet#786]
I am not sure there's a setting for airdrops but connected to mainnet and airdrops for ONT tokens aren't showing up.
Also, how do I customize the list of NEP-5 tokens that are displayed to only show those with tokens > 0?
![neon wallet](https://user-images.githubusercontent.com/36959427/36847996-cc1101f6-1d14-11e8-9fe4-d9b1b87464fe.png)

**Comment by mhuggins** [comment]
The actual airdrop of ONT will occur in the coming weeks.  From their discord:

> We have now reached the block height 1974823, and the snapshot of NEO addresses has been taken. Delivery of the first portion of ONT will be completed in the weeks following March 1, 2018 (0.1 ONT per NEO). The other locked half (0.1 ONT per NEO) will be using the same snapshot, but will instead be airdropped after the release of Ontology MainNet in Q2 2018. ONT is not released on any exchanges. Further details will be announced later.

When that happens, all you need to do to see it in neon-wallet is add the ONT script hash in the settings screen.

**Comment by relativityE** [comment]
Thanks for the quick response.
One more item. Can I get the wallet display to only show NEP-5 tokens with
amounts > 0? Since there's only so much real estate for display of various
tokens. Example below
[image: Inline image 1]

*:Akin*

**Comment by mhuggins** [comment]
I've actually already addressed the amounts displaying for balances > 0.  It will ship with our redesigned wallet in the near future.

**Comment by ruchern** [comment]
Probably related #829
