### ISSUE TITLE
Nano ledger S Neo Wallet Unable to Claim Gas

### ISSUE THREAD

**Issue by Failuretolisten** [CityOfZion/neon-wallet#791]
Unable to claim gas today in Neo wallet get transaction error message.

**Comment by Omegshi147** [comment]
Same problem. Tried doing everything and nothing is working for me.

**Comment by Kleetz** [comment]
Same boat for me. Claiming Gas triggers a "Transaction Failed!" message

**Comment by JupJar** [comment]
Same, can't claim (Transaction Failed), Can't send either, Error.

**Comment by Omegshi147** [comment]
It's working now guys. Try again.

**Comment by Kleetz** [comment]
Can confirm, it's back up!

**Comment by JupJar** [comment]
ONLY claiming GAS works.
Sending GAS not (Error message)

**Comment by Alotoffixins** [comment]
Has this issue been resolved yet? I am unable to send NEP5 tokens (RPX) out of my wallet, receiving a "transaction failed" message each time.

**Comment by JupJar** [comment]
Fine fo me. Could send GAS today.

**Comment by mhuggins** [comment]
Tracking this issue under #882.
