### ISSUE TITLE
Just moved my NEO into wallet and this morning its all gone!!!

### ISSUE THREAD

**Issue by ph3l1x** [CityOfZion/neon-wallet#792]
I just created a wallet at neotracker.io/wallet and I wake up this morning and its all gone. Doesn't show anything in transaction history either.. what has happened!!!!

**Comment by mhuggins** [comment]
CANVAS_PLANS_MANAGE_ACCESS

**Comment by ph3l1x** [comment]
Yes, I just recently checked on there and I see it on there.. Any idea what is happening with the wallet?

**Comment by mhuggins** [comment]
It's likely just a connectivity issue.

**Comment by stevesbrain** [comment]
@ph3l1x If you have a connectivity to the upstream blockchain, then you'll experience issues like this. Likewhis, if neon-wallet servers are done, the app doesn't have an accurate source of information to retrieve and display your balance from.
