### ISSUE TITLE
NEO GONE??

### ISSUE THREAD

**Issue by ph3l1x** [CityOfZion/neon-wallet#793]
I just created an account and moved all my neo to the wallet. It was there last night. I wake up this morning and everything is gone??? Then for a split second I saw my neo in there and then it went back to 0 again.. There are 0  transactions.. What is happening? Where is my NEO at????

**Comment by mhuggins** [comment]
Check the address on the blockchain (e.g.: neoscan).  If you see it on there, then it's fine.  It's possible the wallet is having connectivity issues.

**Comment by mhuggins** [comment]
Closing this, as it's a duplicate of #792.
