### ISSUE TITLE
Airdropped ONT 

### ISSUE THREAD

**Issue by romancewasborn** [CityOfZion/neon-wallet#794]
how do i claim my ONT??...i had NEO in my wallet but no coins have arrived yet>> please help

**Comment by Diplomat47** [comment]
I also do not have anything on the account

**Comment by romancewasborn** [comment]
please check, as i had NEO during The snapshot at block number 1974823...what do you need to check my wallet

**Comment by mhuggins** [comment]
There is nothing to claim, ONT has not been airdropped yet.  Only the snapshot has occurred.  Please refer to the blog post for more info: https://neo.org/blog/details/3061

**Comment by OntologyIO** [comment]
read here how to claim ONT via neon wallet: https://medium.com/@andrijlax/how-to-claim-2nd-ontology-airdrop-288a04a4c01
