### ISSUE TITLE
Unable to open the application file 

### ISSUE THREAD

**Issue by Raheelsiddiqui786** [CityOfZion/neon-wallet#795]
## PLEASE NOTE

![image](https://user-images.githubusercontent.com/37016943/36934017-29504406-1efc-11e8-8cbd-199c049a7610.png)

**Comment by comountainclimber** [comment]
@Raheelsiddiqui786 this is the default behavior for any application that did not come from the app store https://support.apple.com/kb/PH25088?locale=en_US
