### ISSUE TITLE
dev branch: Stale wallet data displayed when loading new wallet

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neon-wallet#796]
This appears to be a new issue on the `dev` branch as compared with 0.1.4.  On 0.1.4, any time you opened a new wallet, you would see the green "loading" bars displayed until the wallet's data was loaded. On the `dev` build, those loading bars appear to have been removed and instead you see the _previous_ wallet's balances displayed temporarily until the new wallet's balances are fetched and updated in the UI. This is probably just a minor issue, but if there is a network issue, then it can lead to old balances being displayed for longer which is unexpected and undesirable.

I think the previous behavior of not showing any balances until the data is fetched is the preferable UX.

**Comment by mhuggins** [comment]
I see what's happening.  We're calling `accountsAction.reset()` when the user logs out, which should in turn reset each associated request (on balances, claims, and transactions), but that is not happening.  I'll try to figure it out.

**Comment by mhuggins** [comment]
@brianlenz I submitted a fix for this under #800.

**Comment by brianlenz** [comment]
Fix confirmed! 👍
