### ISSUE TITLE
NEON Wallet Mac ONT After Newsletter?

### ISSUE THREAD

**Issue by zactm56** [CityOfZion/neon-wallet#809]
Hey can someone please post clear instructions on how to access ONT via the NEON wallet. I registered for the newsletter and received confirmation, but am not sure how to access ONT and transfer to exchange. Any help is appreciated.

**Comment by romancewasborn** [comment]
me to please, i cant see my airdrop ONT

**Comment by Matty1ce** [comment]
NEON wallet will probably update to show ONT balances soon, but if you want just open NEON wallet > Settings > Manage Tokens > +Add a New Token > Then enter this script hash: ceab719b8baa2310f232ee0d277c061704541cfb

This will now show your ONT token balance when you open your wallet.

**Comment by mhuggins** [comment]
The ONT script hash has been added as of version 0.2.0 so that users don't need to add it themselves.
