### ISSUE TITLE
Enhancement: Proper container/component architecture.

### ISSUE THREAD

**Issue by Alexintosh** [CityOfZion/neon-wallet#81]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[X] proposal

**Current behavior:**
At the moment many components are using the connect function from redux which makes them containers.

**Expected behavior:**
Proper separation of pure presentational components from stateful components as explained in the [container/component architecture](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0).
It's a good idea to use [styled-components](https://github.com/styled-components/styled-components) for pure presentational components.

**Comment by Alexintosh** [comment]
I'll be glad to work on this. 
It's not completely clear how the process works to get PRs reviewed, I made a couple based on github issues last week. I'd appreciate if someone cold add me on Trello.

**Comment by shawnmclean** [comment]
This falls under #216
