### ISSUE TITLE
Little Snitch: No Code signature.

### ISSUE THREAD

**Issue by joshrio** [CityOfZion/neon-wallet#812]
I have NEON wallet installed and little Snitch running in the background. 

This alert just popped up.

> NEON
> wants to connect to api.wallet.cityofzion.io
> The process has no code signature. The executable can be maliciously modified without being detected.

Whats the deal with this?

**Comment by stevesbrain** [comment]
Presumably you're on a Mac? If so, that message would indicate that the particular bit of software is not signed with a cert issued by Apple.
