### ISSUE TITLE
Neon wallet not sending ONT tokens

### ISSUE THREAD

**Issue by squallss4** [CityOfZion/neon-wallet#818]
Every time I try to send ONT tokens it says transaction Failed

**Comment by AlphaCVK** [comment]
Same issue, really bad... haven't found any solutions. Losing value...

**Comment by gheon** [comment]
Same here. Tried with version 0.1.3 and 0.1.4 and both a failing.

**Comment by dennish007** [comment]
I had the same problem with sending MAX. Not only ONT but also other tokens.
Example: Display says 0.2 ONT. In reality this is just a little bit less. Sending 1.9999 works.
I filed this under an other issue with sending GAS. See #764

**Comment by mhuggins** [comment]
Please try downloading the latest version.
