### ISSUE TITLE
CAN NOT SEND TKY TOKENS FROM NEON WALLET

### ISSUE THREAD

**Issue by coinheo** [CityOfZion/neon-wallet#819]

**Comment by slim16** [comment]
Same issue as this. Simply get a transaction failed message. Would be really nice to get some kind of more informative error message as well.

**Comment by coinheo** [comment]
I just upload latest version of ledger nano s and neon wallet and it has be done !

**Comment by slim16** [comment]
still having this issue on the desktop wallet v 0.1.4
