### ISSUE TITLE
[Feature Request]Transaction tracking for NEP5 tokens

### ISSUE THREAD

**Issue by slim16** [CityOfZion/neon-wallet#821]
Would be good to be able to see transaction history for each token rather than just NEO

**Comment by nsbindo** [comment]
Is there a way to 
1. Get transaction detail of NEP-5 and NEO?
2. Get a list of NEP-5 transaction history of an Address?

**Comment by comountainclimber** [comment]
New feature in v2 🎉 completed here => https://github.com/CityOfZion/neon-wallet/pull/1418
