### ISSUE TITLE
Feature: Display sum of available and unavailable GAS as balance

### ISSUE THREAD

**Issue by MediaServe** [CityOfZion/neon-wallet#822]
GAS claims are taking up a lot of transactions on the network, though mostly GAS claims are useless. I'm assuming people are claiming GAS mostly just to see the total balance. If we would display the sum of available and unavailable GAS as total GAS balance, then the need to claim GAS would be reduced, which is good for the network. The claim option could also be a bit more hidden then.

**Comment by mhuggins** [comment]
Thanks for the suggestion!  This is actually already implemented as a feature for the next UI update.
