### ISSUE TITLE
My Neo coins missing

### ISSUE THREAD

**Issue by sebjules** [CityOfZion/neon-wallet#824]
I sent two NEO coins from Neonwallet a while ago. Transaction not found on neo tracker.
this is my TX

c94543e230489825dd06d7587d9b39ddc2e62703a0242e509c77a33034c34e5e

plse find the coins...
thanks

**Comment by bitcoinnewbie78** [comment]
same exact thing for me....i went to the tracker page, and the last blocks i can see that were processed were on 3-3-18.....i'm wondering if i'm misreading something or if there is a known issue and that they are just that far behind from that 2hr outage not too long ago???

**Comment by Tristan1986** [comment]
Same here. 

Send 10 neo from NeonWallet, tx: 1b84b8cd8aaf4a3b09c213425095bbdb478254afd4d889730dc99d09526d7ca5

I cant find them where they should be transferred to, neither on my wallet anymore. Anyone knows what happened?

**Comment by sebjules** [comment]
I asked the guys at the neo telegram group. They asked me to relax. Said coins transfer now taking up to four hours. 
I checked tx on neo scan and they are there. Hopefully the coins arrive at binance. Cheers guys

**Comment by bitcoinnewbie78** [comment]
maybe i'm using the wrong hash to track mine.....is there somewhere else i can find the tx number? i see that my number is many digits shorter than the other 2 listed here.....

**Comment by chunkyninja** [comment]
Hi, Im having problems with the neon wallet. I'm using the 0.1.4 but its saying that my wallet is out of date? I have tried downloading the most recent wallet again but its still saying out of date?
Does anybody know what's going on?

**Comment by sebjules** [comment]
Bitnewbie, yes, yr tx is short. 
The transaction links are in the wallet on the right..

**Comment by bitcoinnewbie78** [comment]
thats where i copied the TX number from....the TX History on the right side of the Neon Wallet......hmm....i was able to trace the destination wallet on Neo Scan, and i was able to find my whole TX number. I'm just wondering why the whole number doesnt show in my wallet.....

**Comment by sebjules** [comment]
I think the neo tracker is on maintenance. Just hang in there. The coins should arrive. Many facing same problem as us. Cheers

**Comment by sebjules** [comment]
They have finally arrived:)

**Comment by bitcoinnewbie78** [comment]
Mine too!!! Haha, just a shade under 14hrs

Happy trading!
