### ISSUE TITLE
ONT token Transaction not Showing Up

### ISSUE THREAD

**Issue by lemmallari** [CityOfZion/neon-wallet#825]
I received some ONT airdrop based from my NEO holdings in my NEO wallet. I tried transferring those ONT tokens to Binance but no transaction is showing up in my Neon wallet and no ONT tokens were coming in to Binance.

**Comment by limun-dnaw** [comment]
Same, it showed as "successfully sent" but transaction is not showing up neither in NEON or Binance

**Comment by neo-xp-lee** [comment]
so am i

**Comment by ruchern** [comment]
Probably related #829

**Comment by mhuggins** [comment]
The ONT script hash has been added as of version 0.2.0 so that users don't need to add it themselves.
