### ISSUE TITLE
dev: Show loading spinner when switching between MainNet & TestNet

### ISSUE THREAD

**Issue by mhuggins** [CityOfZion/neon-wallet#826]
When switching between MainNet and TestNet on the `master` branch, we show the loading spinner while data is fetched.  This is not true on the `dev` branch, which results in the user possibly opening a modal with "stale" data while the new data is still being loaded.

The `dev` branch should maintain this loading spinner functionality when switching networks.

**Comment by comountainclimber** [comment]
This does not seem to be an issue at this point... Closing for now
