### ISSUE TITLE
dev: Allow claiming GAS from different wallets within 5 minutes

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neon-wallet#831]
It looks like the 5 minute limitation for claiming GAS is being enforced across wallets. If I claim gas in one wallet, I should be able to load a different wallet and claim GAS there. In that case, however, Neon is preventing you from doing so:

> You can claim GAS once every 5 minutes

You can simply restart Neon wallet to get around this limitation, which makes me wonder if the 5-minute GAS claim limitation should be tracked differently (e.g. via transaction history) instead of an in-memory timer. That very well may be a separate issue, but thought I would mention it here since it's related.

**Comment by mhuggins** [comment]
This has been an issue for awhile I believe and shouldn't block release. I have actually been thinking about this and i think this will be easier to solve once the claiming action has been replaced by the new actions architecture.

**Comment by mhuggins** [comment]
The reason being that there's an easy way to clear data from the store based upon user actions.

**Comment by brianlenz** [comment]
OK, cool! I wasn't sure it was new. Definitely not a blocker, but wanted to get it logged once I noticed it 😁
