### ISSUE TITLE
[Bug] Price always show USD value

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neon-wallet#843]
The price functionality always reflect the USD value even if you change it to any other currency. 

The symbol changes but the number doesn't. So I see my 1 NEO at 95 USD and also at 95 JPY.

**Comment by Vijabei** [comment]
Same with EUR =)

**Comment by jpenner123** [comment]
Have the same problem with 0.2.1. It seemed to work with the previous version.

**Comment by morgangrice** [comment]
Same issue occurring with AUD in version 0.2.1
