### ISSUE TITLE
MacOS 0.2.1 SHA-256 wrong?

### ISSUE THREAD

**Issue by da-gargian** [CityOfZion/neon-wallet#844]
Hi,

calculating SHA 256 gives another hash as shown. without leading 1. copy paste error?

## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by ucc-xx** [comment]
Since a sha256 should always be 64 char long and the postet hash is 65 char long, I'd also suspect a c'n'p error and nothing malicious.

**Comment by ruchern** [comment]
It's just a copy and paste error. Omitting the `1` at the start, the string and hash is correct throughout.

**Comment by mhuggins** [comment]
Fixed, thanks!
