### ISSUE TITLE
Received less that 0.2 ONT for 50% Neo in Wallet

### ISSUE THREAD

**Issue by RoseM2018** [CityOfZion/neon-wallet#846]

**Comment by mhuggins** [comment]
0.1 per neo has been released, 0.1 per neo has not been released.

**Comment by RoseM2018** [comment]
I know that and I should have received 54.4 ONT coins now but only got 42.4.   And another 54.4 when  the ONT mainnet goes live

**Comment by mhuggins** [comment]
You should reach out to the Ontology team then, City of Zion has nothing to do with ONT distribution.

**Comment by RoseM2018** [comment]
Thanks, I wasn't sure what to do.
