### ISSUE TITLE
Feature: Allow NEP-5 tokens to be disabled/enabled

### ISSUE THREAD

**Issue by ThomasLobker** [CityOfZion/neon-wallet#847]
It consumes a relative amount of server resources to check all tokens every time. Especially with the growing amount of NEO tokens. It would be better to be able to disable tokens that you don't have.

**Comment by comountainclimber** [comment]
Tracking this issue here https://github.com/CityOfZion/neon-wallet/issues/1391 will definitely be implemented in v2 thanks @ThomasLobker
