### ISSUE TITLE
Can't claim GAS

### ISSUE THREAD

**Issue by giancarlosrn** [CityOfZion/neon-wallet#85]
Every time I hit claim on GAS, it shows zero balance on the history. 

<img width="988" alt="screen shot 2017-08-11 at 12 35 55 pm" src="https://user-images.githubusercontent.com/30935414/29224889-c7c5adf8-7e91-11e7-9c6a-d51991889099.png">

**Comment by eavanes** [comment]
I have the same issue. Could you figure it out?

**Comment by FrankieSpades** [comment]
same here!  it only worked the first time.

**Comment by merretta** [comment]
I have the same issue however my Claim button always shows 0 GAS, the other odd thing is when I click on any of the links in the transaction history it goes to http://antcha.in with a 404 page error in the middle of the website even on the transaction that shows the NEO coins.

![image](https://user-images.githubusercontent.com/30979376/29250372-cbf331c6-8084-11e7-9d84-9427f66ebea0.png)

Should I move my NEO again to a new wallet?

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this.** As an aside, I've had to close about 5 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
