### ISSUE TITLE
Loading wallet recovery file ends in blank page until app is restarted

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#851]
**Wallet version:**
0.2.1
**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.248
**Prerequisites:**
Any wallet recovery file
**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Load wallet recovery file" button
4. Choose your wallet recovery file

Wallet is imported with success but app ends in blank page until it's restarted.

![load_wallet_rec_file_blank](https://user-images.githubusercontent.com/8177587/37302723-a6fbbf70-262c-11e8-882d-68b24c503621.gif)

**Comment by cupid-stunt** [comment]
I get the same on a MAC

**Comment by mhuggins** [comment]
Thanks for the report, I'll look into this.

**Comment by Apetech** [comment]
I got the same problem on OS X Yosemite 10.10.5

**Comment by mhuggins** [comment]
Will work on a fix this week.

**Comment by drptbl** [comment]
@mhuggins This is already fixed on `dev` branch ❤️ .

**Comment by mhuggins** [comment]
Ahh, awesome!  Sorry for the misunderstanding on my end.  I'll update the release notes and close this then.
