### ISSUE TITLE
Error Calculating claimable GAS failed.

### ISSUE THREAD

**Issue by juliancedrone** [CityOfZion/neon-wallet#855]
After updating to the newest 0.2.1 update I'am now getting this message when attempting to claim my GAS...

Error
Calculating claimable GAS failed.

I have not attempted to send or receive an funds from my wallet just as a precaution. Any help would be much appreciated.

**Comment by spocek** [comment]
Same here.

**Comment by juliancedrone** [comment]
Seems to have resolved itself. I'll leave thread open for others.

**Comment by spocek** [comment]
I get the same message: "Calculating claimable GAS failed."

I am able to send and receive NEO and GAS.

**Comment by spocek** [comment]
I just tested claiming GAS. The problem remains.

**Comment by juliancedrone** [comment]
Not sure. I waited for a new block and then tried, and it seemed to work for me. I'm not sure.

**Comment by juliancedrone** [comment]
I'm not sure, I tried as soon as a new block started and it worked.

**Comment by spocek** [comment]
It worked for me too. I know that there is a 5 minute per claim GAS limit but the problem occurs outside the limit.

**Comment by juliancedrone** [comment]
Sounds like it could be a congestion problem perhaps?

**Comment by spocek** [comment]
Not sure.

**Comment by spocek** [comment]
I just tried again outside the 5 minute time limit window. The error is still there and I am unable to claim GAS.

**Comment by mhuggins** [comment]
Have you received a number of transaction since the last one you sent?  What's possibly happening is that the new transaction (needed for calculating unclaimed GAS) is attempting to be comprised of NEO  across various transactions, and the number of previous transactions exceeds the memory limit of the Ledger.

**Comment by spocek** [comment]
After an hour-long break claiming GAS works.

**Comment by mhuggins** [comment]
@spocek Did you have any other transactions in between not being your failed claim and successful claim?

**Comment by spocek** [comment]
No.

**Comment by GoldVintage** [comment]
Hi All,  

I have got the same issue with my ledger "calculation gas claimable failed". My ledger is in the last version of Firmware and I an using neon wallet 0.2.2? How can I proceed to solve this issue? thanks for your help

**Comment by maximbroos** [comment]
Same issue, i've left the 0.2.2 wallet untouched over the weekend. Still get the same error...
Have you guys fixed it by just trying many many times and then suddenly it worked?

**Comment by GoldVintage** [comment]
still not fixed for me...

**Comment by t2crypto** [comment]
This happened to me. The issue in my case was my ledger nano S. It has signed me out so I needed to sign back in. Also you need to authorize/confirm the trx on your ledger nano.

**Comment by digidan** [comment]
This just happened to me today after trying to claim gas in Neon on my Nano S latest firmware.  Can't seem to get it to work.

**Comment by ncooksammy** [comment]
I am having the same issue too.  Cannot claim gas.  Using the latest version of the ledger and using 0.2.2 of the neo wallet.  Is there a resolution?

**Comment by ncooksammy** [comment]
Not sure what happened, but it just worked :)  May be it just resolves itself

**Comment by sfaisal-modus** [comment]
+1

**Comment by utgarda** [comment]
Seeing the message every time, no matter ho many times I logout/login or restart the wallet.

Neon 0.2.5, Ledger Nano S

**Comment by bitoutshop** [comment]
+1

**Comment by Goro2030** [comment]
+1 on latest version of everything as of today...

**Comment by gfijrb** [comment]
still exist on 0.2.2 neon

**Comment by bitoutshop** [comment]
Still a problem in 0.2.7

**Comment by jinike** [comment]
Hi ! I have similar problem.... tried many times...after a few hours still the same problem.
Error calculating claimable GAS: timeout of 5000ms exceeded 
my is 0.2.7 version...even I log out and login back..same problem.
any solution ?

**Comment by dreekes** [comment]
I have problems in the latest wallet, on the neotracker site... 
I cannot claim gas nor withdraw neo... when will this be fixed?
This is so frustrating!
![image](https://user-images.githubusercontent.com/42683333/44606883-ee7ca000-a7ee-11e8-9c53-c3383f3942f3.png)

**Comment by mikemacintire** [comment]
Count me in as another person unable to claim gas using a Ledger with everything up-to-date.

**Comment by jeramyRR** [comment]
Same here, even updated to the latest wallet.

**Comment by AdverseCatalyst** [comment]
Still a problem with Ver 0.2.8.Same message,cannot claim/send gas or send neo

**Comment by vexatuvex** [comment]
yep, same problem.. v 0.2.8

**Comment by vexatuvex** [comment]
claim your gas with Aphelion Wallet, it works

**Comment by tomasdev** [comment]
Same problem here, last version. Trying to claim 0.21 gas.

**Comment by AdverseCatalyst** [comment]
Mine started working again on 31st Oct.Version 0.2.8.I also noticed at the time I was having trouble Binance was showing network congestion on both Neo and Gas networks and now the Binance is showing it as normal.So yeah,network congestion.I got Neo in multiple places just to be sure plus if it happens again I might consider moving it to a safer place.Neon wallet is nice letting one claim every 5mins though.

**Comment by user905** [comment]
Still happening. 

Wallet: v2.5.0.
Ledger Nano S, firmware: 1.6.0

**Comment by marshalleq** [comment]
Still happening, latest firmware of Nano S, latest Neon on Mac.  Will see if I can try something other than Neon as suggested above, because apparently in lieu of any care to fix this bug, other apps work.  Would suggest others look to same solution.

**Comment by alex-96-eng** [comment]
+1
