### ISSUE TITLE
Blank page after update with Ledger Nano S

### ISSUE THREAD

**Issue by nosynaxerror** [CityOfZion/neon-wallet#860]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by nosynaxerror** [comment]
This was a windows version update .0.2.1.  
I read the past comment about the blank page and tried to bring up the console for the code error.

**Comment by jakesorce** [comment]
Same issue on Mac High Sierra

<img width="1000" alt="screen shot 2018-03-13 at 10 10 19 pm" src="https://user-images.githubusercontent.com/801470/37382979-65db2b54-270b-11e8-8883-2e8e8b7dcf08.png">

**Comment by ciband** [comment]
Same issue for me on Windows 0.2.3

**Comment by drptbl** [comment]
@nosynaxerror @jakesorce @ciband 
1. When does this issue happen? Straight after running the wallet or after clicking on "Login with Ledger" button?
2. Which OS are you using?
3. Which wallet version are you trying to run?
4. Did it happen before or after update or there was no connection at all with updating the wallet (it was working fine and suddenly stopped to work)? If it broke after update, what version did you use before?
5. Do you remember if you did something specific before you closed wallet last time before it broke?
6. Are you sure that nothing is blocking your connection/wallet process from access to internet connection (firewall for example)?
7. Did you try running wallet as administrator?
8. Are you using some anti-virus software?
9. Did you try to reinstall the wallet? (please re-download installation file, don't use the old one)
10. Based on https://github.com/electron-userland/electron-prebuilt-compile/issues/36, do you have `ePowerEvent.exe` process in task manager? If yes, can you kill it and try to run wallet again?
11. If nothing of above worked, can you remove `C:\Users\<YOUR_USER>\AppData\Roaming\Neon` folder and try to run wallet again? Please keep in mind that it will remove all of your wallet settings (imported wallets, address book, etc, so please do a backup of this folder somewhere). If that didn't help, you could try to uninstall the wallet, remove `Neon` folder from `appdata`, install the wallet again and check if it's working.

Please, check if there are no running processes of Neon Wallet in background (using Task Manager) on last 3 steps.

**Comment by ciband** [comment]
@drptbl 

I will try to answer the other questions this weekend when I pull the ledger out of the safe.

1. This happens after the wallet detects the ledger and I click the "Login with Ledger" button.  The screen flash with what looks like the expected interface, but then goes white.

2. Windows 10 64 bit Home Edition

3. Latest, 0.2.3.  File pulled from Github releases

4.  This was after initial virgin install.  Same software on my other Windows 10 64 desktop works fine.

5. Happened on the first run ever on that machine.

7. Yes.  No Change.

8. Windows Defender.  Did not try disabling it.  Windows Defender is on both machines (working and non-working)

9.  Yes. No change.

I'll try to get you answers to 6, 10, and 11 this weekend.

Thanks.
