### ISSUE TITLE
ICO token doesn't show up on the list after adding it until wallet is restarted

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#861]
**Wallet version:**
0.2.1
**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.248
**Prerequisites:**
At least one wallet imported to the app
**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Switch to "TestNet"
5. Click on "Participate in a token sale" button
6. Click on "Add a new token to purchase" button
7. Click on "Add a new token" button
8. Type `84a487e5572ee920e548061fa875bf820ac29d0a` in "script hash" input field (it's NRV token)
9. Click on "Save" button
10. Click on "Participate in a token sale" button

List of "Select ICO token to purchase" is still empty after adding new token. After restarting a Neon Wallet, previously added token will show up.

**Video:**
![neonbug1](https://user-images.githubusercontent.com/8177587/37357015-a12bf630-26e7-11e8-8f25-04bdd1f7314d.gif)

**Comment by drptbl** [comment]
This issue won't be valid anymore after recent changes on `dev` branch (flow of participate in token sale has changed).

**Comment by comountainclimber** [comment]
Fixed in v2.0.0
