### ISSUE TITLE
ICO token is not removed from the list of "ICO tokens to purchase" after removal from "Manage Tokens" list until app is restarted

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#862]
**Wallet version:**
0.2.1
**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.248
**Prerequisites:**
At least one wallet imported to the app
NRV token added to the list of tokens (`84a487e5572ee920e548061fa875bf820ac29d0a`)
**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Switch to "TestNet"
5. Click on "Participate in a token sale" button
6. Click on "Add a new token to purchase" button
7. Click on "Delete" button next to NRV token (`84a487e5572ee920e548061fa875bf820ac29d0a`)
8. Click on "Save" button
9. Click on "Participate in a token sale" button
10. Click on "Select ICO token to purchase" drop-down list

List of "Select ICO tokens to purchase" still contains NRV token even if it was deleted from list of "Managed Tokens". Issue is solved after restarting Neon Wallet.

**Video:**
![neonbug2](https://user-images.githubusercontent.com/8177587/37357476-d6147b50-26e8-11e8-9585-a76594c1e708.gif)

**Comment by drptbl** [comment]
This issue won't be valid anymore after recent changes on `dev` branch (flow of participate in token sale has changed).

**Comment by comountainclimber** [comment]
Fixed in https://github.com/CityOfZion/neon-wallet/releases/tag/2.0.0
