### ISSUE TITLE
Support for PrivNet development mode

### ISSUE THREAD

**Issue by robmoorman** [CityOfZion/neon-wallet#871]
Would it be feasible to have a developer mode built in to hook up your own PrivNet endpoint?

Personally for development purposes (and demo's) it would be very nice to have this feature. I can make the PR if you want.

Thanks.

- [ ] Make neon-js support PrivNet
- [ ] Make neon-wallet-db support PrivNet
- [ ] Make PrivNet available in network switch (only if development is turned on via settings)
- [ ] Instructions how to host neo-privnet, neo-scan and neon-wallet-db

**Comment by drptbl** [comment]
#372

**Comment by robmoorman** [comment]
Haven't tried yet; but will switching to Neoscan and point the neoscan endpoint to e.g. local docker port work?

**Comment by khalifaT** [comment]
Hi all,
I am wondering if this issue is resolved or not yet??

**Comment by robmoorman** [comment]
Don't think so :) @khalifaT

**Comment by comountainclimber** [comment]
I think this is a great idea... The team will try and work this into v2

**Comment by robmoorman** [comment]
He @comountainclimber absolutely! From upcoming week I'll have more time to contribute available. If you want me to pick this up we can arrange that :).

**Comment by dauTT** [comment]
FYI, I am working on this. We can leverage the nice work done by @nunojusto:  https://github.com/CityOfZion/neo-local

**Comment by dauTT** [comment]
I need to make a detour and focus first on https://github.com/CityOfZion/neon-js/issues/455. :smile:
