### ISSUE TITLE
I did not receive my coins on my wallet

### ISSUE THREAD

**Issue by mharw** [CityOfZion/neon-wallet#88]
Hello. 
Dont delete my this is message.
Today I sent 3 (three) NEO coins to the address AUsf7BE2YLGyAdoc3kQTfMW7MH7ggtiKrm (purse NEON), and coins have not yet come to me. 
Show balance 0.
What should I do? 
Thank you. (Sorry, I do not speak English and Chinese. Translate Google)

**Comment by canesin** [comment]
Your message was not deleted https://github.com/CityOfZion/neon-wallet/issues/87.
