### ISSUE TITLE
Prevent invoking too many NEP-5 tokens transfers in a single request

### ISSUE THREAD

**Issue by mhuggins** [CityOfZion/neon-wallet#881]
Currently, Neon Wallet only supports sending transactions that cost 0 GAS (the fee is hard coded).  It's possible to create a transaction that should cost > 0 GAS using the wallet today, and it will fail due to no GAS being supplied for the fee.  This occurs when a user attempts to transfer too many NEP-5 tokens in a single transaction, as invocations above a certain threshold requires a fee.

To solve this, we should add a limit to how many tokens can be included in a transaction.  To determine what that invocation limit is, just try a test invoke for 1...N NEP-5 transfers to see at what point it fails.

**Comment by comountainclimber** [comment]
Limiting the number of transfers in a single transaction is currently implemented in the v2 send UX flow as well as the ability to add a fee 👍
