### ISSUE TITLE
DM Image not recognised

### ISSUE THREAD

**Issue by arakapas** [CityOfZion/neon-wallet#889]
I keep getting a message telling me my Wallet ( NEON) is  out of date please download latest. I tried to download latest, but I then gat an error message when I try to open the download saying  'image not recognised' I'm using a MAC the Version of NEON wallet is curently V 0.1.4

**Comment by valdor27** [comment]
Last one is : [https://github.com/CityOfZion/neon-wallet/releases/tag/0.2.2](0.2.2)

Did you download the .dmg file for MAC ?

**Comment by arakapas** [comment]
Hi
Yes I did

**Comment by mhuggins** [comment]
Try downloading again, the download may not have completed successfully.
