### ISSUE TITLE
Updated to new Version 0.2.2 Neon wallet

### ISSUE THREAD

**Issue by HORSEBIT** [CityOfZion/neon-wallet#892]
Tried to log in using a saved wallet but there are no drop down wallet options so cannot see if my transferred neo is there.  Al the other boxes have a greyed out log in so cannot access them either.

Any idea on what might be the problem?

## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by drptbl** [comment]
@HORSEBIT are you still encountering these issues? can you post some screenshots?

**Comment by HORSEBIT** [comment]
Hello,
All good,

Thank you,
