### ISSUE TITLE
Problem with gas claiming using NEON

### ISSUE THREAD

**Issue by antoninobf** [CityOfZion/neon-wallet#899]
Hello,

I'm not able to claim mys gas on my NEO address.
How can I solve that ?

Thanks,
AR

**Comment by mhuggins** [comment]
Not enough details provided.  Feel free to reopen with more insight as to what the issue is.

**Comment by antoninobf** [comment]
Hello,

Please feel free to ask me any details you need.
The last time that we want to get our gas was last week. The result failed.

Please find below the hash reference :
691316bf7470e0ba88a9b914e5ce663fd99443cb599a82291fc8c2b6ec3ebf5e




<https://www.bochslerfinance.com/>


*Antonino Ristagno **antonino@bochslerfinance.com*
<antonino@bochslerfinance.com>

Executive Director



Bochsler Finance

Gotthardstrasse 26

6300 Zoug, Switzerland

T +41 78 812 35 78 <+41788123578>

This electronic message and its accompanying attachments(if any) may
contain information that is confidential or otherwise legally privileged.
Such information is intended solely for the individual or entity to whom it
is addressed. If you are not the intended recipient of this message, please
notify the sender immediately and be aware that any disclosure, copying,
distribution, or use of this message or its accompanying attachments (if
any) is prohibited.

2018-04-29 21:46 GMT+02:00 Matt Huggins <notifications@github.com>:
