### ISSUE TITLE
Contacts phone book

### ISSUE THREAD

**Issue by canesin** [CityOfZion/neon-wallet#9]
We need a contacts list on the wallet (I need it, too many people with hash strings) .. 

A MVP should support for "alias", "name", "email" and "accounts" (as one have multiple accounts) with tags for identifying usage of each contact account, like "new year party"  "COZ" or "work".

**Comment by Ejhfast** [comment]
This can be the first thing we add after we give the wallet the ability to persist user state

**Comment by canesin** [comment]
just to remember this is annoying to not have :D

**Comment by nimgnusmik** [comment]
NEO / GAS Web Wallet https://www.neowebwallet.com

**Comment by comountainclimber** [comment]
I am definitely interested in engineering this feature. Is there a plan moving forwarding for persisting this data? A cache on the clients machine might work well...

**Comment by Ejhfast** [comment]
@comountainclimber we are already using persistent storage to save encrypted keys (electron-json-storage, or something like that). imagine we can use the same to store addresses

**Comment by comountainclimber** [comment]
@Ejhfast Thanks for the fast reply! I am going to create a rough mock for review/iteration on slack and then get to work

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/pull/422

**Comment by mhuggins** [comment]
@dvdschwrtz I think this issue can be closed now.
