### ISSUE TITLE
Problem with NEON WALLET since 0.2.0 : Failed to load.

### ISSUE THREAD

**Issue by Mantrah** [CityOfZion/neon-wallet#900]
Hi,

I have this problem since 2.0 : 
<img width="810" alt="neonload" src="https://user-images.githubusercontent.com/37581321/37653372-f75f79e4-2c3e-11e8-84ba-7eb9b1388055.png">
This is what i get when i launch the Neon app. I use Windows 10.
It gets "back to normal" when i install 1.4
Does someone know why do i get this problem ?

**Comment by javen123** [comment]
I'm also having this issue with same version running in both Fedora and Debian. I haven't tried going back to 1.4.

**Comment by mhuggins** [comment]
This happens when some request fails to load, such as when there is no internet connection.  Will track improving this under #918.
