### ISSUE TITLE
Can the USD or other currency be used to show the value of individual NEP-5 tokens?

### ISSUE THREAD

**Issue by spocek** [CityOfZion/neon-wallet#902]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by spocek** [comment]
This would be a nice addition to the Neon wallet as currently only NEO and GAS values in USD are shown.

Thanks!

**Comment by mhuggins** [comment]
Thanks for the suggestion!  This has been added for our v2 design, but just hasn't been released yet.  Look for it in an upcoming future release.
