### ISSUE TITLE
"Transaction failed"  I can't send neo or claim gas for 4 weeks now. I have the latest version of both the ledger nano s and neon wallet 0.2.2 

### ISSUE THREAD

**Issue by chrisI2018** [CityOfZion/neon-wallet#905]
"Transaction failed"  I can't send neo coins or claim gas for 4 weeks now. I have the latest version of both the ledger nano s and neon wallet 0.2.2 

## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by mhuggins** [comment]
Tracking this issue under #882.

**Comment by chrisI2018** [comment]
Hi

I have gas of about 37 coins i cannot claim.

I have updated the ledger and it appears to be a neon wallet problem only.

Could you please advise on how to claim these gas coins?

Thank you very much
Chris

--------------------------------------------
On Sun, 29/4/18, Matt Huggins <notifications@github.com> wrote:

 Subject: Re: [CityOfZion/neon-wallet] "Transaction failed" I can't send neo or claim gas for 4 weeks now. I have the latest version of both the ledger nano s and neon wallet 0.2.2 (#905)
 To: "CityOfZion/neon-wallet" <neon-wallet@noreply.github.com>
 Cc: "chrisI2018" <chrisi1776@yahoo.co.uk>, "Author" <author@noreply.github.com>
 Date: Sunday, 29 April, 2018, 20:47
 
 Closed #905.
 
 —
 You are
 receiving this because you authored the thread.
 Reply
 to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by zeethereum** [comment]
I had the same issue. But i cleared the cache history in my Chrome browser and then it worked.
