### ISSUE TITLE
Missing Token and Balance page

### ISSUE THREAD

**Issue by swolfaardt** [CityOfZion/neon-wallet#906]
#305 
I upgraded from 0.1.4 to 0.2.1 and then 0.2.2 and my token and history page in blank, I have checked my hash tags and thery are there, using nano s ledger to login any suggestions

See pics 
![img_1011](https://user-images.githubusercontent.com/37324357/37710088-1d19fb26-2d54-11e8-90c3-4f3b36b53a72.jpg)
![img_1010](https://user-images.githubusercontent.com/37324357/37710091-1ee82d24-2d54-11e8-8142-12b919606d2c.jpg)
![img_1009](https://user-images.githubusercontent.com/37324357/37710097-20baffaa-2d54-11e8-8d2e-ba6345f615ed.jpg)

**Comment by mhuggins** [comment]
0-balance tokens are not displayed on the dashboard in version 0.2.2.

**Comment by swolfaardt** [comment]
Thanks mate
