### ISSUE TITLE
Installation Error - Neon Wallet 0.2.2

### ISSUE THREAD

**Issue by bwatana** [CityOfZion/neon-wallet#908]
I am getting this error when trying to install Neon Wallet 0.2.2.Mac.dmg.  Any ideas?

The following disk image couldn't be opened.
Neon-0.2.2.Mac.dmg image Image not recognized.

**Comment by sjrowan** [comment]
Had the same issue. On impulse I delete the hyphen from the .dmg name. Worked fine.

**Comment by cswilsonmd** [comment]
I am not able to upgrade to 0.2.2.Mac.dmg either, getting the same "image not recognized" message.

**Comment by sjrowan** [comment]
You could try downloading and editing out the hyphen again. This is the exact name that worked for me: Neon0.2.2.Mac.dmg

**Comment by drptbl** [comment]
@bwatana Seems like your issue has been fixed. I'm closing this one.
