### ISSUE TITLE
Give me my 90neo

### ISSUE THREAD

**Issue by riandad** [CityOfZion/neon-wallet#91]
![image](https://user-images.githubusercontent.com/30951157/29239628-c3d28af2-7f8d-11e7-955e-ef889dbb1f77.png)

![image](https://user-images.githubusercontent.com/30951157/29239633-e13bd4b8-7f8d-11e7-9800-61487dfb2215.png)

If you sign up like a different Wallet, you know you can download the file separately.
I can not find the key.

**Comment by dop89** [comment]
Did you save your private key which you have generated in the first place anywhere else?

**Comment by riandad** [comment]
No......

**Comment by saltyskip** [comment]
If you do not have access to the private key, I'm sorry your funds are lost

**Comment by dop89** [comment]
We should display a warning message to user to backup the key, after it has been created.

**Comment by anfn101** [comment]
That is exactly what we do. But nobody reads it.
