### ISSUE TITLE
Get token hashes and open ICOs dynamically from a JSON file hosted at GitHub

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neon-wallet#910]
Remove hardcoded token hashes from neon-wallet, and instead have neon-wallet dynamically load token hashes (and open ICOs) dynamically from a JSON file hosted at GitHub pages. This could simply be a JSON file in a `/docs` folder that is published to GitHub pages, or a separate repo (`coz/neon-wallet-tokens`?).

That way projects could add or remove their tokens and we wouldn't need to release a new version of neon-wallet for every change.

cc/ @mhuggins @snowypowers @Ejhfast @dvdschwrtz

**Comment by vidov1** [comment]
Tokens are hardcoded ? Is that the reason for which I can't see a token even after entering its hash in the Neon token management menu ?

**Comment by snowypowers** [comment]
If we can get the token sale format approved as an NEP, we can check the blockchain itself for the token sale start instead of manually editing the token sale list. It also comes with added benefit of checking if the current address is whitelisted.

My preference is to remove the entire hardcoded token list and have users maintain their own token list as an NEP6 wallet.

**Comment by vidov1** [comment]
What about tokens, not token sales ? I deployed a token on the testnet, it has its own hash, but NEON doesn't want to display my balance with that token. What's so difficult ? Even neo-python can import a token with its hash and display the balance, even generate transfer transactions etc.

**Comment by metachris** [comment]
@snowypowers I'm not sure this is a feasible approach. For one -- there are outdated NEP-5 tokens on the blockchain, for instance the first Narrative SC which people should absolutely not use. 

Having users maintain their own token list is okay for developers, but too complicated for normal people that just want to check their balances and do transfers. Even I would like to just open neon-wallet and see my token balances, without having to go to some weird websites and copy hashes around and hope things work. Neon-wallet should continue to provide this out of the box.

That's the rationale for replacing hard-coded token hashes with the ones from a simple JSON file. Then we wouldn't need to update neon-wallet as soon as anything changes too. Only benefits, easy to maintain, and very little effort, as far as i can see.

**Comment by vidov1** [comment]
Well, the drawback is immediately obvious : in testnet, you deploy a token, you can't see it with NEON. Hence NEON becomes unusable for testing.
Also, I don't see why there is a dedicated menu for inputting a NEP5 token hash in NEON, if anyway NEON is going to be using only hardcoded tokens. 
That looks like a big bug to me.

**Comment by metachris** [comment]
You wouldn't want to show all NEP-5 smart contracts that were deployed to TestNet, that are hundreds. If you deploy a SC to TestNet, you know the hash anyway, and can easily add it. Btw, currently NEON is using a hardcoded list AND allows users to add custom hashes.

**Comment by vidov1** [comment]
I'm sorry, but that doesn't work. I deployed a token in testnet yesterday, I added its hash to NEON, it is not displayed.

**Comment by Ejhfast** [comment]
@vidov1 if you added it and it does not display, that is a separate
problem. it does not mean Neon should automatically display each of the
hundreds of deployed tokens on TestNet... what is the hash of your TestNet
token? maybe someone can help you debug

i continue to think the best approach here is a middle ground where token
name => hash bindings are served by a trusted service run by CoZ, which
will make the process of adding tokens to the wallet much easier for most
users

**Comment by mhuggins** [comment]
@vidov1 neon wallet does not display tokens with a balance of 0.  Make sure you transfer tokens to the wallet if you want it to display there.

**Comment by vidov1** [comment]
I did transfer tokens to the address, of course. The token is not displayed.

**Comment by mhuggins** [comment]
@vidov1 If you have extra on TestNet, send some to AP4AswDCgRCRF7Z6oMQMrFBzTuRgbeiQNF, and I'll take a look.

**Comment by vidov1** [comment]
Done. scripthash is a6c05f234081f6694e1da68f36741e53e2ead8e2 .

**Comment by comountainclimber** [comment]
Step 1 complete http://cityofzion.io/neon-wallet-tokens/token-list.json PR coming in neon-wallet coming shortly

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/releases/tag/0.2.7 this work has also been carefully ported over to v2
