### ISSUE TITLE
NEON Wallet Issue- Unable to Claim Gas and Transactions getting failed while sending NEO to other exchanges

### ISSUE THREAD

**Issue by sridharfeb28** [CityOfZion/neon-wallet#917]
I have been using Neon 0.2.2. I am unable to claim GAS also Transactios getting failed while i am trying to send the NEO to other exchanges..

Appreciate your support in this regard

Thanks,
Sridhar G

**Comment by FatherHall** [comment]
I'm having the same issue for the past few days.   Have you figured out how to fix it?

**Comment by sridharfeb28** [comment]
Yes.. I have installed in another machine and it's working..

**Comment by FatherHall** [comment]
thanks... weird but i'll try it.

**Comment by mpweber007** [comment]
I finally got it to work. Apparently you now need to click both buttons on the Ledger Nano S each time the Neon wallet asks to verify from the hardware device.

**Comment by Cryptomanifest** [comment]
This is happening to me now after not using my crypto computer for a month. Decided to send some NEO to sell and failed transactions across the board even after updating everything and reinstalling neon 0.2.3 and all ledger FW & APPS. Never had any issues before. Any fixes?

**Comment by mhuggins** [comment]
This issue should be fixed in [version 0.2.4](https://github.com/CityOfZion/neon-wallet/releases/tag/0.2.4).
