### ISSUE TITLE
Gas Claim Failed

### ISSUE THREAD

**Issue by Cubbies905** [CityOfZion/neon-wallet#92]
I am trying to claim my GAS, and when I click to do so, it eventually gives me a Claim Failed message.  I see the 0 NEO transaction that I should, but the GAS never shows up in my wallet and it still shows as claimable.

**Comment by nisargap** [comment]
Same issue

**Comment by DeepM1** [comment]
I have the similar problem.  I claim greater than 0.0001 GAS and the related transaction shows 0.0000 GAS.
Transaction ID a82de7fcd1dc6f494184d07dc02dc8a9
Is there a MINIMUM requirement amount for a GAS claim to show up in this NEON wallet?

**Comment by anfn101** [comment]
Yes- a very small amount will not show up in the transaction list. We can extend that later.

**Comment by Cubbies905** [comment]
i'm trying to claim 58 GAS not a small amount! please re open

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this.** As an aside, I've had to close about 10 other posts on this same exact subject... please read all issues before this one before creating a new one. Thanks.
