### ISSUE TITLE
NEON 0.2.2. install failure with McAfee 

### ISSUE THREAD

**Issue by gabrielSchel** [CityOfZion/neon-wallet#920]
Hi, I try to install new Neon, but McAfee lifesave removes the installed files because of detection. Is this only at my side or does it happen at more users?

**Comment by drptbl** [comment]
@gabrielSchel Are you still having this issue or any other person?

**Comment by texdevo** [comment]
i have. Keep having to download and exe. after opened and closed gets deleted again.
