### ISSUE TITLE
Neon wallet problem - ask for help

### ISSUE THREAD

**Issue by michaeluebelhart** [CityOfZion/neon-wallet#922]
I sent twice a neo to Kucoin today from my neon wallet, Version 0.2.2 (Ledger nano s is also updated). 
Both times this transaction was displayed correctly in my wallet, also shown in the transaction history. Both transactions also arrived in Kucoin.
Then I did a bigger neon transaction in exactly the same way (same NEO wallet deposit address in Kucoin).
This time, the transaction was not shown in the transaction history.
Unfortunately, the sum was deducted from my total amount neo in the Wallet.
In Kucoin the transaction did not appear either.
Then I tried the same again with a neo. With the same result. What can I do?
I appreciate any help.

**Comment by Lchorley** [comment]
This morning I sent 2000 Tnc from my Neon wallet to Kucoin. Kucoin has not recieved it and in my Neon wallet it does not show in my transaction history and yet it shows 0 balance in the wallet. Can someone help me?

Is there any admin for the Neon Wallet that can give assistance
