### ISSUE TITLE
Problem with gas claiming using NEON wallet version 0.2.1

### ISSUE THREAD

**Issue by pataloeke** [CityOfZion/neon-wallet#924]
Each time I hit the 'Claim GAS' button, it started (text in button become flu) and after some time it changes the text color in the 'claim button' back to normal but there is no GAS added.
On date 26/3/2018 it was still working but now not anymore.
Please can you fix it.

Thx, 
Pataloeke

## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by jroque-seertech** [comment]
+1
console logging error 500

![screen shot 2018-03-31 at 12 59 14 am](https://user-images.githubusercontent.com/23204793/38146075-f0b289ae-347e-11e8-9dea-fe600bc071d2.png)

**Comment by mhuggins** [comment]
This issue should be fixed in [version 0.2.4](https://github.com/CityOfZion/neon-wallet/releases/tag/0.2.4).
