### ISSUE TITLE
Minor documentation issue with alpha release 0.0.3c

### ISSUE THREAD

**Issue by js7558** [CityOfZion/neon-wallet#93]
https://github.com/CityOfZion/neon-wallet/releases/tag/0.0.3c  says to compute sha256sum as follows:

Linux (appimage): 73a7c29453dc0b3324eec1d18a6183f30d46c6da4b1f5be9a32eed1d48df9d77
sha256sum Linux.Neon-0.0.3-x86_64.AppImage.tar.gz

Linux (debian): c52c2bc775b5f7ff1ab9514c3ca3918044b134ba99d10ea08036356b75ba5594
sha256sum Linux.Neon_0.0.3_amd64.deb.tar.gz

The download links are actually not .tar.gz.  The sha256sum appears to be correct, however as follows from my box:

root@neo-antshares:~# sha256sum Linux.Neon_0.0.3_amd64.deb
c52c2bc775b5f7ff1ab9514c3ca3918044b134ba99d10ea08036356b75ba5594  Linux.Neon_0.0.3_amd64.deb
root@neo-antshares:~#

**Comment by totalvm** [comment]
Thanks I updated the release documentation!
