### ISSUE TITLE
Neon Wallet from a non-secure website

### ISSUE THREAD

**Issue by Monstroso88** [CityOfZion/neon-wallet#937]
Hello, second post here

Just wanted to report this somewhere, but there is non-secure site, neonwallet.com, with download links to get Neon Wallet. I found this suspicious, and regrettably did not realize it until right after I downloaded Neon Wallet and installed it from these links (grrrr, why do I do this?). 

I double-checked, and the links provided are actually directed to the same links that can be found on https://neo.org. Despite of the links being legit, I uninstalled immediately and ran a virus scan. I have reported the website to Neo.

Any thoughts?

**Comment by mhuggins** [comment]
Thanks for reporting.  There is an open issue for this under the neon-wallet-website repo, which is being tracked here: https://github.com/CityOfZion/neon-wallet-website/issues/1
