### ISSUE TITLE
Install Instructions for Ubuntu 14.04

### ISSUE THREAD

**Issue by js7558** [CityOfZion/neon-wallet#94]
Not really a bug report so much as a quick/dirty recap of how to get Linux.Neon_0.0.3_amd64.deb running on a fresh install of Ubuntu 14.04 Server.   I did this after verifying the sha256sum 
1) Log in as root
2) apt-get update && apt-get upgrade
3) dpkg -i Linux.Neon_0.0.3_amd64.deb
    <this threw a bunch of erros about unresolved dependencies on my machine>
4) apt-get -f install
    <this resolves those dependencies>
5) dpkg -i Linux.Neon_0.0.3_amd64.deb
6) At this point ldd showed several libraries not available:
      root@neo-antshares:~# ldd /usr/local/bin/neon |grep 'not found' | awk '{print $1}'
       libnode.so
       libX11-xcb.so.1
       libffmpeg.so

       libnode.so and libffmpeg.so were in /opt/neon according to dpkg -S.   apt-file showed that libx11-xcb1 was not installed so I needed to install this.   

      The fix for the former was to update LD_LIBRARY_PATH
     echo 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/neon; export LD_LIBRARY_PATH' >> .bashrc
      source .bashrc

      The fix for the latter was to install libx11-xcb1
      apt-get install libx11-xcb1

7)   After that, I was able to run neon.   If you have trouble with that, add /usr/local/bin to PATH and try again.

**Comment by NinjaTurtle007** [comment]
Thank you! I was unsure if I should install this or the AppImage package. (what is it for?)

When installed like that on linux to what parts of the OS it has access?
I'm afraid if it can access my bitcoin and ether wallets.

**Comment by js7558** [comment]
I don't know how to use the AppImage  as I mostly work on Ubuntu/Debian so am most comfortable with .deb. 

In terms of your question about being "afraid if it can access my bitcoin and ether wallets", you might consider running this in an isolated VM so that this is much less likely.   You can install KVM on your Ubuntu host and then run any number of individual VMs on top of it.  For example, you could have a VM called bitcoin that runs Electrum, a VM called ether that runs Exodus, a VM called neo-antshares that runs neon-wallet, etc.   When you're transacting you can start them up, otherwise leave them shutdown.  Probably makes most sense if you have unique logins on each VM.

**Comment by canesin** [comment]
@js7558 AppImage is supported in Debian and derivatives, it is a containerized packaged that bundle dependencies, please try it on the mean time ...  ping me again on this in 1 week please.
