### ISSUE TITLE
Neon Wallet shows blank page when i try to log in.

### ISSUE THREAD

**Issue by Mohirsi** [CityOfZion/neon-wallet#941]
![image](https://user-images.githubusercontent.com/34321834/38392235-cd041570-38f4-11e8-829c-806608027020.png)

I downloaded the latest version from Github 0.2.2.  it only shows blank page when i try to login to my wallet.  can anyone help me? i have windows 10.
![image](https://user-images.githubusercontent.com/34321834/38392271-f1f536f2-38f4-11e8-9dad-25e1417062fb.png)

**Comment by mhuggins** [comment]
Do you have an NVIDIA chip?  Might be a duplicate of #696.
