### ISSUE TITLE
Hello, I mistakenly sent NEO to the ONT token sale (it was an honest mistake where I was going to participate in the CGE token sale, but accidentally selected ONT as that was what I was just researching at the time). The address NEO is sent to is AefdBvb3bh7dNJHLmrQeQ193ckPch8ic5g. I know I should have been more careful but is there any way to receive the funds back from?

### ISSUE THREAD

**Issue by yw503414** [CityOfZion/neon-wallet#945]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by ZCChaos** [comment]
The same thing here... To the address: AefdBvb3bh7dNJHLmrQeQ193ckPch8ic5g.
I am wondering why no one is answering you. This is something serious. Someone just please answer!

**Comment by mhuggins** [comment]
This is not something that can be addressed by any maintainers of this repo.  You will need to reach out to the ONT team, as they are the owners of the wallet you sent to.
