### ISSUE TITLE
Provide cryptographic signatures for all builds

### ISSUE THREAD

**Issue by js990** [CityOfZion/neon-wallet#95]
For integrity verification purposes, I would like to put forward the suggestion of providing a gpg signed list of sha256 checksums for all builds. I do understand that officials builds may not be produced yet, but I just thought I'd mention it.

Thank you for all your hard work.

**Comment by stevesbrain** [comment]
I second this, and was planning to suggest it today as well. In addition to being a "download validity checksum", this would also help to protect against the unlikely circumstance that the repo gets compromised. In this event, it is unlikely the attacker would also have the private PGP keys to be able to sign the releases :smile:
