### ISSUE TITLE
Failed to load - Neon Wallet 0.2.2 & 0.2.3

### ISSUE THREAD

**Issue by LimitedEdition2017** [CityOfZion/neon-wallet#951]
It was working fine 5 hours ago. 

However, when I want to launch Neon Desktop Wallet 0.2.2 & 0.2.3 , both are failed to load.

What's wrong with that?

**Comment by mhuggins** [comment]
This happens when there is a network connectivity issue.  A new version in the future will prevent this blanket error screen when that happens.
