### ISSUE TITLE
List of tokens is not refreshed after adding a new token on "participate in token sale" page

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#952]
**Wallet version:**
0.2.3
**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.309
**Prerequisites:**
At least one wallet imported to the app
Imported wallet has to have some funds of NEP-5 token which is not added to default list of tokens (using THOR token as example)
**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Switch to "TestNet"
5. Click on "Participate in a token sale" button
6. Click on "Add a new token to purchase" button
7. Click on "Add a new token" button
8. Type `ae36e5a84ee861200676627df409b0f6eec44bd7` in "script hash" input field (it's THOR token)
9. Click on "Save" button

After doing last reproduction step you can notice that you're taken back to main wallet page and transaction history gets refreshed, but it looks like it doesn't refresh tokens list and probably balances - if user goes to "participate in token sale" he is still not able to choose token he just added until he manually click on "refresh account balance" button on main wallet page or waits patiently (1 minute or more?) for next automatic refresh of transaction list (it looks like it doesn't work with the first one which is triggered instantly after saving new custom token).

Same issue occurs after removal of previously added token from the list - it's still visible on the list of tokens and on "participate in token sale" page until user click on "refresh account balance" button on main wallet page or waits for next automatic refresh of transaction list.

**Video for adding new token:**
![add_token_doesnt_refresh](https://user-images.githubusercontent.com/8177587/38522427-d753c366-3c48-11e8-8abb-7d6fc142b748.gif)
**Video for removal of previously added token:**
![remove_token_doesnt_refresh](https://user-images.githubusercontent.com/8177587/38522438-e2b7597a-3c48-11e8-8ab1-eae0d61d9e15.gif)

**Comment by mhuggins** [comment]
Thanks for the extensive details!

**Comment by comountainclimber** [comment]
Fixed in v2.0.0

**Comment by drptbl** [comment]
Tested, fixed in v2.
