### ISSUE TITLE
"Participate in a token sale" modal disappears after opening "Manage Tokens" modal

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#954]
After going to "Participate in a token sale" and then clicking on "Add a new token to purchase" button - new modal is shown ("Manage Tokens") which replaces the old one. Now if you add a new token, fill the hash and save it - it takes you back to main wallet page instead of back to where you came from - which is "Participate in a token sale" modal.

It's not a bug, it's improvement proposal.

**Comment by comountainclimber** [comment]
Fixed in v2
