### ISSUE TITLE
latest wallet version not opening up

### ISSUE THREAD

**Issue by rmaman** [CityOfZion/neon-wallet#956]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

Iv updated my nano s....trying to download the latest Neon Wallet version. It downloads but wont open up.....the pop up window comes up without the green blocks but rather blank with waves playing in it......

**Comment by mhuggins** [comment]
I don't understand your description.  Can you share a screenshot and your system specs/OS?  You may find that you receive better support on the Discord channel that's mentioned in your message.

**Comment by bolle307** [comment]
Neon Wallet Update 0.2.3 does not work , is not opening after installation. After installation wallet opens and still says , '' Error , make sure you have downlaoded the latest .............''  , doesn't work , AGAIN.

**Comment by Bubiiii** [comment]
#Neonwallet not showing tokens, is someone having the same problem?
Before 4 days  everything worked perfectly. I'm using Nano S.
Nano wallet version 0.2.2.

**Comment by drptbl** [comment]
@rmaman @bolle307 
1. Which OS are you using?
2. Which wallet version are you trying to run?
3. Did it happen before or after update or there was no connection at all with updating the wallet (it was working fine and suddenly stopped to work)? If it broke after update, what version did you use before?
4. Do you remember if you did something specific before you closed wallet last time before it broke?
5. Are you sure that nothing is blocking your connection/wallet process from access to internet connection (firewall for example)?
