### ISSUE TITLE
Build instructions for various platforms

### ISSUE THREAD

**Issue by nitinsurana** [CityOfZion/neon-wallet#958]
Readme says that individual standalones are not available, but yet the website http://neonwallet.com/ provides executable downloads for various platforms - windows, mac, linux.

What are the build instructions for creating binaries for these platforms ? Am I looking into the wrong place (readme.md) ?

Thanks

**Comment by mhuggins** [comment]
Ahh, the readme is pretty outdated in that sense.  If you look at the [circle config](https://github.com/CityOfZion/neon-wallet/blob/dev/.circleci/config.yml), you can see the steps for [building Windows](https://github.com/CityOfZion/neon-wallet/blob/dev/.circleci/config.yml#L82-L84) and [building Linux](https://github.com/CityOfZion/neon-wallet/blob/dev/.circleci/config.yml#L97-L98).  Building on macOS is the same as building on Linux.

**Comment by nitinsurana** [comment]
Thanks @mhuggins 

`yarn install && yarn dist`
Will create Mac binaries. Strangely, the actual Mac .dmg is 135MB but the one created using this command is only 62MB, but seems to work.

`yarn build -w --x64`
Will create windows binaries. Strangely, the actual windows .exe on neonwallet.com is 134MB but the one created is only 44MB, but seems to work.

Any idea what's going wrong ? Why the build is having a different size altogether - is it because I'm building on a MacOS ?

Also, 
`yarn install && yarn dist` builds the .deb on Ubuntu, but again it's size is 41MB as opposed to 134MB shown on the website. And same as above, it still works.

Any ideas - why are they working ? And why the size is so small comparatively ?
