### ISSUE TITLE
Issue with Receiving THOR tokens

### ISSUE THREAD

**Issue by AlmsforOlAir** [CityOfZion/neon-wallet#959]
Hello I purchased THOR tokens on the neon wallet and I cannot view them in my wallet does any one know how to get them to show up?

**Comment by mhuggins** [comment]
The THOR token sale ended March 26.  If you used Neon Wallet to try to participate in their token sale after it ended, then you'll have to contact them to see if they can reimburse you, it is not a guarantee though.

**Comment by AlmsforOlAir** [comment]
Oh bummer.  Thanks for your help though
