### ISSUE TITLE
Sent Funds to Wrong Address

### ISSUE THREAD

**Issue by kajlul** [CityOfZion/neon-wallet#96]
Hi,
i deposited 641 GAS from my NEON Wallet Address: AarrWDuqD4HJ2ZpDaAaQbZ7dJTtLc7g8mv
to Binance wallet address: AbWeRDPA7SwcZtsnm9jcY3Bz6NikKd5ucc but my neo wallet shows this number on transaction history: 1387394c81bc45a23450caace12d0e53 as shown in the pictures bellow. i looked up my neon wallet address on Neoscan website it shows this totally different outputs address: AVn3ieeMPNxNfjSYi69h1Ws2L95udiQBy2 as shown in picture bellow. the funds left my neon wallet but has not hit binance for the past 1.5 hours. i am so confused this is freaking me out, i cant lose all my life savings PLEASE HELP. 
<img width="998" alt="screen shot 2017-08-12 at 9 13 17 pm" src="https://user-images.githubusercontent.com/30969260/29246175-810ba1a4-7fa6-11e7-8389-908b4294b268.png">
<img width="1050" alt="screen shot 2017-08-12 at 9 14 22 pm" src="https://user-images.githubusercontent.com/30969260/29246177-84c9fb38-7fa6-11e7-9fa3-45ee633b0c33.png">
<img width="1173" alt="screen shot 2017-08-12 at 10 21 08 pm" src="https://user-images.githubusercontent.com/30969260/29246376-e1830062-7fac-11e7-8b98-f7eccd8be6ca.png">

**Comment by totalvm** [comment]
If you sent it to the wrong wallet, there is nothing we can do.
As soon as it leaves your account you can't cancel it anymore.

If you don't have access to the account you sent it to, I'm afraid your funds are lost.

**Comment by kajlul** [comment]
is this address a valid NEO/GAS Address: AVn3ieeMPNxNfjSYi69h1Ws2L95udiQBy2

**Comment by saltyskip** [comment]
Yes, that is a valid address, you can see the gas here

https://www.neoscan.io/address/AVn3ieeMPNxNfjSYi69h1Ws2L95udiQBy2

If you do not have access to that address, then @totalvm is correct, the funds are lost

**Comment by kajlul** [comment]
i sent it to this address AbWeRDPA7SwcZtsnm9jcY3Bz6NikKd5ucc which is binance gas address.
i have no idea why Neoscan shows AVn3ieeMPNxNfjSYi69h1Ws2L95udiQBy2 as output address. i have not been dealing with any other gas address all day today. how could it go to another gas address. this is killing me. i can't think of anything to do

**Comment by saltyskip** [comment]
Most likely you copy and pasted the wrong address when making the transaction. I'm trulysorry for your loss, but there is nothing that can be done.

**Comment by Alisamix** [comment]
were you asked by someone on reddit to download an updated version?

**Comment by kajlul** [comment]
i followed this youtube video when i downloaded the neon wallet https://youtu.be/GkINIvg83go

**Comment by Alisamix** [comment]
That is the correct wallet - weird.

**Comment by kajlul** [comment]
is there anyone i should contact who can help me? i have not been missing with any other gas address in my life, how could it be sent to that other gas address when i haven't even seen such an address. i copied the correct address from my binance gas wallet and pasted it into the neon send address field, but i dont remember if i double checked the address to make sure or not. even if i didnt double check, how could that wrong address be copied in my clip board?

**Comment by Alisamix** [comment]
Some kind of criminal activity is entirely possible - I could try to look into it, but without access to logs, the client etc there isnt anything I could do.

**Comment by kajlul** [comment]
i will really appreciate that. what specific info you need so i write it here for you.

**Comment by Alisamix** [comment]
You can add me in skype: alisami3000
