### ISSUE TITLE
Not able to sent ONT or QLC

### ISSUE THREAD

**Issue by Raoul60** [CityOfZion/neon-wallet#961]
When l want to send ONT or QLC from my NEON wallet l get the notification "transaction failed, invalid status 6d07". 
l use the NEON wallet 0.2.3 with the Nano S ledger. I had the same problem with the 0.2.2. version. I am able to claim GAS, and send NEO and GAS. And the problem seems to be caused by the combination of the NEON wallet and the Nano S ledger, as l was earlier able to send QLC with the NEON wallet and a private key.

**Comment by blakemarkland** [comment]
same issue
