### ISSUE TITLE
NEX Airdrop started! and ICO?

### ISSUE THREAD

**Issue by Jeniffer99** [CityOfZion/neon-wallet#962]
Saw today that NEX Airdrop started, include the ICO 

we need to update our wallet? if I have won the lottery? 

https://medium.com/@FabianWahle2/how-to-participate-in-upcoming-nex-ico-7bfcbb3a8d92

**Comment by mhuggins** [comment]
You don't use the neon wallet to participate in the ICO.  Check out the link you posted, it explains how to participate.
