### ISSUE TITLE
 Neo token is not displayed at all

### ISSUE THREAD

**Issue by yuuhi0320** [CityOfZion/neon-wallet#964]
I used neon wallet version 0.2.3 today.
But Neo token is not displayed at all
Is this a bug?
![2018-04-14 7 29 01](https://user-images.githubusercontent.com/32263918/38760332-9d4af57a-3fb5-11e8-9f02-1b739aca8215.png)

**Comment by Bubiiii** [comment]
I'm using the 0.2.2 Version and I'm having the same problem.
And I don't know how to fix it.

**Comment by dmlipat** [comment]
had the same problem, so now im back to using 0.1.4 until things get sorted
