### ISSUE TITLE
[v2] Authentication

### ISSUE THREAD

**Issue by mhuggins** [CityOfZion/neon-wallet#969]
Placeholder story

**Comment by comountainclimber** [comment]
First pass complete and encapsulated within this PR https://github.com/CityOfZion/neon-wallet/pull/1018

**Comment by comountainclimber** [comment]
now completed https://github.com/CityOfZion/neon-wallet/pull/1018

**Comment by mhuggins** [comment]
Code complete, just pending QA.

**Comment by drptbl** [comment]
Looks good for now 👍.
