### ISSUE TITLE
My gas had been accumulating on my neon wallet and then it disappeared to zero and stopped accumulating.

### ISSUE THREAD

**Issue by BitRov** [CityOfZion/neon-wallet#97]

**Comment by FrankieSpades** [comment]
I have the same problem!  Yesterday I created the wallet, sent over my NEO and it started accumulating GAS. A few minutes later, I claimed it and it showed up on my balance. Today I went to claim my GAS and when I did, the Gas never showed up and the amount of gas to claim is at 0.   The original Gas i claimed the previous day is still there. Where did the gas go that I am supposed to claim?

**Comment by CodeJynx** [comment]
I installed the Mac Neon wallet for the first time yesterday and the gas accumulated until today when I reopened the app. I still have that Gas but it doesn't accumulate anymore.

**Comment by BitRov** [comment]
Thanks for the comments Frankie and Code. I installed the neon mac wallet 4 days ago and my gas was accumulating just fine until I checked it today and my gas balance was zero and no further accumulation. Hopefully somebody will be able to help us.

**Comment by CodeJynx** [comment]
Third party apps should always be scrutinised... Who knows if our NEO wont disappear someday?

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), **do not use Github as tech support** - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. **Please let everybody you know know this.**

**Comment by CodeJynx** [comment]
I'd like to join the slack channel.. What's the address for an invite??

**Comment by BitRov** [comment]
Frankie and Code I went to   neotracker.io   I then copied and pasted my public address and clicked open wallet and put in my keys and was able to claim my gas and it was sent to my neon wallet. Although I still don’t see it accumulating on my neon wallet it is accumulating on neotracker. Hopefully we can get back to accumulating the gas on the neon wallet and just clicking the button. Anyhow hope this helps. If anybody has any further suggestions please feel free to comment. Thank you

**Comment by anfn101** [comment]
Please... read my comment thoroughly. **Please stop posting on Github.** There are proper channels of support.

**Comment by BitRov** [comment]
Sorry anfn101. I did not see your comment before I made my last one. Thank you for your help and input.
