### ISSUE TITLE
Can't open wallet, endless loading screen

### ISSUE THREAD

**Issue by ggstorms** [CityOfZion/neon-wallet#984]
Hello, I am using Neon Wallet 0.2.3. I have had no issues the past few weeks using it with Ledger Nano S, but starting today the wallet just gives me an endless loading screen. I am sure this is not a problem with Ledger as it doesn't even get to the point of choosing the option of selecting Ledger to access the wallet. 

I have several different computers with Neon Wallet, they all have the same problem. I have tried uninstalling and re-installing, but no luck. I have waited for up to 2 hours to see if the loading screen ever changes, but it never does. I hope someone can please help me. 

![capture](https://user-images.githubusercontent.com/38409625/38784198-5e7c0ae6-40c3-11e8-8147-4b328d51532d.PNG)

**Comment by drptbl** [comment]
1. Which OS are you using?
2. Which wallet version are you trying to run?
3. Did it happen before or after update or there was no connection at all with updating the wallet (it was working fine and suddenly stopped to work)? If it broke after update, what version did you use before?
4. Do you remember if you did something specific before you closed wallet last time before it broke?
5. Are you sure that nothing is blocking your connection/wallet process from access to internet connection (firewall for example)?
