### ISSUE TITLE
Sending NEP5 tokens requires holding at least 1 drop of GAS

### ISSUE THREAD

**Issue by Kimmy0907** [CityOfZion/neon-wallet#985]
Hi Dev,
I am using Mac, and it keep saying "Sending NEP5 tokens requires holding at least 1 drop of GAS" to send my RPX out of Neon wallet.

Im using Neon with Ledger Nano S

Mac 10.13.3
Neon 0.2.3
Neo Ledger App 1.1.2
Ledger 1.4.1 

I tried uninstalled & reinstalled both Neo Ledger App & Neon.
Turned off and on several times.

and it keep saying

Sending NEP5 tokens requires holding at least 1 drop of GAS

Im holding more than 20 NEOs & 3 Gas in my wallet.

Thx!

**Comment by Kimmy0907** [comment]
Shame on me. 
It seems its just warning for those who doesn't have gas in wallet.

Red in "Sending NEP5 tokens requires holding at least 1 drop of GAS"
with 
Graying out "NEXT" button

seems giving confusion. 

Can you only show this message when actually theres no gas in wallet?

**Comment by Asubayo** [comment]
Does it mean that we need to hold at least 1 GAS to be able to send tokens from neon wallet ?
I have DBC on my neon wallet. Does it mean that I can't send it somewhere else if I don't have 1 GAS ?
