### ISSUE TITLE
When I give my ledger public address in NEO scan and click search -no txs are displayed ,nor the balance 

### ISSUE THREAD

**Issue by PREDDY-LONDON** [CityOfZion/neon-wallet#988]
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by stevesbrain** [comment]
And is this definitely an address you've sent to before? What is a previous transaction ID? When looking up that transaction ID, is it definitely this address you've sent to? Have you seen balance on *this* address before?

**Comment by mhuggins** [comment]
This is a neo-scan issue, not neon wallet.  You can submit your issue here: https://github.com/CityOfZion/neo-scan
