### ISSUE TITLE
Trezor support

### ISSUE THREAD

**Issue by frapell** [CityOfZion/neon-wallet#989]
Is there a plan to support Trezor wallet? I don't currently have a Ledger, but I do have a Trezor and I would LOVE to have my NEO protected by it.

Is it possible? if so, are you planning to add support in the wallet for it?

**Comment by bwatana** [comment]
My solution was to get a Ledger Nano S for this and give Trezor to my sister.  ;)

**Comment by frapell** [comment]
Well, I don't really like the Ledger... A friend of mine has one and it just feels of inferior quality than the Trezor...

Also, Trezor has this ability to use as many passphrases you like in order to create new wallets, so you can have several parallel wallets in the same device with no issues at all...

Anyway, I don't know the technical aspect, but if possible, I would LOVE to use my Trezor

**Comment by comountainclimber** [comment]
There is no short term plan to support Trezor wallet at this time... Will reopen or at least link this issue if that changes in the future
