### ISSUE TITLE
No GAS

### ISSUE THREAD

**Issue by snowzman** [CityOfZion/neon-wallet#99]
Hi

anyone having 0 gas and not accumulating gas? 
i was able to see the gas accumulated previously and now it shows as 0 gas andi am already on v0.0.3

**Comment by cryptoneep** [comment]
I have the same problem since this morning. Yesterday it worked perfectly, I could claim GAS all day long. But today it shows "Claim 0 GAS", and when I click on that, it just says "Waiting for transaction to clear..." for a while.

Also on v0.0.3

**Comment by code-runner-77** [comment]
Same here.  Using  https://neotrack.io, my address has unclaimed GAS on the chain; however, NEON walllet which worked yesterday, shows "Claim 0 GAS", and if I press the Claim button anyway, the transaction hangs with "Waiting for transactions to clear..." ribbon at the top of the wallet window and it never finishes... Explorer still shows the GAS as unclaimed.

**Comment by anfn101** [comment]
The wallet is under maintenance, as has been stated on Reddit and our support Slack for a while now. As a reminder (again), do not use Github as tech support - this is an area for developers to discuss code. It simply makes it more difficult to work here. You can refer to Reddit or our support Slack, a link to which can be found in the sidebar of the subreddit. Please let everybody you know know this.
