### ISSUE TITLE
"Claim X GAS" button differs from designs (icon is missing, wrong background color) on wallet dashboard

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#990]
**Wallet version or commit SHA:**
be16b42

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.371

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button

"Claim X GAS" button has no icon currently (hand with pennies).  Also button background color should be white.

For reference check `2.0-Home-Light` designs.

**Screenshots/Video:**
![claim_gas_current](https://user-images.githubusercontent.com/8177587/38880611-69bfef68-4266-11e8-85f2-f5bb82207873.png)

**Comment by comountainclimber** [comment]
Good catch I can take care of this one...

**Comment by mhuggins** [comment]
@comountainclimber Sorry man, I didn't see your comment and was just looking at this on the project board directly.  I ended up getting this done along with some other fixes.

**Comment by drptbl** [comment]
Re-tested, confirming that it's fixed 🎉.
