### ISSUE TITLE
Calculating claimable Gas failed

### ISSUE THREAD

**Issue by AdvocateOne** [CityOfZion/neon-wallet#991]
Version 0.2.3, Windows 7

When trying to claim gas, I get the following message:

"Calculating claimable Gas failed"

The gas then remains unclaimed.

**Comment by buddhaman8** [comment]
Yea same here, claiming GAS isn't working! (again!)

**Comment by drdemarco** [comment]
Same here MacOS 10.13.4 NeonWallet 0.2.3 with Ledger Nano S (new update 1.4.2)...
I can Claim and SIGN 1/2 TX btw... the 2/2 never show up and it says Claim gas failed after some time... 
One thing I see... the transaction history seems to be stuck... coz I send 1 NEO to Binance... and send 1 NEO back to Neon and it dont show on my History.

**Comment by pposca** [comment]
Same GAS issue here. 

MacOS 10.13.4 since I updated to NeonWallet 0.2.3

**Comment by Kimmy0907** [comment]
same here as drdemarco. 1/2 TX showed. 2/2 never shows up

**Comment by jobbord** [comment]
Yeah, I get that too. Error: Claiming GAS failed.

**Comment by drptbl** [comment]
**Wallet version:** 0.2.3, **Env:** Win 10 Home (64 bit) Version 1709 Build 16299.371
Claimed my GAS with success on MainNet without using Ledger.
https://neotracker.io/tx/41468f8d8678863b3942b5d25457189260225bb75586c90dc6eec55853f3b6e4
------------
**Wallet version:** 0.2.3, **Env:** MacOS 10.13.2
Also claimed my GAS with success on MainNet without using Ledger.
https://neotracker.io/tx/6cac23bd14c2c9d0dee5e84c2fdb1144ec26f5e5c2be24e0873df55fb7bbc7b4
------------
Issue with claiming GAS using Ledger is known, for example: #882, #833, #791

**Comment by drdemarco** [comment]
Kimmy0907 after several times I claim GAS but 2 things (had around 0.034 to claim and just come only 0.016) and now I have the issue like many others... I can sign 1/2 TX but when 2/2 appear it just disapear as fast as not show up on Ledger visor then it says Claim GAS Failed... I try all the versions... cleaning registry with the CCleaner also try set the Firewall settings but nothing works... so SAD

**Comment by pposca** [comment]
I downgrade to version 0.2.2 and I am getting the same problem (notice I hadn't it before installing 0.2.3).

BTW, I an not using Ledger.

**Comment by telcy** [comment]
Same here. Claiming Gas does not work on Mac.

**Comment by drdemarco** [comment]
I try one last thing... I had one plus ledger still lacred on box... I read in some places this is a memory problem of ledger... some people get a new one and the problem solved... well not in my case... I set new ledger and update all... when try to claim gas.... still failed.... I will w8 for an new update from the wallet... if not solved... will move my coins out.

**Comment by zedocrob** [comment]
For me, "Gas claiming" is Working on windows 10 with my Ledger Nano S - firmware 1.4.2 latest.
Not working on Mac for the moment...

**Comment by Cool1ca** [comment]
Yes I believe it's the new software ledger just had us upgrade to. Because
I never upgraded my second nano and the neon wallet is working just fine
with it.But I'd still like to blame it on the button sticking on my nano .
