### ISSUE TITLE
Percentage changes are missing in "Balances" section (for NEO and GAS) on wallet dashboard

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#992]
**Wallet version or commit SHA:**
be16b42

**Prerequisites:**
At least one wallet imported to the app

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button

Percentage changes are missing in "Balances" section (for NEO and GAS). 

For reference check `2.0-Home-Light` designs.

**Screenshots/Video:**
![balances_current](https://user-images.githubusercontent.com/8177587/38882442-6448f9c2-426a-11e8-9952-367025a1a254.png)

**Comment by tzyl** [comment]
Hey @drptbl, I would be interested in contributing this! Can you point me to where I can see the designs for reference?

**Comment by drptbl** [comment]
Re-tested, looks good.
