### ISSUE TITLE
Percentage is trimmed while it's equal to "100.0%" in "Portfolio" section on wallet dashboard

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#996]
**Wallet version or commit SHA:**
be16b42

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.371

**Prerequisites:**
At least one wallet imported to the app,
Balance of only one valuable token which is added to the wallet (for example: NEO balance only)

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button

Percentage is trimmed while it's equal to "100.0%" in "Portfolio" section on wallet dashboard. This issue doesn't happen when percentage is less than 100%.

**Screenshots/Video:**
![portfolio](https://user-images.githubusercontent.com/8177587/38892073-82bca78e-4286-11e8-98d5-35462771eca1.png)

**Comment by mhuggins** [comment]
Someone contributed a fix for this.  Please let me know if it doesn't look right, though!

**Comment by drptbl** [comment]
Re-tested, works fine, thanks 👍 .
