### ISSUE TITLE
Ontology

### ISSUE THREAD

**Issue by swolfaardt** [CityOfZion/neon-wallet#997]
Hi 

I login on to my neon wallet and went to participate in token sales and used one Neo token to buy Ontology , nothing is in my wallet using version 0.2.2

**Comment by swolfaardt** [comment]
Any help

**Comment by mhuggins** [comment]
Ontology is not having a public sale, you should not send NEO to ONT.  That is why there is a big red banner taking up half the screen to explain that.  You will have to contact the ONT to see if they can return your NEO.
